


Reading Parameter File....................done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Reading pairs.............................done.
Sorting pairs.............................done.

RELPAL analysis.......  1
  Reading pair IBD states ................done.
  Performing second level score test......done.
  Performing second level regression test.done.
  Performing second level score test......done.
  Performing second level regression test.done.
  Performing second level score test......done.
  Performing second level regression test.done.

Analysis complete!



