


%RELPAL-W: [22] Phenotype (found 'A / 0' at sex-dependent marker 'DXS1297' is
           inconsistent with the sex of individual '44' in pedigree '8'. 
           Marker will be set to missing for this individual.
%RELPAL-W: [22] Phenotype (found 'A / 0' at sex-dependent marker 'DXS1304' is
           inconsistent with the sex of individual '44' in pedigree '8'. 
           Marker will be set to missing for this individual.
%RELPAL-W: [22] Phenotype (found 'A / 0' at sex-dependent marker 'DXS1263' is
           inconsistent with the sex of individual '44' in pedigree '8'. 
           Marker will be set to missing for this individual.
%RELPAL-W: [24] Phenotype (found 'A / 0' at sex-dependent marker 'DXS1297' is
           inconsistent with the sex of individual '55' in pedigree '8'. 
           Marker will be set to missing for this individual.
%RELPAL-W: [24] Phenotype (found 'A / 0' at sex-dependent marker 'DXS1304' is
           inconsistent with the sex of individual '55' in pedigree '8'. 
           Marker will be set to missing for this individual.
%RELPAL-W: [24] Phenotype (found 'A / 0' at sex-dependent marker 'DXS1263' is
           inconsistent with the sex of individual '55' in pedigree '8'. 
           Marker will be set to missing for this individual.

Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     6             1             F         0             0           
     6             2             M         0             0           
     6             3             M         1             2           
     6             4             M         1             2           
     6             5             F         1             2           
     6             11            F         0             0           
     6             22            M         0             0           
     6             33            M         11            22          
     6             44            M         11            22          
     6             55            F         11            22          


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         alc                   test                
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     6             1             1                     1                     1                     10                    1                     1                   
     6             2             0                     1                     1                     10                    1                     2                   
     6             3             0                     1                     0                     10                    1                     3                   
     6             4             0                     1                     0                     10                    1                     4                   
     6             5             1                     1                     0                     10                    0                     5                   
     6             11            1                     1                     1                     10                    1                     1                   
     6             22            0                     1                     1                     10                    1                     2                   
     6             33            0                     1                     0                     10                    1                     3                   
     6             44            0                     1                     0                     10                    1                     4                   
     6             55            1                     1                     0                     10                    0                     5                   


Markers for the first 10 individuals read from file: ped

     PED. ID       IND. ID       D3S1297       D3S1304       D3S1263       DXS1297       DXS1304       DXS1263     
     ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
     6             1             A/B           0/0           0/0           A/B           0/0           0/0         
     6             2             C/D           0/0           0/0           C/0           0/0           0/0         
     6             3             A/C           A/C           A/C           A/0           A/0           A/0         
     6             4             A/D           0/0           0/0           A/0           A/0           A/0         
     6             5             B/C           0/0           0/0           B/C           B/C           B/C         
     6             11            A/B           0/0           0/0           A/B           0/0           0/0         
     6             22            C/D           0/0           0/0           C/0           0/0           0/0         
     6             33            A/C           A/C           A/C           A/0           A/0           A/0         
     6             44            A/D           0/0           0/0           A/0           A/0           A/0         
     6             55            B/C           0/0           0/0           B/C           B/C           B/C         

%RELPAL-W: Pedigree '6' has 2 constituent pedigrees which are disjoint from one
           another.  This may not be intended.  Results may be incorrect.  See
           manual for details on constituent pedigrees.

RELPAL analysis.......1  

%RELPAL-I: No Markers are specified for the single_marker model.  Using all
           markers from the ibd file...

=================================
  Relpal Analysis Specification  
=================================

model: single trait, single marker

trait:
   trait 1: alc

first_level:
  covariate 1: test, adj_t = all

transform residuals from 1st level to 2nd level

second_level:
  test marker 1: D3S1297
  test marker 2: D3S1304
  test marker 3: D3S1263

data options:
  use_members = every
  use_pairs = all

output options:
  detailed_out = yes
  export_out = no
  data_out = no
  debug_out = no
  residual_out = yes

asymptotic pvalue options:
  seed = 100
  replicates = 0
  min_replicates = 20
  max_replicates = 10000
  threshold = 0.05
  width = 0.2
  confidence = 0.95

variance options:
  naive variance = true
  robust sandwich variance = true
  alternative variance = true
  IBD variance conditional on trait = true


%RELPAL-W: Variance components out of bound!
