



Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             1         0             0           
     1             2             2         0             0           
     1             3             1         1             2           
     1             4             1         1             2           


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         rep                 
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     4                     1                   
     1             2             1                     1                     1                     4                     2                   
     1             3             0                     1                     0                     4                     3                   
     1             4             0                     1                     0                     4                     4                   


Markers for the first 10 individuals read from file: ped

     PED. ID       IND. ID       m1            m2          
     ------------  ------------  ------------  ------------
     1             1             1/2           1/2         
     1             2             1/2           1/2         
     1             3             1/2           1/2         
     1             4             1/1           1/1         

%DECIPHER-I: Mapping function not specified.  Using Haldane Mapping Function.

  Performing analysis: Analysis 1
  ===========================================================================

    Total population. 
      Determining possible haplotype combinations ................... done.

  ===========================================================================

