


=============================================================================
  Conditional Logistic Analysis of Affected Relative Pairs - multipoint
=============================================================================

    Trait    : TBnew
                concordantly affected relative pairs
                 contrast to discordantly affected relative pairs

    Method   : default analysis method

    Model    : one-parameter model, constrained, alpha = 2.634

=============================================================================
                            Full   Half                  Param Est  1st Deriv
                  LOD       Sib    Sib    Other  All     ---------  ---------
MARKER      cM    SCORE     Pairs  Pairs  Pairs  Pairs   Beta1      Beta1    
----------------- --------- ------ ------ ------ ------  ---------  ---------
 D6S270       0.0  0.025068      2      0      1      3   0.225695   0.000000
 D6S1587      3.2  0.030917      2      0      1      3   0.215249  -0.000000
 D6S1675      9.3  0.126219      2      0      1      3   0.491369   0.000000
=============================================================================


