


=================================================================================================
  Conditional Logistic Analysis of Affected Relative Pairs - multipoint
=================================================================================================

    Trait    : TBnew
                concordantly affected relative pairs
                 contrast to discordantly affected relative pairs

    Method   : default analysis method

    Model    : two-parameter model, constrained

=================================================================================================
                            Full   Half                  Parameter Estimates  First Derivatives
                  LOD       Sib    Sib    Other  All     -------------------  -------------------
MARKER      cM    SCORE     Pairs  Pairs  Pairs  Pairs   Beta1     Beta2      Beta1     Beta2    
----------------- --------- ------ ------ ------ ------  --------- ---------  --------- ---------
 D6S270       0.0  0.201494      2      0      1      3   0.000000  1.942800   0.000000  0.000000
 D6S1587      3.2  0.283341      2      0      1      3   0.000000  1.746740   0.000000  0.063602
 D6S1675      9.3  0.425150      2      0      1      3   0.000000  1.589048   0.000000 -0.020956
=================================================================================================


