


%SIBPAL-W: [7] Unable to read sex of individual I7 in pedigree F1.  Found ''. 
           Setting sex to unknown.
%SIBPAL-W: The sex of individual 'I5' in pedigree 'F1' is believed to be male. 
           Sex code will be reset.
%SIBPAL-W: The sex of individual 'I7' in pedigree 'F1' is believed to be male. 
           Sex code will be reset.

Family structure information on the first 100 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     F1            I1            M         0             0           
     F1            I2            F         0             0           
     F1            I3            M         0             0           
     F1            I4            F         0             0           
     F1            I5            M         I1            I2          
     F1            I6            F         0             0           
     F1            I7            M         I3            I4          
     F1            I8            ?         I3            I4          
     F1            I9            F         I3            I4          
     F1            I10           F         I5            I6          
     F1            I11           M         I6            I7          
     F1            I12           F         I6            I7          
     F1            I13           M         I6            I7          
     F1            I14           F         I6            I7          
     F1            I15           M         I6            I7          
     F1            I16           M         0             0           
     F1            I17           M         I16           I9          
     F2            I1            M         0             0           
     F2            I2            F         0             0           
     F2            I3            M         0             0           
     F2            I4            F         0             0           
     F2            I5            M         I1            I2          
     F2            I6            F         0             0           
     F2            I7            M         I3            I4          
     F2            I8            M         I3            I4          
     F2            I9            F         I3            I4          
     F2            I10           F         I5            I6          
     F2            I11           M         I6            I7          
     F2            I12           F         I6            I7          
     F2            I13           M         I6            I7          
     F2            I14           F         I6            I7          
     F2            I15           M         I6            I7          
     F2            I16           M         0             0           
     F2            I17           M         I16           I9          


Phenotypes for the first 100 individuals read from file: ped

     PED. ID       IND. ID       Trait1              
     ------------  ------------  --------------------
     F1            I1            2                   
     F1            I2            6                   
     F1            I3            4                   
     F1            I4            4                   
     F1            I5            4                   
     F1            I6            6                   
     F1            I7            4                   
     F1            I8            2                   
     F1            I9            6                   
     F1            I10           6                   
     F1            I11           6                   
     F1            I12           4                   
     F1            I13           4                   
     F1            I14           6                   
     F1            I15           4                   
     F1            I16           2                   
     F1            I17           4                   
     F2            I1            4                   
     F2            I2            2                   
     F2            I3            4                   
     F2            I4            6                   
     F2            I5            4                   
     F2            I6            4                   
     F2            I7            4                   
     F2            I8            6                   
     F2            I9            6                   
     F2            I10           2                   
     F2            I11           6                   
     F2            I12           4                   
     F2            I13           4                   
     F2            I14           4                   
     F2            I15           XXX                 
     F2            I16           6                   
     F2            I17           6                   

%SIBPAL-W: Invalid value specified for parameter 'print_qls'.  Skipping...
