


Reading Parameter File....................done.
Reading Marker Locus Description File.....done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Reading Genome Description File...........done.

  No analyses specified.
Performing MCMC_ENGINE default analysis...

Processing Analysis....
Processing Region: REGION1
=======================================

Pedigree 1
marker informative? true
marker informative? true
mcmc_meiosis_map dump :
p_meioses :
0 1 : -1, -1
1 2 : -1, -1
2 3 : 0, 1
3 4 : 2, 3
4 5 : 4, 5

individual_positions :
0 : 2
1 : 3
2 : 4

nfbits = 6
founder_count = 2, nonfounder_count = 3
individual count 5
family count 1

mcmc_data_accessor dump :
locus_count        = 2
indicator size     = 2
valid_loci size    = 2

inheritance vector  000000
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	4	3	2	0	
     1   1 / 2  	0	
     2   1 / ?  	4	3	2	1	
     3   1 / 3  	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      0 <-> 2   
     3      4   1 / 2      0 <-> 2   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   ? / ?  	4	3	2	0	
     1   1 / 3  	0	
     2   ? / ?  	4	3	2	1	
     3   1 / 2  	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      0 <-> 2   
     3      4   1 / 3      0 <-> 2   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
inheritance vector  000001
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	4	3	0	
     1   1 / 2  	2	0	
     2   1 / ?  	4	3	2	1	
     3   1 / 3  	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      1 <-> 2   
     3      4   1 / 2      0 <-> 2   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   3 / ?  	4	3	0	
     1   1 / ?  	2	0	
     2   ? / ?  	4	3	2	1	
     3   1 / 2  	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      1 <-> 2   
     3      4   1 / 3      0 <-> 2   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
inheritance vector  000010
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	2	4	3	0	
     1   1 / 2  	0	
     2   1 / ?  	4	3	1	
     3   1 / ?  	2	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      0 <-> 3   
     3      4   1 / 2      0 <-> 2   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   ? / ?  	2	4	3	0	
     1   1 / 3  	0	
     2   ? / ?  	4	3	1	
     3   1 / ?  	2	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      0 <-> 3   
     3      4   1 / 3      0 <-> 2   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
inheritance vector  000011
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	4	3	0	
     1   1 / 2  	2	0	
     2   1 / ?  	4	3	1	
     3   1 / ?  	2	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      1 <-> 3   
     3      4   1 / 2      0 <-> 2   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   3 / ?  	4	3	0	
     1   1 / ?  	2	0	
     2   ? / ?  	4	3	1	
     3   1 / ?  	2	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      1 <-> 3   
     3      4   1 / 3      0 <-> 2   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
inheritance vector  000100
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	2	4	0	
     1   1 / 2  	3	0	
     2   1 / ?  	2	4	3	1	
     3   1 / 3  	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      0 <-> 2   
     3      4   1 / 2      1 <-> 2   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   ? / ?  	2	4	0	
     1   1 / 3  	3	0	
     2   ? / ?  	2	4	3	1	
     3   1 / 2  	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      0 <-> 2   
     3      4   1 / 3      1 <-> 2   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
inheritance vector  000101
Marker 0
Founder Allele Graph is: VALID with likelihood 0.006//-5.116
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	4	0	
     1   1 / 2  	2	3	0	
     2   1 / ?  	2	4	3	1	
     3   1 / 3  	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      1 <-> 2   
     3      4   1 / 2      1 <-> 2   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 

# founder allele patterns: 1

Pattern #0: likelihood = 0.006//-5.116
IndID  Alleles
=====  =======
    1   1 / 2
    2   1 / 3
    3   2 / 1
    4   2 / 1
    5   1 / 1

Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   3 / ?  	4	0	
     1   1 / ?  	2	3	0	
     2   ? / ?  	2	4	3	1	
     3   1 / 2  	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      1 <-> 2   
     3      4   1 / 3      1 <-> 2   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
inheritance vector  000110
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	2	4	0	
     1   1 / 2  	3	0	
     2   1 / ?  	4	3	1	
     3   1 / ?  	2	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      0 <-> 3   
     3      4   1 / 2      1 <-> 2   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   ? / ?  	2	4	0	
     1   1 / 3  	3	0	
     2   ? / ?  	4	3	1	
     3   1 / ?  	2	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      0 <-> 3   
     3      4   1 / 3      1 <-> 2   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
inheritance vector  000111
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	4	0	
     1   1 / 2  	2	3	0	
     2   1 / ?  	4	3	1	
     3   1 / ?  	2	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      1 <-> 3   
     3      4   1 / 2      1 <-> 2   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   3 / ?  	4	0	
     1   1 / ?  	2	3	0	
     2   ? / ?  	4	3	1	
     3   1 / ?  	2	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      1 <-> 3   
     3      4   1 / 3      1 <-> 2   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
inheritance vector  001000
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	3	2	4	0	
     1   1 / 2  	0	
     2   1 / ?  	2	4	1	
     3   1 / ?  	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      0 <-> 2   
     3      4   1 / 2      0 <-> 3   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   ? / ?  	3	2	4	0	
     1   1 / 3  	0	
     2   ? / ?  	2	4	1	
     3   1 / ?  	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      0 <-> 2   
     3      4   1 / 3      0 <-> 3   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
inheritance vector  001001
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	3	4	0	
     1   1 / 2  	2	0	
     2   1 / ?  	2	4	1	
     3   1 / ?  	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      1 <-> 2   
     3      4   1 / 2      0 <-> 3   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   3 / ?  	3	4	0	
     1   1 / ?  	2	0	
     2   ? / ?  	2	4	1	
     3   1 / ?  	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      1 <-> 2   
     3      4   1 / 3      0 <-> 3   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
inheritance vector  001010
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	2	3	4	0	
     1   1 / 2  	0	
     2   1 / ?  	4	1	
     3   1 / ?  	2	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      0 <-> 3   
     3      4   1 / 2      0 <-> 3   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   ? / ?  	2	3	4	0	
     1   1 / 3  	0	
     2   2 / ?  	4	1	
     3   1 / ?  	2	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      0 <-> 3   
     3      4   1 / 3      0 <-> 3   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
inheritance vector  001011
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	3	4	0	
     1   1 / 2  	2	0	
     2   1 / ?  	4	1	
     3   1 / ?  	2	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      1 <-> 3   
     3      4   1 / 2      0 <-> 3   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: VALID with likelihood 0.006//-5.116
NodeID  Alleles 	Edges
======  ======= 	=====
     0   3 / ?  	3	4	0	
     1   1 / ?  	2	0	
     2   2 / ?  	4	1	
     3   1 / ?  	2	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      1 <-> 3   
     3      4   1 / 3      0 <-> 3   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 

# founder allele patterns: 1

Pattern #0: likelihood = 0.006//-5.116
IndID  Alleles
=====  =======
    1   3 / 1
    2   2 / 1
    3   1 / 1
    4   3 / 1
    5   3 / 2

inheritance vector  001100
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	2	4	0	
     1   1 / 2  	3	0	
     2   1 / ?  	2	4	1	
     3   1 / ?  	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      0 <-> 2   
     3      4   1 / 2      1 <-> 3   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   ? / ?  	2	4	0	
     1   1 / 3  	3	0	
     2   ? / ?  	2	4	1	
     3   1 / ?  	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      0 <-> 2   
     3      4   1 / 3      1 <-> 3   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 
inheritance vector  001101
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	4	0	
     1   1 / 2  	2	3	0	
     2   1 / ?  	2	4	1	
     3   1 / ?  	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      1 <-> 2   
     3      4   1 / 2      1 <-> 3   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   3 / ?  	4	0	
     1   1 / ?  	2	3	0	
     2   ? / ?  	2	4	1	
     3   1 / ?  	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      1 <-> 2   
     3      4   1 / 3      1 <-> 3   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 
inheritance vector  001110
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	2	4	0	
     1   1 / 2  	3	0	
     2   1 / ?  	4	1	
     3   1 / ?  	2	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      0 <-> 3   
     3      4   1 / 2      1 <-> 3   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   ? / ?  	2	4	0	
     1   1 / 3  	3	0	
     2   2 / ?  	4	1	
     3   1 / ?  	2	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      0 <-> 3   
     3      4   1 / 3      1 <-> 3   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
inheritance vector  001111
Marker 0
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   1 / ?  	4	0	
     1   1 / 2  	2	3	0	
     2   1 / ?  	4	1	
     3   1 / ?  	2	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 2      0 <-> 1   
     1      2   1 / 3      2 <-> 3   
     2      3   1 / 2      1 <-> 3   
     3      4   1 / 2      1 <-> 3   
     4      5   1 / 1      0 <-> 2   

Dirty Nodes: 
0 1 2 3 
Marker 1
Founder Allele Graph is: INVALID!
NodeID  Alleles 	Edges
======  ======= 	=====
     0   3 / ?  	4	0	
     1   1 / ?  	2	3	0	
     2   2 / ?  	4	1	
     3   1 / ?  	2	3	1	

EdgeID  IndID  Alleles  M.Node F.Node
======  =====  =======  ====== ======
     0      1   1 / 3      0 <-> 1   
     1      2   1 / 2      2 <-> 3   
     2      3   1 / 1      1 <-> 3   
     3      4   1 / 3      1 <-> 3   
     4      5   2 / 3      0 <-> 2   

Dirty Nodes: 
0 1 2 3 


Analysis complete!

