=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : one mean
    Mean covariates              :
          cov1                   : (Mean =      0.51800)
          cov2                   : (Mean =     -0.02241)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : 
    Transmission                 : homogeneous no transmission


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 100
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean                -0.06292000      0.05737329      0.00000000     Independent
  cov1                 1.98550940      0.11486579      0.00306052     Independent
  cov2                 2.99445050      0.05692197     -0.03403723     Independent
  variance             4.93868917      0.18039210     -0.04773499     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean            cov1            cov2            variance   
------------------------------------------------------------------------------
  mean       |      0.00329169      0.00000000      0.00000000      0.00000000
  cov1       |      0.00000000      0.01319415      0.00015135     -0.00000031
  cov2       |      0.00000000      0.00015135      0.00324011      0.00000071
  variance   |      0.00000000     -0.00000031      0.00000071      0.03254131
------------------------------------------------------------------------------

 Likelihood Surface Flat: variance matrix near singular and 
 may be affected by rounding error 
 Reducing the number of parameters to be estimated is recommended 

        LN(Likelihood) : -3326
     -2 LN(Likelihood) : 6651.99
    Akaike's AIC score : 6659.99
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Mean covariates              :
          cov1                   : (Mean =      0.51800)
          cov2                   : (Mean =     -0.02241)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : non Hardy-Weinberg equilibrium
    Transmission                 : homogeneous mendelian


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 100
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB          -1.81550919      0.06612087      0.00053249     Independent
  mean_BB              1.65158970      0.06519581      0.00041810     Independent
  cov1                 2.05970736      0.08721942      0.00020115     Independent
  cov2                 2.99677083      0.04433986      0.00101387     Independent
  variance             1.93368119      0.09153486      0.00007142     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.21401661      0.02831862      0.00055243     Independent functional
  prob_AB              0.25770697      0.03435681                     Dependent
  prob_BB              0.52827642      0.02396662      0.00000000     Independent functional
  freq_A               0.34287010      0.01982609                     Dependent
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.50000000                                     Fixed
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A     
--------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.00437197      0.00116726     -0.00012668      0.00003942      0.00097587      0.00015406      0.00029422     -0.00044828      0.00030117
  mean_BB    |      0.00116726      0.00425049     -0.00003214      0.00008639     -0.00097945     -0.00001849      0.00055331     -0.00053482      0.00025817
  cov1       |     -0.00012668     -0.00003214      0.00760723     -0.00004453      0.00012007      0.00007115     -0.00013600      0.00006486      0.00000315
  cov2       |      0.00003942      0.00008639     -0.00004453      0.00196602     -0.00007916      0.00000548      0.00002612     -0.00003160      0.00001854
  variance   |      0.00097587     -0.00097945      0.00012007     -0.00007916      0.00837863      0.00029910     -0.00047015      0.00017105      0.00006403
  prob_AA    |      0.00015406     -0.00001849      0.00007115      0.00000548      0.00029910      0.00080194     -0.00070397     -0.00009798      0.00044996
  prob_AB    |      0.00029422      0.00055331     -0.00013600      0.00002612     -0.00047015     -0.00070397      0.00118039     -0.00047642     -0.00011377
  prob_BB    |     -0.00044828     -0.00053482      0.00006486     -0.00003160      0.00017105     -0.00009798     -0.00047642      0.00057440     -0.00033619
  freq_A     |      0.00030117      0.00025817      0.00000315      0.00001854      0.00006403      0.00044996     -0.00011377     -0.00033619      0.00039307
--------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -3137.6
     -2 LN(Likelihood) : 6275.19
    Akaike's AIC score : 6289.19
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Mean covariates              :
          cov1                   : (Mean =      0.51800)
          cov2                   : (Mean =     -0.02241)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : non Hardy-Weinberg equilibrium
    Transmission                 : homogeneous mendelian


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 100
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA             -1.90191361      0.05985774      0.00007261     Independent
  mean_AB              1.10518646      0.08087303      0.00012496     Independent
  mean_BB              3.67301059      0.16597759     -0.00003760     Independent
  cov1                 1.97637076      0.08091978      0.00006988     Independent
  cov2                 3.01964708      0.04069048      0.00004574     Independent
  variance             1.40086264      0.07985613      0.00019717     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.47151509      0.02309515      0.00027621     Independent functional
  prob_AB              0.42584104      0.02533569                     Dependent
  prob_BB              0.10264387      0.01652632      0.00000000     Independent functional
  freq_A               0.68443561      0.01558134                     Dependent
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.50000000                                     Fixed
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A     
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.00358295      0.00164050     -0.00019313      0.00004588     -0.00004334      0.00155817      0.00044937     -0.00038965     -0.00005972      0.00025455
  mean_AB    |      0.00164050      0.00654045      0.00265702     -0.00004538     -0.00008884      0.00047436      0.00059976     -0.00016637     -0.00043339      0.00051657
  mean_BB    |     -0.00019313      0.00265702      0.02754856     -0.00033087      0.00037856     -0.00431213     -0.00004811      0.00129591     -0.00124779      0.00059984
  cov1       |      0.00004588     -0.00004538     -0.00033087      0.00654801      0.00005006      0.00010568     -0.00001476      0.00000977      0.00000499     -0.00000988
  cov2       |     -0.00004334     -0.00008884      0.00037856      0.00005006      0.00165572     -0.00017038     -0.00000314      0.00001764     -0.00001450      0.00000568
  variance   |      0.00155817      0.00047436     -0.00431213      0.00010568     -0.00017038      0.00637700      0.00031074     -0.00044831      0.00013758      0.00008658
  prob_AA    |      0.00044937      0.00059976     -0.00004811     -0.00001476     -0.00000314      0.00031074      0.00053339     -0.00045108     -0.00008230      0.00030784
  prob_AB    |     -0.00038965     -0.00016637      0.00129591      0.00000977      0.00001764     -0.00044831     -0.00045108      0.00064190     -0.00019082     -0.00013013
  prob_BB    |     -0.00005972     -0.00043339     -0.00124779      0.00000499     -0.00001450      0.00013758     -0.00008230     -0.00019082      0.00027312     -0.00017771
  freq_A     |      0.00025455      0.00051657      0.00059984     -0.00000988      0.00000568      0.00008658      0.00030784     -0.00013013     -0.00017771      0.00024278
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -3116.45
     -2 LN(Likelihood) : 6232.9
    Akaike's AIC score : 6248.9
=====================================================================================================

%SEGREG-W: Accumulation of round off errors or boundary problem 
%SEGREG-W: Check results carefully 


