=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : one mean
    Mean covariates              :
          cov1                   : (Mean =      0.51800)
          cov2                   : (Mean =     -0.02241)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : 
    Transmission                 : homogeneous no transmission


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 100
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean                -0.06292000      0.05737329      0.00000000     Independent
  cov1                 1.98550940      0.11486579      0.00306052     Independent
  cov2                 2.99445050      0.05692197     -0.03403723     Independent
  variance             4.93868917      0.18039210     -0.04773499     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean            cov1            cov2            variance   
------------------------------------------------------------------------------
  mean       |      0.00329169      0.00000000      0.00000000      0.00000000
  cov1       |      0.00000000      0.01319415      0.00015135     -0.00000031
  cov2       |      0.00000000      0.00015135      0.00324011      0.00000071
  variance   |     -0.00000000     -0.00000031      0.00000071      0.03254131
------------------------------------------------------------------------------


        LN(Likelihood) : -3326
     -2 LN(Likelihood) : 6651.99
    Akaike's AIC score : 6659.99
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Mean covariates              :
          cov1                   : (Mean =      0.51800)
          cov2                   : (Mean =     -0.02241)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : mitochondrial


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 100
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB           1.61022749      0.06220754      0.00000000     Independent
  mean_BB             -1.75766673      0.06506375      0.00000000     Independent
  cov1                 2.00357495      0.08340144      0.00000000     Independent
  cov2                 2.97771739      0.04169639      0.00000000     Independent
  variance             2.10194496      0.08459416     -0.00006570     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.08631696      0.00938410                     Dependent
  prob_AB              0.41496104      0.01317251                     Dependent
  prob_BB              0.49872200      0.02255662                     Dependent
  freq_A               0.29379748      0.01597036      0.00000000     Independent functional
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A     
--------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.00386978      0.00102343      0.00002436      0.00007943     -0.00012961     -0.00015023     -0.00021088      0.00036112     -0.00025568
  mean_BB    |      0.00102343      0.00423329      0.00001477      0.00011716      0.00062535     -0.00017049     -0.00023932      0.00040981     -0.00029015
  cov1       |      0.00002436      0.00001477      0.00695580      0.00016169      0.00004324      0.00000741      0.00001040     -0.00001781      0.00001261
  cov2       |      0.00007943      0.00011716      0.00016169      0.00173859      0.00000347     -0.00001308     -0.00001836      0.00003144     -0.00002226
  variance   |     -0.00012961      0.00062535      0.00004324      0.00000347      0.00715617     -0.00003012     -0.00004228      0.00007240     -0.00005126
  prob_AA    |     -0.00015023     -0.00017049      0.00000741     -0.00001308     -0.00003012      0.00008806      0.00012361     -0.00021167      0.00014987
  prob_AB    |     -0.00021088     -0.00023932      0.00001040     -0.00001836     -0.00004228      0.00012361      0.00017352     -0.00029713      0.00021037
  prob_BB    |      0.00036112      0.00040981     -0.00001781      0.00003144      0.00007240     -0.00021167     -0.00029713      0.00050880     -0.00036024
  freq_A     |     -0.00025568     -0.00029015      0.00001261     -0.00002226     -0.00005126      0.00014987      0.00021037     -0.00036024      0.00025505
--------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -3051.18
     -2 LN(Likelihood) : 6102.35
    Akaike's AIC score : 6114.35
=====================================================================================================

%SEGREG-W: Accumulation of round off errors or boundary problem 
%SEGREG-W: Check results carefully 


