



Family structure information on the first 1000 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     0             1             1         0_parent1     0_parent2   
     0             2             2         0_parent1     0_parent2   
     0             3             1         0_parent1     0_parent2   
     0             4             2         0_parent1     0_parent2   
     0             5             1         0_parent1     0_parent2   
     0             6             2         0_parent1     0_parent2   
     0             7             1         0_parent1     0_parent2   
     0             8             2         0_parent1     0_parent2   
     0             9             1         0_parent1     0_parent2   
     0             10            2         0_parent1     0_parent2   


Phenotypes for the first 1000 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE       
     ------------  ------------  --------------------  --------------------  --------------------  --------------------
     0             1             0                     1                     0                     12                  
     0             2             1                     1                     0                     12                  
     0             3             0                     1                     0                     12                  
     0             4             1                     1                     0                     12                  
     0             5             0                     1                     0                     12                  
     0             6             1                     1                     0                     12                  
     0             7             0                     1                     0                     12                  
     0             8             1                     1                     0                     12                  
     0             9             0                     1                     0                     12                  
     0             10            1                     1                     0                     12                  

