


Reading Parameter File....................done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Reading pairs.............................done.
Sorting pairs.............................done.

  No analyses specified.
Performing default analysis...

Performing mean tests.....................done.
Performing trait regressions..............done.

Analysis complete!



