



Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     3             5             1         0             0           
     3             6             2         0             0           
     3             483           2         5             6           
     3             484           2         5             6           
     3             485           1         5             6           
     4             7             1         0             0           
     4             8             2         0             0           
     4             486           2         7             8           
     4             487           1         7             8           
     5             9             1         0             0           


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         Q1                    Q2                    marker1_ADD_A         M2_DOM_B              M3_ADD_A              M4_ADD_A              M5_ADD_A            
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     3             5             0                     1                     1                     5                     27.984                23.3207               0                     ?                     2                     1                     1                   
     3             6             1                     1                     1                     5                     28.162                24.0919               2                     0                     1                     1                     0                   
     3             483           1                     1                     0                     5                     21.642                30.1111               1                     0                     1                     1                     1                   
     3             484           1                     1                     0                     5                     31.999                22.101                1                     0                     1                     0                     0                   
     3             485           0                     1                     0                     5                     35.381                14.1793               1                     0                     1                     1                     1                   
     4             7             0                     1                     1                     4                     32.321                27.1019               2                     0                     0                     0                     1                   
     4             8             1                     1                     1                     4                     37.427                30.5959               0                     1                     1                     1                     2                   
     4             486           1                     1                     0                     4                     31.882                31.3736               1                     1                     0                     1                     2                   
     4             487           0                     1                     0                     4                     41.825                5.9521                1                     0                     0                     1                     1                   
     5             9             0                     1                     1                     4                     24.813                26.772                1                     0                     1                     0                     1                   

%AGEON-E: Could not evaluate function block expression 'add(M1, 'A')' for one
          or more individuals.  Missing value(s) generated.

New phenotypes for individuals created by function block(s) :

     PED. ID       IND. ID       M1_add              
     ------------  ------------  --------------------
     3             5                                 
     3             6                                 
     3             483                               
     3             484                               
     3             485                               
     4             7                                 
     4             8                                 
     4             486                               
     4             487                               
     5             9                                 


%AGEON-E: 
