pedigree 1, subpedigree 1:2, member 1, log likelihood -4.55429, lod score  0.255273
pedigree 1, subpedigree 1:2, member 5, log likelihood -4.55429, lod score  0.255273
pedigree 1, subpedigree 1:2, member 4, log likelihood -4.55429, lod score  0.255273
pedigree 1, subpedigree 1:2, member 2, log likelihood -4.55429, lod score  0.255273
pedigree 1, subpedigree 1:2, member 3, log likelihood -4.55429, lod score  0.255273
