



Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             m         -1            -1          
     1             2             f         -1            -1          
     1             3             m         1             2           
     1             4             m         1             2           
     1             5             f         1             2           
     2             1             m         -1            -1          
     2             2             f         -1            -1          
     2             3             m         1             2           
     2             4             m         1             2           
     2             5             f         1             2           


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         AFF                   cluster_var         
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     5                     0                     1                   
     1             2             1                     1                     1                     5                     0                     1                   
     1             3             0                     1                     0                     5                     0                     1                   
     1             4             0                     1                     0                     5                     1                     1                   
     1             5             1                     1                     0                     5                     1                     1                   
     2             1             0                     1                     1                     5                     0                     2                   
     2             2             1                     1                     1                     5                     0                     2                   
     2             3             0                     1                     0                     5                     0                     2                   
     2             4             0                     1                     0                     5                     0                     2                   
     2             5             1                     1                     0                     5                     0                     2                   


New phenotypes for individuals created by function block(s) :

     PED. ID       IND. ID       m                   
     ------------  ------------  --------------------
     1             1             0                   
     1             2             0                   
     1             3             0                   
     1             4             0                   
     1             5             0                   
     2             1             1                   
     2             2             1                   
     2             3             0                   
     2             4             2                   
     2             5             0                   


Beginning new analysis block....

%ASSOC-I: Variance of Polygenic effect converged to 1e-07 for model 'Baseline'.
          Remaximizing without Polygenic effect ...
