



Family structure information on the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             M         0             0           
     1             2             M         0             0           
     1             3             M         0             0           
     1             4             M         0             0           
     1             5             M         0             0           
     1             6             M         0             0           
     1             7             M         0             0           
     1             8             M         0             0           
     1             9             M         0             0           
     1             10            M         0             0           


Phenotypes for the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE       
     ------------  ------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     10                  
     1             2             0                     1                     1                     10                  
     1             3             0                     1                     1                     10                  
     1             4             0                     1                     1                     10                  
     1             5             0                     1                     1                     10                  
     1             6             0                     1                     1                     10                  
     1             7             0                     1                     1                     10                  
     1             8             0                     1                     1                     10                  
     1             9             0                     1                     1                     10                  
     1             10            0                     1                     1                     10                  


Markers for the first 20 individuals read from file: ped

     PED. ID       IND. ID       M0            M1            M2            M3            M4          
     ------------  ------------  ------------  ------------  ------------  ------------  ------------
     1             1             a/a           a/a           q/q           A/a           A/a         
     1             2             a/A           a/A           Q/Q           A/a           a/a         
     1             3             a/A           a/A           Q/Q           a/a           A/a         
     1             4             a/a           a/A           q/Q           A/a           A/a         
     1             5             a/a           a/a           q/Q           A/a           A/a         
     1             6             a/A           a/a           q/q           A/A           A/a         
     1             7             a/a           a/A           q/Q           A/a           A/a         
     1             8             A/A           a/a           q/Q           A/a           A/a         
     1             9             a/A           a/a           q/Q           a/a           A/A         
     1             10            A/A           a/a           q/Q           a/a           A/a         

%DECIPHER-I: Mapping function not specified.  Using Haldane Mapping Function.
%DECIPHER-E: Parameter 'ALL_POSSIBLE_DIPLOTYPES' in tasks sub-block not
             recognized.  Ignoring parameter ...

  Performing analysis: Analysis 1
  ===========================================================================

    Total population. 
      Determining possible haplotype combinations ................... done.

  ===========================================================================

