MARKER MODELS:
============================

M0
----------------------------

Alleles:
A	= 0.500000	a	= 0.500000	

Genotype    Genotypic Frequency
     A/A     0.250000
     A/a     0.500000
     a/a     0.250000

M1
----------------------------

Alleles:
A	= 0.500000	a	= 0.500000	

Genotype    Genotypic Frequency
     A/A     0.250000
     A/a     0.500000
     a/a     0.250000

M2
----------------------------

Alleles:
Q	= 0.500000	q	= 0.500000	

Genotype    Genotypic Frequency
     Q/Q     0.250000
     Q/q     0.500000
     q/q     0.250000

M3
----------------------------

Alleles:
A	= 0.500000	a	= 0.500000	

Genotype    Genotypic Frequency
     A/A     0.250000
     A/a     0.500000
     a/a     0.250000

M4
----------------------------

Alleles:
A	= 0.500000	a	= 0.500000	

Genotype    Genotypic Frequency
     A/A     0.250000
     A/a     0.500000
     a/a     0.250000

