


==========
Analysis 1
==========


Markers in order:
  M2 M3 



                      All Possible Haplotype Combinations


                    Pedigree:Member
          1:1  1:10 1:2  1:3  1:4  1:5  1:6  1:7  1:8  1:9  
Q-A  Q-a   -    -    x    -    -    -    -    -    -    -   
Q-A  q-a   -    -    -    -    x    x    -    x    x    -   
Q-a  Q-a   -    -    -    x    -    -    -    -    -    -   
Q-a  q-A   -    -    -    -    x    x    -    x    x    -   
Q-a  q-a   -    x    -    -    -    -    -    -    -    x   
q-A  q-A   -    -    -    -    -    -    x    -    -    -   
q-A  q-a   x    -    -    -    -    -    -    -    -    -   


