



Family structure information on the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             M         0             0           
     1             2             M         0             0           
     1             3             M         0             0           
     1             4             M         0             0           
     1             5             M         0             0           
     1             6             M         0             0           
     1             7             M         0             0           
     1             8             M         0             0           
     1             9             M         0             0           
     1             10            M         0             0           


Phenotypes for the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE       
     ------------  ------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     10                  
     1             2             0                     1                     1                     10                  
     1             3             0                     1                     1                     10                  
     1             4             0                     1                     1                     10                  
     1             5             0                     1                     1                     10                  
     1             6             0                     1                     1                     10                  
     1             7             0                     1                     1                     10                  
     1             8             0                     1                     1                     10                  
     1             9             0                     1                     1                     10                  
     1             10            0                     1                     1                     10                  


Markers for the first 20 individuals read from file: ped

     PED. ID       IND. ID       M0            M1            M2            M3            M4          
     ------------  ------------  ------------  ------------  ------------  ------------  ------------
     1             1             c/c           a/a           q/q           A/a           B/b         
     1             2             C/c           A/a           Q/Q           A/a           b/b         
     1             3             C/c           A/a           Q/Q           a/a           B/b         
     1             4             c/c           A/a           Q/q           A/a           B/b         
     1             5             c/c           a/a           Q/q           A/a           B/b         
     1             6             c/c           a/a           q/q           A/A           B/b         
     1             7             c/c           A/a           Q/q           A/a           B/b         
     1             8             C/C           a/a           Q/q           A/a           b/b         
     1             9             C/c           a/a           Q/q           a/a           B/B         
     1             10            C/c           a/a           Q/q           a/a           B/b         


  Performing analysis: Analysis 1
  ===========================================================================

%DECIPHER-I: Marker, M3, omitted from the current region on the basis of low
             minor allele frequency ...
%DECIPHER-I: Marker, M1, omitted from the current region on the basis of low
             minor allele frequency ...
    Total population. 
      Determining possible haplotype combinations ................... done.
      Maximizing likelihood ......................................... done. 

  ===========================================================================

