


Reading Parameter File....................done.
Reading Marker Locus Description File.....done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Reading Genome Description File...........done.

GENIBD analysis.......  1

===========================================================================
Analysis 1 : Multipoint analysis on region (CHR3):
        * - Maximum size for exact method is set to 18.
===========================================================================

  Processing Region: CHR3
  =======================================

  Analysis 1: Pedigree 6

    Subpedigree 1 of pedigree '6' : founders (1, 2)

        Generating Marker Likelihoods      ....................Done.
        Generating Multipoint Combined Info....................Done.
        Generating Multipoint IBDs         ....................Done.

    Subpedigree 2 of pedigree '6' : founders (11, 22)

        Generating Marker Likelihoods      ....................Done.
        Generating Multipoint Combined Info....................Done.
        Generating Multipoint IBDs         ....................Done.

  Analysis 1: Pedigree 7
        Generating Marker Likelihoods      ....................Done.
        Generating Multipoint Combined Info....................Done.
        Generating Multipoint IBDs         ....................Done.

  Analysis 1: Pedigree 8
        Generating Marker Likelihoods      ....................Done.
        Generating Multipoint Combined Info....................Done.
        Generating Multipoint IBDs         ....................Done.


Analysis complete!



