


==========
Analysis 1
==========


Markers in order:
  C01R0002 C01R0003 C01R0004 



                      All Possible Haplotype Combinations


                        Pedigree:Member
              17:2 17:3 17:4 32:2 32:3 32:4 32:5 
1-1-1          x    -    -    -    -    -    x   
1-2-1  1-2-1   -    x    -    -    -    -    -   
1-2-2  1-2-2   -    -    -    -    x    x    -   
2-2-2  2-2-2   -    -    x    x    -    -    -   


