


==========
Analysis 1
==========


Markers in order:
  M1 M2 



                      Most Likely Haplotype Combinations


Note:  Haplotype combinations listed have estimated probabilities greater than or equal
       to the cutoff or have the greatest probability estimate.

Pool     Combination     Probability
----     -----------     -----------
1:1      a-A  a-a        1.00000
1:10     A-a  a-a        1.00000
1:2      A-A  A-a        1.00000
1:3      A-a  A-a        1.00000
1:4      A-a  a-A        0.934723
         A-A  a-a        0.0652768
1:5      A-a  a-A        0.934723
         A-A  a-a        0.0652768
1:6      a-A  a-A        1.00000
1:7      A-a  a-A        0.934723
         A-A  a-a        0.0652768
1:8      A-a  a-A        0.934723
         A-A  a-a        0.0652768
1:9      A-a  a-a        1.00000




                      All Possible Haplotype Combinations


                    Pool
          1:1  1:10 1:2  1:3  1:4  1:5  1:6  1:7  1:8  1:9  
A-A  A-a   -    -    x    -    -    -    -    -    -    -   
A-A  a-a   -    -    -    -    x    x    -    x    x    -   
A-a  A-a   -    -    -    x    -    -    -    -    -    -   
A-a  a-A   -    -    -    -    x    x    -    x    x    -   
A-a  a-a   -    x    -    -    -    -    -    -    -    x   
a-A  a-A   -    -    -    -    -    -    x    -    -    -   
a-A  a-a   x    -    -    -    -    -    -    -    -    -   


