



Family structure information on the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             M         0             0           
     1             2             M         0             0           
     1             3             M         0             0           
     1             4             M         0             0           
     1             5             M         0             0           
     1             6             F         0             0           
     1             7             F         0             0           
     1             8             F         0             0           
     1             9             F         0             0           
     1             10            F         0             0           


Phenotypes for the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         M1                    M2                  
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     10                    0                     0.5                 
     1             2             0                     1                     1                     10                    1                     0.5                 
     1             3             0                     1                     1                     10                    1                     0                   
     1             4             0                     1                     1                     10                    0.5                   0.5                 
     1             5             0                     1                     1                     10                    0.5                   0.5                 
     1             6             1                     1                     1                     10                    0                     1                   
     1             7             1                     1                     1                     10                    0.5                   0.5                 
     1             8             1                     1                     1                     10                    0.5                   0.5                 
     1             9             1                     1                     1                     10                    0.5                   0                   
     1             10            1                     1                     1                     10                    0.5                   0                   


  Performing analysis: Analysis 1
  ===========================================================================

    Total population. 
      Determining possible haplotype combinations ................... done.
      Maximizing likelihood ......................................... done. 

  ===========================================================================

