#!/usr/bin/bash
#============================================================================
# File:      newexps
#                                                                          
# Author:    Dan Baechle
#                                                                          
# History:   Created 12/12/01           djb
#                                                                          
# Notes:     Script for updating the 'expected' files for runtest12.
#                                                                          
# Copyright (c) 2001 R.C. Elston                                           
# All Rights Reserved                                                    
#============================================================================

cp testparser.out testparser.out.exp
cp testparser.inf testparser.inf.exp
cd ..
runtest12