



Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     F1            I1            M         0             0           
     F1            I2            F         0             0           
     F1            I3            M         0             0           
     F1            I4            F         0             0           
     F1            I5            M         I1            I2          
     F1            I6            F         0             0           
     F1            I7            M         I3            I4          
     F1            I8            M         I3            I4          
     F1            I9            F         I3            I4          
     F1            I10           F         I5            I6          


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       Trait1              
     ------------  ------------  --------------------
     F1            I1            2                   
     F1            I2            6                   
     F1            I3            4                   
     F1            I4            4                   
     F1            I5            4                   
     F1            I6            6                   
     F1            I7            4                   
     F1            I8            2                   
     F1            I9            6                   
     F1            I10           6                   

