


==============================================================================
  Haseman-Elston Regression Analysis of Full Sibs
  - single marker regression
==============================================================================

    Continuous trait : Trait1

    Dependent variate : Weighted square trait sum and difference (W2)

    w1 : 0.5

    Other options used :
      Identity weights = no
      Robust variance  = no
      Use sibship mean = no
      Use BLUP mean    = yes

    Legend :
      Note - kurtosis = coefficient of kurtosis - 3
      *   - significance  .05 level;
      **  - significance  .01 level;
      *** - significance .001 level;
      #   - Negative intercept set to 0;

==============================================================================
Test  Independent                                                 Nominal     
No.   variable          Pairs   Parameter    Estimate Std Error   P-value     
----- ----------------- ----- ----------- ----------- --------- ---------     
1     Marker               19 (A+D)GenVar     1.4780 #   1.0664 0.0913318     
==============================================================================


