
Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             F                                   
     1             2             M                                   
     1             3             M         1             2           
     1             4             F         1             2           
     1             5             M                                   
     1             6             F         4             5           


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         DISEASE               HEMATOCRIT            t                     u                     v                     w                     x                     y                     z                   
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             1                     1                     1                     6                     1                     30                    1                     2                     3                     4                     5                     6                     7                   
     1             2             0                     1                     1                     6                     0                     40                    1                     2                     3                     4                     5                     6                     7                   
     1             3             0                     1                     0                     6                     0                     27.1                  1                     2                     3                     4                     5                     6                     7                   
     1             4             1                     1                     0                     6                     1                     39                    1                     2                     3                     4                     5                     6                     7                   
     1             5             0                     1                     1                     6                     0                     37.6                  1                     2                     3                     4                     5                     6                     7                   
     1             6             1                     1                     0                     6                     1                     41.1                  1                     2                     3                     4                     5                     6                     7                   

%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 1 New Analysis Block 1 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Critical:Option, two variances, specified in type_var
                           sub-block with option, one mean, specified in
                           type_mean sub-block.  Skipping analysis ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 2 New Analysis Block 2 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 3 New Analysis Block 3 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:geno_freq sub-block not relevant for one type. 
                        Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 4 New Analysis Block 4 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:geno_freq sub-block not relevant for one type. 
                        Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 5 New Analysis Block 5 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:type_var sub-block specified with mean sub-block
                        specified and transmission sub-block not specified. 
                        Ignoring type_var sub-block ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 6 New Analysis Block 6 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:geno_freq sub-block specified with mean or suscept
                        sub-block specified and transmission sub-block not
                        specified.  Ignoring geno_freq sub-block ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 7 New Analysis Block 7 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:geno_freq sub-block specified with mean or suscept
                        sub-block specified and transmission sub-block not
                        specified.  Ignoring geno_freq sub-block ...
