#! Type Probability File, version 1.1.
#  This file is automatically generated.  Do not edit!

Model="mendel",title="Three Mean Model - Mendelian"
{
  alleles
  {
    A = 0.5
    B = 0.5
  }
  pedigree=1
  {
    individual=1, type=founder
    {
      A_A=1
    }
    individual=10, type=nonfounder
    {
      A_A=1
    }
    individual=2, type=founder
    {
      A_A=1
    }
    individual=3, type=nonfounder
    {
      A_A=1
    }
    individual=4, type=nonfounder
    {
      A_A=1
    }
    individual=5, type=nonfounder
    {
      A_A=1
    }
    individual=6, type=nonfounder
    {
      A_A=1
    }
    individual=7, type=nonfounder
    {
      A_A=1
    }
    individual=8, type=nonfounder
    {
      A_A=1
    }
    individual=9, type=nonfounder
    {
      A_A=1
    }
  }
  pedigree=2
  {
    individual=1, type=founder
    {
      A_B=0.99998
      B_B=2.02238e-05
    }
    individual=10, type=nonfounder
    {
      A_B=0.992007
      B_B=0.00799251
    }
    individual=2, type=founder
    {
      A_B=0.999999
    }
    individual=3, type=nonfounder
    {
      A_B=0.99998
      B_B=2.00296e-05
    }
    individual=4, type=nonfounder
    {
      A_B=0.999999
    }
    individual=5, type=nonfounder
    {
      A_B=0.998114
      B_B=0.00188572
    }
    individual=6, type=nonfounder
    {
      A_B=0.999915
      B_B=8.54113e-05
    }
    individual=7, type=nonfounder
    {
      A_B=0.999999
    }
    individual=8, type=nonfounder
    {
      A_A=4.0214e-05
      A_B=0.99996
    }
    individual=9, type=nonfounder
    {
      A_A=0.000267652
      A_B=0.999732
    }
  }
  pedigree=3
  {
    individual=1, type=founder
    {
      B_B=1
    }
    individual=10, type=nonfounder
    {
      B_B=1
    }
    individual=2, type=founder
    {
      B_B=0.999999
    }
    individual=3, type=nonfounder
    {
      B_B=1
    }
    individual=4, type=nonfounder
    {
      B_B=1
    }
    individual=5, type=nonfounder
    {
      B_B=1
    }
    individual=6, type=nonfounder
    {
      B_B=1
    }
    individual=7, type=nonfounder
    {
      B_B=1
    }
    individual=8, type=nonfounder
    {
      B_B=1
    }
    individual=9, type=nonfounder
    {
      B_B=1
    }
  }
  pedigree=4
  {
    individual=1, type=founder
    {
      A_A=1
    }
    individual=2, type=founder
    {
      A_B=1
    }
    individual=3, type=nonfounder
    {
      A_A=1
    }
    individual=4, type=nonfounder
    {
      A_A=1
    }
    individual=5, type=nonfounder
    {
      A_B=1
    }
    individual=6, type=nonfounder
    {
      A_B=1
    }
  }
  pedigree=5
  {
    individual=1, type=founder
    {
      A_A=1
    }
    individual=2, type=founder
    {
      A_B=9.24422e-06
      B_B=0.999991
    }
    individual=3, type=nonfounder
    {
      A_B=1
    }
    individual=4, type=nonfounder
    {
      A_B=1
    }
    individual=5, type=nonfounder
    {
      A_B=1
    }
    individual=6, type=nonfounder
    {
      A_B=1
    }
  }
  pedigree=6
  {
    individual=1, type=founder
    {
      A_B=1
    }
    individual=2, type=founder
    {
      A_B=1
    }
    individual=3, type=nonfounder
    {
      A_A=1
    }
    individual=4, type=nonfounder
    {
      A_B=0.999999
    }
    individual=5, type=nonfounder
    {
      A_B=0.99998
      B_B=2.00292e-05
    }
    individual=6, type=nonfounder
    {
      A_B=0.000147887
      B_B=0.999852
    }
  }
  pedigree=7
  {
    individual=1, type=founder
    {
      A_B=1
    }
    individual=2, type=founder
    {
      A_B=1
    }
    individual=3, type=nonfounder
    {
      A_B=0.99998
      B_B=2.00292e-05
    }
    individual=4, type=nonfounder
    {
      A_B=0.999999
    }
    individual=5, type=nonfounder
    {
      A_B=6.68723e-06
      B_B=0.999993
    }
    individual=6, type=nonfounder
    {
      A_B=0.000147887
      B_B=0.999852
    }
    individual=7, type=nonfounder
    {
      A_A=1
    }
  }
}
