#! Type Probability File, version 1.1.
#  This file is automatically generated.  Do not edit!

Model="mendel",title="Three Mean Model - Mendelian"
{
  alleles
  {
    A = 0.5
    B = 0.5
  }
  pedigree=1
  {
    individual=1, type=founder
    {
      genotype="A/A",penetrance=1
    }
    individual=10, type=nonfounder
    {
      genotype="A/A",penetrance=1
    }
    individual=2, type=founder
    {
      genotype="A/A",penetrance=1
    }
    individual=3, type=nonfounder
    {
      genotype="A/A",penetrance=1
    }
    individual=4, type=nonfounder
    {
      genotype="A/A",penetrance=1
    }
    individual=5, type=nonfounder
    {
      genotype="A/A",penetrance=1
    }
    individual=6, type=nonfounder
    {
      genotype="A/A",penetrance=1
    }
    individual=7, type=nonfounder
    {
      genotype="A/A",penetrance=1
    }
    individual=8, type=nonfounder
    {
      genotype="A/A",penetrance=1
    }
    individual=9, type=nonfounder
    {
      genotype="A/A",penetrance=1
    }
  }
  pedigree=2
  {
    individual=1, type=founder
    {
      genotype="A/B",penetrance=0.99998
      genotype="B/B",penetrance=2.02238e-05
    }
    individual=10, type=nonfounder
    {
      genotype="A/B",penetrance=0.992007
      genotype="B/B",penetrance=0.00799251
    }
    individual=2, type=founder
    {
      genotype="A/B",penetrance=0.999999
    }
    individual=3, type=nonfounder
    {
      genotype="A/B",penetrance=0.99998
      genotype="B/B",penetrance=2.00296e-05
    }
    individual=4, type=nonfounder
    {
      genotype="A/B",penetrance=0.999999
    }
    individual=5, type=nonfounder
    {
      genotype="A/B",penetrance=0.998114
      genotype="B/B",penetrance=0.00188572
    }
    individual=6, type=nonfounder
    {
      genotype="A/B",penetrance=0.999915
      genotype="B/B",penetrance=8.54113e-05
    }
    individual=7, type=nonfounder
    {
      genotype="A/B",penetrance=0.999999
    }
    individual=8, type=nonfounder
    {
      genotype="A/A",penetrance=4.0214e-05
      genotype="A/B",penetrance=0.99996
    }
    individual=9, type=nonfounder
    {
      genotype="A/A",penetrance=0.000267652
      genotype="A/B",penetrance=0.999732
    }
  }
  pedigree=3
  {
    individual=1, type=founder
    {
      genotype="B/B",penetrance=1
    }
    individual=10, type=nonfounder
    {
      genotype="B/B",penetrance=1
    }
    individual=2, type=founder
    {
      genotype="B/B",penetrance=0.999999
    }
    individual=3, type=nonfounder
    {
      genotype="B/B",penetrance=1
    }
    individual=4, type=nonfounder
    {
      genotype="B/B",penetrance=1
    }
    individual=5, type=nonfounder
    {
      genotype="B/B",penetrance=1
    }
    individual=6, type=nonfounder
    {
      genotype="B/B",penetrance=1
    }
    individual=7, type=nonfounder
    {
      genotype="B/B",penetrance=1
    }
    individual=8, type=nonfounder
    {
      genotype="B/B",penetrance=1
    }
    individual=9, type=nonfounder
    {
      genotype="B/B",penetrance=1
    }
  }
  pedigree=4
  {
    individual=1, type=founder
    {
      genotype="A/A",penetrance=1
    }
    individual=2, type=founder
    {
      genotype="A/B",penetrance=1
    }
    individual=3, type=nonfounder
    {
      genotype="A/A",penetrance=1
    }
    individual=4, type=nonfounder
    {
      genotype="A/A",penetrance=1
    }
    individual=5, type=nonfounder
    {
      genotype="A/B",penetrance=1
    }
    individual=6, type=nonfounder
    {
      genotype="A/B",penetrance=1
    }
  }
  pedigree=5
  {
    individual=1, type=founder
    {
      genotype="A/A",penetrance=1
    }
    individual=2, type=founder
    {
      genotype="A/B",penetrance=9.24422e-06
      genotype="B/B",penetrance=0.999991
    }
    individual=3, type=nonfounder
    {
      genotype="A/B",penetrance=1
    }
    individual=4, type=nonfounder
    {
      genotype="A/B",penetrance=1
    }
    individual=5, type=nonfounder
    {
      genotype="A/B",penetrance=1
    }
    individual=6, type=nonfounder
    {
      genotype="A/B",penetrance=1
    }
  }
  pedigree=6
  {
    individual=1, type=founder
    {
      genotype="A/B",penetrance=1
    }
    individual=2, type=founder
    {
      genotype="A/B",penetrance=1
    }
    individual=3, type=nonfounder
    {
      genotype="A/A",penetrance=1
    }
    individual=4, type=nonfounder
    {
      genotype="A/B",penetrance=0.999999
    }
    individual=5, type=nonfounder
    {
      genotype="A/B",penetrance=0.99998
      genotype="B/B",penetrance=2.00292e-05
    }
    individual=6, type=nonfounder
    {
      genotype="A/B",penetrance=0.000147887
      genotype="B/B",penetrance=0.999852
    }
  }
  pedigree=7
  {
    individual=1, type=founder
    {
      genotype="A/B",penetrance=1
    }
    individual=2, type=founder
    {
      genotype="A/B",penetrance=1
    }
    individual=3, type=nonfounder
    {
      genotype="A/B",penetrance=0.99998
      genotype="B/B",penetrance=2.00292e-05
    }
    individual=4, type=nonfounder
    {
      genotype="A/B",penetrance=0.999999
    }
    individual=5, type=nonfounder
    {
      genotype="A/B",penetrance=6.68723e-06
      genotype="B/B",penetrance=0.999993
    }
    individual=6, type=nonfounder
    {
      genotype="A/B",penetrance=0.000147887
      genotype="B/B",penetrance=0.999852
    }
    individual=7, type=nonfounder
    {
      genotype="A/A",penetrance=1
    }
  }
}
