=====================

     Analysis #1

=====================

  Transmission type:        Allele             
  Marker:                   m                  
  Trait:                    Trait1             
  Parental trait:           Not specified      
  Parental sex(es) scored:  Paternal/maternal  
  Max. children/family:                     1  
  Max. sib pairs/family:                    0  

---------------------------------------
  T/NT  0       1      2       3       
---------------------------------------
  0      30968   6960    7960    9960  
  1       6960   2552    3768    6344  
  2       7960   3768    6608   11568  
  3       9960   6344   11568   22880  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       90592       102400   0.884687      
  Families                        90592       102400   0.884687      
  Affected children               90592        90592   1.000000      
  Affected sib pairs                  0            0   0.000000      
  Sample size                     93120       156128   0.596434      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

  Transmission type:        Allele         
  Marker:                   m              
  Trait:                    Trait1         
  Parental trait:           Not specified  
  Parental sex(es) scored:  Paternal       
  Max. children/family:                 1  
  Max. sib pairs/family:                0  

-------------------------------------
  T/NT  0       1      2      3      
-------------------------------------
  0      29400   5800   5640   5320  
  1       5800   1176   1128   1064  
  2       5640   1128   1104   1008  
  3       5320   1064   1008    864  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       72464       102400   0.707656      
  Families                        72464       102400   0.707656      
  Affected children               72464        72464   1.000000      
  Affected sib pairs                  0            0   0.000000      
  Sample size                     39920        72464   0.550894      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

  Transmission type:        Allele         
  Marker:                   m              
  Trait:                    Trait1         
  Parental trait:           Not specified  
  Parental sex(es) scored:  Maternal       
  Max. children/family:                 1  
  Max. sib pairs/family:                0  

--------------------------------------
  T/NT  0      1      2       3       
--------------------------------------
  0       768   1080    2160    4320  
  1      1080   1344    2608    5216  
  2      2160   2608    5376   10432  
  3      4320   5216   10432   21504  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       80624       102400   0.787344      
  Families                        80624       102400   0.787344      
  Affected children               80624        80624   1.000000      
  Affected sib pairs                  0            0   0.000000      
  Sample size                     51632        80624   0.640405      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

=====================

     Analysis #2

=====================

  Transmission type:        Allele             
  Marker:                   m                  
  Trait:                    Trait1             
  Parental trait:           Not specified      
  Parental sex(es) scored:  Paternal/maternal  
  Max. children/family:                     0  
  Max. sib pairs/family:                    1  

--------------------------------------
  T/NT  0       1      2      3       
--------------------------------------
  0      28072   3248   3796    4892  
  1       3248   2216   1668    2796  
  2       3796   1668   5616    5064  
  3       4892   2796   5064   19232  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       66024       102400   0.644766      
  Families                        66024       102400   0.644766      
  Affected children                   0            0   0.000000      
  Affected sib pairs              66024        73888   0.893569      
  Sample size                     42928        98064   0.437755      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

  Transmission type:        Allele         
  Marker:                   m              
  Trait:                    Trait1         
  Parental trait:           Not specified  
  Parental sex(es) scored:  Paternal       
  Max. children/family:                 0  
  Max. sib pairs/family:                1  

-------------------------------------
  T/NT  0       1      2      3      
-------------------------------------
  0      26600   2620   2540   2380  
  1       2620   1064    508    476  
  2       2540    508   1008    424  
  3       2380    476    424    800  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       47368       102400   0.462578      
  Families                        47368       102400   0.462578      
  Affected children                   0            0   0.000000      
  Affected sib pairs              47368        73888   0.641078      
  Sample size                     17896        47368   0.377808      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

  Transmission type:        Allele         
  Marker:                   m              
  Trait:                    Trait1         
  Parental trait:           Not specified  
  Parental sex(es) scored:  Maternal       
  Max. children/family:                 0  
  Max. sib pairs/family:                1  

-------------------------------------
  T/NT  0      1      2      3       
-------------------------------------
  0       672    468    936    1872  
  1       468   1120   1096    2192  
  2       936   1096   4480    4384  
  3      1872   2192   4384   17920  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       46088       102400   0.450078      
  Families                        46088       102400   0.450078      
  Affected children                   0            0   0.000000      
  Affected sib pairs              46088        73888   0.623755      
  Sample size                     21896        46088   0.475091      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

=====================

     Analysis #3

=====================

  Transmission type:        Allele             
  Marker:                   m                  
  Trait:                    Trait1             
  Parental trait:           Not specified      
  Parental sex(es) scored:  Paternal/maternal  
  Max. children/family:                     1  
  Max. sib pairs/family:                    1  

--------------------------------------
  T/NT  0       1      2      3       
--------------------------------------
  0      30968   4872   5504    6768  
  1       4872   2552   2688    4528  
  2       5504   2688   6608    8280  
  3       6768   4528   8280   22880  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       90592       102400   0.884687      
  Families                        90592       102400   0.884687      
  Affected children               24568        24568   1.000000      
  Affected sib pairs              66024        73888   0.893569      
  Sample size                     65280       128288   0.508855      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

  Transmission type:        Allele         
  Marker:                   m              
  Trait:                    Trait1         
  Parental trait:           Not specified  
  Parental sex(es) scored:  Paternal       
  Max. children/family:                 1  
  Max. sib pairs/family:                1  

-------------------------------------
  T/NT  0       1      2      3      
-------------------------------------
  0      29400   5800   5640   5320  
  1       5800   1176   1128   1064  
  2       5640   1128   1104   1008  
  3       5320   1064   1008    864  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       72464       102400   0.707656      
  Families                        72464       102400   0.707656      
  Affected children               25096        25096   1.000000      
  Affected sib pairs              47368        73888   0.641078      
  Sample size                     39920        72464   0.550894      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

  Transmission type:        Allele         
  Marker:                   m              
  Trait:                    Trait1         
  Parental trait:           Not specified  
  Parental sex(es) scored:  Maternal       
  Max. children/family:                 1  
  Max. sib pairs/family:                1  

--------------------------------------
  T/NT  0      1      2       3       
--------------------------------------
  0       768   1080    2160    4320  
  1      1080   1344    2608    5216  
  2      2160   2608    5376   10432  
  3      4320   5216   10432   21504  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       80624       102400   0.787344      
  Families                        80624       102400   0.787344      
  Affected children               34536        34536   1.000000      
  Affected sib pairs              46088        73888   0.623755      
  Sample size                     51632        80624   0.640405      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

=====================

     Analysis #4

=====================

  Transmission type:        Allele             
  Marker:                   m                  
  Trait:                    Trait1             
  Parental trait:           Not specified      
  Parental sex(es) scored:  Paternal/maternal  
  Max. children/family:     Unlimited          
  Max. sib pairs/family:                    0  

----------------------------------------
  T/NT  0       1       2       3       
----------------------------------------
  0      59040   13376   15392   19424  
  1      13376    4768    7072   11872  
  2      15392    7072   12224   21568  
  3      19424   11872   21568   42112  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       90592       102400   0.884687      
  Families                        90592       102400   0.884687      
  Affected children              164480       164480   1.000000      
  Affected sib pairs                  0            0   0.000000      
  Sample size                    177408       295552   0.600260      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

  Transmission type:        Allele         
  Marker:                   m              
  Trait:                    Trait1         
  Parental trait:           Not specified  
  Parental sex(es) scored:  Paternal       
  Max. children/family:     Unlimited      
  Max. sib pairs/family:                0  

----------------------------------------
  T/NT  0       1       2       3       
----------------------------------------
  0      56000   11040   10720   10080  
  1      11040    2240    2144    2016  
  2      10720    2144    2112    1856  
  3      10080    2016    1856    1664  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       72464       102400   0.707656      
  Families                        72464       102400   0.707656      
  Affected children              137728       137728   1.000000      
  Affected sib pairs                  0            0   0.000000      
  Sample size                     75712       137728   0.549721      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

  Transmission type:        Allele         
  Marker:                   m              
  Trait:                    Trait1         
  Parental trait:           Not specified  
  Parental sex(es) scored:  Maternal       
  Max. children/family:     Unlimited      
  Max. sib pairs/family:                0  

--------------------------------------
  T/NT  0      1      2       3       
--------------------------------------
  0      1440   2016    4032    8064  
  1      2016   2464    4800    9600  
  2      4032   4800    9856   19200  
  3      8064   9600   19200   39424  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       80624       102400   0.787344      
  Families                        80624       102400   0.787344      
  Affected children              148608       148608   1.000000      
  Affected sib pairs                  0            0   0.000000      
  Sample size                     95424       148608   0.642119      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

=====================

     Analysis #5

=====================

  Transmission type:        Allele             
  Marker:                   m                  
  Trait:                    Trait1             
  Parental trait:           Not specified      
  Parental sex(es) scored:  Paternal/maternal  
  Max. children/family:                     0  
  Max. sib pairs/family:    Unlimited          

--------------------------------------
  T/NT  0       1      2      3       
--------------------------------------
  0      28072   3248   3796    4892  
  1       3248   2216   1668    2796  
  2       3796   1668   5616    5064  
  3       4892   2796   5064   19232  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       66024       102400   0.644766      
  Families                        66024       102400   0.644766      
  Affected children                   0            0   0.000000      
  Affected sib pairs              66024        73888   0.893569      
  Sample size                     42928        98064   0.437755      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

  Transmission type:        Allele         
  Marker:                   m              
  Trait:                    Trait1         
  Parental trait:           Not specified  
  Parental sex(es) scored:  Paternal       
  Max. children/family:                 0  
  Max. sib pairs/family:    Unlimited      

-------------------------------------
  T/NT  0       1      2      3      
-------------------------------------
  0      26600   2620   2540   2380  
  1       2620   1064    508    476  
  2       2540    508   1008    424  
  3       2380    476    424    800  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       47368       102400   0.462578      
  Families                        47368       102400   0.462578      
  Affected children                   0            0   0.000000      
  Affected sib pairs              47368        73888   0.641078      
  Sample size                     17896        47368   0.377808      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

  Transmission type:        Allele         
  Marker:                   m              
  Trait:                    Trait1         
  Parental trait:           Not specified  
  Parental sex(es) scored:  Maternal       
  Max. children/family:                 0  
  Max. sib pairs/family:    Unlimited      

-------------------------------------
  T/NT  0      1      2      3       
-------------------------------------
  0       672    468    936    1872  
  1       468   1120   1096    2192  
  2       936   1096   4480    4384  
  3      1872   2192   4384   17920  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       46088       102400   0.450078      
  Families                        46088       102400   0.450078      
  Affected children                   0            0   0.000000      
  Affected sib pairs              46088        73888   0.623755      
  Sample size                     21896        46088   0.475091      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

=====================

     Analysis #6

=====================

  Transmission type:        Allele             
  Marker:                   m                  
  Trait:                    Trait1             
  Parental trait:           Not specified      
  Parental sex(es) scored:  Paternal/maternal  
  Max. children/family:     Unlimited          
  Max. sib pairs/family:    Unlimited          

--------------------------------------
  T/NT  0       1      2      3       
--------------------------------------
  0      30968   5952   6684    8148  
  1       5952   2552   3244    5444  
  2       6684   3244   6608    9928  
  3       8148   5444   9928   22880  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       90592       102400   0.884687      
  Families                        90592       102400   0.884687      
  Affected children               32432        32432   1.000000      
  Affected sib pairs              66024        73888   0.893569      
  Sample size                     78800       141808   0.555681      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

  Transmission type:        Allele         
  Marker:                   m              
  Trait:                    Trait1         
  Parental trait:           Not specified  
  Parental sex(es) scored:  Paternal       
  Max. children/family:     Unlimited      
  Max. sib pairs/family:    Unlimited      

-------------------------------------
  T/NT  0       1      2      3      
-------------------------------------
  0      29400   8420   8180   7700  
  1       8420   1176   1636   1540  
  2       8180   1636   1104   1432  
  3       7700   1540   1432    864  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       72464       102400   0.707656      
  Families                        72464       102400   0.707656      
  Affected children               42992        42992   1.000000      
  Affected sib pairs              47368        73888   0.641078      
  Sample size                     57816        90360   0.639841      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

  Transmission type:        Allele         
  Marker:                   m              
  Trait:                    Trait1         
  Parental trait:           Not specified  
  Parental sex(es) scored:  Maternal       
  Max. children/family:     Unlimited      
  Max. sib pairs/family:    Unlimited      

--------------------------------------
  T/NT  0      1      2       3       
--------------------------------------
  0       768   1548    3096    6192  
  1      1548   1344    3704    7408  
  2      3096   3704    5376   14816  
  3      6192   7408   14816   21504  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       80624       102400   0.787344      
  Families                        80624       102400   0.787344      
  Affected children               56432        56432   1.000000      
  Affected sib pairs              46088        73888   0.623755      
  Sample size                     73528       102520   0.717206      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

=====================

     Analysis #7

=====================

  Transmission type:        Genotype           
  Marker:                   m                  
  Trait:                    Trait1             
  Parental trait:           Not specified      
  Parental sex(es) scored:  Paternal/maternal  
  Max. children/family:                     1  
  Max. sib pairs/family:                    0  

----------------------------------------------------------------------------
  T/NT  0/0    0/1    0/2    0/3    1/1   1/2    1/3    2/2   2/3    3/3    
----------------------------------------------------------------------------
  0/0     400    480    880   1680    80    240    400   160    480    320  
  0/1     480    576   1056   2016    96    288    480   192    576    384  
  0/2     880   1056   1936   3696   176    528    880   352   1056    704  
  0/3    1680   2016   3696   7056   336   1008   1680   672   2016   1344  
  1/1      80     96    176    336    16     48     80    32     96     64  
  1/2     240    288    528   1008    48    144    240    96    288    192  
  1/3     400    480    880   1680    80    240    400   160    480    320  
  2/2     160    192    352    672    32     96    160    64    192    128  
  2/3     480    576   1056   2016    96    288    480   192    576    384  
  3/3     320    384    704   1344    64    192    320   128    384    256  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       65536       102400   0.640000      
  Families                        65536       102400   0.640000      
  Affected children               65536        98944   0.662354      
  Affected sib pairs                  0            0   0.000000      
  Sample size                     54112        65536   0.825684      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

=====================

     Analysis #8

=====================

  Transmission type:        Genotype           
  Marker:                   m                  
  Trait:                    Trait1             
  Parental trait:           Not specified      
  Parental sex(es) scored:  Paternal/maternal  
  Max. children/family:                     0  
  Max. sib pairs/family:                    1  

---------------------------------------------------------------------
  T/NT  0/0   0/1   0/2    0/3    1/1  1/2   1/3   2/2   2/3   3/3   
---------------------------------------------------------------------
  0/0    400   240    440    840   20    60   100    40   120    80  
  0/1    240   496    468    908   48   100   156    48   144    96  
  0/2    440   468   1776   1728   44   216   220   176   360   176  
  0/3    840   908   1728   6736   84   252   744   168   832   672  
  1/1     20    48     44     84   16    24    40     8    24    16  
  1/2     60   100    216    252   24   112    96    48   104    48  
  1/3    100   156    220    744   40    96   336    40   192   160  
  2/2     40    48    176    168    8    48    40    64    96    32  
  2/3    120   144    360    832   24   104   192    96   448   192  
  3/3     80    96    176    672   16    48   160    32   192   256  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       32040       102400   0.312891      
  Families                        32040       102400   0.312891      
  Affected children                   0            0   0.000000      
  Affected sib pairs              32040        73888   0.433629      
  Sample size                     21400        32040   0.667915      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

=====================

     Analysis #9

=====================

  Transmission type:        Genotype           
  Marker:                   m                  
  Trait:                    Trait1             
  Parental trait:           Not specified      
  Parental sex(es) scored:  Paternal/maternal  
  Max. children/family:                     1  
  Max. sib pairs/family:                    1  

----------------------------------------------------------------------------
  T/NT  0/0    0/1    0/2    0/3    1/1   1/2    1/3    2/2   2/3    3/3    
----------------------------------------------------------------------------
  0/0     400    480    880   1680    80    240    400   160    480    320  
  0/1     480    576   1056   2016    96    288    480   192    576    384  
  0/2     880   1056   1936   3696   176    528    880   352   1056    704  
  0/3    1680   2016   3696   7056   336   1008   1680   672   2016   1344  
  1/1      80     96    176    336    16     48     80    32     96     64  
  1/2     240    288    528   1008    48    144    240    96    288    192  
  1/3     400    480    880   1680    80    240    400   160    480    320  
  2/2     160    192    352    672    32     96    160    64    192    128  
  2/3     480    576   1056   2016    96    288    480   192    576    384  
  3/3     320    384    704   1344    64    192    320   128    384    256  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       65536       102400   0.640000      
  Families                        65536       102400   0.640000      
  Affected children               33496        66904   0.500658      
  Affected sib pairs              32040        73888   0.433629      
  Sample size                     54112        65536   0.825684      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

======================

     Analysis #10

======================

  Transmission type:        Genotype           
  Marker:                   m                  
  Trait:                    Trait1             
  Parental trait:           Not specified      
  Parental sex(es) scored:  Paternal/maternal  
  Max. children/family:     Unlimited          
  Max. sib pairs/family:                    0  

------------------------------------------------------------------------------
  T/NT  0/0    0/1    0/2    0/3     1/1   1/2    1/3    2/2    2/3    3/3    
------------------------------------------------------------------------------
  0/0     800    960   1760    3360   160    480    800    320    960    640  
  0/1     960   1152   2112    4032   192    576    960    384   1152    768  
  0/2    1760   2112   3872    7392   352   1056   1760    704   2112   1408  
  0/3    3360   4032   7392   14112   672   2016   3360   1344   4032   2688  
  1/1     160    192    352     672    32     96    160     64    192    128  
  1/2     480    576   1056    2016    96    288    480    192    576    384  
  1/3     800    960   1760    3360   160    480    800    320    960    640  
  2/2     320    384    704    1344    64    192    320    128    384    256  
  2/3     960   1152   2112    4032   192    576    960    384   1152    768  
  3/3     640    768   1408    2688   128    384    640    256    768    512  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       65536       102400   0.640000      
  Families                        65536       102400   0.640000      
  Affected children              131072       164480   0.796887      
  Affected sib pairs                  0            0   0.000000      
  Sample size                    108224       131072   0.825684      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

======================

     Analysis #11

======================

  Transmission type:        Genotype           
  Marker:                   m                  
  Trait:                    Trait1             
  Parental trait:           Not specified      
  Parental sex(es) scored:  Paternal/maternal  
  Max. children/family:                     0  
  Max. sib pairs/family:    Unlimited          

---------------------------------------------------------------------
  T/NT  0/0   0/1   0/2    0/3    1/1  1/2   1/3   2/2   2/3   3/3   
---------------------------------------------------------------------
  0/0    400   240    440    840   20    60   100    40   120    80  
  0/1    240   496    468    908   48   100   156    48   144    96  
  0/2    440   468   1776   1728   44   216   220   176   360   176  
  0/3    840   908   1728   6736   84   252   744   168   832   672  
  1/1     20    48     44     84   16    24    40     8    24    16  
  1/2     60   100    216    252   24   112    96    48   104    48  
  1/3    100   156    220    744   40    96   336    40   192   160  
  2/2     40    48    176    168    8    48    40    64    96    32  
  2/3    120   144    360    832   24   104   192    96   448   192  
  3/3     80    96    176    672   16    48   160    32   192   256  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       32040       102400   0.312891      
  Families                        32040       102400   0.312891      
  Affected children                   0            0   0.000000      
  Affected sib pairs              32040        73888   0.433629      
  Sample size                     21400        32040   0.667915      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

======================

     Analysis #12

======================

  Transmission type:        Genotype           
  Marker:                   m                  
  Trait:                    Trait1             
  Parental trait:           Not specified      
  Parental sex(es) scored:  Paternal/maternal  
  Max. children/family:     Unlimited          
  Max. sib pairs/family:    Unlimited          

-----------------------------------------------------------------------------
  T/NT  0/0    0/1    0/2    0/3    1/1   1/2    1/3    2/2    2/3    3/3    
-----------------------------------------------------------------------------
  0/0     400    720   1320   2520   140    420    700    280    840    560  
  0/1     720    656   1644   3124   144    476    804    336   1008    672  
  0/2    1320   1644   2096   5664   308    840   1540    528   1752   1232  
  0/3    2520   3124   5664   7376   588   1764   2616   1176   3200   2016  
  1/1     140    144    308    588    16     72    120     56    168    112  
  1/2     420    476    840   1764    72    176    384    144    472    336  
  1/3     700    804   1540   2616   120    384    464    280    768    480  
  2/2     280    336    528   1176    56    144    280     64    288    224  
  2/3     840   1008   1752   3200   168    472    768    288    704    576  
  3/3     560    672   1232   2016   112    336    480    224    576    256  

---------------------------------------------------------------------
  Group               Informative count  Total count  % Informative  
---------------------------------------------------------------------
  Pedigrees                       65536       102400   0.640000      
  Families                        65536       102400   0.640000      
  Affected children               66992       100400   0.667251      
  Affected sib pairs              32040        73888   0.433629      
  Sample size                     86824        99032   0.876727      

----------------------------------------------------------
  Exact test statistic              P-value    Std. err.  
----------------------------------------------------------
  Exact McNemar test                (skipped)             
  Monte Carlo McNemar test          (skipped)             
  Monte Carlo Marginal Homogeneity  (skipped)             

----------------------------------------------------
  Asymptotic test statistic          P-value        
----------------------------------------------------
  McNemar test                       1.00000000     
  Continuity corrected McNemar test  1.00000000     
  Marginal homogeneity test          1.00000000     

