pedigree
{
  delimiters = "\t"
  delimiter_mode = single
  individual_missing_value = "."

  sex_code, male = "1", female = "2", missing = "."

  pedigree_id = pedid
  individual_id = indid
  parent_id = dad
  parent_id = mom
  sex_field = sex


  string = DNAID

  marker = "D9S910"
  marker = "D16S539"
  marker = "D5S820"
  marker = "D15S655"
  marker = "D11S1984"
  marker = "D11S4464"
  marker = "DXS7132", x_linked
  marker = "GATA165B12", x_linked
  marker = "D10S1430"
}

marker
{
  allele_missing = "."
  allele_delimiter = "/"
}
