
Reading Parameter File....................done.
Reading Marker Locus Description File.....done.
Reading Pedigree File.....................
              from ped....................done.
%MARKERINFO-E: Error(s) building pedigree '10001': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10002': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10003': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10004': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10005': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10006': 2 errors.
%MARKERINFO-E: Error(s) building pedigree '10007': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10008': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10009': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10010': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10011': 2 errors.
%MARKERINFO-E: Error(s) building pedigree '10012': 2 errors.
%MARKERINFO-E: Error(s) building pedigree '10013': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10014': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10015': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10016': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10017': 2 errors.
%MARKERINFO-E: Error(s) building pedigree '10018': 2 errors.
%MARKERINFO-E: Error(s) building pedigree '10019': 2 errors.
%MARKERINFO-E: Error(s) building pedigree '10020': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10021': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10022': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10023': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10024': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10025': 2 errors.
%MARKERINFO-E: Error(s) building pedigree '10026': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10027': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10028': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10029': 2 errors.
%MARKERINFO-E: Error(s) building pedigree '10030': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10031': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10032': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10033': 1 errors.
%MARKERINFO-E: Error(s) building pedigree '10034': 1 errors.
%MARKERINFO-E: Errors appear in pedigree data. Results may be incomplete.
Sorting Pedigrees.........................done.

MARKERINFO analysis.......

Processing pedigree '10001'...............done.
Processing pedigree '10002'...............done.
Processing pedigree '10003'...............done.
Processing pedigree '10004'...............done.
Processing pedigree '10005'...............done.
Processing pedigree '10006'...............done.
Processing pedigree '10007'...............done.
Processing pedigree '10008'...............done.
Processing pedigree '10009'...............done.
Processing pedigree '10010'...............done.
Processing pedigree '10011'...............done.
Processing pedigree '10012'...............done.
Processing pedigree '10013'...............done.
Processing pedigree '10014'...............done.
Processing pedigree '10015'...............done.
Processing pedigree '10016'...............done.
Processing pedigree '10017'...............done.
Processing pedigree '10018'...............done.
Processing pedigree '10019'...............done.
Processing pedigree '10020'...............done.
Processing pedigree '10021'...............done.
Processing pedigree '10022'...............done.
Processing pedigree '10023'...............done.
Processing pedigree '10024'...............done.
Processing pedigree '10025'...............done.
Processing pedigree '10026'...............done.
Processing pedigree '10027'...............done.
Processing pedigree '10028'...............done.
Processing pedigree '10029'...............done.
Processing pedigree '10030'...............done.
Processing pedigree '10031'...............done.
Processing pedigree '10032'...............done.
Processing pedigree '10033'...............done.
Processing pedigree '10034'...............done.

Analysis complete!

