



Family structure information on the first 10 individuals read from file: simul.dat

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     simul0001     9             1         0             0           
     simul0001     1             2         0             0           
     simul0001     2             1         1             9           
     simul0002     1             1         0             0           
     simul0002     9             2         0             0           
     simul0002     2             1         1             9           
     simul0002     3             2         1             9           
     simul0002     4             2         1             9           
     simul0003     1             1         0             0           
     simul0003     9             2         0             0           


Phenotypes for the first 10 individuals read from file: simul.dat

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         TRAIT1                TRAIT2              
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     simul0001     9             0                     1                     1                     3                                                               
     simul0001     1             1                     1                     1                     3                     0.0348171             -1.6992             
     simul0001     2             0                     1                     0                     3                     1.04168               0.91798             
     simul0002     1             0                     1                     1                     5                     0.729862              0.447896            
     simul0002     9             1                     1                     1                     5                                                               
     simul0002     2             0                     1                     0                     5                     -0.239527             0.15972             
     simul0002     3             1                     1                     0                     5                     -0.123131             0.360612            
     simul0002     4             1                     1                     0                     5                     -0.188082             -0.390238           
     simul0003     1             0                     1                     1                     5                     0.0464436             1.34372             
     simul0003     9             1                     1                     1                     5                                                               

%FCOR-I: Invalid value for generation_limit : a
         Skipped...
%FCOR-I: Invalid trait name for var_cov block : TRAIT3
         Skipped...
