



============================================================================
  Tables of the Smallest Number of Pairs Used in
    Calculating Required Correlations for for Sub/Maintypes
============================================================================

    Number of pedigrees = 207
    Number of traits    = 2

    Trait(s) : TRAIT1 TRAIT2

    [      ] : Excluded the number of pairs for nonestimable required
               correlations.

============================================================================
Main Relationship Type : self
============================================================================
Subtypes Pooled   : male-self
                    female-self
Total Pairs Found = 857
-------------------------------------
   POOLED       TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1             *          86  
-------------------------------------
   TRAIT2                         *  
-------------------------------------



Relationship Type : male-self
      Pairs Found = 421
-------------------------------------
   POOLED       TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1             *         178  
-------------------------------------
   TRAIT2                         *  
-------------------------------------



Relationship Type : female-self
      Pairs Found = 436
-------------------------------------
   POOLED       TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1             *         154  
-------------------------------------
   TRAIT2                         *  
-------------------------------------


============================================================================
Main Relationship Type : parent:offspring
============================================================================
Subtypes Pooled   : father:son
                    mother:son
                    father:daughter
                    mother:daughter
Total Pairs Found = 913
-------------------------------------
 INTERCLASS     TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1            86          86  
-------------------------------------
   TRAIT2            86          86  
-------------------------------------



Relationship Type : father(Row):son(Column)
      Pairs Found = 241
-------------------------------------
 INTERCLASS     TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1           178         178  
-------------------------------------
   TRAIT2           178         178  
-------------------------------------



Relationship Type : mother(Row):son(Column)
      Pairs Found = 229
-------------------------------------
 INTERCLASS     TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1           178         178  
-------------------------------------
   TRAIT2           178         178  
-------------------------------------



Relationship Type : father(Row):daughter(Column)
      Pairs Found = 219
-------------------------------------
 INTERCLASS     TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1           154         154  
-------------------------------------
   TRAIT2           154         154  
-------------------------------------



Relationship Type : mother(Row):daughter(Column)
      Pairs Found = 224
-------------------------------------
 INTERCLASS     TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1           154         154  
-------------------------------------
   TRAIT2           154         154  
-------------------------------------


============================================================================
Main Relationship Type : sibling
============================================================================
Subtypes Pooled   : brother:brother
                    sister:brother
                    sister:sister
Total Pairs Found = 686
-------------------------------------
 INTRACLASS     TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1           686         686  
-------------------------------------
   TRAIT2                       686  
-------------------------------------



Relationship Type : brother(Row):brother(Column)
      Pairs Found = 178
-------------------------------------
 INTRACLASS     TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1           178         178  
-------------------------------------
   TRAIT2                       178  
-------------------------------------



Relationship Type : sister(Row):brother(Column)
      Pairs Found = 354
-------------------------------------
 INTERCLASS     TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1           154         154  
-------------------------------------
   TRAIT2           154         154  
-------------------------------------



Relationship Type : sister(Row):sister(Column)
      Pairs Found = 154
-------------------------------------
 INTRACLASS     TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1           154         154  
-------------------------------------
   TRAIT2                       154  
-------------------------------------


============================================================================
Main Relationship Type : mother:father
============================================================================
Total Pairs Found = 86
-------------------------------------
 INTERCLASS     TRAIT1      TRAIT2   
-------------------------------------
   TRAIT1            86          86  
-------------------------------------
   TRAIT2            86          86  
-------------------------------------

