



Family structure information on the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             M         0             0           
     1             2             M         0             0           
     1             3             M         0             0           
     1             11            M         0             0           
     1             4             M         0             0           
     1             5             M         0             0           
     1             12            M         0             0           
     1             13            M         0             0           
     1             6             M         0             0           
     1             7             M         0             0           
     1             8             M         0             0           
     1             9             M         0             0           
     1             10            M         0             0           


Phenotypes for the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         partition           
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     13                    2                   
     1             2             0                     1                     1                     13                    2                   
     1             3             0                     1                     1                     13                    2                   
     1             11            0                     1                     1                     13                    0                   
     1             4             0                     1                     1                     13                    0                   
     1             5             0                     1                     1                     13                    0                   
     1             12            0                     1                     1                     13                    1                   
     1             13            0                     1                     1                     13                    1                   
     1             6             0                     1                     1                     13                    2                   
     1             7             0                     1                     1                     13                    2                   
     1             8             0                     1                     1                     13                    2                   
     1             9             0                     1                     1                     13                    2                   
     1             10            0                     1                     1                     13                    2                   


Markers for the first 20 individuals read from file: ped

     PED. ID       IND. ID       M1            M2          
     ------------  ------------  ------------  ------------
     1             1             a/a           A/a         
     1             2             A/A           A/a         
     1             3             A/A           a/a         
     1             11            a/A           A/a         
     1             4             a/A           A/a         
     1             5             a/A           A/a         
     1             12            a/a           A/A         
     1             13            a/a           a/a         
     1             6             a/a           A/A         
     1             7             a/A           A/a         
     1             8             a/A           A/a         
     1             9             a/A           a/a         
     1             10            a/A           a/a         

%DECIPHER-I: Mapping function not specified.  Using Haldane Mapping Function.

  Performing analysis: Analysis 1
  ===========================================================================

    Subpopulation: 1
      Determining possible haplotype combinations ................... done.
    Subpopulation: 2
      Determining possible haplotype combinations ................... done.

  ===========================================================================

