





MARKER MODELS:
============================

Reading Pedigree File.....................
              from ped....................done.

Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     2             1             F                                   
     2             2             M                                   
     2             6             F                                   
     2             3             M         1             2           
     2             4             F         1             2           
     2             5             M         1             2           
     2             7             F                                   
     2             8             M         3             6           
     2             9             M         3             6           
     2             10            M         3             6           


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       T1                    HEMATOCRIT          
     ------------  ------------  --------------------  --------------------
     2             1             1                     37.6                
     2             2             1                     33.1                
     2             6             1                     42.7                
     2             3             1                     35.9                
     2             4             1                     36.3                
     2             5             1                     33.2                
     2             7             1                     29.7                
     2             8             1                     32.4                
     2             9             1                     35.2                
     2             10            1                     36.4                


Markers for the first 10 individuals read from file: ped

     PED. ID       IND. ID       Mark1       
     ------------  ------------  ------------
     2             1             0/0         
     2             2             0/0         
     2             6             0/0         
     2             3             0/0         
     2             4             0/0         
     2             5             1/2         
     2             7             0/0         
     2             8             3/3         
     2             9             0/0         
     2             10            0/0         

Sorting pedigrees.........................done.
Testing parental penetrance model: 

1: founder   : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    

10: nonfounder: 3<2x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<2x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<2x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<2x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<2x3<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<1x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<1x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<1x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<1x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<1x3<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 1<3x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 1<3x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 1<3x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 1<3x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 1<3x3<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 2<3x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 2<3x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 2<3x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 2<3x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 2<3x3<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<3x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<3x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<3x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<3x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
10: nonfounder: 3<3x3<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    

10: nonfounder: 3<2x3<2 : 3<2 = 1    
10: nonfounder: 3<2x3<1 : 3<2 = 1    
10: nonfounder: 3<2x1<3 : 3<2 = 1    
10: nonfounder: 3<2x2<3 : 3<2 = 1    
10: nonfounder: 3<2x3<3 : 3<2 = 1    
10: nonfounder: 3<1x3<2 : 3<2 = 1    
10: nonfounder: 3<1x3<1 : 3<2 = 1    
10: nonfounder: 3<1x1<3 : 3<2 = 1    
10: nonfounder: 3<1x2<3 : 3<2 = 1    
10: nonfounder: 3<1x3<3 : 3<2 = 1    
10: nonfounder: 1<3x3<2 : 3<2 = 1    
10: nonfounder: 1<3x3<1 : 3<2 = 1    
10: nonfounder: 1<3x1<3 : 3<2 = 1    
10: nonfounder: 1<3x2<3 : 3<2 = 1    
10: nonfounder: 1<3x3<3 : 3<2 = 1    
10: nonfounder: 2<3x3<2 : 3<2 = 1    
10: nonfounder: 2<3x3<1 : 3<2 = 1    
10: nonfounder: 2<3x1<3 : 3<2 = 1    
10: nonfounder: 2<3x2<3 : 3<2 = 1    
10: nonfounder: 2<3x3<3 : 3<2 = 1    
10: nonfounder: 3<3x3<2 : 3<2 = 1    
10: nonfounder: 3<3x3<1 : 3<2 = 1    
10: nonfounder: 3<3x1<3 : 3<2 = 1    
10: nonfounder: 3<3x2<3 : 3<2 = 1    
10: nonfounder: 3<3x3<3 : 3<2 = 1    

10: nonfounder: 3<2x3<2 : 3<1 = 1    
10: nonfounder: 3<2x3<1 : 3<1 = 1    
10: nonfounder: 3<2x1<3 : 3<1 = 1    
10: nonfounder: 3<2x2<3 : 3<1 = 1    
10: nonfounder: 3<2x3<3 : 3<1 = 1    
10: nonfounder: 3<1x3<2 : 3<1 = 1    
10: nonfounder: 3<1x3<1 : 3<1 = 1    
10: nonfounder: 3<1x1<3 : 3<1 = 1    
10: nonfounder: 3<1x2<3 : 3<1 = 1    
10: nonfounder: 3<1x3<3 : 3<1 = 1    
10: nonfounder: 1<3x3<2 : 3<1 = 1    
10: nonfounder: 1<3x3<1 : 3<1 = 1    
10: nonfounder: 1<3x1<3 : 3<1 = 1    
10: nonfounder: 1<3x2<3 : 3<1 = 1    
10: nonfounder: 1<3x3<3 : 3<1 = 1    
10: nonfounder: 2<3x3<2 : 3<1 = 1    
10: nonfounder: 2<3x3<1 : 3<1 = 1    
10: nonfounder: 2<3x1<3 : 3<1 = 1    
10: nonfounder: 2<3x2<3 : 3<1 = 1    
10: nonfounder: 2<3x3<3 : 3<1 = 1    
10: nonfounder: 3<3x3<2 : 3<1 = 1    
10: nonfounder: 3<3x3<1 : 3<1 = 1    
10: nonfounder: 3<3x1<3 : 3<1 = 1    
10: nonfounder: 3<3x2<3 : 3<1 = 1    
10: nonfounder: 3<3x3<3 : 3<1 = 1    

10: nonfounder: 3<2x3<2 : 2<1 = 1    
10: nonfounder: 3<2x3<1 : 2<1 = 1    
10: nonfounder: 3<2x1<3 : 2<1 = 1    
10: nonfounder: 3<2x2<3 : 2<1 = 1    
10: nonfounder: 3<2x3<3 : 2<1 = 1    
10: nonfounder: 3<1x3<2 : 2<1 = 1    
10: nonfounder: 3<1x3<1 : 2<1 = 1    
10: nonfounder: 3<1x1<3 : 2<1 = 1    
10: nonfounder: 3<1x2<3 : 2<1 = 1    
10: nonfounder: 3<1x3<3 : 2<1 = 1    
10: nonfounder: 1<3x3<2 : 2<1 = 1    
10: nonfounder: 1<3x3<1 : 2<1 = 1    
10: nonfounder: 1<3x1<3 : 2<1 = 1    
10: nonfounder: 1<3x2<3 : 2<1 = 1    
10: nonfounder: 1<3x3<3 : 2<1 = 1    
10: nonfounder: 2<3x3<2 : 2<1 = 1    
10: nonfounder: 2<3x3<1 : 2<1 = 1    
10: nonfounder: 2<3x1<3 : 2<1 = 1    
10: nonfounder: 2<3x2<3 : 2<1 = 1    
10: nonfounder: 2<3x3<3 : 2<1 = 1    
10: nonfounder: 3<3x3<2 : 2<1 = 1    
10: nonfounder: 3<3x3<1 : 2<1 = 1    
10: nonfounder: 3<3x1<3 : 2<1 = 1    
10: nonfounder: 3<3x2<3 : 2<1 = 1    
10: nonfounder: 3<3x3<3 : 2<1 = 1    

10: nonfounder: 3<2x3<2 : 1<1 = 1    
10: nonfounder: 3<2x3<1 : 1<1 = 1    
10: nonfounder: 3<2x1<3 : 1<1 = 1    
10: nonfounder: 3<2x2<3 : 1<1 = 1    
10: nonfounder: 3<2x3<3 : 1<1 = 1    
10: nonfounder: 3<1x3<2 : 1<1 = 1    
10: nonfounder: 3<1x3<1 : 1<1 = 1    
10: nonfounder: 3<1x1<3 : 1<1 = 1    
10: nonfounder: 3<1x2<3 : 1<1 = 1    
10: nonfounder: 3<1x3<3 : 1<1 = 1    
10: nonfounder: 1<3x3<2 : 1<1 = 1    
10: nonfounder: 1<3x3<1 : 1<1 = 1    
10: nonfounder: 1<3x1<3 : 1<1 = 1    
10: nonfounder: 1<3x2<3 : 1<1 = 1    
10: nonfounder: 1<3x3<3 : 1<1 = 1    
10: nonfounder: 2<3x3<2 : 1<1 = 1    
10: nonfounder: 2<3x3<1 : 1<1 = 1    
10: nonfounder: 2<3x1<3 : 1<1 = 1    
10: nonfounder: 2<3x2<3 : 1<1 = 1    
10: nonfounder: 2<3x3<3 : 1<1 = 1    
10: nonfounder: 3<3x3<2 : 1<1 = 1    
10: nonfounder: 3<3x3<1 : 1<1 = 1    
10: nonfounder: 3<3x1<3 : 1<1 = 1    
10: nonfounder: 3<3x2<3 : 1<1 = 1    
10: nonfounder: 3<3x3<3 : 1<1 = 1    

10: nonfounder: 3<2x3<2 : 1<2 = 1    
10: nonfounder: 3<2x3<1 : 1<2 = 1    
10: nonfounder: 3<2x1<3 : 1<2 = 1    
10: nonfounder: 3<2x2<3 : 1<2 = 1    
10: nonfounder: 3<2x3<3 : 1<2 = 1    
10: nonfounder: 3<1x3<2 : 1<2 = 1    
10: nonfounder: 3<1x3<1 : 1<2 = 1    
10: nonfounder: 3<1x1<3 : 1<2 = 1    
10: nonfounder: 3<1x2<3 : 1<2 = 1    
10: nonfounder: 3<1x3<3 : 1<2 = 1    
10: nonfounder: 1<3x3<2 : 1<2 = 1    
10: nonfounder: 1<3x3<1 : 1<2 = 1    
10: nonfounder: 1<3x1<3 : 1<2 = 1    
10: nonfounder: 1<3x2<3 : 1<2 = 1    
10: nonfounder: 1<3x3<3 : 1<2 = 1    
10: nonfounder: 2<3x3<2 : 1<2 = 1    
10: nonfounder: 2<3x3<1 : 1<2 = 1    
10: nonfounder: 2<3x1<3 : 1<2 = 1    
10: nonfounder: 2<3x2<3 : 1<2 = 1    
10: nonfounder: 2<3x3<3 : 1<2 = 1    
10: nonfounder: 3<3x3<2 : 1<2 = 1    
10: nonfounder: 3<3x3<1 : 1<2 = 1    
10: nonfounder: 3<3x1<3 : 1<2 = 1    
10: nonfounder: 3<3x2<3 : 1<2 = 1    
10: nonfounder: 3<3x3<3 : 1<2 = 1    

10: nonfounder: 3<2x3<2 : 2<2 = 1    
10: nonfounder: 3<2x3<1 : 2<2 = 1    
10: nonfounder: 3<2x1<3 : 2<2 = 1    
10: nonfounder: 3<2x2<3 : 2<2 = 1    
10: nonfounder: 3<2x3<3 : 2<2 = 1    
10: nonfounder: 3<1x3<2 : 2<2 = 1    
10: nonfounder: 3<1x3<1 : 2<2 = 1    
10: nonfounder: 3<1x1<3 : 2<2 = 1    
10: nonfounder: 3<1x2<3 : 2<2 = 1    
10: nonfounder: 3<1x3<3 : 2<2 = 1    
10: nonfounder: 1<3x3<2 : 2<2 = 1    
10: nonfounder: 1<3x3<1 : 2<2 = 1    
10: nonfounder: 1<3x1<3 : 2<2 = 1    
10: nonfounder: 1<3x2<3 : 2<2 = 1    
10: nonfounder: 1<3x3<3 : 2<2 = 1    
10: nonfounder: 2<3x3<2 : 2<2 = 1    
10: nonfounder: 2<3x3<1 : 2<2 = 1    
10: nonfounder: 2<3x1<3 : 2<2 = 1    
10: nonfounder: 2<3x2<3 : 2<2 = 1    
10: nonfounder: 2<3x3<3 : 2<2 = 1    
10: nonfounder: 3<3x3<2 : 2<2 = 1    
10: nonfounder: 3<3x3<1 : 2<2 = 1    
10: nonfounder: 3<3x1<3 : 2<2 = 1    
10: nonfounder: 3<3x2<3 : 2<2 = 1    
10: nonfounder: 3<3x3<3 : 2<2 = 1    

10: nonfounder: 3<2x3<2 : 1<3 = 1    
10: nonfounder: 3<2x3<1 : 1<3 = 1    
10: nonfounder: 3<2x1<3 : 1<3 = 1    
10: nonfounder: 3<2x2<3 : 1<3 = 1    
10: nonfounder: 3<2x3<3 : 1<3 = 1    
10: nonfounder: 3<1x3<2 : 1<3 = 1    
10: nonfounder: 3<1x3<1 : 1<3 = 1    
10: nonfounder: 3<1x1<3 : 1<3 = 1    
10: nonfounder: 3<1x2<3 : 1<3 = 1    
10: nonfounder: 3<1x3<3 : 1<3 = 1    
10: nonfounder: 1<3x3<2 : 1<3 = 1    
10: nonfounder: 1<3x3<1 : 1<3 = 1    
10: nonfounder: 1<3x1<3 : 1<3 = 1    
10: nonfounder: 1<3x2<3 : 1<3 = 1    
10: nonfounder: 1<3x3<3 : 1<3 = 1    
10: nonfounder: 2<3x3<2 : 1<3 = 1    
10: nonfounder: 2<3x3<1 : 1<3 = 1    
10: nonfounder: 2<3x1<3 : 1<3 = 1    
10: nonfounder: 2<3x2<3 : 1<3 = 1    
10: nonfounder: 2<3x3<3 : 1<3 = 1    
10: nonfounder: 3<3x3<2 : 1<3 = 1    
10: nonfounder: 3<3x3<1 : 1<3 = 1    
10: nonfounder: 3<3x1<3 : 1<3 = 1    
10: nonfounder: 3<3x2<3 : 1<3 = 1    
10: nonfounder: 3<3x3<3 : 1<3 = 1    

10: nonfounder: 3<2x3<2 : 2<3 = 1    
10: nonfounder: 3<2x3<1 : 2<3 = 1    
10: nonfounder: 3<2x1<3 : 2<3 = 1    
10: nonfounder: 3<2x2<3 : 2<3 = 1    
10: nonfounder: 3<2x3<3 : 2<3 = 1    
10: nonfounder: 3<1x3<2 : 2<3 = 1    
10: nonfounder: 3<1x3<1 : 2<3 = 1    
10: nonfounder: 3<1x1<3 : 2<3 = 1    
10: nonfounder: 3<1x2<3 : 2<3 = 1    
10: nonfounder: 3<1x3<3 : 2<3 = 1    
10: nonfounder: 1<3x3<2 : 2<3 = 1    
10: nonfounder: 1<3x3<1 : 2<3 = 1    
10: nonfounder: 1<3x1<3 : 2<3 = 1    
10: nonfounder: 1<3x2<3 : 2<3 = 1    
10: nonfounder: 1<3x3<3 : 2<3 = 1    
10: nonfounder: 2<3x3<2 : 2<3 = 1    
10: nonfounder: 2<3x3<1 : 2<3 = 1    
10: nonfounder: 2<3x1<3 : 2<3 = 1    
10: nonfounder: 2<3x2<3 : 2<3 = 1    
10: nonfounder: 2<3x3<3 : 2<3 = 1    
10: nonfounder: 3<3x3<2 : 2<3 = 1    
10: nonfounder: 3<3x3<1 : 2<3 = 1    
10: nonfounder: 3<3x1<3 : 2<3 = 1    
10: nonfounder: 3<3x2<3 : 2<3 = 1    
10: nonfounder: 3<3x3<3 : 2<3 = 1    

10: nonfounder: 3<2x3<2 : 3<3 = 1    
10: nonfounder: 3<2x3<1 : 3<3 = 1    
10: nonfounder: 3<2x1<3 : 3<3 = 1    
10: nonfounder: 3<2x2<3 : 3<3 = 1    
10: nonfounder: 3<2x3<3 : 3<3 = 1    
10: nonfounder: 3<1x3<2 : 3<3 = 1    
10: nonfounder: 3<1x3<1 : 3<3 = 1    
10: nonfounder: 3<1x1<3 : 3<3 = 1    
10: nonfounder: 3<1x2<3 : 3<3 = 1    
10: nonfounder: 3<1x3<3 : 3<3 = 1    
10: nonfounder: 1<3x3<2 : 3<3 = 1    
10: nonfounder: 1<3x3<1 : 3<3 = 1    
10: nonfounder: 1<3x1<3 : 3<3 = 1    
10: nonfounder: 1<3x2<3 : 3<3 = 1    
10: nonfounder: 1<3x3<3 : 3<3 = 1    
10: nonfounder: 2<3x3<2 : 3<3 = 1    
10: nonfounder: 2<3x3<1 : 3<3 = 1    
10: nonfounder: 2<3x1<3 : 3<3 = 1    
10: nonfounder: 2<3x2<3 : 3<3 = 1    
10: nonfounder: 2<3x3<3 : 3<3 = 1    
10: nonfounder: 3<3x3<2 : 3<3 = 1    
10: nonfounder: 3<3x3<1 : 3<3 = 1    
10: nonfounder: 3<3x1<3 : 3<3 = 1    
10: nonfounder: 3<3x2<3 : 3<3 = 1    
10: nonfounder: 3<3x3<3 : 3<3 = 1    

11: nonfounder: 2<1x2<1 : 2<2 = 1    
11: nonfounder: 2<1x1<2 : 2<2 = 1    
11: nonfounder: 1<2x2<1 : 2<2 = 1    
11: nonfounder: 1<2x1<2 : 2<2 = 1    

11: nonfounder: 2<1x2<1 : 2<2 = 1    
11: nonfounder: 2<1x1<2 : 2<2 = 1    
11: nonfounder: 1<2x2<1 : 2<2 = 1    
11: nonfounder: 1<2x1<2 : 2<2 = 1    

12: nonfounder: 2<1x2<1 : 1<1 = 1    
12: nonfounder: 2<1x1<2 : 1<1 = 1    
12: nonfounder: 1<2x2<1 : 1<1 = 1    
12: nonfounder: 1<2x1<2 : 1<1 = 1    

12: nonfounder: 2<1x2<1 : 1<1 = 1    
12: nonfounder: 2<1x1<2 : 1<1 = 1    
12: nonfounder: 1<2x2<1 : 1<1 = 1    
12: nonfounder: 1<2x1<2 : 1<1 = 1    

13: nonfounder: 2<1x2<1 : 2<1 = 1    1<2 = 1    
13: nonfounder: 2<1x1<2 : 2<1 = 1    1<2 = 1    
13: nonfounder: 1<2x2<1 : 2<1 = 1    1<2 = 1    
13: nonfounder: 1<2x1<2 : 2<1 = 1    1<2 = 1    

13: nonfounder: 2<1x2<1 : 2<1 = 1    
13: nonfounder: 2<1x1<2 : 2<1 = 1    
13: nonfounder: 1<2x2<1 : 2<1 = 1    
13: nonfounder: 1<2x1<2 : 2<1 = 1    

13: nonfounder: 2<1x2<1 : 1<2 = 1    
13: nonfounder: 2<1x1<2 : 1<2 = 1    
13: nonfounder: 1<2x2<1 : 1<2 = 1    
13: nonfounder: 1<2x1<2 : 1<2 = 1    

14: founder   : 3<2 = 1    2<3 = 1    

15: nonfounder: 3<2x2<1 : 3<1 = 1    
15: nonfounder: 3<2x1<2 : 3<1 = 1    
15: nonfounder: 2<3x2<1 : 3<1 = 1    
15: nonfounder: 2<3x1<2 : 3<1 = 1    

15: nonfounder: 3<2x2<1 : 3<1 = 1    
15: nonfounder: 3<2x1<2 : 3<1 = 1    
15: nonfounder: 2<3x2<1 : 3<1 = 1    
15: nonfounder: 2<3x1<2 : 3<1 = 1    

16: nonfounder: 3<2x2<1 : 3<2 = 1    
16: nonfounder: 3<2x1<2 : 3<2 = 1    
16: nonfounder: 2<3x2<1 : 3<2 = 1    
16: nonfounder: 2<3x1<2 : 3<2 = 1    

16: nonfounder: 3<2x2<1 : 3<2 = 1    
16: nonfounder: 3<2x1<2 : 3<2 = 1    
16: nonfounder: 2<3x2<1 : 3<2 = 1    
16: nonfounder: 2<3x1<2 : 3<2 = 1    

2: founder   : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    

3: nonfounder: 3<2x3<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<2x3<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<2x2<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<2x1<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<2x1<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<2x2<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<2x1<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<2x2<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<1x3<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<1x3<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<1x2<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<1x1<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<1x1<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<1x2<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<1x1<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 3<1x2<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<1x3<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<1x3<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<1x2<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<1x1<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<1x1<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<1x2<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<1x1<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<1x2<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<1x3<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<1x3<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<1x2<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<1x1<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<1x1<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<1x2<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<1x1<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<1x2<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<2x3<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<2x3<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<2x2<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<2x1<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<2x1<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<2x2<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<2x1<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<2x2<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<2x3<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<2x3<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<2x2<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<2x1<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<2x1<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<2x2<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<2x1<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<2x2<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<3x3<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<3x3<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<3x2<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<3x1<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<3x1<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<3x2<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<3x1<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 1<3x2<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<3x3<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<3x3<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<3x2<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<3x1<1 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<3x1<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<3x2<2 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<3x1<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
3: nonfounder: 2<3x2<3 : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    

3: nonfounder: 3<2x3<2 : 3<2 = 1    
3: nonfounder: 3<2x3<1 : 3<2 = 1    
3: nonfounder: 3<2x2<1 : 3<2 = 1    
3: nonfounder: 3<2x1<1 : 3<2 = 1    
3: nonfounder: 3<2x1<2 : 3<2 = 1    
3: nonfounder: 3<2x2<2 : 3<2 = 1    
3: nonfounder: 3<2x1<3 : 3<2 = 1    
3: nonfounder: 3<2x2<3 : 3<2 = 1    
3: nonfounder: 3<1x3<2 : 3<2 = 1    
3: nonfounder: 3<1x3<1 : 3<2 = 1    
3: nonfounder: 3<1x2<1 : 3<2 = 1    
3: nonfounder: 3<1x1<1 : 3<2 = 1    
3: nonfounder: 3<1x1<2 : 3<2 = 1    
3: nonfounder: 3<1x2<2 : 3<2 = 1    
3: nonfounder: 3<1x1<3 : 3<2 = 1    
3: nonfounder: 3<1x2<3 : 3<2 = 1    
3: nonfounder: 2<1x3<2 : 3<2 = 1    
3: nonfounder: 2<1x3<1 : 3<2 = 1    
3: nonfounder: 2<1x2<1 : 3<2 = 1    
3: nonfounder: 2<1x1<1 : 3<2 = 1    
3: nonfounder: 2<1x1<2 : 3<2 = 1    
3: nonfounder: 2<1x2<2 : 3<2 = 1    
3: nonfounder: 2<1x1<3 : 3<2 = 1    
3: nonfounder: 2<1x2<3 : 3<2 = 1    
3: nonfounder: 1<1x3<2 : 3<2 = 1    
3: nonfounder: 1<1x3<1 : 3<2 = 1    
3: nonfounder: 1<1x2<1 : 3<2 = 1    
3: nonfounder: 1<1x1<1 : 3<2 = 1    
3: nonfounder: 1<1x1<2 : 3<2 = 1    
3: nonfounder: 1<1x2<2 : 3<2 = 1    
3: nonfounder: 1<1x1<3 : 3<2 = 1    
3: nonfounder: 1<1x2<3 : 3<2 = 1    
3: nonfounder: 1<2x3<2 : 3<2 = 1    
3: nonfounder: 1<2x3<1 : 3<2 = 1    
3: nonfounder: 1<2x2<1 : 3<2 = 1    
3: nonfounder: 1<2x1<1 : 3<2 = 1    
3: nonfounder: 1<2x1<2 : 3<2 = 1    
3: nonfounder: 1<2x2<2 : 3<2 = 1    
3: nonfounder: 1<2x1<3 : 3<2 = 1    
3: nonfounder: 1<2x2<3 : 3<2 = 1    
3: nonfounder: 2<2x3<2 : 3<2 = 1    
3: nonfounder: 2<2x3<1 : 3<2 = 1    
3: nonfounder: 2<2x2<1 : 3<2 = 1    
3: nonfounder: 2<2x1<1 : 3<2 = 1    
3: nonfounder: 2<2x1<2 : 3<2 = 1    
3: nonfounder: 2<2x2<2 : 3<2 = 1    
3: nonfounder: 2<2x1<3 : 3<2 = 1    
3: nonfounder: 2<2x2<3 : 3<2 = 1    
3: nonfounder: 1<3x3<2 : 3<2 = 1    
3: nonfounder: 1<3x3<1 : 3<2 = 1    
3: nonfounder: 1<3x2<1 : 3<2 = 1    
3: nonfounder: 1<3x1<1 : 3<2 = 1    
3: nonfounder: 1<3x1<2 : 3<2 = 1    
3: nonfounder: 1<3x2<2 : 3<2 = 1    
3: nonfounder: 1<3x1<3 : 3<2 = 1    
3: nonfounder: 1<3x2<3 : 3<2 = 1    
3: nonfounder: 2<3x3<2 : 3<2 = 1    
3: nonfounder: 2<3x3<1 : 3<2 = 1    
3: nonfounder: 2<3x2<1 : 3<2 = 1    
3: nonfounder: 2<3x1<1 : 3<2 = 1    
3: nonfounder: 2<3x1<2 : 3<2 = 1    
3: nonfounder: 2<3x2<2 : 3<2 = 1    
3: nonfounder: 2<3x1<3 : 3<2 = 1    
3: nonfounder: 2<3x2<3 : 3<2 = 1    

3: nonfounder: 3<2x3<2 : 3<1 = 1    
3: nonfounder: 3<2x3<1 : 3<1 = 1    
3: nonfounder: 3<2x2<1 : 3<1 = 1    
3: nonfounder: 3<2x1<1 : 3<1 = 1    
3: nonfounder: 3<2x1<2 : 3<1 = 1    
3: nonfounder: 3<2x2<2 : 3<1 = 1    
3: nonfounder: 3<2x1<3 : 3<1 = 1    
3: nonfounder: 3<2x2<3 : 3<1 = 1    
3: nonfounder: 3<1x3<2 : 3<1 = 1    
3: nonfounder: 3<1x3<1 : 3<1 = 1    
3: nonfounder: 3<1x2<1 : 3<1 = 1    
3: nonfounder: 3<1x1<1 : 3<1 = 1    
3: nonfounder: 3<1x1<2 : 3<1 = 1    
3: nonfounder: 3<1x2<2 : 3<1 = 1    
3: nonfounder: 3<1x1<3 : 3<1 = 1    
3: nonfounder: 3<1x2<3 : 3<1 = 1    
3: nonfounder: 2<1x3<2 : 3<1 = 1    
3: nonfounder: 2<1x3<1 : 3<1 = 1    
3: nonfounder: 2<1x2<1 : 3<1 = 1    
3: nonfounder: 2<1x1<1 : 3<1 = 1    
3: nonfounder: 2<1x1<2 : 3<1 = 1    
3: nonfounder: 2<1x2<2 : 3<1 = 1    
3: nonfounder: 2<1x1<3 : 3<1 = 1    
3: nonfounder: 2<1x2<3 : 3<1 = 1    
3: nonfounder: 1<1x3<2 : 3<1 = 1    
3: nonfounder: 1<1x3<1 : 3<1 = 1    
3: nonfounder: 1<1x2<1 : 3<1 = 1    
3: nonfounder: 1<1x1<1 : 3<1 = 1    
3: nonfounder: 1<1x1<2 : 3<1 = 1    
3: nonfounder: 1<1x2<2 : 3<1 = 1    
3: nonfounder: 1<1x1<3 : 3<1 = 1    
3: nonfounder: 1<1x2<3 : 3<1 = 1    
3: nonfounder: 1<2x3<2 : 3<1 = 1    
3: nonfounder: 1<2x3<1 : 3<1 = 1    
3: nonfounder: 1<2x2<1 : 3<1 = 1    
3: nonfounder: 1<2x1<1 : 3<1 = 1    
3: nonfounder: 1<2x1<2 : 3<1 = 1    
3: nonfounder: 1<2x2<2 : 3<1 = 1    
3: nonfounder: 1<2x1<3 : 3<1 = 1    
3: nonfounder: 1<2x2<3 : 3<1 = 1    
3: nonfounder: 2<2x3<2 : 3<1 = 1    
3: nonfounder: 2<2x3<1 : 3<1 = 1    
3: nonfounder: 2<2x2<1 : 3<1 = 1    
3: nonfounder: 2<2x1<1 : 3<1 = 1    
3: nonfounder: 2<2x1<2 : 3<1 = 1    
3: nonfounder: 2<2x2<2 : 3<1 = 1    
3: nonfounder: 2<2x1<3 : 3<1 = 1    
3: nonfounder: 2<2x2<3 : 3<1 = 1    
3: nonfounder: 1<3x3<2 : 3<1 = 1    
3: nonfounder: 1<3x3<1 : 3<1 = 1    
3: nonfounder: 1<3x2<1 : 3<1 = 1    
3: nonfounder: 1<3x1<1 : 3<1 = 1    
3: nonfounder: 1<3x1<2 : 3<1 = 1    
3: nonfounder: 1<3x2<2 : 3<1 = 1    
3: nonfounder: 1<3x1<3 : 3<1 = 1    
3: nonfounder: 1<3x2<3 : 3<1 = 1    
3: nonfounder: 2<3x3<2 : 3<1 = 1    
3: nonfounder: 2<3x3<1 : 3<1 = 1    
3: nonfounder: 2<3x2<1 : 3<1 = 1    
3: nonfounder: 2<3x1<1 : 3<1 = 1    
3: nonfounder: 2<3x1<2 : 3<1 = 1    
3: nonfounder: 2<3x2<2 : 3<1 = 1    
3: nonfounder: 2<3x1<3 : 3<1 = 1    
3: nonfounder: 2<3x2<3 : 3<1 = 1    

3: nonfounder: 3<2x3<2 : 1<3 = 1    
3: nonfounder: 3<2x3<1 : 1<3 = 1    
3: nonfounder: 3<2x2<1 : 1<3 = 1    
3: nonfounder: 3<2x1<1 : 1<3 = 1    
3: nonfounder: 3<2x1<2 : 1<3 = 1    
3: nonfounder: 3<2x2<2 : 1<3 = 1    
3: nonfounder: 3<2x1<3 : 1<3 = 1    
3: nonfounder: 3<2x2<3 : 1<3 = 1    
3: nonfounder: 3<1x3<2 : 1<3 = 1    
3: nonfounder: 3<1x3<1 : 1<3 = 1    
3: nonfounder: 3<1x2<1 : 1<3 = 1    
3: nonfounder: 3<1x1<1 : 1<3 = 1    
3: nonfounder: 3<1x1<2 : 1<3 = 1    
3: nonfounder: 3<1x2<2 : 1<3 = 1    
3: nonfounder: 3<1x1<3 : 1<3 = 1    
3: nonfounder: 3<1x2<3 : 1<3 = 1    
3: nonfounder: 2<1x3<2 : 1<3 = 1    
3: nonfounder: 2<1x3<1 : 1<3 = 1    
3: nonfounder: 2<1x2<1 : 1<3 = 1    
3: nonfounder: 2<1x1<1 : 1<3 = 1    
3: nonfounder: 2<1x1<2 : 1<3 = 1    
3: nonfounder: 2<1x2<2 : 1<3 = 1    
3: nonfounder: 2<1x1<3 : 1<3 = 1    
3: nonfounder: 2<1x2<3 : 1<3 = 1    
3: nonfounder: 1<1x3<2 : 1<3 = 1    
3: nonfounder: 1<1x3<1 : 1<3 = 1    
3: nonfounder: 1<1x2<1 : 1<3 = 1    
3: nonfounder: 1<1x1<1 : 1<3 = 1    
3: nonfounder: 1<1x1<2 : 1<3 = 1    
3: nonfounder: 1<1x2<2 : 1<3 = 1    
3: nonfounder: 1<1x1<3 : 1<3 = 1    
3: nonfounder: 1<1x2<3 : 1<3 = 1    
3: nonfounder: 1<2x3<2 : 1<3 = 1    
3: nonfounder: 1<2x3<1 : 1<3 = 1    
3: nonfounder: 1<2x2<1 : 1<3 = 1    
3: nonfounder: 1<2x1<1 : 1<3 = 1    
3: nonfounder: 1<2x1<2 : 1<3 = 1    
3: nonfounder: 1<2x2<2 : 1<3 = 1    
3: nonfounder: 1<2x1<3 : 1<3 = 1    
3: nonfounder: 1<2x2<3 : 1<3 = 1    
3: nonfounder: 2<2x3<2 : 1<3 = 1    
3: nonfounder: 2<2x3<1 : 1<3 = 1    
3: nonfounder: 2<2x2<1 : 1<3 = 1    
3: nonfounder: 2<2x1<1 : 1<3 = 1    
3: nonfounder: 2<2x1<2 : 1<3 = 1    
3: nonfounder: 2<2x2<2 : 1<3 = 1    
3: nonfounder: 2<2x1<3 : 1<3 = 1    
3: nonfounder: 2<2x2<3 : 1<3 = 1    
3: nonfounder: 1<3x3<2 : 1<3 = 1    
3: nonfounder: 1<3x3<1 : 1<3 = 1    
3: nonfounder: 1<3x2<1 : 1<3 = 1    
3: nonfounder: 1<3x1<1 : 1<3 = 1    
3: nonfounder: 1<3x1<2 : 1<3 = 1    
3: nonfounder: 1<3x2<2 : 1<3 = 1    
3: nonfounder: 1<3x1<3 : 1<3 = 1    
3: nonfounder: 1<3x2<3 : 1<3 = 1    
3: nonfounder: 2<3x3<2 : 1<3 = 1    
3: nonfounder: 2<3x3<1 : 1<3 = 1    
3: nonfounder: 2<3x2<1 : 1<3 = 1    
3: nonfounder: 2<3x1<1 : 1<3 = 1    
3: nonfounder: 2<3x1<2 : 1<3 = 1    
3: nonfounder: 2<3x2<2 : 1<3 = 1    
3: nonfounder: 2<3x1<3 : 1<3 = 1    
3: nonfounder: 2<3x2<3 : 1<3 = 1    

3: nonfounder: 3<2x3<2 : 2<3 = 1    
3: nonfounder: 3<2x3<1 : 2<3 = 1    
3: nonfounder: 3<2x2<1 : 2<3 = 1    
3: nonfounder: 3<2x1<1 : 2<3 = 1    
3: nonfounder: 3<2x1<2 : 2<3 = 1    
3: nonfounder: 3<2x2<2 : 2<3 = 1    
3: nonfounder: 3<2x1<3 : 2<3 = 1    
3: nonfounder: 3<2x2<3 : 2<3 = 1    
3: nonfounder: 3<1x3<2 : 2<3 = 1    
3: nonfounder: 3<1x3<1 : 2<3 = 1    
3: nonfounder: 3<1x2<1 : 2<3 = 1    
3: nonfounder: 3<1x1<1 : 2<3 = 1    
3: nonfounder: 3<1x1<2 : 2<3 = 1    
3: nonfounder: 3<1x2<2 : 2<3 = 1    
3: nonfounder: 3<1x1<3 : 2<3 = 1    
3: nonfounder: 3<1x2<3 : 2<3 = 1    
3: nonfounder: 2<1x3<2 : 2<3 = 1    
3: nonfounder: 2<1x3<1 : 2<3 = 1    
3: nonfounder: 2<1x2<1 : 2<3 = 1    
3: nonfounder: 2<1x1<1 : 2<3 = 1    
3: nonfounder: 2<1x1<2 : 2<3 = 1    
3: nonfounder: 2<1x2<2 : 2<3 = 1    
3: nonfounder: 2<1x1<3 : 2<3 = 1    
3: nonfounder: 2<1x2<3 : 2<3 = 1    
3: nonfounder: 1<1x3<2 : 2<3 = 1    
3: nonfounder: 1<1x3<1 : 2<3 = 1    
3: nonfounder: 1<1x2<1 : 2<3 = 1    
3: nonfounder: 1<1x1<1 : 2<3 = 1    
3: nonfounder: 1<1x1<2 : 2<3 = 1    
3: nonfounder: 1<1x2<2 : 2<3 = 1    
3: nonfounder: 1<1x1<3 : 2<3 = 1    
3: nonfounder: 1<1x2<3 : 2<3 = 1    
3: nonfounder: 1<2x3<2 : 2<3 = 1    
3: nonfounder: 1<2x3<1 : 2<3 = 1    
3: nonfounder: 1<2x2<1 : 2<3 = 1    
3: nonfounder: 1<2x1<1 : 2<3 = 1    
3: nonfounder: 1<2x1<2 : 2<3 = 1    
3: nonfounder: 1<2x2<2 : 2<3 = 1    
3: nonfounder: 1<2x1<3 : 2<3 = 1    
3: nonfounder: 1<2x2<3 : 2<3 = 1    
3: nonfounder: 2<2x3<2 : 2<3 = 1    
3: nonfounder: 2<2x3<1 : 2<3 = 1    
3: nonfounder: 2<2x2<1 : 2<3 = 1    
3: nonfounder: 2<2x1<1 : 2<3 = 1    
3: nonfounder: 2<2x1<2 : 2<3 = 1    
3: nonfounder: 2<2x2<2 : 2<3 = 1    
3: nonfounder: 2<2x1<3 : 2<3 = 1    
3: nonfounder: 2<2x2<3 : 2<3 = 1    
3: nonfounder: 1<3x3<2 : 2<3 = 1    
3: nonfounder: 1<3x3<1 : 2<3 = 1    
3: nonfounder: 1<3x2<1 : 2<3 = 1    
3: nonfounder: 1<3x1<1 : 2<3 = 1    
3: nonfounder: 1<3x1<2 : 2<3 = 1    
3: nonfounder: 1<3x2<2 : 2<3 = 1    
3: nonfounder: 1<3x1<3 : 2<3 = 1    
3: nonfounder: 1<3x2<3 : 2<3 = 1    
3: nonfounder: 2<3x3<2 : 2<3 = 1    
3: nonfounder: 2<3x3<1 : 2<3 = 1    
3: nonfounder: 2<3x2<1 : 2<3 = 1    
3: nonfounder: 2<3x1<1 : 2<3 = 1    
3: nonfounder: 2<3x1<2 : 2<3 = 1    
3: nonfounder: 2<3x2<2 : 2<3 = 1    
3: nonfounder: 2<3x1<3 : 2<3 = 1    
3: nonfounder: 2<3x2<3 : 2<3 = 1    

3: nonfounder: 3<2x3<2 : 3<3 = 1    
3: nonfounder: 3<2x3<1 : 3<3 = 1    
3: nonfounder: 3<2x2<1 : 3<3 = 1    
3: nonfounder: 3<2x1<1 : 3<3 = 1    
3: nonfounder: 3<2x1<2 : 3<3 = 1    
3: nonfounder: 3<2x2<2 : 3<3 = 1    
3: nonfounder: 3<2x1<3 : 3<3 = 1    
3: nonfounder: 3<2x2<3 : 3<3 = 1    
3: nonfounder: 3<1x3<2 : 3<3 = 1    
3: nonfounder: 3<1x3<1 : 3<3 = 1    
3: nonfounder: 3<1x2<1 : 3<3 = 1    
3: nonfounder: 3<1x1<1 : 3<3 = 1    
3: nonfounder: 3<1x1<2 : 3<3 = 1    
3: nonfounder: 3<1x2<2 : 3<3 = 1    
3: nonfounder: 3<1x1<3 : 3<3 = 1    
3: nonfounder: 3<1x2<3 : 3<3 = 1    
3: nonfounder: 2<1x3<2 : 3<3 = 1    
3: nonfounder: 2<1x3<1 : 3<3 = 1    
3: nonfounder: 2<1x2<1 : 3<3 = 1    
3: nonfounder: 2<1x1<1 : 3<3 = 1    
3: nonfounder: 2<1x1<2 : 3<3 = 1    
3: nonfounder: 2<1x2<2 : 3<3 = 1    
3: nonfounder: 2<1x1<3 : 3<3 = 1    
3: nonfounder: 2<1x2<3 : 3<3 = 1    
3: nonfounder: 1<1x3<2 : 3<3 = 1    
3: nonfounder: 1<1x3<1 : 3<3 = 1    
3: nonfounder: 1<1x2<1 : 3<3 = 1    
3: nonfounder: 1<1x1<1 : 3<3 = 1    
3: nonfounder: 1<1x1<2 : 3<3 = 1    
3: nonfounder: 1<1x2<2 : 3<3 = 1    
3: nonfounder: 1<1x1<3 : 3<3 = 1    
3: nonfounder: 1<1x2<3 : 3<3 = 1    
3: nonfounder: 1<2x3<2 : 3<3 = 1    
3: nonfounder: 1<2x3<1 : 3<3 = 1    
3: nonfounder: 1<2x2<1 : 3<3 = 1    
3: nonfounder: 1<2x1<1 : 3<3 = 1    
3: nonfounder: 1<2x1<2 : 3<3 = 1    
3: nonfounder: 1<2x2<2 : 3<3 = 1    
3: nonfounder: 1<2x1<3 : 3<3 = 1    
3: nonfounder: 1<2x2<3 : 3<3 = 1    
3: nonfounder: 2<2x3<2 : 3<3 = 1    
3: nonfounder: 2<2x3<1 : 3<3 = 1    
3: nonfounder: 2<2x2<1 : 3<3 = 1    
3: nonfounder: 2<2x1<1 : 3<3 = 1    
3: nonfounder: 2<2x1<2 : 3<3 = 1    
3: nonfounder: 2<2x2<2 : 3<3 = 1    
3: nonfounder: 2<2x1<3 : 3<3 = 1    
3: nonfounder: 2<2x2<3 : 3<3 = 1    
3: nonfounder: 1<3x3<2 : 3<3 = 1    
3: nonfounder: 1<3x3<1 : 3<3 = 1    
3: nonfounder: 1<3x2<1 : 3<3 = 1    
3: nonfounder: 1<3x1<1 : 3<3 = 1    
3: nonfounder: 1<3x1<2 : 3<3 = 1    
3: nonfounder: 1<3x2<2 : 3<3 = 1    
3: nonfounder: 1<3x1<3 : 3<3 = 1    
3: nonfounder: 1<3x2<3 : 3<3 = 1    
3: nonfounder: 2<3x3<2 : 3<3 = 1    
3: nonfounder: 2<3x3<1 : 3<3 = 1    
3: nonfounder: 2<3x2<1 : 3<3 = 1    
3: nonfounder: 2<3x1<1 : 3<3 = 1    
3: nonfounder: 2<3x1<2 : 3<3 = 1    
3: nonfounder: 2<3x2<2 : 3<3 = 1    
3: nonfounder: 2<3x1<3 : 3<3 = 1    
3: nonfounder: 2<3x2<3 : 3<3 = 1    

4: nonfounder: 3<2x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<2x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<2x2<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<2x1<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<2x1<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<2x2<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<2x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<2x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<1x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<1x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<1x2<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<1x1<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<1x1<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<1x2<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<1x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 3<1x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<1x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<1x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<1x2<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<1x1<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<1x1<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<1x2<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<1x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<1x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<1x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<1x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<1x2<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<1x1<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<1x1<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<1x2<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<1x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<1x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<2x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<2x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<2x2<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<2x1<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<2x1<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<2x2<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<2x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<2x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<2x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<2x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<2x2<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<2x1<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<2x1<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<2x2<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<2x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<2x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<3x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<3x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<3x2<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<3x1<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<3x1<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<3x2<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<3x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 1<3x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<3x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<3x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<3x2<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<3x1<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<3x1<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<3x2<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<3x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
4: nonfounder: 2<3x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    

4: nonfounder: 3<2x3<2 : 3<2 = 1    
4: nonfounder: 3<2x3<1 : 3<2 = 1    
4: nonfounder: 3<2x2<1 : 3<2 = 1    
4: nonfounder: 3<2x1<1 : 3<2 = 1    
4: nonfounder: 3<2x1<2 : 3<2 = 1    
4: nonfounder: 3<2x2<2 : 3<2 = 1    
4: nonfounder: 3<2x1<3 : 3<2 = 1    
4: nonfounder: 3<2x2<3 : 3<2 = 1    
4: nonfounder: 3<1x3<2 : 3<2 = 1    
4: nonfounder: 3<1x3<1 : 3<2 = 1    
4: nonfounder: 3<1x2<1 : 3<2 = 1    
4: nonfounder: 3<1x1<1 : 3<2 = 1    
4: nonfounder: 3<1x1<2 : 3<2 = 1    
4: nonfounder: 3<1x2<2 : 3<2 = 1    
4: nonfounder: 3<1x1<3 : 3<2 = 1    
4: nonfounder: 3<1x2<3 : 3<2 = 1    
4: nonfounder: 2<1x3<2 : 3<2 = 1    
4: nonfounder: 2<1x3<1 : 3<2 = 1    
4: nonfounder: 2<1x2<1 : 3<2 = 1    
4: nonfounder: 2<1x1<1 : 3<2 = 1    
4: nonfounder: 2<1x1<2 : 3<2 = 1    
4: nonfounder: 2<1x2<2 : 3<2 = 1    
4: nonfounder: 2<1x1<3 : 3<2 = 1    
4: nonfounder: 2<1x2<3 : 3<2 = 1    
4: nonfounder: 1<1x3<2 : 3<2 = 1    
4: nonfounder: 1<1x3<1 : 3<2 = 1    
4: nonfounder: 1<1x2<1 : 3<2 = 1    
4: nonfounder: 1<1x1<1 : 3<2 = 1    
4: nonfounder: 1<1x1<2 : 3<2 = 1    
4: nonfounder: 1<1x2<2 : 3<2 = 1    
4: nonfounder: 1<1x1<3 : 3<2 = 1    
4: nonfounder: 1<1x2<3 : 3<2 = 1    
4: nonfounder: 1<2x3<2 : 3<2 = 1    
4: nonfounder: 1<2x3<1 : 3<2 = 1    
4: nonfounder: 1<2x2<1 : 3<2 = 1    
4: nonfounder: 1<2x1<1 : 3<2 = 1    
4: nonfounder: 1<2x1<2 : 3<2 = 1    
4: nonfounder: 1<2x2<2 : 3<2 = 1    
4: nonfounder: 1<2x1<3 : 3<2 = 1    
4: nonfounder: 1<2x2<3 : 3<2 = 1    
4: nonfounder: 2<2x3<2 : 3<2 = 1    
4: nonfounder: 2<2x3<1 : 3<2 = 1    
4: nonfounder: 2<2x2<1 : 3<2 = 1    
4: nonfounder: 2<2x1<1 : 3<2 = 1    
4: nonfounder: 2<2x1<2 : 3<2 = 1    
4: nonfounder: 2<2x2<2 : 3<2 = 1    
4: nonfounder: 2<2x1<3 : 3<2 = 1    
4: nonfounder: 2<2x2<3 : 3<2 = 1    
4: nonfounder: 1<3x3<2 : 3<2 = 1    
4: nonfounder: 1<3x3<1 : 3<2 = 1    
4: nonfounder: 1<3x2<1 : 3<2 = 1    
4: nonfounder: 1<3x1<1 : 3<2 = 1    
4: nonfounder: 1<3x1<2 : 3<2 = 1    
4: nonfounder: 1<3x2<2 : 3<2 = 1    
4: nonfounder: 1<3x1<3 : 3<2 = 1    
4: nonfounder: 1<3x2<3 : 3<2 = 1    
4: nonfounder: 2<3x3<2 : 3<2 = 1    
4: nonfounder: 2<3x3<1 : 3<2 = 1    
4: nonfounder: 2<3x2<1 : 3<2 = 1    
4: nonfounder: 2<3x1<1 : 3<2 = 1    
4: nonfounder: 2<3x1<2 : 3<2 = 1    
4: nonfounder: 2<3x2<2 : 3<2 = 1    
4: nonfounder: 2<3x1<3 : 3<2 = 1    
4: nonfounder: 2<3x2<3 : 3<2 = 1    

4: nonfounder: 3<2x3<2 : 3<1 = 1    
4: nonfounder: 3<2x3<1 : 3<1 = 1    
4: nonfounder: 3<2x2<1 : 3<1 = 1    
4: nonfounder: 3<2x1<1 : 3<1 = 1    
4: nonfounder: 3<2x1<2 : 3<1 = 1    
4: nonfounder: 3<2x2<2 : 3<1 = 1    
4: nonfounder: 3<2x1<3 : 3<1 = 1    
4: nonfounder: 3<2x2<3 : 3<1 = 1    
4: nonfounder: 3<1x3<2 : 3<1 = 1    
4: nonfounder: 3<1x3<1 : 3<1 = 1    
4: nonfounder: 3<1x2<1 : 3<1 = 1    
4: nonfounder: 3<1x1<1 : 3<1 = 1    
4: nonfounder: 3<1x1<2 : 3<1 = 1    
4: nonfounder: 3<1x2<2 : 3<1 = 1    
4: nonfounder: 3<1x1<3 : 3<1 = 1    
4: nonfounder: 3<1x2<3 : 3<1 = 1    
4: nonfounder: 2<1x3<2 : 3<1 = 1    
4: nonfounder: 2<1x3<1 : 3<1 = 1    
4: nonfounder: 2<1x2<1 : 3<1 = 1    
4: nonfounder: 2<1x1<1 : 3<1 = 1    
4: nonfounder: 2<1x1<2 : 3<1 = 1    
4: nonfounder: 2<1x2<2 : 3<1 = 1    
4: nonfounder: 2<1x1<3 : 3<1 = 1    
4: nonfounder: 2<1x2<3 : 3<1 = 1    
4: nonfounder: 1<1x3<2 : 3<1 = 1    
4: nonfounder: 1<1x3<1 : 3<1 = 1    
4: nonfounder: 1<1x2<1 : 3<1 = 1    
4: nonfounder: 1<1x1<1 : 3<1 = 1    
4: nonfounder: 1<1x1<2 : 3<1 = 1    
4: nonfounder: 1<1x2<2 : 3<1 = 1    
4: nonfounder: 1<1x1<3 : 3<1 = 1    
4: nonfounder: 1<1x2<3 : 3<1 = 1    
4: nonfounder: 1<2x3<2 : 3<1 = 1    
4: nonfounder: 1<2x3<1 : 3<1 = 1    
4: nonfounder: 1<2x2<1 : 3<1 = 1    
4: nonfounder: 1<2x1<1 : 3<1 = 1    
4: nonfounder: 1<2x1<2 : 3<1 = 1    
4: nonfounder: 1<2x2<2 : 3<1 = 1    
4: nonfounder: 1<2x1<3 : 3<1 = 1    
4: nonfounder: 1<2x2<3 : 3<1 = 1    
4: nonfounder: 2<2x3<2 : 3<1 = 1    
4: nonfounder: 2<2x3<1 : 3<1 = 1    
4: nonfounder: 2<2x2<1 : 3<1 = 1    
4: nonfounder: 2<2x1<1 : 3<1 = 1    
4: nonfounder: 2<2x1<2 : 3<1 = 1    
4: nonfounder: 2<2x2<2 : 3<1 = 1    
4: nonfounder: 2<2x1<3 : 3<1 = 1    
4: nonfounder: 2<2x2<3 : 3<1 = 1    
4: nonfounder: 1<3x3<2 : 3<1 = 1    
4: nonfounder: 1<3x3<1 : 3<1 = 1    
4: nonfounder: 1<3x2<1 : 3<1 = 1    
4: nonfounder: 1<3x1<1 : 3<1 = 1    
4: nonfounder: 1<3x1<2 : 3<1 = 1    
4: nonfounder: 1<3x2<2 : 3<1 = 1    
4: nonfounder: 1<3x1<3 : 3<1 = 1    
4: nonfounder: 1<3x2<3 : 3<1 = 1    
4: nonfounder: 2<3x3<2 : 3<1 = 1    
4: nonfounder: 2<3x3<1 : 3<1 = 1    
4: nonfounder: 2<3x2<1 : 3<1 = 1    
4: nonfounder: 2<3x1<1 : 3<1 = 1    
4: nonfounder: 2<3x1<2 : 3<1 = 1    
4: nonfounder: 2<3x2<2 : 3<1 = 1    
4: nonfounder: 2<3x1<3 : 3<1 = 1    
4: nonfounder: 2<3x2<3 : 3<1 = 1    

4: nonfounder: 3<2x3<2 : 2<1 = 1    
4: nonfounder: 3<2x3<1 : 2<1 = 1    
4: nonfounder: 3<2x2<1 : 2<1 = 1    
4: nonfounder: 3<2x1<1 : 2<1 = 1    
4: nonfounder: 3<2x1<2 : 2<1 = 1    
4: nonfounder: 3<2x2<2 : 2<1 = 1    
4: nonfounder: 3<2x1<3 : 2<1 = 1    
4: nonfounder: 3<2x2<3 : 2<1 = 1    
4: nonfounder: 3<1x3<2 : 2<1 = 1    
4: nonfounder: 3<1x3<1 : 2<1 = 1    
4: nonfounder: 3<1x2<1 : 2<1 = 1    
4: nonfounder: 3<1x1<1 : 2<1 = 1    
4: nonfounder: 3<1x1<2 : 2<1 = 1    
4: nonfounder: 3<1x2<2 : 2<1 = 1    
4: nonfounder: 3<1x1<3 : 2<1 = 1    
4: nonfounder: 3<1x2<3 : 2<1 = 1    
4: nonfounder: 2<1x3<2 : 2<1 = 1    
4: nonfounder: 2<1x3<1 : 2<1 = 1    
4: nonfounder: 2<1x2<1 : 2<1 = 1    
4: nonfounder: 2<1x1<1 : 2<1 = 1    
4: nonfounder: 2<1x1<2 : 2<1 = 1    
4: nonfounder: 2<1x2<2 : 2<1 = 1    
4: nonfounder: 2<1x1<3 : 2<1 = 1    
4: nonfounder: 2<1x2<3 : 2<1 = 1    
4: nonfounder: 1<1x3<2 : 2<1 = 1    
4: nonfounder: 1<1x3<1 : 2<1 = 1    
4: nonfounder: 1<1x2<1 : 2<1 = 1    
4: nonfounder: 1<1x1<1 : 2<1 = 1    
4: nonfounder: 1<1x1<2 : 2<1 = 1    
4: nonfounder: 1<1x2<2 : 2<1 = 1    
4: nonfounder: 1<1x1<3 : 2<1 = 1    
4: nonfounder: 1<1x2<3 : 2<1 = 1    
4: nonfounder: 1<2x3<2 : 2<1 = 1    
4: nonfounder: 1<2x3<1 : 2<1 = 1    
4: nonfounder: 1<2x2<1 : 2<1 = 1    
4: nonfounder: 1<2x1<1 : 2<1 = 1    
4: nonfounder: 1<2x1<2 : 2<1 = 1    
4: nonfounder: 1<2x2<2 : 2<1 = 1    
4: nonfounder: 1<2x1<3 : 2<1 = 1    
4: nonfounder: 1<2x2<3 : 2<1 = 1    
4: nonfounder: 2<2x3<2 : 2<1 = 1    
4: nonfounder: 2<2x3<1 : 2<1 = 1    
4: nonfounder: 2<2x2<1 : 2<1 = 1    
4: nonfounder: 2<2x1<1 : 2<1 = 1    
4: nonfounder: 2<2x1<2 : 2<1 = 1    
4: nonfounder: 2<2x2<2 : 2<1 = 1    
4: nonfounder: 2<2x1<3 : 2<1 = 1    
4: nonfounder: 2<2x2<3 : 2<1 = 1    
4: nonfounder: 1<3x3<2 : 2<1 = 1    
4: nonfounder: 1<3x3<1 : 2<1 = 1    
4: nonfounder: 1<3x2<1 : 2<1 = 1    
4: nonfounder: 1<3x1<1 : 2<1 = 1    
4: nonfounder: 1<3x1<2 : 2<1 = 1    
4: nonfounder: 1<3x2<2 : 2<1 = 1    
4: nonfounder: 1<3x1<3 : 2<1 = 1    
4: nonfounder: 1<3x2<3 : 2<1 = 1    
4: nonfounder: 2<3x3<2 : 2<1 = 1    
4: nonfounder: 2<3x3<1 : 2<1 = 1    
4: nonfounder: 2<3x2<1 : 2<1 = 1    
4: nonfounder: 2<3x1<1 : 2<1 = 1    
4: nonfounder: 2<3x1<2 : 2<1 = 1    
4: nonfounder: 2<3x2<2 : 2<1 = 1    
4: nonfounder: 2<3x1<3 : 2<1 = 1    
4: nonfounder: 2<3x2<3 : 2<1 = 1    

4: nonfounder: 3<2x3<2 : 1<1 = 1    
4: nonfounder: 3<2x3<1 : 1<1 = 1    
4: nonfounder: 3<2x2<1 : 1<1 = 1    
4: nonfounder: 3<2x1<1 : 1<1 = 1    
4: nonfounder: 3<2x1<2 : 1<1 = 1    
4: nonfounder: 3<2x2<2 : 1<1 = 1    
4: nonfounder: 3<2x1<3 : 1<1 = 1    
4: nonfounder: 3<2x2<3 : 1<1 = 1    
4: nonfounder: 3<1x3<2 : 1<1 = 1    
4: nonfounder: 3<1x3<1 : 1<1 = 1    
4: nonfounder: 3<1x2<1 : 1<1 = 1    
4: nonfounder: 3<1x1<1 : 1<1 = 1    
4: nonfounder: 3<1x1<2 : 1<1 = 1    
4: nonfounder: 3<1x2<2 : 1<1 = 1    
4: nonfounder: 3<1x1<3 : 1<1 = 1    
4: nonfounder: 3<1x2<3 : 1<1 = 1    
4: nonfounder: 2<1x3<2 : 1<1 = 1    
4: nonfounder: 2<1x3<1 : 1<1 = 1    
4: nonfounder: 2<1x2<1 : 1<1 = 1    
4: nonfounder: 2<1x1<1 : 1<1 = 1    
4: nonfounder: 2<1x1<2 : 1<1 = 1    
4: nonfounder: 2<1x2<2 : 1<1 = 1    
4: nonfounder: 2<1x1<3 : 1<1 = 1    
4: nonfounder: 2<1x2<3 : 1<1 = 1    
4: nonfounder: 1<1x3<2 : 1<1 = 1    
4: nonfounder: 1<1x3<1 : 1<1 = 1    
4: nonfounder: 1<1x2<1 : 1<1 = 1    
4: nonfounder: 1<1x1<1 : 1<1 = 1    
4: nonfounder: 1<1x1<2 : 1<1 = 1    
4: nonfounder: 1<1x2<2 : 1<1 = 1    
4: nonfounder: 1<1x1<3 : 1<1 = 1    
4: nonfounder: 1<1x2<3 : 1<1 = 1    
4: nonfounder: 1<2x3<2 : 1<1 = 1    
4: nonfounder: 1<2x3<1 : 1<1 = 1    
4: nonfounder: 1<2x2<1 : 1<1 = 1    
4: nonfounder: 1<2x1<1 : 1<1 = 1    
4: nonfounder: 1<2x1<2 : 1<1 = 1    
4: nonfounder: 1<2x2<2 : 1<1 = 1    
4: nonfounder: 1<2x1<3 : 1<1 = 1    
4: nonfounder: 1<2x2<3 : 1<1 = 1    
4: nonfounder: 2<2x3<2 : 1<1 = 1    
4: nonfounder: 2<2x3<1 : 1<1 = 1    
4: nonfounder: 2<2x2<1 : 1<1 = 1    
4: nonfounder: 2<2x1<1 : 1<1 = 1    
4: nonfounder: 2<2x1<2 : 1<1 = 1    
4: nonfounder: 2<2x2<2 : 1<1 = 1    
4: nonfounder: 2<2x1<3 : 1<1 = 1    
4: nonfounder: 2<2x2<3 : 1<1 = 1    
4: nonfounder: 1<3x3<2 : 1<1 = 1    
4: nonfounder: 1<3x3<1 : 1<1 = 1    
4: nonfounder: 1<3x2<1 : 1<1 = 1    
4: nonfounder: 1<3x1<1 : 1<1 = 1    
4: nonfounder: 1<3x1<2 : 1<1 = 1    
4: nonfounder: 1<3x2<2 : 1<1 = 1    
4: nonfounder: 1<3x1<3 : 1<1 = 1    
4: nonfounder: 1<3x2<3 : 1<1 = 1    
4: nonfounder: 2<3x3<2 : 1<1 = 1    
4: nonfounder: 2<3x3<1 : 1<1 = 1    
4: nonfounder: 2<3x2<1 : 1<1 = 1    
4: nonfounder: 2<3x1<1 : 1<1 = 1    
4: nonfounder: 2<3x1<2 : 1<1 = 1    
4: nonfounder: 2<3x2<2 : 1<1 = 1    
4: nonfounder: 2<3x1<3 : 1<1 = 1    
4: nonfounder: 2<3x2<3 : 1<1 = 1    

4: nonfounder: 3<2x3<2 : 1<2 = 1    
4: nonfounder: 3<2x3<1 : 1<2 = 1    
4: nonfounder: 3<2x2<1 : 1<2 = 1    
4: nonfounder: 3<2x1<1 : 1<2 = 1    
4: nonfounder: 3<2x1<2 : 1<2 = 1    
4: nonfounder: 3<2x2<2 : 1<2 = 1    
4: nonfounder: 3<2x1<3 : 1<2 = 1    
4: nonfounder: 3<2x2<3 : 1<2 = 1    
4: nonfounder: 3<1x3<2 : 1<2 = 1    
4: nonfounder: 3<1x3<1 : 1<2 = 1    
4: nonfounder: 3<1x2<1 : 1<2 = 1    
4: nonfounder: 3<1x1<1 : 1<2 = 1    
4: nonfounder: 3<1x1<2 : 1<2 = 1    
4: nonfounder: 3<1x2<2 : 1<2 = 1    
4: nonfounder: 3<1x1<3 : 1<2 = 1    
4: nonfounder: 3<1x2<3 : 1<2 = 1    
4: nonfounder: 2<1x3<2 : 1<2 = 1    
4: nonfounder: 2<1x3<1 : 1<2 = 1    
4: nonfounder: 2<1x2<1 : 1<2 = 1    
4: nonfounder: 2<1x1<1 : 1<2 = 1    
4: nonfounder: 2<1x1<2 : 1<2 = 1    
4: nonfounder: 2<1x2<2 : 1<2 = 1    
4: nonfounder: 2<1x1<3 : 1<2 = 1    
4: nonfounder: 2<1x2<3 : 1<2 = 1    
4: nonfounder: 1<1x3<2 : 1<2 = 1    
4: nonfounder: 1<1x3<1 : 1<2 = 1    
4: nonfounder: 1<1x2<1 : 1<2 = 1    
4: nonfounder: 1<1x1<1 : 1<2 = 1    
4: nonfounder: 1<1x1<2 : 1<2 = 1    
4: nonfounder: 1<1x2<2 : 1<2 = 1    
4: nonfounder: 1<1x1<3 : 1<2 = 1    
4: nonfounder: 1<1x2<3 : 1<2 = 1    
4: nonfounder: 1<2x3<2 : 1<2 = 1    
4: nonfounder: 1<2x3<1 : 1<2 = 1    
4: nonfounder: 1<2x2<1 : 1<2 = 1    
4: nonfounder: 1<2x1<1 : 1<2 = 1    
4: nonfounder: 1<2x1<2 : 1<2 = 1    
4: nonfounder: 1<2x2<2 : 1<2 = 1    
4: nonfounder: 1<2x1<3 : 1<2 = 1    
4: nonfounder: 1<2x2<3 : 1<2 = 1    
4: nonfounder: 2<2x3<2 : 1<2 = 1    
4: nonfounder: 2<2x3<1 : 1<2 = 1    
4: nonfounder: 2<2x2<1 : 1<2 = 1    
4: nonfounder: 2<2x1<1 : 1<2 = 1    
4: nonfounder: 2<2x1<2 : 1<2 = 1    
4: nonfounder: 2<2x2<2 : 1<2 = 1    
4: nonfounder: 2<2x1<3 : 1<2 = 1    
4: nonfounder: 2<2x2<3 : 1<2 = 1    
4: nonfounder: 1<3x3<2 : 1<2 = 1    
4: nonfounder: 1<3x3<1 : 1<2 = 1    
4: nonfounder: 1<3x2<1 : 1<2 = 1    
4: nonfounder: 1<3x1<1 : 1<2 = 1    
4: nonfounder: 1<3x1<2 : 1<2 = 1    
4: nonfounder: 1<3x2<2 : 1<2 = 1    
4: nonfounder: 1<3x1<3 : 1<2 = 1    
4: nonfounder: 1<3x2<3 : 1<2 = 1    
4: nonfounder: 2<3x3<2 : 1<2 = 1    
4: nonfounder: 2<3x3<1 : 1<2 = 1    
4: nonfounder: 2<3x2<1 : 1<2 = 1    
4: nonfounder: 2<3x1<1 : 1<2 = 1    
4: nonfounder: 2<3x1<2 : 1<2 = 1    
4: nonfounder: 2<3x2<2 : 1<2 = 1    
4: nonfounder: 2<3x1<3 : 1<2 = 1    
4: nonfounder: 2<3x2<3 : 1<2 = 1    

4: nonfounder: 3<2x3<2 : 2<2 = 1    
4: nonfounder: 3<2x3<1 : 2<2 = 1    
4: nonfounder: 3<2x2<1 : 2<2 = 1    
4: nonfounder: 3<2x1<1 : 2<2 = 1    
4: nonfounder: 3<2x1<2 : 2<2 = 1    
4: nonfounder: 3<2x2<2 : 2<2 = 1    
4: nonfounder: 3<2x1<3 : 2<2 = 1    
4: nonfounder: 3<2x2<3 : 2<2 = 1    
4: nonfounder: 3<1x3<2 : 2<2 = 1    
4: nonfounder: 3<1x3<1 : 2<2 = 1    
4: nonfounder: 3<1x2<1 : 2<2 = 1    
4: nonfounder: 3<1x1<1 : 2<2 = 1    
4: nonfounder: 3<1x1<2 : 2<2 = 1    
4: nonfounder: 3<1x2<2 : 2<2 = 1    
4: nonfounder: 3<1x1<3 : 2<2 = 1    
4: nonfounder: 3<1x2<3 : 2<2 = 1    
4: nonfounder: 2<1x3<2 : 2<2 = 1    
4: nonfounder: 2<1x3<1 : 2<2 = 1    
4: nonfounder: 2<1x2<1 : 2<2 = 1    
4: nonfounder: 2<1x1<1 : 2<2 = 1    
4: nonfounder: 2<1x1<2 : 2<2 = 1    
4: nonfounder: 2<1x2<2 : 2<2 = 1    
4: nonfounder: 2<1x1<3 : 2<2 = 1    
4: nonfounder: 2<1x2<3 : 2<2 = 1    
4: nonfounder: 1<1x3<2 : 2<2 = 1    
4: nonfounder: 1<1x3<1 : 2<2 = 1    
4: nonfounder: 1<1x2<1 : 2<2 = 1    
4: nonfounder: 1<1x1<1 : 2<2 = 1    
4: nonfounder: 1<1x1<2 : 2<2 = 1    
4: nonfounder: 1<1x2<2 : 2<2 = 1    
4: nonfounder: 1<1x1<3 : 2<2 = 1    
4: nonfounder: 1<1x2<3 : 2<2 = 1    
4: nonfounder: 1<2x3<2 : 2<2 = 1    
4: nonfounder: 1<2x3<1 : 2<2 = 1    
4: nonfounder: 1<2x2<1 : 2<2 = 1    
4: nonfounder: 1<2x1<1 : 2<2 = 1    
4: nonfounder: 1<2x1<2 : 2<2 = 1    
4: nonfounder: 1<2x2<2 : 2<2 = 1    
4: nonfounder: 1<2x1<3 : 2<2 = 1    
4: nonfounder: 1<2x2<3 : 2<2 = 1    
4: nonfounder: 2<2x3<2 : 2<2 = 1    
4: nonfounder: 2<2x3<1 : 2<2 = 1    
4: nonfounder: 2<2x2<1 : 2<2 = 1    
4: nonfounder: 2<2x1<1 : 2<2 = 1    
4: nonfounder: 2<2x1<2 : 2<2 = 1    
4: nonfounder: 2<2x2<2 : 2<2 = 1    
4: nonfounder: 2<2x1<3 : 2<2 = 1    
4: nonfounder: 2<2x2<3 : 2<2 = 1    
4: nonfounder: 1<3x3<2 : 2<2 = 1    
4: nonfounder: 1<3x3<1 : 2<2 = 1    
4: nonfounder: 1<3x2<1 : 2<2 = 1    
4: nonfounder: 1<3x1<1 : 2<2 = 1    
4: nonfounder: 1<3x1<2 : 2<2 = 1    
4: nonfounder: 1<3x2<2 : 2<2 = 1    
4: nonfounder: 1<3x1<3 : 2<2 = 1    
4: nonfounder: 1<3x2<3 : 2<2 = 1    
4: nonfounder: 2<3x3<2 : 2<2 = 1    
4: nonfounder: 2<3x3<1 : 2<2 = 1    
4: nonfounder: 2<3x2<1 : 2<2 = 1    
4: nonfounder: 2<3x1<1 : 2<2 = 1    
4: nonfounder: 2<3x1<2 : 2<2 = 1    
4: nonfounder: 2<3x2<2 : 2<2 = 1    
4: nonfounder: 2<3x1<3 : 2<2 = 1    
4: nonfounder: 2<3x2<3 : 2<2 = 1    

4: nonfounder: 3<2x3<2 : 1<3 = 1    
4: nonfounder: 3<2x3<1 : 1<3 = 1    
4: nonfounder: 3<2x2<1 : 1<3 = 1    
4: nonfounder: 3<2x1<1 : 1<3 = 1    
4: nonfounder: 3<2x1<2 : 1<3 = 1    
4: nonfounder: 3<2x2<2 : 1<3 = 1    
4: nonfounder: 3<2x1<3 : 1<3 = 1    
4: nonfounder: 3<2x2<3 : 1<3 = 1    
4: nonfounder: 3<1x3<2 : 1<3 = 1    
4: nonfounder: 3<1x3<1 : 1<3 = 1    
4: nonfounder: 3<1x2<1 : 1<3 = 1    
4: nonfounder: 3<1x1<1 : 1<3 = 1    
4: nonfounder: 3<1x1<2 : 1<3 = 1    
4: nonfounder: 3<1x2<2 : 1<3 = 1    
4: nonfounder: 3<1x1<3 : 1<3 = 1    
4: nonfounder: 3<1x2<3 : 1<3 = 1    
4: nonfounder: 2<1x3<2 : 1<3 = 1    
4: nonfounder: 2<1x3<1 : 1<3 = 1    
4: nonfounder: 2<1x2<1 : 1<3 = 1    
4: nonfounder: 2<1x1<1 : 1<3 = 1    
4: nonfounder: 2<1x1<2 : 1<3 = 1    
4: nonfounder: 2<1x2<2 : 1<3 = 1    
4: nonfounder: 2<1x1<3 : 1<3 = 1    
4: nonfounder: 2<1x2<3 : 1<3 = 1    
4: nonfounder: 1<1x3<2 : 1<3 = 1    
4: nonfounder: 1<1x3<1 : 1<3 = 1    
4: nonfounder: 1<1x2<1 : 1<3 = 1    
4: nonfounder: 1<1x1<1 : 1<3 = 1    
4: nonfounder: 1<1x1<2 : 1<3 = 1    
4: nonfounder: 1<1x2<2 : 1<3 = 1    
4: nonfounder: 1<1x1<3 : 1<3 = 1    
4: nonfounder: 1<1x2<3 : 1<3 = 1    
4: nonfounder: 1<2x3<2 : 1<3 = 1    
4: nonfounder: 1<2x3<1 : 1<3 = 1    
4: nonfounder: 1<2x2<1 : 1<3 = 1    
4: nonfounder: 1<2x1<1 : 1<3 = 1    
4: nonfounder: 1<2x1<2 : 1<3 = 1    
4: nonfounder: 1<2x2<2 : 1<3 = 1    
4: nonfounder: 1<2x1<3 : 1<3 = 1    
4: nonfounder: 1<2x2<3 : 1<3 = 1    
4: nonfounder: 2<2x3<2 : 1<3 = 1    
4: nonfounder: 2<2x3<1 : 1<3 = 1    
4: nonfounder: 2<2x2<1 : 1<3 = 1    
4: nonfounder: 2<2x1<1 : 1<3 = 1    
4: nonfounder: 2<2x1<2 : 1<3 = 1    
4: nonfounder: 2<2x2<2 : 1<3 = 1    
4: nonfounder: 2<2x1<3 : 1<3 = 1    
4: nonfounder: 2<2x2<3 : 1<3 = 1    
4: nonfounder: 1<3x3<2 : 1<3 = 1    
4: nonfounder: 1<3x3<1 : 1<3 = 1    
4: nonfounder: 1<3x2<1 : 1<3 = 1    
4: nonfounder: 1<3x1<1 : 1<3 = 1    
4: nonfounder: 1<3x1<2 : 1<3 = 1    
4: nonfounder: 1<3x2<2 : 1<3 = 1    
4: nonfounder: 1<3x1<3 : 1<3 = 1    
4: nonfounder: 1<3x2<3 : 1<3 = 1    
4: nonfounder: 2<3x3<2 : 1<3 = 1    
4: nonfounder: 2<3x3<1 : 1<3 = 1    
4: nonfounder: 2<3x2<1 : 1<3 = 1    
4: nonfounder: 2<3x1<1 : 1<3 = 1    
4: nonfounder: 2<3x1<2 : 1<3 = 1    
4: nonfounder: 2<3x2<2 : 1<3 = 1    
4: nonfounder: 2<3x1<3 : 1<3 = 1    
4: nonfounder: 2<3x2<3 : 1<3 = 1    

4: nonfounder: 3<2x3<2 : 2<3 = 1    
4: nonfounder: 3<2x3<1 : 2<3 = 1    
4: nonfounder: 3<2x2<1 : 2<3 = 1    
4: nonfounder: 3<2x1<1 : 2<3 = 1    
4: nonfounder: 3<2x1<2 : 2<3 = 1    
4: nonfounder: 3<2x2<2 : 2<3 = 1    
4: nonfounder: 3<2x1<3 : 2<3 = 1    
4: nonfounder: 3<2x2<3 : 2<3 = 1    
4: nonfounder: 3<1x3<2 : 2<3 = 1    
4: nonfounder: 3<1x3<1 : 2<3 = 1    
4: nonfounder: 3<1x2<1 : 2<3 = 1    
4: nonfounder: 3<1x1<1 : 2<3 = 1    
4: nonfounder: 3<1x1<2 : 2<3 = 1    
4: nonfounder: 3<1x2<2 : 2<3 = 1    
4: nonfounder: 3<1x1<3 : 2<3 = 1    
4: nonfounder: 3<1x2<3 : 2<3 = 1    
4: nonfounder: 2<1x3<2 : 2<3 = 1    
4: nonfounder: 2<1x3<1 : 2<3 = 1    
4: nonfounder: 2<1x2<1 : 2<3 = 1    
4: nonfounder: 2<1x1<1 : 2<3 = 1    
4: nonfounder: 2<1x1<2 : 2<3 = 1    
4: nonfounder: 2<1x2<2 : 2<3 = 1    
4: nonfounder: 2<1x1<3 : 2<3 = 1    
4: nonfounder: 2<1x2<3 : 2<3 = 1    
4: nonfounder: 1<1x3<2 : 2<3 = 1    
4: nonfounder: 1<1x3<1 : 2<3 = 1    
4: nonfounder: 1<1x2<1 : 2<3 = 1    
4: nonfounder: 1<1x1<1 : 2<3 = 1    
4: nonfounder: 1<1x1<2 : 2<3 = 1    
4: nonfounder: 1<1x2<2 : 2<3 = 1    
4: nonfounder: 1<1x1<3 : 2<3 = 1    
4: nonfounder: 1<1x2<3 : 2<3 = 1    
4: nonfounder: 1<2x3<2 : 2<3 = 1    
4: nonfounder: 1<2x3<1 : 2<3 = 1    
4: nonfounder: 1<2x2<1 : 2<3 = 1    
4: nonfounder: 1<2x1<1 : 2<3 = 1    
4: nonfounder: 1<2x1<2 : 2<3 = 1    
4: nonfounder: 1<2x2<2 : 2<3 = 1    
4: nonfounder: 1<2x1<3 : 2<3 = 1    
4: nonfounder: 1<2x2<3 : 2<3 = 1    
4: nonfounder: 2<2x3<2 : 2<3 = 1    
4: nonfounder: 2<2x3<1 : 2<3 = 1    
4: nonfounder: 2<2x2<1 : 2<3 = 1    
4: nonfounder: 2<2x1<1 : 2<3 = 1    
4: nonfounder: 2<2x1<2 : 2<3 = 1    
4: nonfounder: 2<2x2<2 : 2<3 = 1    
4: nonfounder: 2<2x1<3 : 2<3 = 1    
4: nonfounder: 2<2x2<3 : 2<3 = 1    
4: nonfounder: 1<3x3<2 : 2<3 = 1    
4: nonfounder: 1<3x3<1 : 2<3 = 1    
4: nonfounder: 1<3x2<1 : 2<3 = 1    
4: nonfounder: 1<3x1<1 : 2<3 = 1    
4: nonfounder: 1<3x1<2 : 2<3 = 1    
4: nonfounder: 1<3x2<2 : 2<3 = 1    
4: nonfounder: 1<3x1<3 : 2<3 = 1    
4: nonfounder: 1<3x2<3 : 2<3 = 1    
4: nonfounder: 2<3x3<2 : 2<3 = 1    
4: nonfounder: 2<3x3<1 : 2<3 = 1    
4: nonfounder: 2<3x2<1 : 2<3 = 1    
4: nonfounder: 2<3x1<1 : 2<3 = 1    
4: nonfounder: 2<3x1<2 : 2<3 = 1    
4: nonfounder: 2<3x2<2 : 2<3 = 1    
4: nonfounder: 2<3x1<3 : 2<3 = 1    
4: nonfounder: 2<3x2<3 : 2<3 = 1    

4: nonfounder: 3<2x3<2 : 3<3 = 1    
4: nonfounder: 3<2x3<1 : 3<3 = 1    
4: nonfounder: 3<2x2<1 : 3<3 = 1    
4: nonfounder: 3<2x1<1 : 3<3 = 1    
4: nonfounder: 3<2x1<2 : 3<3 = 1    
4: nonfounder: 3<2x2<2 : 3<3 = 1    
4: nonfounder: 3<2x1<3 : 3<3 = 1    
4: nonfounder: 3<2x2<3 : 3<3 = 1    
4: nonfounder: 3<1x3<2 : 3<3 = 1    
4: nonfounder: 3<1x3<1 : 3<3 = 1    
4: nonfounder: 3<1x2<1 : 3<3 = 1    
4: nonfounder: 3<1x1<1 : 3<3 = 1    
4: nonfounder: 3<1x1<2 : 3<3 = 1    
4: nonfounder: 3<1x2<2 : 3<3 = 1    
4: nonfounder: 3<1x1<3 : 3<3 = 1    
4: nonfounder: 3<1x2<3 : 3<3 = 1    
4: nonfounder: 2<1x3<2 : 3<3 = 1    
4: nonfounder: 2<1x3<1 : 3<3 = 1    
4: nonfounder: 2<1x2<1 : 3<3 = 1    
4: nonfounder: 2<1x1<1 : 3<3 = 1    
4: nonfounder: 2<1x1<2 : 3<3 = 1    
4: nonfounder: 2<1x2<2 : 3<3 = 1    
4: nonfounder: 2<1x1<3 : 3<3 = 1    
4: nonfounder: 2<1x2<3 : 3<3 = 1    
4: nonfounder: 1<1x3<2 : 3<3 = 1    
4: nonfounder: 1<1x3<1 : 3<3 = 1    
4: nonfounder: 1<1x2<1 : 3<3 = 1    
4: nonfounder: 1<1x1<1 : 3<3 = 1    
4: nonfounder: 1<1x1<2 : 3<3 = 1    
4: nonfounder: 1<1x2<2 : 3<3 = 1    
4: nonfounder: 1<1x1<3 : 3<3 = 1    
4: nonfounder: 1<1x2<3 : 3<3 = 1    
4: nonfounder: 1<2x3<2 : 3<3 = 1    
4: nonfounder: 1<2x3<1 : 3<3 = 1    
4: nonfounder: 1<2x2<1 : 3<3 = 1    
4: nonfounder: 1<2x1<1 : 3<3 = 1    
4: nonfounder: 1<2x1<2 : 3<3 = 1    
4: nonfounder: 1<2x2<2 : 3<3 = 1    
4: nonfounder: 1<2x1<3 : 3<3 = 1    
4: nonfounder: 1<2x2<3 : 3<3 = 1    
4: nonfounder: 2<2x3<2 : 3<3 = 1    
4: nonfounder: 2<2x3<1 : 3<3 = 1    
4: nonfounder: 2<2x2<1 : 3<3 = 1    
4: nonfounder: 2<2x1<1 : 3<3 = 1    
4: nonfounder: 2<2x1<2 : 3<3 = 1    
4: nonfounder: 2<2x2<2 : 3<3 = 1    
4: nonfounder: 2<2x1<3 : 3<3 = 1    
4: nonfounder: 2<2x2<3 : 3<3 = 1    
4: nonfounder: 1<3x3<2 : 3<3 = 1    
4: nonfounder: 1<3x3<1 : 3<3 = 1    
4: nonfounder: 1<3x2<1 : 3<3 = 1    
4: nonfounder: 1<3x1<1 : 3<3 = 1    
4: nonfounder: 1<3x1<2 : 3<3 = 1    
4: nonfounder: 1<3x2<2 : 3<3 = 1    
4: nonfounder: 1<3x1<3 : 3<3 = 1    
4: nonfounder: 1<3x2<3 : 3<3 = 1    
4: nonfounder: 2<3x3<2 : 3<3 = 1    
4: nonfounder: 2<3x3<1 : 3<3 = 1    
4: nonfounder: 2<3x2<1 : 3<3 = 1    
4: nonfounder: 2<3x1<1 : 3<3 = 1    
4: nonfounder: 2<3x1<2 : 3<3 = 1    
4: nonfounder: 2<3x2<2 : 3<3 = 1    
4: nonfounder: 2<3x1<3 : 3<3 = 1    
4: nonfounder: 2<3x2<3 : 3<3 = 1    

5: nonfounder: 3<2x3<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<2x3<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<2x2<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<2x1<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<2x1<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<2x2<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<2x1<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<2x2<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<1x3<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<1x3<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<1x2<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<1x1<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<1x1<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<1x2<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<1x1<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 3<1x2<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<1x3<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<1x3<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<1x2<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<1x1<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<1x1<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<1x2<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<1x1<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<1x2<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<1x3<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<1x3<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<1x2<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<1x1<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<1x1<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<1x2<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<1x1<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<1x2<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<2x3<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<2x3<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<2x2<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<2x1<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<2x1<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<2x2<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<2x1<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<2x2<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<2x3<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<2x3<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<2x2<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<2x1<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<2x1<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<2x2<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<2x1<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<2x2<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<3x3<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<3x3<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<3x2<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<3x1<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<3x1<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<3x2<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<3x1<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 1<3x2<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<3x3<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<3x3<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<3x2<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<3x1<1 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<3x1<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<3x2<2 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<3x1<3 : 2<1 = 1    1<2 = 1    
5: nonfounder: 2<3x2<3 : 2<1 = 1    1<2 = 1    

5: nonfounder: 3<2x3<2 : 2<1 = 1    
5: nonfounder: 3<2x3<1 : 2<1 = 1    
5: nonfounder: 3<2x2<1 : 2<1 = 1    
5: nonfounder: 3<2x1<1 : 2<1 = 1    
5: nonfounder: 3<2x1<2 : 2<1 = 1    
5: nonfounder: 3<2x2<2 : 2<1 = 1    
5: nonfounder: 3<2x1<3 : 2<1 = 1    
5: nonfounder: 3<2x2<3 : 2<1 = 1    
5: nonfounder: 3<1x3<2 : 2<1 = 1    
5: nonfounder: 3<1x3<1 : 2<1 = 1    
5: nonfounder: 3<1x2<1 : 2<1 = 1    
5: nonfounder: 3<1x1<1 : 2<1 = 1    
5: nonfounder: 3<1x1<2 : 2<1 = 1    
5: nonfounder: 3<1x2<2 : 2<1 = 1    
5: nonfounder: 3<1x1<3 : 2<1 = 1    
5: nonfounder: 3<1x2<3 : 2<1 = 1    
5: nonfounder: 2<1x3<2 : 2<1 = 1    
5: nonfounder: 2<1x3<1 : 2<1 = 1    
5: nonfounder: 2<1x2<1 : 2<1 = 1    
5: nonfounder: 2<1x1<1 : 2<1 = 1    
5: nonfounder: 2<1x1<2 : 2<1 = 1    
5: nonfounder: 2<1x2<2 : 2<1 = 1    
5: nonfounder: 2<1x1<3 : 2<1 = 1    
5: nonfounder: 2<1x2<3 : 2<1 = 1    
5: nonfounder: 1<1x3<2 : 2<1 = 1    
5: nonfounder: 1<1x3<1 : 2<1 = 1    
5: nonfounder: 1<1x2<1 : 2<1 = 1    
5: nonfounder: 1<1x1<1 : 2<1 = 1    
5: nonfounder: 1<1x1<2 : 2<1 = 1    
5: nonfounder: 1<1x2<2 : 2<1 = 1    
5: nonfounder: 1<1x1<3 : 2<1 = 1    
5: nonfounder: 1<1x2<3 : 2<1 = 1    
5: nonfounder: 1<2x3<2 : 2<1 = 1    
5: nonfounder: 1<2x3<1 : 2<1 = 1    
5: nonfounder: 1<2x2<1 : 2<1 = 1    
5: nonfounder: 1<2x1<1 : 2<1 = 1    
5: nonfounder: 1<2x1<2 : 2<1 = 1    
5: nonfounder: 1<2x2<2 : 2<1 = 1    
5: nonfounder: 1<2x1<3 : 2<1 = 1    
5: nonfounder: 1<2x2<3 : 2<1 = 1    
5: nonfounder: 2<2x3<2 : 2<1 = 1    
5: nonfounder: 2<2x3<1 : 2<1 = 1    
5: nonfounder: 2<2x2<1 : 2<1 = 1    
5: nonfounder: 2<2x1<1 : 2<1 = 1    
5: nonfounder: 2<2x1<2 : 2<1 = 1    
5: nonfounder: 2<2x2<2 : 2<1 = 1    
5: nonfounder: 2<2x1<3 : 2<1 = 1    
5: nonfounder: 2<2x2<3 : 2<1 = 1    
5: nonfounder: 1<3x3<2 : 2<1 = 1    
5: nonfounder: 1<3x3<1 : 2<1 = 1    
5: nonfounder: 1<3x2<1 : 2<1 = 1    
5: nonfounder: 1<3x1<1 : 2<1 = 1    
5: nonfounder: 1<3x1<2 : 2<1 = 1    
5: nonfounder: 1<3x2<2 : 2<1 = 1    
5: nonfounder: 1<3x1<3 : 2<1 = 1    
5: nonfounder: 1<3x2<3 : 2<1 = 1    
5: nonfounder: 2<3x3<2 : 2<1 = 1    
5: nonfounder: 2<3x3<1 : 2<1 = 1    
5: nonfounder: 2<3x2<1 : 2<1 = 1    
5: nonfounder: 2<3x1<1 : 2<1 = 1    
5: nonfounder: 2<3x1<2 : 2<1 = 1    
5: nonfounder: 2<3x2<2 : 2<1 = 1    
5: nonfounder: 2<3x1<3 : 2<1 = 1    
5: nonfounder: 2<3x2<3 : 2<1 = 1    

5: nonfounder: 3<2x3<2 : 1<2 = 1    
5: nonfounder: 3<2x3<1 : 1<2 = 1    
5: nonfounder: 3<2x2<1 : 1<2 = 1    
5: nonfounder: 3<2x1<1 : 1<2 = 1    
5: nonfounder: 3<2x1<2 : 1<2 = 1    
5: nonfounder: 3<2x2<2 : 1<2 = 1    
5: nonfounder: 3<2x1<3 : 1<2 = 1    
5: nonfounder: 3<2x2<3 : 1<2 = 1    
5: nonfounder: 3<1x3<2 : 1<2 = 1    
5: nonfounder: 3<1x3<1 : 1<2 = 1    
5: nonfounder: 3<1x2<1 : 1<2 = 1    
5: nonfounder: 3<1x1<1 : 1<2 = 1    
5: nonfounder: 3<1x1<2 : 1<2 = 1    
5: nonfounder: 3<1x2<2 : 1<2 = 1    
5: nonfounder: 3<1x1<3 : 1<2 = 1    
5: nonfounder: 3<1x2<3 : 1<2 = 1    
5: nonfounder: 2<1x3<2 : 1<2 = 1    
5: nonfounder: 2<1x3<1 : 1<2 = 1    
5: nonfounder: 2<1x2<1 : 1<2 = 1    
5: nonfounder: 2<1x1<1 : 1<2 = 1    
5: nonfounder: 2<1x1<2 : 1<2 = 1    
5: nonfounder: 2<1x2<2 : 1<2 = 1    
5: nonfounder: 2<1x1<3 : 1<2 = 1    
5: nonfounder: 2<1x2<3 : 1<2 = 1    
5: nonfounder: 1<1x3<2 : 1<2 = 1    
5: nonfounder: 1<1x3<1 : 1<2 = 1    
5: nonfounder: 1<1x2<1 : 1<2 = 1    
5: nonfounder: 1<1x1<1 : 1<2 = 1    
5: nonfounder: 1<1x1<2 : 1<2 = 1    
5: nonfounder: 1<1x2<2 : 1<2 = 1    
5: nonfounder: 1<1x1<3 : 1<2 = 1    
5: nonfounder: 1<1x2<3 : 1<2 = 1    
5: nonfounder: 1<2x3<2 : 1<2 = 1    
5: nonfounder: 1<2x3<1 : 1<2 = 1    
5: nonfounder: 1<2x2<1 : 1<2 = 1    
5: nonfounder: 1<2x1<1 : 1<2 = 1    
5: nonfounder: 1<2x1<2 : 1<2 = 1    
5: nonfounder: 1<2x2<2 : 1<2 = 1    
5: nonfounder: 1<2x1<3 : 1<2 = 1    
5: nonfounder: 1<2x2<3 : 1<2 = 1    
5: nonfounder: 2<2x3<2 : 1<2 = 1    
5: nonfounder: 2<2x3<1 : 1<2 = 1    
5: nonfounder: 2<2x2<1 : 1<2 = 1    
5: nonfounder: 2<2x1<1 : 1<2 = 1    
5: nonfounder: 2<2x1<2 : 1<2 = 1    
5: nonfounder: 2<2x2<2 : 1<2 = 1    
5: nonfounder: 2<2x1<3 : 1<2 = 1    
5: nonfounder: 2<2x2<3 : 1<2 = 1    
5: nonfounder: 1<3x3<2 : 1<2 = 1    
5: nonfounder: 1<3x3<1 : 1<2 = 1    
5: nonfounder: 1<3x2<1 : 1<2 = 1    
5: nonfounder: 1<3x1<1 : 1<2 = 1    
5: nonfounder: 1<3x1<2 : 1<2 = 1    
5: nonfounder: 1<3x2<2 : 1<2 = 1    
5: nonfounder: 1<3x1<3 : 1<2 = 1    
5: nonfounder: 1<3x2<3 : 1<2 = 1    
5: nonfounder: 2<3x3<2 : 1<2 = 1    
5: nonfounder: 2<3x3<1 : 1<2 = 1    
5: nonfounder: 2<3x2<1 : 1<2 = 1    
5: nonfounder: 2<3x1<1 : 1<2 = 1    
5: nonfounder: 2<3x1<2 : 1<2 = 1    
5: nonfounder: 2<3x2<2 : 1<2 = 1    
5: nonfounder: 2<3x1<3 : 1<2 = 1    
5: nonfounder: 2<3x2<3 : 1<2 = 1    

6: founder   : 3<2 = 1    3<1 = 1    1<3 = 1    2<3 = 1    3<3 = 1    

7: founder   : 2<1 = 1    1<2 = 1    

8: nonfounder: 3<2x3<2 : 3<3 = 1    
8: nonfounder: 3<2x3<1 : 3<3 = 1    
8: nonfounder: 3<2x1<3 : 3<3 = 1    
8: nonfounder: 3<2x2<3 : 3<3 = 1    
8: nonfounder: 3<2x3<3 : 3<3 = 1    
8: nonfounder: 3<1x3<2 : 3<3 = 1    
8: nonfounder: 3<1x3<1 : 3<3 = 1    
8: nonfounder: 3<1x1<3 : 3<3 = 1    
8: nonfounder: 3<1x2<3 : 3<3 = 1    
8: nonfounder: 3<1x3<3 : 3<3 = 1    
8: nonfounder: 1<3x3<2 : 3<3 = 1    
8: nonfounder: 1<3x3<1 : 3<3 = 1    
8: nonfounder: 1<3x1<3 : 3<3 = 1    
8: nonfounder: 1<3x2<3 : 3<3 = 1    
8: nonfounder: 1<3x3<3 : 3<3 = 1    
8: nonfounder: 2<3x3<2 : 3<3 = 1    
8: nonfounder: 2<3x3<1 : 3<3 = 1    
8: nonfounder: 2<3x1<3 : 3<3 = 1    
8: nonfounder: 2<3x2<3 : 3<3 = 1    
8: nonfounder: 2<3x3<3 : 3<3 = 1    
8: nonfounder: 3<3x3<2 : 3<3 = 1    
8: nonfounder: 3<3x3<1 : 3<3 = 1    
8: nonfounder: 3<3x1<3 : 3<3 = 1    
8: nonfounder: 3<3x2<3 : 3<3 = 1    
8: nonfounder: 3<3x3<3 : 3<3 = 1    

8: nonfounder: 3<2x3<2 : 3<3 = 1    
8: nonfounder: 3<2x3<1 : 3<3 = 1    
8: nonfounder: 3<2x1<3 : 3<3 = 1    
8: nonfounder: 3<2x2<3 : 3<3 = 1    
8: nonfounder: 3<2x3<3 : 3<3 = 1    
8: nonfounder: 3<1x3<2 : 3<3 = 1    
8: nonfounder: 3<1x3<1 : 3<3 = 1    
8: nonfounder: 3<1x1<3 : 3<3 = 1    
8: nonfounder: 3<1x2<3 : 3<3 = 1    
8: nonfounder: 3<1x3<3 : 3<3 = 1    
8: nonfounder: 1<3x3<2 : 3<3 = 1    
8: nonfounder: 1<3x3<1 : 3<3 = 1    
8: nonfounder: 1<3x1<3 : 3<3 = 1    
8: nonfounder: 1<3x2<3 : 3<3 = 1    
8: nonfounder: 1<3x3<3 : 3<3 = 1    
8: nonfounder: 2<3x3<2 : 3<3 = 1    
8: nonfounder: 2<3x3<1 : 3<3 = 1    
8: nonfounder: 2<3x1<3 : 3<3 = 1    
8: nonfounder: 2<3x2<3 : 3<3 = 1    
8: nonfounder: 2<3x3<3 : 3<3 = 1    
8: nonfounder: 3<3x3<2 : 3<3 = 1    
8: nonfounder: 3<3x3<1 : 3<3 = 1    
8: nonfounder: 3<3x1<3 : 3<3 = 1    
8: nonfounder: 3<3x2<3 : 3<3 = 1    
8: nonfounder: 3<3x3<3 : 3<3 = 1    

9: nonfounder: 3<2x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<2x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<2x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<2x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<2x3<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<1x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<1x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<1x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<1x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<1x3<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 1<3x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 1<3x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 1<3x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 1<3x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 1<3x3<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 2<3x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 2<3x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 2<3x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 2<3x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 2<3x3<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<3x3<2 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<3x3<1 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<3x1<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<3x2<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    
9: nonfounder: 3<3x3<3 : 3<2 = 1    3<1 = 1    2<1 = 1    1<1 = 1    1<2 = 1    2<2 = 1    1<3 = 1    2<3 = 1    3<3 = 1    

9: nonfounder: 3<2x3<2 : 3<2 = 1    
9: nonfounder: 3<2x3<1 : 3<2 = 1    
9: nonfounder: 3<2x1<3 : 3<2 = 1    
9: nonfounder: 3<2x2<3 : 3<2 = 1    
9: nonfounder: 3<2x3<3 : 3<2 = 1    
9: nonfounder: 3<1x3<2 : 3<2 = 1    
9: nonfounder: 3<1x3<1 : 3<2 = 1    
9: nonfounder: 3<1x1<3 : 3<2 = 1    
9: nonfounder: 3<1x2<3 : 3<2 = 1    
9: nonfounder: 3<1x3<3 : 3<2 = 1    
9: nonfounder: 1<3x3<2 : 3<2 = 1    
9: nonfounder: 1<3x3<1 : 3<2 = 1    
9: nonfounder: 1<3x1<3 : 3<2 = 1    
9: nonfounder: 1<3x2<3 : 3<2 = 1    
9: nonfounder: 1<3x3<3 : 3<2 = 1    
9: nonfounder: 2<3x3<2 : 3<2 = 1    
9: nonfounder: 2<3x3<1 : 3<2 = 1    
9: nonfounder: 2<3x1<3 : 3<2 = 1    
9: nonfounder: 2<3x2<3 : 3<2 = 1    
9: nonfounder: 2<3x3<3 : 3<2 = 1    
9: nonfounder: 3<3x3<2 : 3<2 = 1    
9: nonfounder: 3<3x3<1 : 3<2 = 1    
9: nonfounder: 3<3x1<3 : 3<2 = 1    
9: nonfounder: 3<3x2<3 : 3<2 = 1    
9: nonfounder: 3<3x3<3 : 3<2 = 1    

9: nonfounder: 3<2x3<2 : 3<1 = 1    
9: nonfounder: 3<2x3<1 : 3<1 = 1    
9: nonfounder: 3<2x1<3 : 3<1 = 1    
9: nonfounder: 3<2x2<3 : 3<1 = 1    
9: nonfounder: 3<2x3<3 : 3<1 = 1    
9: nonfounder: 3<1x3<2 : 3<1 = 1    
9: nonfounder: 3<1x3<1 : 3<1 = 1    
9: nonfounder: 3<1x1<3 : 3<1 = 1    
9: nonfounder: 3<1x2<3 : 3<1 = 1    
9: nonfounder: 3<1x3<3 : 3<1 = 1    
9: nonfounder: 1<3x3<2 : 3<1 = 1    
9: nonfounder: 1<3x3<1 : 3<1 = 1    
9: nonfounder: 1<3x1<3 : 3<1 = 1    
9: nonfounder: 1<3x2<3 : 3<1 = 1    
9: nonfounder: 1<3x3<3 : 3<1 = 1    
9: nonfounder: 2<3x3<2 : 3<1 = 1    
9: nonfounder: 2<3x3<1 : 3<1 = 1    
9: nonfounder: 2<3x1<3 : 3<1 = 1    
9: nonfounder: 2<3x2<3 : 3<1 = 1    
9: nonfounder: 2<3x3<3 : 3<1 = 1    
9: nonfounder: 3<3x3<2 : 3<1 = 1    
9: nonfounder: 3<3x3<1 : 3<1 = 1    
9: nonfounder: 3<3x1<3 : 3<1 = 1    
9: nonfounder: 3<3x2<3 : 3<1 = 1    
9: nonfounder: 3<3x3<3 : 3<1 = 1    

9: nonfounder: 3<2x3<2 : 2<1 = 1    
9: nonfounder: 3<2x3<1 : 2<1 = 1    
9: nonfounder: 3<2x1<3 : 2<1 = 1    
9: nonfounder: 3<2x2<3 : 2<1 = 1    
9: nonfounder: 3<2x3<3 : 2<1 = 1    
9: nonfounder: 3<1x3<2 : 2<1 = 1    
9: nonfounder: 3<1x3<1 : 2<1 = 1    
9: nonfounder: 3<1x1<3 : 2<1 = 1    
9: nonfounder: 3<1x2<3 : 2<1 = 1    
9: nonfounder: 3<1x3<3 : 2<1 = 1    
9: nonfounder: 1<3x3<2 : 2<1 = 1    
9: nonfounder: 1<3x3<1 : 2<1 = 1    
9: nonfounder: 1<3x1<3 : 2<1 = 1    
9: nonfounder: 1<3x2<3 : 2<1 = 1    
9: nonfounder: 1<3x3<3 : 2<1 = 1    
9: nonfounder: 2<3x3<2 : 2<1 = 1    
9: nonfounder: 2<3x3<1 : 2<1 = 1    
9: nonfounder: 2<3x1<3 : 2<1 = 1    
9: nonfounder: 2<3x2<3 : 2<1 = 1    
9: nonfounder: 2<3x3<3 : 2<1 = 1    
9: nonfounder: 3<3x3<2 : 2<1 = 1    
9: nonfounder: 3<3x3<1 : 2<1 = 1    
9: nonfounder: 3<3x1<3 : 2<1 = 1    
9: nonfounder: 3<3x2<3 : 2<1 = 1    
9: nonfounder: 3<3x3<3 : 2<1 = 1    

9: nonfounder: 3<2x3<2 : 1<1 = 1    
9: nonfounder: 3<2x3<1 : 1<1 = 1    
9: nonfounder: 3<2x1<3 : 1<1 = 1    
9: nonfounder: 3<2x2<3 : 1<1 = 1    
9: nonfounder: 3<2x3<3 : 1<1 = 1    
9: nonfounder: 3<1x3<2 : 1<1 = 1    
9: nonfounder: 3<1x3<1 : 1<1 = 1    
9: nonfounder: 3<1x1<3 : 1<1 = 1    
9: nonfounder: 3<1x2<3 : 1<1 = 1    
9: nonfounder: 3<1x3<3 : 1<1 = 1    
9: nonfounder: 1<3x3<2 : 1<1 = 1    
9: nonfounder: 1<3x3<1 : 1<1 = 1    
9: nonfounder: 1<3x1<3 : 1<1 = 1    
9: nonfounder: 1<3x2<3 : 1<1 = 1    
9: nonfounder: 1<3x3<3 : 1<1 = 1    
9: nonfounder: 2<3x3<2 : 1<1 = 1    
9: nonfounder: 2<3x3<1 : 1<1 = 1    
9: nonfounder: 2<3x1<3 : 1<1 = 1    
9: nonfounder: 2<3x2<3 : 1<1 = 1    
9: nonfounder: 2<3x3<3 : 1<1 = 1    
9: nonfounder: 3<3x3<2 : 1<1 = 1    
9: nonfounder: 3<3x3<1 : 1<1 = 1    
9: nonfounder: 3<3x1<3 : 1<1 = 1    
9: nonfounder: 3<3x2<3 : 1<1 = 1    
9: nonfounder: 3<3x3<3 : 1<1 = 1    

9: nonfounder: 3<2x3<2 : 1<2 = 1    
9: nonfounder: 3<2x3<1 : 1<2 = 1    
9: nonfounder: 3<2x1<3 : 1<2 = 1    
9: nonfounder: 3<2x2<3 : 1<2 = 1    
9: nonfounder: 3<2x3<3 : 1<2 = 1    
9: nonfounder: 3<1x3<2 : 1<2 = 1    
9: nonfounder: 3<1x3<1 : 1<2 = 1    
9: nonfounder: 3<1x1<3 : 1<2 = 1    
9: nonfounder: 3<1x2<3 : 1<2 = 1    
9: nonfounder: 3<1x3<3 : 1<2 = 1    
9: nonfounder: 1<3x3<2 : 1<2 = 1    
9: nonfounder: 1<3x3<1 : 1<2 = 1    
9: nonfounder: 1<3x1<3 : 1<2 = 1    
9: nonfounder: 1<3x2<3 : 1<2 = 1    
9: nonfounder: 1<3x3<3 : 1<2 = 1    
9: nonfounder: 2<3x3<2 : 1<2 = 1    
9: nonfounder: 2<3x3<1 : 1<2 = 1    
9: nonfounder: 2<3x1<3 : 1<2 = 1    
9: nonfounder: 2<3x2<3 : 1<2 = 1    
9: nonfounder: 2<3x3<3 : 1<2 = 1    
9: nonfounder: 3<3x3<2 : 1<2 = 1    
9: nonfounder: 3<3x3<1 : 1<2 = 1    
9: nonfounder: 3<3x1<3 : 1<2 = 1    
9: nonfounder: 3<3x2<3 : 1<2 = 1    
9: nonfounder: 3<3x3<3 : 1<2 = 1    

9: nonfounder: 3<2x3<2 : 2<2 = 1    
9: nonfounder: 3<2x3<1 : 2<2 = 1    
9: nonfounder: 3<2x1<3 : 2<2 = 1    
9: nonfounder: 3<2x2<3 : 2<2 = 1    
9: nonfounder: 3<2x3<3 : 2<2 = 1    
9: nonfounder: 3<1x3<2 : 2<2 = 1    
9: nonfounder: 3<1x3<1 : 2<2 = 1    
9: nonfounder: 3<1x1<3 : 2<2 = 1    
9: nonfounder: 3<1x2<3 : 2<2 = 1    
9: nonfounder: 3<1x3<3 : 2<2 = 1    
9: nonfounder: 1<3x3<2 : 2<2 = 1    
9: nonfounder: 1<3x3<1 : 2<2 = 1    
9: nonfounder: 1<3x1<3 : 2<2 = 1    
9: nonfounder: 1<3x2<3 : 2<2 = 1    
9: nonfounder: 1<3x3<3 : 2<2 = 1    
9: nonfounder: 2<3x3<2 : 2<2 = 1    
9: nonfounder: 2<3x3<1 : 2<2 = 1    
9: nonfounder: 2<3x1<3 : 2<2 = 1    
9: nonfounder: 2<3x2<3 : 2<2 = 1    
9: nonfounder: 2<3x3<3 : 2<2 = 1    
9: nonfounder: 3<3x3<2 : 2<2 = 1    
9: nonfounder: 3<3x3<1 : 2<2 = 1    
9: nonfounder: 3<3x1<3 : 2<2 = 1    
9: nonfounder: 3<3x2<3 : 2<2 = 1    
9: nonfounder: 3<3x3<3 : 2<2 = 1    

9: nonfounder: 3<2x3<2 : 1<3 = 1    
9: nonfounder: 3<2x3<1 : 1<3 = 1    
9: nonfounder: 3<2x1<3 : 1<3 = 1    
9: nonfounder: 3<2x2<3 : 1<3 = 1    
9: nonfounder: 3<2x3<3 : 1<3 = 1    
9: nonfounder: 3<1x3<2 : 1<3 = 1    
9: nonfounder: 3<1x3<1 : 1<3 = 1    
9: nonfounder: 3<1x1<3 : 1<3 = 1    
9: nonfounder: 3<1x2<3 : 1<3 = 1    
9: nonfounder: 3<1x3<3 : 1<3 = 1    
9: nonfounder: 1<3x3<2 : 1<3 = 1    
9: nonfounder: 1<3x3<1 : 1<3 = 1    
9: nonfounder: 1<3x1<3 : 1<3 = 1    
9: nonfounder: 1<3x2<3 : 1<3 = 1    
9: nonfounder: 1<3x3<3 : 1<3 = 1    
9: nonfounder: 2<3x3<2 : 1<3 = 1    
9: nonfounder: 2<3x3<1 : 1<3 = 1    
9: nonfounder: 2<3x1<3 : 1<3 = 1    
9: nonfounder: 2<3x2<3 : 1<3 = 1    
9: nonfounder: 2<3x3<3 : 1<3 = 1    
9: nonfounder: 3<3x3<2 : 1<3 = 1    
9: nonfounder: 3<3x3<1 : 1<3 = 1    
9: nonfounder: 3<3x1<3 : 1<3 = 1    
9: nonfounder: 3<3x2<3 : 1<3 = 1    
9: nonfounder: 3<3x3<3 : 1<3 = 1    

9: nonfounder: 3<2x3<2 : 2<3 = 1    
9: nonfounder: 3<2x3<1 : 2<3 = 1    
9: nonfounder: 3<2x1<3 : 2<3 = 1    
9: nonfounder: 3<2x2<3 : 2<3 = 1    
9: nonfounder: 3<2x3<3 : 2<3 = 1    
9: nonfounder: 3<1x3<2 : 2<3 = 1    
9: nonfounder: 3<1x3<1 : 2<3 = 1    
9: nonfounder: 3<1x1<3 : 2<3 = 1    
9: nonfounder: 3<1x2<3 : 2<3 = 1    
9: nonfounder: 3<1x3<3 : 2<3 = 1    
9: nonfounder: 1<3x3<2 : 2<3 = 1    
9: nonfounder: 1<3x3<1 : 2<3 = 1    
9: nonfounder: 1<3x1<3 : 2<3 = 1    
9: nonfounder: 1<3x2<3 : 2<3 = 1    
9: nonfounder: 1<3x3<3 : 2<3 = 1    
9: nonfounder: 2<3x3<2 : 2<3 = 1    
9: nonfounder: 2<3x3<1 : 2<3 = 1    
9: nonfounder: 2<3x1<3 : 2<3 = 1    
9: nonfounder: 2<3x2<3 : 2<3 = 1    
9: nonfounder: 2<3x3<3 : 2<3 = 1    
9: nonfounder: 3<3x3<2 : 2<3 = 1    
9: nonfounder: 3<3x3<1 : 2<3 = 1    
9: nonfounder: 3<3x1<3 : 2<3 = 1    
9: nonfounder: 3<3x2<3 : 2<3 = 1    
9: nonfounder: 3<3x3<3 : 2<3 = 1    

9: nonfounder: 3<2x3<2 : 3<3 = 1    
9: nonfounder: 3<2x3<1 : 3<3 = 1    
9: nonfounder: 3<2x1<3 : 3<3 = 1    
9: nonfounder: 3<2x2<3 : 3<3 = 1    
9: nonfounder: 3<2x3<3 : 3<3 = 1    
9: nonfounder: 3<1x3<2 : 3<3 = 1    
9: nonfounder: 3<1x3<1 : 3<3 = 1    
9: nonfounder: 3<1x1<3 : 3<3 = 1    
9: nonfounder: 3<1x2<3 : 3<3 = 1    
9: nonfounder: 3<1x3<3 : 3<3 = 1    
9: nonfounder: 1<3x3<2 : 3<3 = 1    
9: nonfounder: 1<3x3<1 : 3<3 = 1    
9: nonfounder: 1<3x1<3 : 3<3 = 1    
9: nonfounder: 1<3x2<3 : 3<3 = 1    
9: nonfounder: 1<3x3<3 : 3<3 = 1    
9: nonfounder: 2<3x3<2 : 3<3 = 1    
9: nonfounder: 2<3x3<1 : 3<3 = 1    
9: nonfounder: 2<3x1<3 : 3<3 = 1    
9: nonfounder: 2<3x2<3 : 3<3 = 1    
9: nonfounder: 2<3x3<3 : 3<3 = 1    
9: nonfounder: 3<3x3<2 : 3<3 = 1    
9: nonfounder: 3<3x3<1 : 3<3 = 1    
9: nonfounder: 3<3x1<3 : 3<3 = 1    
9: nonfounder: 3<3x2<3 : 3<3 = 1    
9: nonfounder: 3<3x3<3 : 3<3 = 1    

Testing parental penetrance model: 

1: founder   : A<A = 0    A<B = 1    B<A = 1    B<B = 2    

10: nonfounder: A<AxA<A : A<A = 3    
10: nonfounder: A<AxA<B : A<A = 4    A<B = 5    
10: nonfounder: A<AxB<A : A<B = 5    A<A = 4    
10: nonfounder: A<AxB<B : A<B = 6    
10: nonfounder: A<BxA<A : A<A = 7    B<A = 8    
10: nonfounder: A<BxA<B : A<A = 9    A<B = 10    B<A = 10    B<B = 11    
10: nonfounder: A<BxB<A : A<B = 10    A<A = 9    B<B = 11    B<A = 10    
10: nonfounder: A<BxB<B : A<B = 12    B<B = 13    
10: nonfounder: B<AxA<A : B<A = 8    A<A = 7    
10: nonfounder: B<AxA<B : B<A = 10    B<B = 11    A<A = 9    A<B = 10    
10: nonfounder: B<AxB<A : B<B = 11    B<A = 10    A<B = 10    A<A = 9    
10: nonfounder: B<AxB<B : B<B = 13    A<B = 12    
10: nonfounder: B<BxA<A : B<A = 14    
10: nonfounder: B<BxA<B : B<A = 15    B<B = 16    
10: nonfounder: B<BxB<A : B<B = 16    B<A = 15    
10: nonfounder: B<BxB<B : B<B = 17    

10: nonfounder: A<AxA<A : A<A = 3    
10: nonfounder: A<AxA<B : A<A = 4    
10: nonfounder: A<AxB<A : A<A = 4    
10: nonfounder: A<AxB<B : A<A = NaNQ    
10: nonfounder: A<BxA<A : A<A = 7    
10: nonfounder: A<BxA<B : A<A = 9    
10: nonfounder: A<BxB<A : A<A = 9    
10: nonfounder: A<BxB<B : A<A = NaNQ    
10: nonfounder: B<AxA<A : A<A = 7    
10: nonfounder: B<AxA<B : A<A = 9    
10: nonfounder: B<AxB<A : A<A = 9    
10: nonfounder: B<AxB<B : A<A = NaNQ    
10: nonfounder: B<BxA<A : A<A = NaNQ    
10: nonfounder: B<BxA<B : A<A = NaNQ    
10: nonfounder: B<BxB<A : A<A = NaNQ    
10: nonfounder: B<BxB<B : A<A = NaNQ    

10: nonfounder: A<AxA<A : A<B = NaNQ    
10: nonfounder: A<AxA<B : A<B = 5    
10: nonfounder: A<AxB<A : A<B = 5    
10: nonfounder: A<AxB<B : A<B = 6    
10: nonfounder: A<BxA<A : A<B = 8    
10: nonfounder: A<BxA<B : A<B = 10    
10: nonfounder: A<BxB<A : A<B = 10    
10: nonfounder: A<BxB<B : A<B = 12    
10: nonfounder: B<AxA<A : A<B = 8    
10: nonfounder: B<AxA<B : A<B = 10    
10: nonfounder: B<AxB<A : A<B = 10    
10: nonfounder: B<AxB<B : A<B = 12    
10: nonfounder: B<BxA<A : A<B = 14    
10: nonfounder: B<BxA<B : A<B = 15    
10: nonfounder: B<BxB<A : A<B = 15    
10: nonfounder: B<BxB<B : A<B = NaNQ    

10: nonfounder: A<AxA<A : B<A = NaNQ    
10: nonfounder: A<AxA<B : B<A = 5    
10: nonfounder: A<AxB<A : B<A = 5    
10: nonfounder: A<AxB<B : B<A = 6    
10: nonfounder: A<BxA<A : B<A = 8    
10: nonfounder: A<BxA<B : B<A = 10    
10: nonfounder: A<BxB<A : B<A = 10    
10: nonfounder: A<BxB<B : B<A = 12    
10: nonfounder: B<AxA<A : B<A = 8    
10: nonfounder: B<AxA<B : B<A = 10    
10: nonfounder: B<AxB<A : B<A = 10    
10: nonfounder: B<AxB<B : B<A = 12    
10: nonfounder: B<BxA<A : B<A = 14    
10: nonfounder: B<BxA<B : B<A = 15    
10: nonfounder: B<BxB<A : B<A = 15    
10: nonfounder: B<BxB<B : B<A = NaNQ    

10: nonfounder: A<AxA<A : B<B = NaNQ    
10: nonfounder: A<AxA<B : B<B = NaNQ    
10: nonfounder: A<AxB<A : B<B = NaNQ    
10: nonfounder: A<AxB<B : B<B = NaNQ    
10: nonfounder: A<BxA<A : B<B = NaNQ    
10: nonfounder: A<BxA<B : B<B = 11    
10: nonfounder: A<BxB<A : B<B = 11    
10: nonfounder: A<BxB<B : B<B = 13    
10: nonfounder: B<AxA<A : B<B = NaNQ    
10: nonfounder: B<AxA<B : B<B = 11    
10: nonfounder: B<AxB<A : B<B = 11    
10: nonfounder: B<AxB<B : B<B = 13    
10: nonfounder: B<BxA<A : B<B = NaNQ    
10: nonfounder: B<BxA<B : B<B = 16    
10: nonfounder: B<BxB<A : B<B = 16    
10: nonfounder: B<BxB<B : B<B = 17    

11: nonfounder: A<AxA<A : A<A = 18    
11: nonfounder: A<AxA<B : A<A = 19    A<B = 20    
11: nonfounder: A<AxB<A : A<B = 20    A<A = 19    
11: nonfounder: A<AxB<B : A<B = 21    
11: nonfounder: A<BxA<A : A<A = 22    B<A = 23    
11: nonfounder: A<BxA<B : A<A = 24    A<B = 25    B<A = 25    B<B = 26    
11: nonfounder: A<BxB<A : A<B = 25    A<A = 24    B<B = 26    B<A = 25    
11: nonfounder: A<BxB<B : A<B = 27    B<B = 28    
11: nonfounder: B<AxA<A : B<A = 23    A<A = 22    
11: nonfounder: B<AxA<B : B<A = 25    B<B = 26    A<A = 24    A<B = 25    
11: nonfounder: B<AxB<A : B<B = 26    B<A = 25    A<B = 25    A<A = 24    
11: nonfounder: B<AxB<B : B<B = 28    A<B = 27    
11: nonfounder: B<BxA<A : B<A = 29    
11: nonfounder: B<BxA<B : B<A = 30    B<B = 31    
11: nonfounder: B<BxB<A : B<B = 31    B<A = 30    
11: nonfounder: B<BxB<B : B<B = 32    

11: nonfounder: A<AxA<A : A<A = 18    
11: nonfounder: A<AxA<B : A<A = 19    
11: nonfounder: A<AxB<A : A<A = 19    
11: nonfounder: A<AxB<B : A<A = NaNQ    
11: nonfounder: A<BxA<A : A<A = 22    
11: nonfounder: A<BxA<B : A<A = 24    
11: nonfounder: A<BxB<A : A<A = 24    
11: nonfounder: A<BxB<B : A<A = NaNQ    
11: nonfounder: B<AxA<A : A<A = 22    
11: nonfounder: B<AxA<B : A<A = 24    
11: nonfounder: B<AxB<A : A<A = 24    
11: nonfounder: B<AxB<B : A<A = NaNQ    
11: nonfounder: B<BxA<A : A<A = NaNQ    
11: nonfounder: B<BxA<B : A<A = NaNQ    
11: nonfounder: B<BxB<A : A<A = NaNQ    
11: nonfounder: B<BxB<B : A<A = NaNQ    

11: nonfounder: A<AxA<A : A<B = NaNQ    
11: nonfounder: A<AxA<B : A<B = 20    
11: nonfounder: A<AxB<A : A<B = 20    
11: nonfounder: A<AxB<B : A<B = 21    
11: nonfounder: A<BxA<A : A<B = 23    
11: nonfounder: A<BxA<B : A<B = 25    
11: nonfounder: A<BxB<A : A<B = 25    
11: nonfounder: A<BxB<B : A<B = 27    
11: nonfounder: B<AxA<A : A<B = 23    
11: nonfounder: B<AxA<B : A<B = 25    
11: nonfounder: B<AxB<A : A<B = 25    
11: nonfounder: B<AxB<B : A<B = 27    
11: nonfounder: B<BxA<A : A<B = 29    
11: nonfounder: B<BxA<B : A<B = 30    
11: nonfounder: B<BxB<A : A<B = 30    
11: nonfounder: B<BxB<B : A<B = NaNQ    

11: nonfounder: A<AxA<A : B<A = NaNQ    
11: nonfounder: A<AxA<B : B<A = 20    
11: nonfounder: A<AxB<A : B<A = 20    
11: nonfounder: A<AxB<B : B<A = 21    
11: nonfounder: A<BxA<A : B<A = 23    
11: nonfounder: A<BxA<B : B<A = 25    
11: nonfounder: A<BxB<A : B<A = 25    
11: nonfounder: A<BxB<B : B<A = 27    
11: nonfounder: B<AxA<A : B<A = 23    
11: nonfounder: B<AxA<B : B<A = 25    
11: nonfounder: B<AxB<A : B<A = 25    
11: nonfounder: B<AxB<B : B<A = 27    
11: nonfounder: B<BxA<A : B<A = 29    
11: nonfounder: B<BxA<B : B<A = 30    
11: nonfounder: B<BxB<A : B<A = 30    
11: nonfounder: B<BxB<B : B<A = NaNQ    

11: nonfounder: A<AxA<A : B<B = NaNQ    
11: nonfounder: A<AxA<B : B<B = NaNQ    
11: nonfounder: A<AxB<A : B<B = NaNQ    
11: nonfounder: A<AxB<B : B<B = NaNQ    
11: nonfounder: A<BxA<A : B<B = NaNQ    
11: nonfounder: A<BxA<B : B<B = 26    
11: nonfounder: A<BxB<A : B<B = 26    
11: nonfounder: A<BxB<B : B<B = 28    
11: nonfounder: B<AxA<A : B<B = NaNQ    
11: nonfounder: B<AxA<B : B<B = 26    
11: nonfounder: B<AxB<A : B<B = 26    
11: nonfounder: B<AxB<B : B<B = 28    
11: nonfounder: B<BxA<A : B<B = NaNQ    
11: nonfounder: B<BxA<B : B<B = 31    
11: nonfounder: B<BxB<A : B<B = 31    
11: nonfounder: B<BxB<B : B<B = 32    

12: nonfounder: A<AxA<A : A<A = 33    
12: nonfounder: A<AxA<B : A<A = 34    A<B = 35    
12: nonfounder: A<AxB<A : A<B = 35    A<A = 34    
12: nonfounder: A<AxB<B : A<B = 36    
12: nonfounder: A<BxA<A : A<A = 37    B<A = 38    
12: nonfounder: A<BxA<B : A<A = 39    A<B = 40    B<A = 40    B<B = 41    
12: nonfounder: A<BxB<A : A<B = 40    A<A = 39    B<B = 41    B<A = 40    
12: nonfounder: A<BxB<B : A<B = 42    B<B = 43    
12: nonfounder: B<AxA<A : B<A = 38    A<A = 37    
12: nonfounder: B<AxA<B : B<A = 40    B<B = 41    A<A = 39    A<B = 40    
12: nonfounder: B<AxB<A : B<B = 41    B<A = 40    A<B = 40    A<A = 39    
12: nonfounder: B<AxB<B : B<B = 43    A<B = 42    
12: nonfounder: B<BxA<A : B<A = 44    
12: nonfounder: B<BxA<B : B<A = 45    B<B = 46    
12: nonfounder: B<BxB<A : B<B = 46    B<A = 45    
12: nonfounder: B<BxB<B : B<B = 47    

12: nonfounder: A<AxA<A : A<A = 33    
12: nonfounder: A<AxA<B : A<A = 34    
12: nonfounder: A<AxB<A : A<A = 34    
12: nonfounder: A<AxB<B : A<A = NaNQ    
12: nonfounder: A<BxA<A : A<A = 37    
12: nonfounder: A<BxA<B : A<A = 39    
12: nonfounder: A<BxB<A : A<A = 39    
12: nonfounder: A<BxB<B : A<A = NaNQ    
12: nonfounder: B<AxA<A : A<A = 37    
12: nonfounder: B<AxA<B : A<A = 39    
12: nonfounder: B<AxB<A : A<A = 39    
12: nonfounder: B<AxB<B : A<A = NaNQ    
12: nonfounder: B<BxA<A : A<A = NaNQ    
12: nonfounder: B<BxA<B : A<A = NaNQ    
12: nonfounder: B<BxB<A : A<A = NaNQ    
12: nonfounder: B<BxB<B : A<A = NaNQ    

12: nonfounder: A<AxA<A : A<B = NaNQ    
12: nonfounder: A<AxA<B : A<B = 35    
12: nonfounder: A<AxB<A : A<B = 35    
12: nonfounder: A<AxB<B : A<B = 36    
12: nonfounder: A<BxA<A : A<B = 38    
12: nonfounder: A<BxA<B : A<B = 40    
12: nonfounder: A<BxB<A : A<B = 40    
12: nonfounder: A<BxB<B : A<B = 42    
12: nonfounder: B<AxA<A : A<B = 38    
12: nonfounder: B<AxA<B : A<B = 40    
12: nonfounder: B<AxB<A : A<B = 40    
12: nonfounder: B<AxB<B : A<B = 42    
12: nonfounder: B<BxA<A : A<B = 44    
12: nonfounder: B<BxA<B : A<B = 45    
12: nonfounder: B<BxB<A : A<B = 45    
12: nonfounder: B<BxB<B : A<B = NaNQ    

12: nonfounder: A<AxA<A : B<A = NaNQ    
12: nonfounder: A<AxA<B : B<A = 35    
12: nonfounder: A<AxB<A : B<A = 35    
12: nonfounder: A<AxB<B : B<A = 36    
12: nonfounder: A<BxA<A : B<A = 38    
12: nonfounder: A<BxA<B : B<A = 40    
12: nonfounder: A<BxB<A : B<A = 40    
12: nonfounder: A<BxB<B : B<A = 42    
12: nonfounder: B<AxA<A : B<A = 38    
12: nonfounder: B<AxA<B : B<A = 40    
12: nonfounder: B<AxB<A : B<A = 40    
12: nonfounder: B<AxB<B : B<A = 42    
12: nonfounder: B<BxA<A : B<A = 44    
12: nonfounder: B<BxA<B : B<A = 45    
12: nonfounder: B<BxB<A : B<A = 45    
12: nonfounder: B<BxB<B : B<A = NaNQ    

12: nonfounder: A<AxA<A : B<B = NaNQ    
12: nonfounder: A<AxA<B : B<B = NaNQ    
12: nonfounder: A<AxB<A : B<B = NaNQ    
12: nonfounder: A<AxB<B : B<B = NaNQ    
12: nonfounder: A<BxA<A : B<B = NaNQ    
12: nonfounder: A<BxA<B : B<B = 41    
12: nonfounder: A<BxB<A : B<B = 41    
12: nonfounder: A<BxB<B : B<B = 43    
12: nonfounder: B<AxA<A : B<B = NaNQ    
12: nonfounder: B<AxA<B : B<B = 41    
12: nonfounder: B<AxB<A : B<B = 41    
12: nonfounder: B<AxB<B : B<B = 43    
12: nonfounder: B<BxA<A : B<B = NaNQ    
12: nonfounder: B<BxA<B : B<B = 46    
12: nonfounder: B<BxB<A : B<B = 46    
12: nonfounder: B<BxB<B : B<B = 47    

13: nonfounder: A<AxA<A : A<A = 48    
13: nonfounder: A<AxA<B : A<A = 49    A<B = 50    
13: nonfounder: A<AxB<A : A<B = 50    A<A = 49    
13: nonfounder: A<AxB<B : A<B = 51    
13: nonfounder: A<BxA<A : A<A = 52    B<A = 53    
13: nonfounder: A<BxA<B : A<A = 54    A<B = 55    B<A = 55    B<B = 56    
13: nonfounder: A<BxB<A : A<B = 55    A<A = 54    B<B = 56    B<A = 55    
13: nonfounder: A<BxB<B : A<B = 57    B<B = 58    
13: nonfounder: B<AxA<A : B<A = 53    A<A = 52    
13: nonfounder: B<AxA<B : B<A = 55    B<B = 56    A<A = 54    A<B = 55    
13: nonfounder: B<AxB<A : B<B = 56    B<A = 55    A<B = 55    A<A = 54    
13: nonfounder: B<AxB<B : B<B = 58    A<B = 57    
13: nonfounder: B<BxA<A : B<A = 59    
13: nonfounder: B<BxA<B : B<A = 60    B<B = 61    
13: nonfounder: B<BxB<A : B<B = 61    B<A = 60    
13: nonfounder: B<BxB<B : B<B = 62    

13: nonfounder: A<AxA<A : A<A = 48    
13: nonfounder: A<AxA<B : A<A = 49    
13: nonfounder: A<AxB<A : A<A = 49    
13: nonfounder: A<AxB<B : A<A = NaNQ    
13: nonfounder: A<BxA<A : A<A = 52    
13: nonfounder: A<BxA<B : A<A = 54    
13: nonfounder: A<BxB<A : A<A = 54    
13: nonfounder: A<BxB<B : A<A = NaNQ    
13: nonfounder: B<AxA<A : A<A = 52    
13: nonfounder: B<AxA<B : A<A = 54    
13: nonfounder: B<AxB<A : A<A = 54    
13: nonfounder: B<AxB<B : A<A = NaNQ    
13: nonfounder: B<BxA<A : A<A = NaNQ    
13: nonfounder: B<BxA<B : A<A = NaNQ    
13: nonfounder: B<BxB<A : A<A = NaNQ    
13: nonfounder: B<BxB<B : A<A = NaNQ    

13: nonfounder: A<AxA<A : A<B = NaNQ    
13: nonfounder: A<AxA<B : A<B = 50    
13: nonfounder: A<AxB<A : A<B = 50    
13: nonfounder: A<AxB<B : A<B = 51    
13: nonfounder: A<BxA<A : A<B = 53    
13: nonfounder: A<BxA<B : A<B = 55    
13: nonfounder: A<BxB<A : A<B = 55    
13: nonfounder: A<BxB<B : A<B = 57    
13: nonfounder: B<AxA<A : A<B = 53    
13: nonfounder: B<AxA<B : A<B = 55    
13: nonfounder: B<AxB<A : A<B = 55    
13: nonfounder: B<AxB<B : A<B = 57    
13: nonfounder: B<BxA<A : A<B = 59    
13: nonfounder: B<BxA<B : A<B = 60    
13: nonfounder: B<BxB<A : A<B = 60    
13: nonfounder: B<BxB<B : A<B = NaNQ    

13: nonfounder: A<AxA<A : B<A = NaNQ    
13: nonfounder: A<AxA<B : B<A = 50    
13: nonfounder: A<AxB<A : B<A = 50    
13: nonfounder: A<AxB<B : B<A = 51    
13: nonfounder: A<BxA<A : B<A = 53    
13: nonfounder: A<BxA<B : B<A = 55    
13: nonfounder: A<BxB<A : B<A = 55    
13: nonfounder: A<BxB<B : B<A = 57    
13: nonfounder: B<AxA<A : B<A = 53    
13: nonfounder: B<AxA<B : B<A = 55    
13: nonfounder: B<AxB<A : B<A = 55    
13: nonfounder: B<AxB<B : B<A = 57    
13: nonfounder: B<BxA<A : B<A = 59    
13: nonfounder: B<BxA<B : B<A = 60    
13: nonfounder: B<BxB<A : B<A = 60    
13: nonfounder: B<BxB<B : B<A = NaNQ    

13: nonfounder: A<AxA<A : B<B = NaNQ    
13: nonfounder: A<AxA<B : B<B = NaNQ    
13: nonfounder: A<AxB<A : B<B = NaNQ    
13: nonfounder: A<AxB<B : B<B = NaNQ    
13: nonfounder: A<BxA<A : B<B = NaNQ    
13: nonfounder: A<BxA<B : B<B = 56    
13: nonfounder: A<BxB<A : B<B = 56    
13: nonfounder: A<BxB<B : B<B = 58    
13: nonfounder: B<AxA<A : B<B = NaNQ    
13: nonfounder: B<AxA<B : B<B = 56    
13: nonfounder: B<AxB<A : B<B = 56    
13: nonfounder: B<AxB<B : B<B = 58    
13: nonfounder: B<BxA<A : B<B = NaNQ    
13: nonfounder: B<BxA<B : B<B = 61    
13: nonfounder: B<BxB<A : B<B = 61    
13: nonfounder: B<BxB<B : B<B = 62    

14: founder   : A<A = 63    A<B = 64    B<A = 64    B<B = 65    

15: nonfounder: A<AxA<A : A<A = 66    
15: nonfounder: A<AxA<B : A<A = 67    A<B = 68    
15: nonfounder: A<AxB<A : A<B = 68    A<A = 67    
15: nonfounder: A<AxB<B : A<B = 69    
15: nonfounder: A<BxA<A : A<A = 70    B<A = 71    
15: nonfounder: A<BxA<B : A<A = 72    A<B = 73    B<A = 73    B<B = 74    
15: nonfounder: A<BxB<A : A<B = 73    A<A = 72    B<B = 74    B<A = 73    
15: nonfounder: A<BxB<B : A<B = 75    B<B = 76    
15: nonfounder: B<AxA<A : B<A = 71    A<A = 70    
15: nonfounder: B<AxA<B : B<A = 73    B<B = 74    A<A = 72    A<B = 73    
15: nonfounder: B<AxB<A : B<B = 74    B<A = 73    A<B = 73    A<A = 72    
15: nonfounder: B<AxB<B : B<B = 76    A<B = 75    
15: nonfounder: B<BxA<A : B<A = 77    
15: nonfounder: B<BxA<B : B<A = 78    B<B = 79    
15: nonfounder: B<BxB<A : B<B = 79    B<A = 78    
15: nonfounder: B<BxB<B : B<B = 80    

15: nonfounder: A<AxA<A : A<A = 66    
15: nonfounder: A<AxA<B : A<A = 67    
15: nonfounder: A<AxB<A : A<A = 67    
15: nonfounder: A<AxB<B : A<A = NaNQ    
15: nonfounder: A<BxA<A : A<A = 70    
15: nonfounder: A<BxA<B : A<A = 72    
15: nonfounder: A<BxB<A : A<A = 72    
15: nonfounder: A<BxB<B : A<A = NaNQ    
15: nonfounder: B<AxA<A : A<A = 70    
15: nonfounder: B<AxA<B : A<A = 72    
15: nonfounder: B<AxB<A : A<A = 72    
15: nonfounder: B<AxB<B : A<A = NaNQ    
15: nonfounder: B<BxA<A : A<A = NaNQ    
15: nonfounder: B<BxA<B : A<A = NaNQ    
15: nonfounder: B<BxB<A : A<A = NaNQ    
15: nonfounder: B<BxB<B : A<A = NaNQ    

15: nonfounder: A<AxA<A : A<B = NaNQ    
15: nonfounder: A<AxA<B : A<B = 68    
15: nonfounder: A<AxB<A : A<B = 68    
15: nonfounder: A<AxB<B : A<B = 69    
15: nonfounder: A<BxA<A : A<B = 71    
15: nonfounder: A<BxA<B : A<B = 73    
15: nonfounder: A<BxB<A : A<B = 73    
15: nonfounder: A<BxB<B : A<B = 75    
15: nonfounder: B<AxA<A : A<B = 71    
15: nonfounder: B<AxA<B : A<B = 73    
15: nonfounder: B<AxB<A : A<B = 73    
15: nonfounder: B<AxB<B : A<B = 75    
15: nonfounder: B<BxA<A : A<B = 77    
15: nonfounder: B<BxA<B : A<B = 78    
15: nonfounder: B<BxB<A : A<B = 78    
15: nonfounder: B<BxB<B : A<B = NaNQ    

15: nonfounder: A<AxA<A : B<A = NaNQ    
15: nonfounder: A<AxA<B : B<A = 68    
15: nonfounder: A<AxB<A : B<A = 68    
15: nonfounder: A<AxB<B : B<A = 69    
15: nonfounder: A<BxA<A : B<A = 71    
15: nonfounder: A<BxA<B : B<A = 73    
15: nonfounder: A<BxB<A : B<A = 73    
15: nonfounder: A<BxB<B : B<A = 75    
15: nonfounder: B<AxA<A : B<A = 71    
15: nonfounder: B<AxA<B : B<A = 73    
15: nonfounder: B<AxB<A : B<A = 73    
15: nonfounder: B<AxB<B : B<A = 75    
15: nonfounder: B<BxA<A : B<A = 77    
15: nonfounder: B<BxA<B : B<A = 78    
15: nonfounder: B<BxB<A : B<A = 78    
15: nonfounder: B<BxB<B : B<A = NaNQ    

15: nonfounder: A<AxA<A : B<B = NaNQ    
15: nonfounder: A<AxA<B : B<B = NaNQ    
15: nonfounder: A<AxB<A : B<B = NaNQ    
15: nonfounder: A<AxB<B : B<B = NaNQ    
15: nonfounder: A<BxA<A : B<B = NaNQ    
15: nonfounder: A<BxA<B : B<B = 74    
15: nonfounder: A<BxB<A : B<B = 74    
15: nonfounder: A<BxB<B : B<B = 76    
15: nonfounder: B<AxA<A : B<B = NaNQ    
15: nonfounder: B<AxA<B : B<B = 74    
15: nonfounder: B<AxB<A : B<B = 74    
15: nonfounder: B<AxB<B : B<B = 76    
15: nonfounder: B<BxA<A : B<B = NaNQ    
15: nonfounder: B<BxA<B : B<B = 79    
15: nonfounder: B<BxB<A : B<B = 79    
15: nonfounder: B<BxB<B : B<B = 80    

16: nonfounder: A<AxA<A : A<A = 81    
16: nonfounder: A<AxA<B : A<A = 82    A<B = 83    
16: nonfounder: A<AxB<A : A<B = 83    A<A = 82    
16: nonfounder: A<AxB<B : A<B = 84    
16: nonfounder: A<BxA<A : A<A = 85    B<A = 86    
16: nonfounder: A<BxA<B : A<A = 87    A<B = 88    B<A = 88    B<B = 89    
16: nonfounder: A<BxB<A : A<B = 88    A<A = 87    B<B = 89    B<A = 88    
16: nonfounder: A<BxB<B : A<B = 90    B<B = 91    
16: nonfounder: B<AxA<A : B<A = 86    A<A = 85    
16: nonfounder: B<AxA<B : B<A = 88    B<B = 89    A<A = 87    A<B = 88    
16: nonfounder: B<AxB<A : B<B = 89    B<A = 88    A<B = 88    A<A = 87    
16: nonfounder: B<AxB<B : B<B = 91    A<B = 90    
16: nonfounder: B<BxA<A : B<A = 92    
16: nonfounder: B<BxA<B : B<A = 93    B<B = 94    
16: nonfounder: B<BxB<A : B<B = 94    B<A = 93    
16: nonfounder: B<BxB<B : B<B = 95    

16: nonfounder: A<AxA<A : A<A = 81    
16: nonfounder: A<AxA<B : A<A = 82    
16: nonfounder: A<AxB<A : A<A = 82    
16: nonfounder: A<AxB<B : A<A = NaNQ    
16: nonfounder: A<BxA<A : A<A = 85    
16: nonfounder: A<BxA<B : A<A = 87    
16: nonfounder: A<BxB<A : A<A = 87    
16: nonfounder: A<BxB<B : A<A = NaNQ    
16: nonfounder: B<AxA<A : A<A = 85    
16: nonfounder: B<AxA<B : A<A = 87    
16: nonfounder: B<AxB<A : A<A = 87    
16: nonfounder: B<AxB<B : A<A = NaNQ    
16: nonfounder: B<BxA<A : A<A = NaNQ    
16: nonfounder: B<BxA<B : A<A = NaNQ    
16: nonfounder: B<BxB<A : A<A = NaNQ    
16: nonfounder: B<BxB<B : A<A = NaNQ    

16: nonfounder: A<AxA<A : A<B = NaNQ    
16: nonfounder: A<AxA<B : A<B = 83    
16: nonfounder: A<AxB<A : A<B = 83    
16: nonfounder: A<AxB<B : A<B = 84    
16: nonfounder: A<BxA<A : A<B = 86    
16: nonfounder: A<BxA<B : A<B = 88    
16: nonfounder: A<BxB<A : A<B = 88    
16: nonfounder: A<BxB<B : A<B = 90    
16: nonfounder: B<AxA<A : A<B = 86    
16: nonfounder: B<AxA<B : A<B = 88    
16: nonfounder: B<AxB<A : A<B = 88    
16: nonfounder: B<AxB<B : A<B = 90    
16: nonfounder: B<BxA<A : A<B = 92    
16: nonfounder: B<BxA<B : A<B = 93    
16: nonfounder: B<BxB<A : A<B = 93    
16: nonfounder: B<BxB<B : A<B = NaNQ    

16: nonfounder: A<AxA<A : B<A = NaNQ    
16: nonfounder: A<AxA<B : B<A = 83    
16: nonfounder: A<AxB<A : B<A = 83    
16: nonfounder: A<AxB<B : B<A = 84    
16: nonfounder: A<BxA<A : B<A = 86    
16: nonfounder: A<BxA<B : B<A = 88    
16: nonfounder: A<BxB<A : B<A = 88    
16: nonfounder: A<BxB<B : B<A = 90    
16: nonfounder: B<AxA<A : B<A = 86    
16: nonfounder: B<AxA<B : B<A = 88    
16: nonfounder: B<AxB<A : B<A = 88    
16: nonfounder: B<AxB<B : B<A = 90    
16: nonfounder: B<BxA<A : B<A = 92    
16: nonfounder: B<BxA<B : B<A = 93    
16: nonfounder: B<BxB<A : B<A = 93    
16: nonfounder: B<BxB<B : B<A = NaNQ    

16: nonfounder: A<AxA<A : B<B = NaNQ    
16: nonfounder: A<AxA<B : B<B = NaNQ    
16: nonfounder: A<AxB<A : B<B = NaNQ    
16: nonfounder: A<AxB<B : B<B = NaNQ    
16: nonfounder: A<BxA<A : B<B = NaNQ    
16: nonfounder: A<BxA<B : B<B = 89    
16: nonfounder: A<BxB<A : B<B = 89    
16: nonfounder: A<BxB<B : B<B = 91    
16: nonfounder: B<AxA<A : B<B = NaNQ    
16: nonfounder: B<AxA<B : B<B = 89    
16: nonfounder: B<AxB<A : B<B = 89    
16: nonfounder: B<AxB<B : B<B = 91    
16: nonfounder: B<BxA<A : B<B = NaNQ    
16: nonfounder: B<BxA<B : B<B = 94    
16: nonfounder: B<BxB<A : B<B = 94    
16: nonfounder: B<BxB<B : B<B = 95    

2: founder   : A<A = 96    A<B = 97    B<A = 97    B<B = 98    

3: nonfounder: A<AxA<A : A<A = 99    
3: nonfounder: A<AxA<B : A<A = 100    A<B = 101    
3: nonfounder: A<AxB<A : A<B = 101    A<A = 100    
3: nonfounder: A<AxB<B : A<B = 102    
3: nonfounder: A<BxA<A : A<A = 103    B<A = 104    
3: nonfounder: A<BxA<B : A<A = 105    A<B = 106    B<A = 106    B<B = 107    
3: nonfounder: A<BxB<A : A<B = 106    A<A = 105    B<B = 107    B<A = 106    
3: nonfounder: A<BxB<B : A<B = 108    B<B = 109    
3: nonfounder: B<AxA<A : B<A = 104    A<A = 103    
3: nonfounder: B<AxA<B : B<A = 106    B<B = 107    A<A = 105    A<B = 106    
3: nonfounder: B<AxB<A : B<B = 107    B<A = 106    A<B = 106    A<A = 105    
3: nonfounder: B<AxB<B : B<B = 109    A<B = 108    
3: nonfounder: B<BxA<A : B<A = 110    
3: nonfounder: B<BxA<B : B<A = 111    B<B = 112    
3: nonfounder: B<BxB<A : B<B = 112    B<A = 111    
3: nonfounder: B<BxB<B : B<B = 113    

3: nonfounder: A<AxA<A : A<A = 99    
3: nonfounder: A<AxA<B : A<A = 100    
3: nonfounder: A<AxB<A : A<A = 100    
3: nonfounder: A<AxB<B : A<A = NaNQ    
3: nonfounder: A<BxA<A : A<A = 103    
3: nonfounder: A<BxA<B : A<A = 105    
3: nonfounder: A<BxB<A : A<A = 105    
3: nonfounder: A<BxB<B : A<A = NaNQ    
3: nonfounder: B<AxA<A : A<A = 103    
3: nonfounder: B<AxA<B : A<A = 105    
3: nonfounder: B<AxB<A : A<A = 105    
3: nonfounder: B<AxB<B : A<A = NaNQ    
3: nonfounder: B<BxA<A : A<A = NaNQ    
3: nonfounder: B<BxA<B : A<A = NaNQ    
3: nonfounder: B<BxB<A : A<A = NaNQ    
3: nonfounder: B<BxB<B : A<A = NaNQ    

3: nonfounder: A<AxA<A : A<B = NaNQ    
3: nonfounder: A<AxA<B : A<B = 101    
3: nonfounder: A<AxB<A : A<B = 101    
3: nonfounder: A<AxB<B : A<B = 102    
3: nonfounder: A<BxA<A : A<B = 104    
3: nonfounder: A<BxA<B : A<B = 106    
3: nonfounder: A<BxB<A : A<B = 106    
3: nonfounder: A<BxB<B : A<B = 108    
3: nonfounder: B<AxA<A : A<B = 104    
3: nonfounder: B<AxA<B : A<B = 106    
3: nonfounder: B<AxB<A : A<B = 106    
3: nonfounder: B<AxB<B : A<B = 108    
3: nonfounder: B<BxA<A : A<B = 110    
3: nonfounder: B<BxA<B : A<B = 111    
3: nonfounder: B<BxB<A : A<B = 111    
3: nonfounder: B<BxB<B : A<B = NaNQ    

3: nonfounder: A<AxA<A : B<A = NaNQ    
3: nonfounder: A<AxA<B : B<A = 101    
3: nonfounder: A<AxB<A : B<A = 101    
3: nonfounder: A<AxB<B : B<A = 102    
3: nonfounder: A<BxA<A : B<A = 104    
3: nonfounder: A<BxA<B : B<A = 106    
3: nonfounder: A<BxB<A : B<A = 106    
3: nonfounder: A<BxB<B : B<A = 108    
3: nonfounder: B<AxA<A : B<A = 104    
3: nonfounder: B<AxA<B : B<A = 106    
3: nonfounder: B<AxB<A : B<A = 106    
3: nonfounder: B<AxB<B : B<A = 108    
3: nonfounder: B<BxA<A : B<A = 110    
3: nonfounder: B<BxA<B : B<A = 111    
3: nonfounder: B<BxB<A : B<A = 111    
3: nonfounder: B<BxB<B : B<A = NaNQ    

3: nonfounder: A<AxA<A : B<B = NaNQ    
3: nonfounder: A<AxA<B : B<B = NaNQ    
3: nonfounder: A<AxB<A : B<B = NaNQ    
3: nonfounder: A<AxB<B : B<B = NaNQ    
3: nonfounder: A<BxA<A : B<B = NaNQ    
3: nonfounder: A<BxA<B : B<B = 107    
3: nonfounder: A<BxB<A : B<B = 107    
3: nonfounder: A<BxB<B : B<B = 109    
3: nonfounder: B<AxA<A : B<B = NaNQ    
3: nonfounder: B<AxA<B : B<B = 107    
3: nonfounder: B<AxB<A : B<B = 107    
3: nonfounder: B<AxB<B : B<B = 109    
3: nonfounder: B<BxA<A : B<B = NaNQ    
3: nonfounder: B<BxA<B : B<B = 112    
3: nonfounder: B<BxB<A : B<B = 112    
3: nonfounder: B<BxB<B : B<B = 113    

4: nonfounder: A<AxA<A : A<A = 114    
4: nonfounder: A<AxA<B : A<A = 115    A<B = 116    
4: nonfounder: A<AxB<A : A<B = 116    A<A = 115    
4: nonfounder: A<AxB<B : A<B = 117    
4: nonfounder: A<BxA<A : A<A = 118    B<A = 119    
4: nonfounder: A<BxA<B : A<A = 120    A<B = 121    B<A = 121    B<B = 122    
4: nonfounder: A<BxB<A : A<B = 121    A<A = 120    B<B = 122    B<A = 121    
4: nonfounder: A<BxB<B : A<B = 123    B<B = 124    
4: nonfounder: B<AxA<A : B<A = 119    A<A = 118    
4: nonfounder: B<AxA<B : B<A = 121    B<B = 122    A<A = 120    A<B = 121    
4: nonfounder: B<AxB<A : B<B = 122    B<A = 121    A<B = 121    A<A = 120    
4: nonfounder: B<AxB<B : B<B = 124    A<B = 123    
4: nonfounder: B<BxA<A : B<A = 125    
4: nonfounder: B<BxA<B : B<A = 126    B<B = 127    
4: nonfounder: B<BxB<A : B<B = 127    B<A = 126    
4: nonfounder: B<BxB<B : B<B = 128    

4: nonfounder: A<AxA<A : A<A = 114    
4: nonfounder: A<AxA<B : A<A = 115    
4: nonfounder: A<AxB<A : A<A = 115    
4: nonfounder: A<AxB<B : A<A = NaNQ    
4: nonfounder: A<BxA<A : A<A = 118    
4: nonfounder: A<BxA<B : A<A = 120    
4: nonfounder: A<BxB<A : A<A = 120    
4: nonfounder: A<BxB<B : A<A = NaNQ    
4: nonfounder: B<AxA<A : A<A = 118    
4: nonfounder: B<AxA<B : A<A = 120    
4: nonfounder: B<AxB<A : A<A = 120    
4: nonfounder: B<AxB<B : A<A = NaNQ    
4: nonfounder: B<BxA<A : A<A = NaNQ    
4: nonfounder: B<BxA<B : A<A = NaNQ    
4: nonfounder: B<BxB<A : A<A = NaNQ    
4: nonfounder: B<BxB<B : A<A = NaNQ    

4: nonfounder: A<AxA<A : A<B = NaNQ    
4: nonfounder: A<AxA<B : A<B = 116    
4: nonfounder: A<AxB<A : A<B = 116    
4: nonfounder: A<AxB<B : A<B = 117    
4: nonfounder: A<BxA<A : A<B = 119    
4: nonfounder: A<BxA<B : A<B = 121    
4: nonfounder: A<BxB<A : A<B = 121    
4: nonfounder: A<BxB<B : A<B = 123    
4: nonfounder: B<AxA<A : A<B = 119    
4: nonfounder: B<AxA<B : A<B = 121    
4: nonfounder: B<AxB<A : A<B = 121    
4: nonfounder: B<AxB<B : A<B = 123    
4: nonfounder: B<BxA<A : A<B = 125    
4: nonfounder: B<BxA<B : A<B = 126    
4: nonfounder: B<BxB<A : A<B = 126    
4: nonfounder: B<BxB<B : A<B = NaNQ    

4: nonfounder: A<AxA<A : B<A = NaNQ    
4: nonfounder: A<AxA<B : B<A = 116    
4: nonfounder: A<AxB<A : B<A = 116    
4: nonfounder: A<AxB<B : B<A = 117    
4: nonfounder: A<BxA<A : B<A = 119    
4: nonfounder: A<BxA<B : B<A = 121    
4: nonfounder: A<BxB<A : B<A = 121    
4: nonfounder: A<BxB<B : B<A = 123    
4: nonfounder: B<AxA<A : B<A = 119    
4: nonfounder: B<AxA<B : B<A = 121    
4: nonfounder: B<AxB<A : B<A = 121    
4: nonfounder: B<AxB<B : B<A = 123    
4: nonfounder: B<BxA<A : B<A = 125    
4: nonfounder: B<BxA<B : B<A = 126    
4: nonfounder: B<BxB<A : B<A = 126    
4: nonfounder: B<BxB<B : B<A = NaNQ    

4: nonfounder: A<AxA<A : B<B = NaNQ    
4: nonfounder: A<AxA<B : B<B = NaNQ    
4: nonfounder: A<AxB<A : B<B = NaNQ    
4: nonfounder: A<AxB<B : B<B = NaNQ    
4: nonfounder: A<BxA<A : B<B = NaNQ    
4: nonfounder: A<BxA<B : B<B = 122    
4: nonfounder: A<BxB<A : B<B = 122    
4: nonfounder: A<BxB<B : B<B = 124    
4: nonfounder: B<AxA<A : B<B = NaNQ    
4: nonfounder: B<AxA<B : B<B = 122    
4: nonfounder: B<AxB<A : B<B = 122    
4: nonfounder: B<AxB<B : B<B = 124    
4: nonfounder: B<BxA<A : B<B = NaNQ    
4: nonfounder: B<BxA<B : B<B = 127    
4: nonfounder: B<BxB<A : B<B = 127    
4: nonfounder: B<BxB<B : B<B = 128    

5: nonfounder: A<AxA<A : A<A = 129    
5: nonfounder: A<AxA<B : A<A = 130    A<B = 131    
5: nonfounder: A<AxB<A : A<B = 131    A<A = 130    
5: nonfounder: A<AxB<B : A<B = 132    
5: nonfounder: A<BxA<A : A<A = 133    B<A = 134    
5: nonfounder: A<BxA<B : A<A = 135    A<B = 136    B<A = 136    B<B = 137    
5: nonfounder: A<BxB<A : A<B = 136    A<A = 135    B<B = 137    B<A = 136    
5: nonfounder: A<BxB<B : A<B = 138    B<B = 139    
5: nonfounder: B<AxA<A : B<A = 134    A<A = 133    
5: nonfounder: B<AxA<B : B<A = 136    B<B = 137    A<A = 135    A<B = 136    
5: nonfounder: B<AxB<A : B<B = 137    B<A = 136    A<B = 136    A<A = 135    
5: nonfounder: B<AxB<B : B<B = 139    A<B = 138    
5: nonfounder: B<BxA<A : B<A = 140    
5: nonfounder: B<BxA<B : B<A = 141    B<B = 142    
5: nonfounder: B<BxB<A : B<B = 142    B<A = 141    
5: nonfounder: B<BxB<B : B<B = 143    

5: nonfounder: A<AxA<A : A<A = 129    
5: nonfounder: A<AxA<B : A<A = 130    
5: nonfounder: A<AxB<A : A<A = 130    
5: nonfounder: A<AxB<B : A<A = NaNQ    
5: nonfounder: A<BxA<A : A<A = 133    
5: nonfounder: A<BxA<B : A<A = 135    
5: nonfounder: A<BxB<A : A<A = 135    
5: nonfounder: A<BxB<B : A<A = NaNQ    
5: nonfounder: B<AxA<A : A<A = 133    
5: nonfounder: B<AxA<B : A<A = 135    
5: nonfounder: B<AxB<A : A<A = 135    
5: nonfounder: B<AxB<B : A<A = NaNQ    
5: nonfounder: B<BxA<A : A<A = NaNQ    
5: nonfounder: B<BxA<B : A<A = NaNQ    
5: nonfounder: B<BxB<A : A<A = NaNQ    
5: nonfounder: B<BxB<B : A<A = NaNQ    

5: nonfounder: A<AxA<A : A<B = NaNQ    
5: nonfounder: A<AxA<B : A<B = 131    
5: nonfounder: A<AxB<A : A<B = 131    
5: nonfounder: A<AxB<B : A<B = 132    
5: nonfounder: A<BxA<A : A<B = 134    
5: nonfounder: A<BxA<B : A<B = 136    
5: nonfounder: A<BxB<A : A<B = 136    
5: nonfounder: A<BxB<B : A<B = 138    
5: nonfounder: B<AxA<A : A<B = 134    
5: nonfounder: B<AxA<B : A<B = 136    
5: nonfounder: B<AxB<A : A<B = 136    
5: nonfounder: B<AxB<B : A<B = 138    
5: nonfounder: B<BxA<A : A<B = 140    
5: nonfounder: B<BxA<B : A<B = 141    
5: nonfounder: B<BxB<A : A<B = 141    
5: nonfounder: B<BxB<B : A<B = NaNQ    

5: nonfounder: A<AxA<A : B<A = NaNQ    
5: nonfounder: A<AxA<B : B<A = 131    
5: nonfounder: A<AxB<A : B<A = 131    
5: nonfounder: A<AxB<B : B<A = 132    
5: nonfounder: A<BxA<A : B<A = 134    
5: nonfounder: A<BxA<B : B<A = 136    
5: nonfounder: A<BxB<A : B<A = 136    
5: nonfounder: A<BxB<B : B<A = 138    
5: nonfounder: B<AxA<A : B<A = 134    
5: nonfounder: B<AxA<B : B<A = 136    
5: nonfounder: B<AxB<A : B<A = 136    
5: nonfounder: B<AxB<B : B<A = 138    
5: nonfounder: B<BxA<A : B<A = 140    
5: nonfounder: B<BxA<B : B<A = 141    
5: nonfounder: B<BxB<A : B<A = 141    
5: nonfounder: B<BxB<B : B<A = NaNQ    

5: nonfounder: A<AxA<A : B<B = NaNQ    
5: nonfounder: A<AxA<B : B<B = NaNQ    
5: nonfounder: A<AxB<A : B<B = NaNQ    
5: nonfounder: A<AxB<B : B<B = NaNQ    
5: nonfounder: A<BxA<A : B<B = NaNQ    
5: nonfounder: A<BxA<B : B<B = 137    
5: nonfounder: A<BxB<A : B<B = 137    
5: nonfounder: A<BxB<B : B<B = 139    
5: nonfounder: B<AxA<A : B<B = NaNQ    
5: nonfounder: B<AxA<B : B<B = 137    
5: nonfounder: B<AxB<A : B<B = 137    
5: nonfounder: B<AxB<B : B<B = 139    
5: nonfounder: B<BxA<A : B<B = NaNQ    
5: nonfounder: B<BxA<B : B<B = 142    
5: nonfounder: B<BxB<A : B<B = 142    
5: nonfounder: B<BxB<B : B<B = 143    

6: founder   : A<A = 144    A<B = 145    B<A = 145    B<B = 146    

7: founder   : A<A = 147    A<B = 148    B<A = 148    B<B = 149    

8: nonfounder: A<AxA<A : A<A = 150    
8: nonfounder: A<AxA<B : A<A = 151    A<B = 152    
8: nonfounder: A<AxB<A : A<B = 152    A<A = 151    
8: nonfounder: A<AxB<B : A<B = 153    
8: nonfounder: A<BxA<A : A<A = 154    B<A = 155    
8: nonfounder: A<BxA<B : A<A = 156    A<B = 157    B<A = 157    B<B = 158    
8: nonfounder: A<BxB<A : A<B = 157    A<A = 156    B<B = 158    B<A = 157    
8: nonfounder: A<BxB<B : A<B = 159    B<B = 160    
8: nonfounder: B<AxA<A : B<A = 155    A<A = 154    
8: nonfounder: B<AxA<B : B<A = 157    B<B = 158    A<A = 156    A<B = 157    
8: nonfounder: B<AxB<A : B<B = 158    B<A = 157    A<B = 157    A<A = 156    
8: nonfounder: B<AxB<B : B<B = 160    A<B = 159    
8: nonfounder: B<BxA<A : B<A = 161    
8: nonfounder: B<BxA<B : B<A = 162    B<B = 163    
8: nonfounder: B<BxB<A : B<B = 163    B<A = 162    
8: nonfounder: B<BxB<B : B<B = 164    

8: nonfounder: A<AxA<A : A<A = 150    
8: nonfounder: A<AxA<B : A<A = 151    
8: nonfounder: A<AxB<A : A<A = 151    
8: nonfounder: A<AxB<B : A<A = NaNQ    
8: nonfounder: A<BxA<A : A<A = 154    
8: nonfounder: A<BxA<B : A<A = 156    
8: nonfounder: A<BxB<A : A<A = 156    
8: nonfounder: A<BxB<B : A<A = NaNQ    
8: nonfounder: B<AxA<A : A<A = 154    
8: nonfounder: B<AxA<B : A<A = 156    
8: nonfounder: B<AxB<A : A<A = 156    
8: nonfounder: B<AxB<B : A<A = NaNQ    
8: nonfounder: B<BxA<A : A<A = NaNQ    
8: nonfounder: B<BxA<B : A<A = NaNQ    
8: nonfounder: B<BxB<A : A<A = NaNQ    
8: nonfounder: B<BxB<B : A<A = NaNQ    

8: nonfounder: A<AxA<A : A<B = NaNQ    
8: nonfounder: A<AxA<B : A<B = 152    
8: nonfounder: A<AxB<A : A<B = 152    
8: nonfounder: A<AxB<B : A<B = 153    
8: nonfounder: A<BxA<A : A<B = 155    
8: nonfounder: A<BxA<B : A<B = 157    
8: nonfounder: A<BxB<A : A<B = 157    
8: nonfounder: A<BxB<B : A<B = 159    
8: nonfounder: B<AxA<A : A<B = 155    
8: nonfounder: B<AxA<B : A<B = 157    
8: nonfounder: B<AxB<A : A<B = 157    
8: nonfounder: B<AxB<B : A<B = 159    
8: nonfounder: B<BxA<A : A<B = 161    
8: nonfounder: B<BxA<B : A<B = 162    
8: nonfounder: B<BxB<A : A<B = 162    
8: nonfounder: B<BxB<B : A<B = NaNQ    

8: nonfounder: A<AxA<A : B<A = NaNQ    
8: nonfounder: A<AxA<B : B<A = 152    
8: nonfounder: A<AxB<A : B<A = 152    
8: nonfounder: A<AxB<B : B<A = 153    
8: nonfounder: A<BxA<A : B<A = 155    
8: nonfounder: A<BxA<B : B<A = 157    
8: nonfounder: A<BxB<A : B<A = 157    
8: nonfounder: A<BxB<B : B<A = 159    
8: nonfounder: B<AxA<A : B<A = 155    
8: nonfounder: B<AxA<B : B<A = 157    
8: nonfounder: B<AxB<A : B<A = 157    
8: nonfounder: B<AxB<B : B<A = 159    
8: nonfounder: B<BxA<A : B<A = 161    
8: nonfounder: B<BxA<B : B<A = 162    
8: nonfounder: B<BxB<A : B<A = 162    
8: nonfounder: B<BxB<B : B<A = NaNQ    

8: nonfounder: A<AxA<A : B<B = NaNQ    
8: nonfounder: A<AxA<B : B<B = NaNQ    
8: nonfounder: A<AxB<A : B<B = NaNQ    
8: nonfounder: A<AxB<B : B<B = NaNQ    
8: nonfounder: A<BxA<A : B<B = NaNQ    
8: nonfounder: A<BxA<B : B<B = 158    
8: nonfounder: A<BxB<A : B<B = 158    
8: nonfounder: A<BxB<B : B<B = 160    
8: nonfounder: B<AxA<A : B<B = NaNQ    
8: nonfounder: B<AxA<B : B<B = 158    
8: nonfounder: B<AxB<A : B<B = 158    
8: nonfounder: B<AxB<B : B<B = 160    
8: nonfounder: B<BxA<A : B<B = NaNQ    
8: nonfounder: B<BxA<B : B<B = 163    
8: nonfounder: B<BxB<A : B<B = 163    
8: nonfounder: B<BxB<B : B<B = 164    

9: nonfounder: A<AxA<A : A<A = 165    
9: nonfounder: A<AxA<B : A<A = 166    A<B = 167    
9: nonfounder: A<AxB<A : A<B = 167    A<A = 166    
9: nonfounder: A<AxB<B : A<B = 168    
9: nonfounder: A<BxA<A : A<A = 169    B<A = 170    
9: nonfounder: A<BxA<B : A<A = 171    A<B = 172    B<A = 172    B<B = 173    
9: nonfounder: A<BxB<A : A<B = 172    A<A = 171    B<B = 173    B<A = 172    
9: nonfounder: A<BxB<B : A<B = 174    B<B = 175    
9: nonfounder: B<AxA<A : B<A = 170    A<A = 169    
9: nonfounder: B<AxA<B : B<A = 172    B<B = 173    A<A = 171    A<B = 172    
9: nonfounder: B<AxB<A : B<B = 173    B<A = 172    A<B = 172    A<A = 171    
9: nonfounder: B<AxB<B : B<B = 175    A<B = 174    
9: nonfounder: B<BxA<A : B<A = 176    
9: nonfounder: B<BxA<B : B<A = 177    B<B = 178    
9: nonfounder: B<BxB<A : B<B = 178    B<A = 177    
9: nonfounder: B<BxB<B : B<B = 179    

9: nonfounder: A<AxA<A : A<A = 165    
9: nonfounder: A<AxA<B : A<A = 166    
9: nonfounder: A<AxB<A : A<A = 166    
9: nonfounder: A<AxB<B : A<A = NaNQ    
9: nonfounder: A<BxA<A : A<A = 169    
9: nonfounder: A<BxA<B : A<A = 171    
9: nonfounder: A<BxB<A : A<A = 171    
9: nonfounder: A<BxB<B : A<A = NaNQ    
9: nonfounder: B<AxA<A : A<A = 169    
9: nonfounder: B<AxA<B : A<A = 171    
9: nonfounder: B<AxB<A : A<A = 171    
9: nonfounder: B<AxB<B : A<A = NaNQ    
9: nonfounder: B<BxA<A : A<A = NaNQ    
9: nonfounder: B<BxA<B : A<A = NaNQ    
9: nonfounder: B<BxB<A : A<A = NaNQ    
9: nonfounder: B<BxB<B : A<A = NaNQ    

9: nonfounder: A<AxA<A : A<B = NaNQ    
9: nonfounder: A<AxA<B : A<B = 167    
9: nonfounder: A<AxB<A : A<B = 167    
9: nonfounder: A<AxB<B : A<B = 168    
9: nonfounder: A<BxA<A : A<B = 170    
9: nonfounder: A<BxA<B : A<B = 172    
9: nonfounder: A<BxB<A : A<B = 172    
9: nonfounder: A<BxB<B : A<B = 174    
9: nonfounder: B<AxA<A : A<B = 170    
9: nonfounder: B<AxA<B : A<B = 172    
9: nonfounder: B<AxB<A : A<B = 172    
9: nonfounder: B<AxB<B : A<B = 174    
9: nonfounder: B<BxA<A : A<B = 176    
9: nonfounder: B<BxA<B : A<B = 177    
9: nonfounder: B<BxB<A : A<B = 177    
9: nonfounder: B<BxB<B : A<B = NaNQ    

9: nonfounder: A<AxA<A : B<A = NaNQ    
9: nonfounder: A<AxA<B : B<A = 167    
9: nonfounder: A<AxB<A : B<A = 167    
9: nonfounder: A<AxB<B : B<A = 168    
9: nonfounder: A<BxA<A : B<A = 170    
9: nonfounder: A<BxA<B : B<A = 172    
9: nonfounder: A<BxB<A : B<A = 172    
9: nonfounder: A<BxB<B : B<A = 174    
9: nonfounder: B<AxA<A : B<A = 170    
9: nonfounder: B<AxA<B : B<A = 172    
9: nonfounder: B<AxB<A : B<A = 172    
9: nonfounder: B<AxB<B : B<A = 174    
9: nonfounder: B<BxA<A : B<A = 176    
9: nonfounder: B<BxA<B : B<A = 177    
9: nonfounder: B<BxB<A : B<A = 177    
9: nonfounder: B<BxB<B : B<A = NaNQ    

9: nonfounder: A<AxA<A : B<B = NaNQ    
9: nonfounder: A<AxA<B : B<B = NaNQ    
9: nonfounder: A<AxB<A : B<B = NaNQ    
9: nonfounder: A<AxB<B : B<B = NaNQ    
9: nonfounder: A<BxA<A : B<B = NaNQ    
9: nonfounder: A<BxA<B : B<B = 173    
9: nonfounder: A<BxB<A : B<B = 173    
9: nonfounder: A<BxB<B : B<B = 175    
9: nonfounder: B<AxA<A : B<B = NaNQ    
9: nonfounder: B<AxA<B : B<B = 173    
9: nonfounder: B<AxB<A : B<B = 173    
9: nonfounder: B<AxB<B : B<B = 175    
9: nonfounder: B<BxA<A : B<B = NaNQ    
9: nonfounder: B<BxA<B : B<B = 178    
9: nonfounder: B<BxB<A : B<B = 178    
9: nonfounder: B<BxB<B : B<B = 179    

