=================

     Results

=================

==============================
     Analysis description
==============================

  Title                        assoc                         
  Primary Trait                AFF (Binary)                  
  Allow averaging              Disabled                      
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  
-------------------------------------------------------------

Note: This output contains results for a binary trait using an algorithm still in Beta release form. Please verify results before reporting.

======================================
     Transformation configuration
======================================



Note: No transformation applied.

=======================
     Summary table
=======================

-------------------------------------------------------------------------------------
  Model   Intercept  Test cov.  Estimate   Std. err.  P-value (Wald)  P-value (LRT)  
-------------------------------------------------------------------------------------
  marker  -0.681050  m           0.029605   0.035097   0.398932        0.399287      
-------------------------------------------------------------------------------------

Note: Models with an asterisk (*) may not have converged.

================================
     Complete summary table
================================

-------------------------------------------------------------------------------------
  Model   Intercept  Test cov.  Estimate   Std. err.  P-value (Wald)  P-value (LRT)  
-------------------------------------------------------------------------------------
  marker  -0.681050  m           0.029605   0.035097   0.398932        0.399287      
-------------------------------------------------------------------------------------

Note: Models with an asterisk (*) may not have converged.

Note: See .det file for more information about each model

