



Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             0001          1         0             0           
     1             0002          2         0             0           
     1             0003          1         0             0           
     1             0004          2         0             0           
     1             0005          2         0001          0002        
     1             0007          2         0001          0002        
     1             0008          1         0003          0004        
     1             0009          2         0003          0004        
     1             0010          1         0             0           
     1             0011          1         0003          0004        


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         Square Root DBH     
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             0001          0                     1                     1                     93                    -1                  
     1             0002          1                     1                     1                     93                    -1                  
     1             0003          0                     1                     1                     93                    -1                  
     1             0004          1                     1                     1                     93                    -1                  
     1             0005          1                     1                     0                     93                    1.56525             
     1             0007          1                     1                     0                     93                    -1                  
     1             0008          0                     1                     0                     93                    -1                  
     1             0009          1                     1                     0                     93                    2.59422             
     1             0010          0                     1                     1                     93                    3.34365             
     1             0011          0                     1                     0                     93                    -1                  

