


%AGEON-W: Please note that no sex field is present in the data; analyses that
          depend on sex-specific data may produce unpredictable results.
%AGEON-E: Error(s) building pedigree '0': 1 errors.
%AGEON-W: Both parents '1' and '2' have unknown sex and cannot be inferred.

Family structure information on the first 1000 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     0             1                       0             0           
     0             2                       0             0           
     0             3                       1             2           
     0             4                       1             2           
     0             5                       1             2           
     0             6                       1             2           
     0             7                       1             2           
     0             8                       1             2           
     0             9                       1             2           
     0             10                      1             2           

%AGEON-E: Errors appear in pedigree data. Results may be incomplete.
