


============================
     SAMPLE DESCRIPTION
============================

  Number of pedigrees in dataset           200  
  Number of analyzable pedigrees           200  
                                                
  Number of individuals in dataset         787  
  Number of sibs in dataset                387  
  Number of analyzable sibs                387  
  Number of sibs with missing age values     0  

===========================
     MODEL DESCRIPTION
===========================

  Title               AGEON Analysis 1  
  Affectedness trait  AFF               
  Age-of-onset trait  AO                
  Age-at-exam trait   AE                

===============================
     CLASSIFICATION SYSTEM
===============================

  Using default classification system:
                                                                

  ??  Both parents are unknown.                                 
  ?A  One of the parents is unknown, the other is affected.     
  ?U  One of the parents is unknown, the other is unaffected.   
  AA  Both parents are affected.                                
  AU  One of the parents is affected, the other is unaffected.  
  UU  Both parents are unaffected.                              

==========================

     CLASS STATISTICS

==========================

==================
     CLASS ??
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            60  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           9  
  MEAN OF AGE OF ONSET                             74.444444  
  VARIANCE OF AGE OF ONSET                          2.777778  
  NUMBER OF INDIVIDUALS AFFECTED                           9  
  PROPORTION OF INDIVIDUALS AFFECTED                0.150000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            74.627451  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         7.758431  

==================
     CLASS ?A
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            80  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          20  
  MEAN OF AGE OF ONSET                             73.650000  
  VARIANCE OF AGE OF ONSET                          6.555263  
  NUMBER OF INDIVIDUALS AFFECTED                          20  
  PROPORTION OF INDIVIDUALS AFFECTED                0.250000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            75.200000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         4.705085  

==================
     CLASS ?U
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            95  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          20  
  MEAN OF AGE OF ONSET                             74.350000  
  VARIANCE OF AGE OF ONSET                          3.186842  
  NUMBER OF INDIVIDUALS AFFECTED                          20  
  PROPORTION OF INDIVIDUALS AFFECTED                0.210526  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            74.733333  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         4.063063  

==================
     CLASS AA
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            20  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           4  
  MEAN OF AGE OF ONSET                             75.000000  
  VARIANCE OF AGE OF ONSET                          2.666667  
  NUMBER OF INDIVIDUALS AFFECTED                           4  
  PROPORTION OF INDIVIDUALS AFFECTED                0.200000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            75.437500  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         3.195833  

==================
     CLASS AU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            89  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          22  
  MEAN OF AGE OF ONSET                             73.681818  
  VARIANCE OF AGE OF ONSET                          4.322511  
  NUMBER OF INDIVIDUALS AFFECTED                          22  
  PROPORTION OF INDIVIDUALS AFFECTED                0.247191  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            75.268657  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         4.532791  

==================
     CLASS UU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            43  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           9  
  MEAN OF AGE OF ONSET                             75.333333  
  VARIANCE OF AGE OF ONSET                          5.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           9  
  PROPORTION OF INDIVIDUALS AFFECTED                0.209302  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            75.235294  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         5.397504  

====================================================================
     MAXIMIZATION RESULTS susceptibilities equal, no truncation
====================================================================

------------------------------------------------------------------------
  Parameter           Estimate    S.E.       P-value     Deriv          
------------------------------------------------------------------------
  Susceptibility intercepts
                  ??   -0.489313   0.162018   0.002527    0.0000007418  
                  ?A   -0.489313   0.162018   0.002527    0.0000000000  
                  ?U   -0.489313   0.162018   0.002527    0.0000000000  
                  AA   -0.489313   0.162018   0.002527    0.0000000000  
                  AU   -0.489313   0.162018   0.002527    0.0000000000  
                  UU   -0.489313   0.162018   0.002527    0.0000000000  

      Mean intercept   73.681929   0.182156  < 1.00e-07  -0.0000000590  

  Mean covariates
                cov1    0.343034   0.172083   0.046215   -0.0000004720  

  Variance intercept    6.308689   1.561857   5.36e-05    0.0000009139  

  Variance covariates
                cov2    1.886832   1.201406   0.116294    0.0000000893  

  Transformation
             Lambda1    1.000000                 Fixed                  
             Lambda2    0.050000                 Fixed                  
------------------------------------------------------------------------

Final ln likelihood: -383.779625

===================================================================
     MAXIMIZATION RESULTS susceptibilities free, no truncation
===================================================================

------------------------------------------------------------------------
  Parameter           Estimate    S.E.       P-value     Deriv          
------------------------------------------------------------------------
  Susceptibility intercepts
                  ??   -0.893122   0.422414   0.034487   -0.0000002265  
                  ?A   -0.295137   0.330400   0.371711    0.0000009104  
                  ?U   -0.437648   0.322447   0.174696   -0.0000014836  
                  AA   -0.761468   0.647490   0.239583    0.0000000443  
                  AU   -0.396850   0.305526   0.193976   -0.0000008429  
                  UU   -0.564788   0.451152   0.210613    0.0000018507  

      Mean intercept   73.683039   0.182786  < 1.00e-07  -0.0000011289  

  Mean covariates
                cov1    0.346353   0.172817   0.045054   -0.0000029334  

  Variance intercept    6.358669   1.578152   5.60e-05   -0.0000002042  

  Variance covariates
                cov2    1.907275   1.214700   0.116378   -0.0000007602  

  Transformation
             Lambda1    1.000000                 Fixed                  
             Lambda2    0.050000                 Fixed                  
------------------------------------------------------------------------

Final ln likelihood: -382.959654

=======================================================================
     MAXIMIZATION RESULTS susceptibilities equal, using truncation
=======================================================================

------------------------------------------------------------------------
  Parameter           Estimate    S.E.       P-value     Deriv          
------------------------------------------------------------------------
  Susceptibility intercepts
                  ??   -0.489313   0.162018   0.002527    0.0000007418  
                  ?A   -0.489313   0.162018   0.002527    0.0000000000  
                  ?U   -0.489313   0.162018   0.002527    0.0000000000  
                  AA   -0.489313   0.162018   0.002527    0.0000000000  
                  AU   -0.489313   0.162018   0.002527    0.0000000000  
                  UU   -0.489313   0.162018   0.002527    0.0000000000  

      Mean intercept   73.681929   0.182156  < 1.00e-07  -0.0000000590  

  Mean covariates
                cov1    0.343034   0.172083   0.046215   -0.0000004720  

  Variance intercept    6.308689   1.561857   5.36e-05    0.0000009139  

  Variance covariates
                cov2    1.886832   1.201406   0.116294    0.0000000893  

  Transformation
             Lambda1    1.000000                 Fixed                  
             Lambda2    0.050000                 Fixed                  
------------------------------------------------------------------------

Final ln likelihood: -383.779625

======================================================================
     MAXIMIZATION RESULTS susceptibilities free, using truncation
======================================================================

------------------------------------------------------------------------
  Parameter           Estimate    S.E.       P-value     Deriv          
------------------------------------------------------------------------
  Susceptibility intercepts
                  ??   -0.893122   0.422414   0.034487   -0.0000002265  
                  ?A   -0.295137   0.330400   0.371711    0.0000009104  
                  ?U   -0.437648   0.322447   0.174696   -0.0000014836  
                  AA   -0.761468   0.647490   0.239583    0.0000000443  
                  AU   -0.396850   0.305526   0.193976   -0.0000008429  
                  UU   -0.564788   0.451152   0.210613    0.0000018507  

      Mean intercept   73.683039   0.182786  < 1.00e-07  -0.0000011289  

  Mean covariates
                cov1    0.346353   0.172817   0.045054   -0.0000029334  

  Variance intercept    6.358669   1.578152   5.60e-05   -0.0000002042  

  Variance covariates
                cov2    1.907275   1.214700   0.116378   -0.0000007602  

  Transformation
             Lambda1    1.000000                 Fixed                  
             Lambda2    0.050000                 Fixed                  
------------------------------------------------------------------------

Final ln likelihood: -382.959654

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities free, no truncation   -382.959654  
  H1 ln likelihood susceptibilities equal, no truncation  -383.779625  
                                                                       
  2 * |H0 - H1|                                              1.639942  
  Degrees of freedom                                                5  
  P-value                                                    0.896377  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities free, using truncation   -382.959654  
  H1 ln likelihood susceptibilities equal, using truncation  -383.779625  
                                                                          
  2 * |H0 - H1|                                                 1.639942  
  Degrees of freedom                                                   5  
  P-value                                                       0.896377  

==========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, no truncation
==========================================================================

--------------------------------------------------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  cov1       cov2       ??         ?A         ?U         AA         AU         UU         
--------------------------------------------------------------------------------------------------------------------------------------------------
  Mean intercept       0.033181        0.057376           -0.003310   0.032530   0.010835   0.010835   0.010835   0.010835   0.010835   0.010835  
  Variance intercept   0.057376        2.439397           -7.35e-05   1.257119   0.041089   0.041089   0.041089   0.041089   0.041089   0.041089  
  cov1                -0.003310       -7.35e-05            0.029613   0.006983  -0.000758  -0.000758  -0.000758  -0.000758  -0.000758  -0.000758  
  cov2                 0.032530        1.257119            0.006983   1.443376   0.021530   0.021530   0.021530   0.021530   0.021530   0.021530  
  ??                   0.010835        0.041089           -0.000758   0.021530   0.026250   0.026250   0.026250   0.026250   0.026250   0.026250  
  ?A                   0.010835        0.041089           -0.000758   0.021530   0.026250   0.026250   0.026250   0.026250   0.026250   0.026250  
  ?U                   0.010835        0.041089           -0.000758   0.021530   0.026250   0.026250   0.026250   0.026250   0.026250   0.026250  
  AA                   0.010835        0.041089           -0.000758   0.021530   0.026250   0.026250   0.026250   0.026250   0.026250   0.026250  
  AU                   0.010835        0.041089           -0.000758   0.021530   0.026250   0.026250   0.026250   0.026250   0.026250   0.026250  
  UU                   0.010835        0.041089           -0.000758   0.021530   0.026250   0.026250   0.026250   0.026250   0.026250   0.026250  

=========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities free, no truncation
=========================================================================

------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                      Mean intercept  Variance intercept  cov1       cov2       ??         ?A         ?U         AA         AU         UU         
------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Mean intercept                       0.033411        0.058578           -0.003341   0.033729   0.009444   0.011435   0.012423   0.010389   0.010946   0.009431  
  Variance intercept                   0.058578        2.490563           -0.000847   1.287137   0.016317   0.052947   0.028804   0.060213   0.056895   0.041067  
  cov1                                -0.003341       -0.000847            0.029866   0.005488  -0.001571   0.000313  -0.000839  -0.003822  -0.002356   0.003566  
  cov2                                 0.033729        1.287137            0.005488   1.475496   0.009828   0.033150   0.006110   0.039946   0.029130   0.024602  
  ??                                   0.009444        0.016317           -0.001571   0.009828   0.178433   0.003202   0.003495   0.002999   0.003118   0.002570  
  ?A                                   0.011435        0.052947            0.000313   0.033150   0.003202   0.109164   0.004312   0.004045   0.004197   0.003784  
  ?U                                   0.012423        0.028804           -0.000839   0.006110   0.003495   0.004312   0.103972   0.003842   0.004176   0.003618  
  AA                                   0.010389        0.060213           -0.003822   0.039946   0.002999   0.004045   0.003842   0.419244   0.004186   0.002945  
  AU                                   0.010946        0.056895           -0.002356   0.029130   0.003118   0.004197   0.004176   0.004186   0.093346   0.003273  
  UU                                   0.009431        0.041067            0.003566   0.024602   0.002570   0.003784   0.003618   0.002945   0.003273   0.203538  
                                                                                                                                                                  
  Likelihood Surface flat                                                                                                                                         
  variance matrix near singular and                                                                                                                               
  may be affected by rounding error.                                                                                                                              
  Reducing the number of parameters                                                                                                                               
  to be estimated is recommended                                                                                                                                  

=============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, using truncation
=============================================================================

--------------------------------------------------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  cov1       cov2       ??         ?A         ?U         AA         AU         UU         
--------------------------------------------------------------------------------------------------------------------------------------------------
  Mean intercept       0.033181        0.057376           -0.003310   0.032530   0.010835   0.010835   0.010835   0.010835   0.010835   0.010835  
  Variance intercept   0.057376        2.439397           -7.35e-05   1.257119   0.041089   0.041089   0.041089   0.041089   0.041089   0.041089  
  cov1                -0.003310       -7.35e-05            0.029613   0.006983  -0.000758  -0.000758  -0.000758  -0.000758  -0.000758  -0.000758  
  cov2                 0.032530        1.257119            0.006983   1.443376   0.021530   0.021530   0.021530   0.021530   0.021530   0.021530  
  ??                   0.010835        0.041089           -0.000758   0.021530   0.026250   0.026250   0.026250   0.026250   0.026250   0.026250  
  ?A                   0.010835        0.041089           -0.000758   0.021530   0.026250   0.026250   0.026250   0.026250   0.026250   0.026250  
  ?U                   0.010835        0.041089           -0.000758   0.021530   0.026250   0.026250   0.026250   0.026250   0.026250   0.026250  
  AA                   0.010835        0.041089           -0.000758   0.021530   0.026250   0.026250   0.026250   0.026250   0.026250   0.026250  
  AU                   0.010835        0.041089           -0.000758   0.021530   0.026250   0.026250   0.026250   0.026250   0.026250   0.026250  
  UU                   0.010835        0.041089           -0.000758   0.021530   0.026250   0.026250   0.026250   0.026250   0.026250   0.026250  

============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities free, using truncation
============================================================================

------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                      Mean intercept  Variance intercept  cov1       cov2       ??         ?A         ?U         AA         AU         UU         
------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Mean intercept                       0.033411        0.058578           -0.003341   0.033729   0.009444   0.011435   0.012423   0.010389   0.010946   0.009431  
  Variance intercept                   0.058578        2.490563           -0.000847   1.287137   0.016317   0.052947   0.028804   0.060213   0.056895   0.041067  
  cov1                                -0.003341       -0.000847            0.029866   0.005488  -0.001571   0.000313  -0.000839  -0.003822  -0.002356   0.003566  
  cov2                                 0.033729        1.287137            0.005488   1.475496   0.009828   0.033150   0.006110   0.039946   0.029130   0.024602  
  ??                                   0.009444        0.016317           -0.001571   0.009828   0.178433   0.003202   0.003495   0.002999   0.003118   0.002570  
  ?A                                   0.011435        0.052947            0.000313   0.033150   0.003202   0.109164   0.004312   0.004045   0.004197   0.003784  
  ?U                                   0.012423        0.028804           -0.000839   0.006110   0.003495   0.004312   0.103972   0.003842   0.004176   0.003618  
  AA                                   0.010389        0.060213           -0.003822   0.039946   0.002999   0.004045   0.003842   0.419244   0.004186   0.002945  
  AU                                   0.010946        0.056895           -0.002356   0.029130   0.003118   0.004197   0.004176   0.004186   0.093346   0.003273  
  UU                                   0.009431        0.041067            0.003566   0.024602   0.002570   0.003784   0.003618   0.002945   0.003273   0.203538  
                                                                                                                                                                  
  Likelihood Surface flat                                                                                                                                         
  variance matrix near singular and                                                                                                                               
  may be affected by rounding error.                                                                                                                              
  Reducing the number of parameters                                                                                                                               
  to be estimated is recommended                                                                                                                                  

