



Family structure information on the first 10 individuals read from file: 11.ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     3             1             1         0             0           
     3             2             2         0             0           
     3             3             1         0             0           
     3             4             2         1             2           
     3             5             2         1             2           
     3             6             1         0             0           
     3             7             1         5             6           
     3             8             2         3             4           
     8             1             1         0             0           
     8             2             2         0             0           


Phenotypes for the first 10 individuals read from file: 11.ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         sle                   race_aa             
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     3             1             0                     1                     1                     8                     0                     1                   
     3             2             1                     1                     1                     8                     0                     1                   
     3             3             0                     1                     1                     8                     0                     1                   
     3             4             1                     1                     0                     8                     0                     1                   
     3             5             1                     1                     0                     8                     0                     1                   
     3             6             0                     1                     1                     8                     0                     1                   
     3             7             0                     1                     0                     8                     1                     1                   
     3             8             1                     1                     0                     8                     1                     1                   
     8             1             0                     1                     1                     13                    0                     1                   
     8             2             1                     1                     1                     13                    0                     1                   

