


Reading Parameter File....................done.
Reading Pedigree File.....................
              from 11.ped.................done.
Sorting Pedigrees.........................done.
Reading pairs.............................done.
Sorting pairs.............................done.

LODPAL analysis.......  1

Computing multipoint lod scores...........done.

LODPAL analysis.......  2

Computing multipoint lod scores...........done.

LODPAL analysis.......  3

Computing multipoint lod scores...........done.

LODPAL analysis.......  4

Computing multipoint lod scores...........done.

Analysis complete!



