


==========
Analysis 2
==========


Markers in order:
  C01R0001 C01R0002 C01R0003 C01R0004 



                      All Possible Haplotype Combinations

Population:  0 / 2

                            Pedigree:Member
                  11:2 13:3 15:2 18:3 32:2 40:3 99:1 
1-1-1-1  1-1-1-1   x    x    x    x    x    x    -   
2-2-2-2  2-2-2-2   -    -    -    -    -    -    x   


Population:  1 / 1

                            Pedigree:Member
                  12:4 14:2 16:2 17:2 34:4 
1-1-1-1  1-1-1-1   x    x    x    x    x   
1-1-1-1  1-2-1-1   -    -    x    -    -   
1-1-1-1  2-1-1-1   x    -    x    -    x   
1-1-1-1  2-2-1-1   -    -    x    -    -   
1-2-1-1  2-1-1-1   -    -    x    -    -   
2-1-1-1  2-1-1-1   x    -    x    -    x   
2-1-1-1  2-2-1-1   -    -    x    -    -   


