


==========
Analysis 1
==========


Options Selected
================
Haplotype region                                   one
Minor allele frequency filter                      no
Sliding window                                     no
Four gamete rule blocks                            no
LD blocks                                          no

Subpopulations specified                           yes
Analysis unit                                      family rep
  Family representatives specified                 yes

Estimate haplotype frequencies                     no
Show all possible haplotype combinations table     yes
List most likely haplotype combinations            no
Do likelihood ratio test                           no
Compute empirical p-value                          no


Results
=======


Markers in order:
  C01R0001 C01R0002 C01R0003 C01R0004 



