


Reading Parameter File....................done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Reading Genome Description File...........done.

Parsing DECIPHER analyses ...


Parsing new analysis block ...


Parsing of Analysis 1 complete.  Analysis valid.
------------------------------------------------------------------------------

  Performing analysis: Analysis 1
  ===========================================================================

    Subpopulation: 0 / 1
      Determining possible haplotype combinations ................... done.
%DECIPHER-E: Subpopulation, 0 / 1 contains no usable data.  Ignoring this
             subpopulation ...
    Subpopulation: 0 / 2
      Determining possible haplotype combinations ................... done.
    Subpopulation: 1 / 1
      Determining possible haplotype combinations ................... done.
    Subpopulation: 1 / 2
      Determining possible haplotype combinations ................... done.
%DECIPHER-E: Subpopulation, 1 / 2 contains no usable data.  Ignoring this
             subpopulation ...

  ===========================================================================


Parsing new analysis block ...


Parsing of Analysis 2 complete.  Analysis valid.
------------------------------------------------------------------------------

  Performing analysis: Analysis 2
  ===========================================================================

    Subpopulation: 0 / 1
      Determining possible haplotype combinations ................... done.
%DECIPHER-E: Subpopulation, 0 / 1 contains no usable data.  Ignoring this
             subpopulation ...
    Subpopulation: 0 / 2
      Determining possible haplotype combinations ................... done.
    Subpopulation: 1 / 1
      Determining possible haplotype combinations ................... done.
    Subpopulation: 1 / 2
      Determining possible haplotype combinations ................... done.
%DECIPHER-E: Subpopulation, 1 / 2 contains no usable data.  Ignoring this
             subpopulation ...

  ===========================================================================


Parsing new analysis block ...


Parsing of Analysis 3 complete.  Analysis valid.
------------------------------------------------------------------------------

  Performing analysis: Analysis 3
  ===========================================================================

    Subpopulation: 0 / 1
      Determining possible haplotype combinations ................... done.
%DECIPHER-E: Subpopulation, 0 / 1 contains no usable data.  Ignoring this
             subpopulation ...
    Subpopulation: 0 / 2
      Determining possible haplotype combinations ................... done.
    Subpopulation: 1 / 1
      Determining possible haplotype combinations ................... done.
    Subpopulation: 1 / 2
      Determining possible haplotype combinations ................... done.
%DECIPHER-E: Subpopulation, 1 / 2 contains no usable data.  Ignoring this
             subpopulation ...

  ===========================================================================



