## ************************************************************************** ##
## **************              Human Genome Map                ************** ##
## **************             (S.A.G.E.  Format)               ************** ##
## ************************************************************************** ##
##                              GAW 12 Data                                   ##
##                                                                            ##
## -------------------------------------------------------------------------- ##
Genome = "homo_sapiens", map = haldane { 
   region = Region_chr01 {
      marker   = "D01G002"              # at    0.0000 cM
      distance =  3.8200000000 
      marker   = "D01G003"              # at    3.8200 cM
      distance =  0.2100000000 
      marker   = "D01G004"              # at    4.0300 cM
      distance =  4.5100000000 
      marker   = "D01G005"              # at    8.5400 cM
      distance =  1.4100000000 
      marker   = "D01G006"              # at    9.9500 cM
      distance =  0.3000000000 
      marker   = "D01G007"              # at   10.2500 cM
      distance =  0.3800000000 
      marker   = "D01G008"              # at   10.6300 cM
      distance =  1.0000000000 
      marker   = "D01G009"              # at   11.6300 cM
      distance =  0.0900000000 
      marker   = "D01G010"              # at   11.7200 cM
      distance =  0.8400000000 
      marker   = "D01G011"              # at   12.5600 cM
      distance =  0.0500000000 
      marker   = "D01G012"              # at   12.6100 cM
      distance =  0.4200000000 
      marker   = "D01G013"              # at   13.0300 cM
      distance =  0.1400000000 
      marker   = "D01G014"              # at   13.1700 cM
      distance =  1.1600000000 
      marker   = "D01G015"              # at   14.3300 cM
      distance =  0.0700000000 
      marker   = "D01G016"              # at   14.4000 cM
      distance =  0.5400000000 
      marker   = "D01G017"              # at   14.9400 cM
      distance =  0.0400000000 
      marker   = "D01G018"              # at   14.9800 cM
      distance =  0.7100000000 
      marker   = "D01G019"              # at   15.6900 cM
      distance =  0.0200000000 
      marker   = "D01G020"              # at   15.7100 cM
      distance =  1.8700000000 
      marker   = "D01G021"              # at   17.5800 cM
      distance =  1.1000000000 
      marker   = "D01G022"              # at   18.6800 cM
      distance =  0.2300000000 
      marker   = "D01G023"              # at   18.9100 cM
      distance =  0.2400000000 
      marker   = "D01G024"              # at   19.1500 cM
      distance =  1.7900000000 
      marker   = "D01G025"              # at   20.9400 cM
      distance =  0.1600000000 
      marker   = "D01G026"              # at   21.1000 cM
      distance =  1.6200000000 
      marker   = "D01G027"              # at   22.7200 cM
      distance =  0.0200000000 
      marker   = "D01G028"              # at   22.7400 cM
      distance =  3.1000000000 
      marker   = "D01G029"              # at   25.8400 cM
      distance =  0.4400000000 
      marker   = "D01G030"              # at   26.2800 cM
      distance =  1.5900000000 
      marker   = "D01G031"              # at   27.8700 cM
      distance =  3.1800000000 
      marker   = "D01G032"              # at   31.0500 cM
      distance =  0.0700000000 
      marker   = "D01G033"              # at   31.1200 cM
      distance =  2.0300000000 
      marker   = "D01G034"              # at   33.1500 cM
      distance =  0.1900000000 
      marker   = "D01G035"              # at   33.3400 cM
      distance =  0.6300000000 
      marker   = "D01G036"              # at   33.9700 cM
      distance =  0.3000000000 
      marker   = "D01G037"              # at   34.2700 cM
      distance =  2.2600000000 
      marker   = "D01G038"              # at   36.5300 cM
      distance =  0.6600000000 
      marker   = "D01G039"              # at   37.1900 cM
      distance =  2.6300000000 
      marker   = "D01G040"              # at   39.8200 cM
      distance =  0.6600000000 
      marker   = "D01G041"              # at   40.4800 cM
      distance =  0.2100000000 
      marker   = "D01G042"              # at   40.6900 cM
      distance =  0.2500000000 
      marker   = "D01G043"              # at   40.9400 cM
      distance =  2.3500000000 
      marker   = "D01G044"              # at   43.2900 cM
      distance =  0.4300000000 
      marker   = "D01G045"              # at   43.7200 cM
      distance =  0.2300000000 
      marker   = "D01G046"              # at   43.9500 cM
      distance =  0.1100000000 
      marker   = "D01G047"              # at   44.0600 cM
      distance =  0.2100000000 
      marker   = "D01G048"              # at   44.2700 cM
      distance =  2.1200000000 
      marker   = "D01G049"              # at   46.3900 cM
      distance =  2.7500000000 
      marker   = "D01G050"              # at   49.1400 cM
      distance =  0.7400000000 
      marker   = "D01G051"              # at   49.8800 cM
      distance =  1.0900000000 
      marker   = "D01G052"              # at   50.9700 cM
      distance =  1.7800000000 
      marker   = "D01G053"              # at   52.7500 cM
      distance =  2.1900000000 
      marker   = "D01G054"              # at   54.9400 cM
      distance =  0.0200000000 
      marker   = "D01G055"              # at   54.9600 cM
      distance =  1.2200000000 
      marker   = "D01G056"              # at   56.1800 cM
      distance =  0.6400000000 
      marker   = "D01G057"              # at   56.8200 cM
      distance =  0.6600000000 
      marker   = "D01G058"              # at   57.4800 cM
      distance =  0.2200000000 
      marker   = "D01G059"              # at   57.7000 cM
      distance =  0.9400000000 
      marker   = "D01G060"              # at   58.6400 cM
      distance =  0.5200000000 
      marker   = "D01G061"              # at   59.1600 cM
      distance =  0.4800000000 
      marker   = "D01G062"              # at   59.6400 cM
      distance =  0.7000000000 
      marker   = "D01G063"              # at   60.3400 cM
      distance =  3.0900000000 
      marker   = "D01G064"              # at   63.4300 cM
      distance =  0.1100000000 
      marker   = "D01G065"              # at   63.5400 cM
      distance =  0.1600000000 
      marker   = "D01G066"              # at   63.7000 cM
      distance =  0.4400000000 
      marker   = "D01G067"              # at   64.1400 cM
      distance =  1.9400000000 
      marker   = "D01G068"              # at   66.0800 cM
      distance =  1.7700000000 
      marker   = "D01G069"              # at   67.8500 cM
      distance =  1.1200000000 
      marker   = "D01G070"              # at   68.9700 cM
      distance =  3.8500000000 
      marker   = "D01G071"              # at   72.8200 cM
      distance =  0.0600000000 
      marker   = "D01G072"              # at   72.8800 cM
      distance =  0.3900000000 
      marker   = "D01G073"              # at   73.2700 cM
      distance =  1.5900000000 
      marker   = "D01G074"              # at   74.8600 cM
      distance =  1.1900000000 
      marker   = "D01G075"              # at   76.0500 cM
      distance =  2.8300000000 
      marker   = "D01G076"              # at   78.8800 cM
      distance =  0.8700000000 
      marker   = "D01G077"              # at   79.7500 cM
      distance =  0.4500000000 
      marker   = "D01G078"              # at   80.2000 cM
      distance =  0.6800000000 
      marker   = "D01G079"              # at   80.8800 cM
      distance =  0.3500000000 
      marker   = "D01G080"              # at   81.2300 cM
      distance =  0.0900000000 
      marker   = "D01G081"              # at   81.3200 cM
      distance =  0.4000000000 
      marker   = "D01G082"              # at   81.7200 cM
      distance =  1.9500000000 
      marker   = "D01G083"              # at   83.6700 cM
      distance =  0.2100000000 
      marker   = "D01G084"              # at   83.8800 cM
      distance =  0.6600000000 
      marker   = "D01G085"              # at   84.5400 cM
      distance =  0.4800000000 
      marker   = "D01G086"              # at   85.0200 cM
      distance =  0.5000000000 
      marker   = "D01G087"              # at   85.5200 cM
      distance =  1.1900000000 
      marker   = "D01G088"              # at   86.7100 cM
      distance =  0.1300000000 
      marker   = "D01G089"              # at   86.8400 cM
      distance =  0.4500000000 
      marker   = "D01G090"              # at   87.2900 cM
      distance =  0.1800000000 
      marker   = "D01G091"              # at   87.4700 cM
      distance =  0.5300000000 
      marker   = "D01G092"              # at   88.0000 cM
      distance =  2.2900000000 
      marker   = "D01G093"              # at   90.2900 cM
      distance =  2.8200000000 
      marker   = "D01G094"              # at   93.1100 cM
      distance =  0.6700000000 
      marker   = "D01G095"              # at   93.7800 cM
      distance =  0.4400000000 
      marker   = "D01G096"              # at   94.2200 cM
      distance =  0.4000000000 
      marker   = "D01G097"              # at   94.6200 cM
      distance =  0.5500000000 
      marker   = "D01G098"              # at   95.1700 cM
      distance =  1.9800000000 
      marker   = "D01G099"              # at   97.1500 cM
      distance =  0.6600000000 
      marker   = "D01G100"              # at   97.8100 cM
      distance =  0.1500000000 
      marker   = "D01G101"              # at   97.9600 cM
      distance =  0.1900000000 
      marker   = "D01G102"              # at   98.1500 cM
      distance =  1.6400000000 
      marker   = "D01G103"              # at   99.7900 cM
      distance =  0.4600000000 
      marker   = "D01G104"              # at  100.2500 cM
      distance =  1.5400000000 
      marker   = "D01G105"              # at  101.7900 cM
      distance =  0.2400000000 
      marker   = "D01G106"              # at  102.0300 cM
      distance =  0.7300000000 
      marker   = "D01G107"              # at  102.7600 cM
      distance =  0.7200000000 
      marker   = "D01G108"              # at  103.4800 cM
      distance =  0.4900000000 
      marker   = "D01G109"              # at  103.9700 cM
      distance =  0.3900000000 
      marker   = "D01G110"              # at  104.3600 cM
      distance =  0.3600000000 
      marker   = "D01G111"              # at  104.7200 cM
      distance =  0.7700000000 
      marker   = "D01G112"              # at  105.4900 cM
      distance =  0.3600000000 
      marker   = "D01G113"              # at  105.8500 cM
      distance =  0.6300000000 
      marker   = "D01G114"              # at  106.4800 cM
      distance =  0.6400000000 
      marker   = "D01G115"              # at  107.1200 cM
      distance =  0.2700000000 
      marker   = "D01G116"              # at  107.3900 cM
      distance =  5.2300000000 
      marker   = "D01G117"              # at  112.6200 cM
      distance =  2.1200000000 
      marker   = "D01G118"              # at  114.7400 cM
      distance =  0.1300000000 
      marker   = "D01G119"              # at  114.8700 cM
      distance =  0.1400000000 
      marker   = "D01G120"              # at  115.0100 cM
      distance =  1.3300000000 
      marker   = "D01G121"              # at  116.3400 cM
      distance =  0.3400000000 
      marker   = "D01G122"              # at  116.6800 cM
      distance =  0.9800000000 
      marker   = "D01G123"              # at  117.6600 cM
      distance =  0.8200000000 
      marker   = "D01G124"              # at  118.4800 cM
      distance =  0.6800000000 
      marker   = "D01G125"              # at  119.1600 cM
      distance =  0.3900000000 
      marker   = "D01G126"              # at  119.5500 cM
      distance =  0.0000000001 
      marker   = "D01G127"              # at  119.5500 cM
      distance =  0.7200000000 
      marker   = "D01G128"              # at  120.2700 cM
      distance =  0.3200000000 
      marker   = "D01G129"              # at  120.5900 cM
      distance =  0.9400000000 
      marker   = "D01G130"              # at  121.5300 cM
      distance =  1.4800000000 
      marker   = "D01G131"              # at  123.0100 cM
      distance =  0.3800000000 
      marker   = "D01G132"              # at  123.3900 cM
      distance =  3.0600000000 
      marker   = "D01G133"              # at  126.4500 cM
      distance =  0.3800000000 
      marker   = "D01G134"              # at  126.8300 cM
      distance =  0.7100000000 
      marker   = "D01G135"              # at  127.5400 cM
      distance =  2.4200000000 
      marker   = "D01G136"              # at  129.9600 cM
      distance =  1.4000000000 
      marker   = "D01G137"              # at  131.3600 cM
      distance =  3.7200000000 
      marker   = "D01G138"              # at  135.0800 cM
      distance =  0.5100000000 
      marker   = "D01G139"              # at  135.5900 cM
      distance =  0.2200000000 
      marker   = "D01G140"              # at  135.8100 cM
      distance =  5.0300000000 
      marker   = "D01G141"              # at  140.8400 cM
      distance =  1.1000000000 
      marker   = "D01G142"              # at  141.9400 cM
      distance =  0.1400000000 
      marker   = "D01G143"              # at  142.0800 cM
      distance =  2.3400000000 
      marker   = "D01G144"              # at  144.4200 cM
      distance =  0.7000000000 
      marker   = "D01G145"              # at  145.1200 cM
      distance =  1.4500000000 
      marker   = "D01G146"              # at  146.5700 cM
      distance =  1.2600000000 
      marker   = "D01G147"              # at  147.8300 cM
      distance =  0.8000000000 
      marker   = "D01G148"              # at  148.6300 cM
      distance =  0.2200000000 
      marker   = "D01G149"              # at  148.8500 cM
      distance =  0.3500000000 
      marker   = "D01G150"              # at  149.2000 cM
      distance =  1.0800000000 
      marker   = "D01G151"              # at  150.2800 cM
      distance =  0.0200000000 
      marker   = "D01G152"              # at  150.3000 cM
      distance =  0.5100000000 
      marker   = "D01G153"              # at  150.8100 cM
      distance =  0.6900000000 
      marker   = "D01G154"              # at  151.5000 cM
      distance =  0.1400000000 
      marker   = "D01G155"              # at  151.6400 cM
      distance =  0.5100000000 
      marker   = "D01G156"              # at  152.1500 cM
      distance =  0.2100000000 
      marker   = "D01G157"              # at  152.3600 cM
      distance =  0.5300000000 
      marker   = "D01G158"              # at  152.8900 cM
      distance =  0.0200000000 
      marker   = "D01G159"              # at  152.9100 cM
      distance =  2.0700000000 
      marker   = "D01G160"              # at  154.9800 cM
      distance =  1.9500000000 
      marker   = "D01G161"              # at  156.9300 cM
      distance =  0.6200000000 
      marker   = "D01G162"              # at  157.5500 cM
      distance =  0.0500000000 
      marker   = "D01G163"              # at  157.6000 cM
      distance =  0.9800000000 
      marker   = "D01G164"              # at  158.5800 cM
      distance =  0.9600000000 
      marker   = "D01G165"              # at  159.5400 cM
      distance =  0.4100000000 
      marker   = "D01G166"              # at  159.9500 cM
      distance =  0.0600000000 
      marker   = "D01G167"              # at  160.0100 cM
      distance =  0.6800000000 
      marker   = "D01G168"              # at  160.6900 cM
      distance =  0.0900000000 
      marker   = "D01G169"              # at  160.7800 cM
      distance =  1.8100000000 
      marker   = "D01G170"              # at  162.5900 cM
      distance =  0.5700000000 
      marker   = "D01G171"              # at  163.1600 cM
      distance =  0.4000000000 
      marker   = "D01G172"              # at  163.5600 cM
      distance =  7.9200000000 
      marker   = "D01G173"              # at  171.4800 cM
      distance =  2.9600000000 
      marker   = "D01G174"              # at  174.4400 cM
      distance =  0.4200000000 
      marker   = "D01G175"              # at  174.8600 cM
      distance =  1.0600000000 
      marker   = "D01G176"              # at  175.9200 cM
      distance =  1.2900000000 
      marker   = "D01G177"              # at  177.2100 cM
      distance =  0.9500000000 
      marker   = "D01G178"              # at  178.1600 cM
      distance =  1.2800000000 
      marker   = "D01G179"              # at  179.4400 cM
      distance =  0.7600000000 
      marker   = "D01G180"              # at  180.2000 cM
      distance =  0.4900000000 
      marker   = "D01G181"              # at  180.6900 cM
      distance =  0.3600000000 
      marker   = "D01G182"              # at  181.0500 cM
      distance =  1.5200000000 
      marker   = "D01G183"              # at  182.5700 cM
      distance =  0.3200000000 
      marker   = "D01G184"              # at  182.8900 cM
      distance =  0.0800000000 
      marker   = "D01G185"              # at  182.9700 cM
      distance =  3.7500000000 
      marker   = "D01G186"              # at  186.7200 cM
      distance =  0.7500000000 
      marker   = "D01G187"              # at  187.4700 cM
      distance =  2.0500000000 
      marker   = "D01G188"              # at  189.5200 cM
      distance =  0.8600000000 
      marker   = "D01G189"              # at  190.3800 cM
      distance =  1.4800000000 
      marker   = "D01G190"              # at  191.8600 cM
      distance =  1.2400000000 
      marker   = "D01G191"              # at  193.1000 cM
      distance =  4.4100000000 
      marker   = "D01G192"              # at  197.5100 cM
      distance =  0.5000000000 
      marker   = "D01G193"              # at  198.0100 cM
      distance =  0.7100000000 
      marker   = "D01G194"              # at  198.7200 cM
      distance =  0.4400000000 
      marker   = "D01G195"              # at  199.1600 cM
      distance =  0.6000000000 
      marker   = "D01G196"              # at  199.7600 cM
      distance =  0.4900000000 
      marker   = "D01G197"              # at  200.2500 cM
      distance =  0.2900000000 
      marker   = "D01G198"              # at  200.5400 cM
      distance =  0.7800000000 
      marker   = "D01G199"              # at  201.3200 cM
      distance =  0.1800000000 
      marker   = "D01G200"              # at  201.5000 cM
      distance =  1.6600000000 
      marker   = "D01G201"              # at  203.1600 cM
      distance =  0.3200000000 
      marker   = "D01G202"              # at  203.4800 cM
      distance =  0.3600000000 
      marker   = "D01G203"              # at  203.8400 cM
      distance =  0.8000000000 
      marker   = "D01G204"              # at  204.6400 cM
      distance =  0.5100000000 
      marker   = "D01G205"              # at  205.1500 cM
      distance =  1.7400000000 
      marker   = "D01G206"              # at  206.8900 cM
      distance =  2.3800000000 
      marker   = "D01G207"              # at  209.2700 cM
      distance =  0.7800000000 
      marker   = "D01G208"              # at  210.0500 cM
      distance =  0.8500000000 
      marker   = "D01G209"              # at  210.9000 cM
      distance =  0.1500000000 
      marker   = "D01G210"              # at  211.0500 cM
      distance =  0.1300000000 
      marker   = "D01G211"              # at  211.1800 cM
      distance =  0.6100000000 
      marker   = "D01G212"              # at  211.7900 cM
      distance =  2.1100000000 
      marker   = "D01G213"              # at  213.9000 cM
      distance =  0.3600000000 
      marker   = "D01G214"              # at  214.2600 cM
      distance =  0.0500000000 
      marker   = "D01G215"              # at  214.3100 cM
      distance =  0.9400000000 
      marker   = "D01G216"              # at  215.2500 cM
      distance =  1.7900000000 
      marker   = "D01G217"              # at  217.0400 cM
      distance =  0.7200000000 
      marker   = "D01G218"              # at  217.7600 cM
      distance =  1.1900000000 
      marker   = "D01G219"              # at  218.9500 cM
      distance =  1.1300000000 
      marker   = "D01G220"              # at  220.0800 cM
      distance =  1.7900000000 
   }

   region = Region_chr02 {
      marker   = "D02G002"              # at    0.0000 cM
      distance =  5.1600000000 
      marker   = "D02G003"              # at    5.1600 cM
      distance =  4.8400000000 
      marker   = "D02G004"              # at   10.0000 cM
      distance =  0.1200000000 
      marker   = "D02G005"              # at   10.1200 cM
      distance =  1.0900000000 
      marker   = "D02G006"              # at   11.2100 cM
      distance =  0.5000000000 
      marker   = "D02G007"              # at   11.7100 cM
      distance =  0.3000000000 
      marker   = "D02G008"              # at   12.0100 cM
      distance =  0.3500000000 
      marker   = "D02G009"              # at   12.3600 cM
      distance =  0.0600000000 
      marker   = "D02G010"              # at   12.4200 cM
      distance =  0.9900000000 
      marker   = "D02G011"              # at   13.4100 cM
      distance =  0.0100000000 
      marker   = "D02G012"              # at   13.4200 cM
      distance =  2.0100000000 
      marker   = "D02G013"              # at   15.4300 cM
      distance =  2.4800000000 
      marker   = "D02G014"              # at   17.9100 cM
      distance =  0.2400000000 
      marker   = "D02G015"              # at   18.1500 cM
      distance =  0.2100000000 
      marker   = "D02G016"              # at   18.3600 cM
      distance =  1.4000000000 
      marker   = "D02G017"              # at   19.7600 cM
      distance =  0.1200000000 
      marker   = "D02G018"              # at   19.8800 cM
      distance =  0.0500000000 
      marker   = "D02G019"              # at   19.9300 cM
      distance =  1.1900000000 
      marker   = "D02G020"              # at   21.1200 cM
      distance =  2.0000000000 
      marker   = "D02G021"              # at   23.1200 cM
      distance =  1.2100000000 
      marker   = "D02G022"              # at   24.3300 cM
      distance =  0.7800000000 
      marker   = "D02G023"              # at   25.1100 cM
      distance =  0.3600000000 
      marker   = "D02G024"              # at   25.4700 cM
      distance =  0.2200000000 
      marker   = "D02G025"              # at   25.6900 cM
      distance =  1.3600000000 
      marker   = "D02G026"              # at   27.0500 cM
      distance =  1.4000000000 
      marker   = "D02G027"              # at   28.4500 cM
      distance =  0.0800000000 
      marker   = "D02G028"              # at   28.5300 cM
      distance =  0.1300000000 
      marker   = "D02G029"              # at   28.6600 cM
      distance =  1.6900000000 
      marker   = "D02G030"              # at   30.3500 cM
      distance =  0.2200000000 
      marker   = "D02G031"              # at   30.5700 cM
      distance =  0.2700000000 
      marker   = "D02G032"              # at   30.8400 cM
      distance =  0.3400000000 
      marker   = "D02G033"              # at   31.1800 cM
      distance =  0.2900000000 
      marker   = "D02G034"              # at   31.4700 cM
      distance =  0.9200000000 
      marker   = "D02G035"              # at   32.3900 cM
      distance =  0.0900000000 
      marker   = "D02G036"              # at   32.4800 cM
      distance =  0.4700000000 
      marker   = "D02G037"              # at   32.9500 cM
      distance =  2.7400000000 
      marker   = "D02G038"              # at   35.6900 cM
      distance =  0.4700000000 
      marker   = "D02G039"              # at   36.1600 cM
      distance =  0.4100000000 
      marker   = "D02G040"              # at   36.5700 cM
      distance =  0.2400000000 
      marker   = "D02G041"              # at   36.8100 cM
      distance =  0.2600000000 
      marker   = "D02G042"              # at   37.0700 cM
      distance =  0.3400000000 
      marker   = "D02G043"              # at   37.4100 cM
      distance =  0.0000000001 
      marker   = "D02G044"              # at   37.4100 cM
      distance =  1.9300000000 
      marker   = "D02G045"              # at   39.3400 cM
      distance =  0.3100000000 
      marker   = "D02G046"              # at   39.6500 cM
      distance =  1.1400000000 
      marker   = "D02G047"              # at   40.7900 cM
      distance =  0.4500000000 
      marker   = "D02G048"              # at   41.2400 cM
      distance =  1.1400000000 
      marker   = "D02G049"              # at   42.3800 cM
      distance =  0.4000000000 
      marker   = "D02G050"              # at   42.7800 cM
      distance =  3.1900000000 
      marker   = "D02G051"              # at   45.9700 cM
      distance =  0.0600000000 
      marker   = "D02G052"              # at   46.0300 cM
      distance =  0.0400000000 
      marker   = "D02G053"              # at   46.0700 cM
      distance =  1.0700000000 
      marker   = "D02G054"              # at   47.1400 cM
      distance =  0.4600000000 
      marker   = "D02G055"              # at   47.6000 cM
      distance =  0.8000000000 
      marker   = "D02G056"              # at   48.4000 cM
      distance =  0.5500000000 
      marker   = "D02G057"              # at   48.9500 cM
      distance =  0.6800000000 
      marker   = "D02G058"              # at   49.6300 cM
      distance =  1.0700000000 
      marker   = "D02G059"              # at   50.7000 cM
      distance =  0.2700000000 
      marker   = "D02G060"              # at   50.9700 cM
      distance =  0.8900000000 
      marker   = "D02G061"              # at   51.8600 cM
      distance =  0.8500000000 
      marker   = "D02G062"              # at   52.7100 cM
      distance =  0.0500000000 
      marker   = "D02G063"              # at   52.7600 cM
      distance =  0.2900000000 
      marker   = "D02G064"              # at   53.0500 cM
      distance =  0.8000000000 
      marker   = "D02G065"              # at   53.8500 cM
      distance =  2.4300000000 
      marker   = "D02G066"              # at   56.2800 cM
      distance =  0.3400000000 
      marker   = "D02G067"              # at   56.6200 cM
      distance =  0.5200000000 
      marker   = "D02G068"              # at   57.1400 cM
      distance =  0.6400000000 
      marker   = "D02G069"              # at   57.7800 cM
      distance =  0.5600000000 
      marker   = "D02G070"              # at   58.3400 cM
      distance =  0.5200000000 
      marker   = "D02G071"              # at   58.8600 cM
      distance =  0.5200000000 
      marker   = "D02G072"              # at   59.3800 cM
      distance =  0.7500000000 
      marker   = "D02G073"              # at   60.1300 cM
      distance =  2.6400000000 
      marker   = "D02G074"              # at   62.7700 cM
      distance =  1.0200000000 
      marker   = "D02G075"              # at   63.7900 cM
      distance =  0.5000000000 
      marker   = "D02G076"              # at   64.2900 cM
      distance =  2.7000000000 
      marker   = "D02G077"              # at   66.9900 cM
      distance =  2.0100000000 
      marker   = "D02G078"              # at   69.0000 cM
      distance =  0.0400000000 
      marker   = "D02G079"              # at   69.0400 cM
      distance =  2.5500000000 
      marker   = "D02G080"              # at   71.5900 cM
      distance =  0.5300000000 
      marker   = "D02G081"              # at   72.1200 cM
      distance =  1.3100000000 
      marker   = "D02G082"              # at   73.4300 cM
      distance =  0.9900000000 
      marker   = "D02G083"              # at   74.4200 cM
      distance =  1.7600000000 
      marker   = "D02G084"              # at   76.1800 cM
      distance =  0.6100000000 
      marker   = "D02G085"              # at   76.7900 cM
      distance =  0.0400000000 
      marker   = "D02G086"              # at   76.8300 cM
      distance =  0.8000000000 
      marker   = "D02G087"              # at   77.6300 cM
      distance =  2.2700000000 
      marker   = "D02G088"              # at   79.9000 cM
      distance =  0.9400000000 
      marker   = "D02G089"              # at   80.8400 cM
      distance =  0.5300000000 
      marker   = "D02G090"              # at   81.3700 cM
      distance =  0.2000000000 
      marker   = "D02G091"              # at   81.5700 cM
      distance =  0.7500000000 
      marker   = "D02G092"              # at   82.3200 cM
      distance =  3.5200000000 
      marker   = "D02G093"              # at   85.8400 cM
      distance =  1.7300000000 
      marker   = "D02G094"              # at   87.5700 cM
      distance =  0.3600000000 
      marker   = "D02G095"              # at   87.9300 cM
      distance =  0.5000000000 
      marker   = "D02G096"              # at   88.4300 cM
      distance =  0.1000000000 
      marker   = "D02G097"              # at   88.5300 cM
      distance =  2.1400000000 
      marker   = "D02G098"              # at   90.6700 cM
      distance =  0.2100000000 
      marker   = "D02G099"              # at   90.8800 cM
      distance =  1.7500000000 
      marker   = "D02G100"              # at   92.6300 cM
      distance =  0.0600000000 
      marker   = "D02G101"              # at   92.6900 cM
      distance =  1.8200000000 
      marker   = "D02G102"              # at   94.5100 cM
      distance =  1.0400000000 
      marker   = "D02G103"              # at   95.5500 cM
      distance =  0.0200000000 
      marker   = "D02G104"              # at   95.5700 cM
      distance =  3.8600000000 
      marker   = "D02G105"              # at   99.4300 cM
      distance =  0.4800000000 
      marker   = "D02G106"              # at   99.9100 cM
      distance =  0.8700000000 
      marker   = "D02G107"              # at  100.7800 cM
      distance =  0.8500000000 
      marker   = "D02G108"              # at  101.6300 cM
      distance =  0.1100000000 
      marker   = "D02G109"              # at  101.7400 cM
      distance =  0.4600000000 
      marker   = "D02G110"              # at  102.2000 cM
      distance =  0.3700000000 
      marker   = "D02G111"              # at  102.5700 cM
      distance =  1.6300000000 
      marker   = "D02G112"              # at  104.2000 cM
      distance =  2.2600000000 
      marker   = "D02G113"              # at  106.4600 cM
      distance =  1.8900000000 
      marker   = "D02G114"              # at  108.3500 cM
      distance =  0.7300000000 
      marker   = "D02G115"              # at  109.0800 cM
      distance =  0.5100000000 
      marker   = "D02G116"              # at  109.5900 cM
      distance =  0.3000000000 
      marker   = "D02G117"              # at  109.8900 cM
      distance =  0.8900000000 
      marker   = "D02G118"              # at  110.7800 cM
      distance =  0.0700000000 
      marker   = "D02G119"              # at  110.8500 cM
      distance =  0.5600000000 
      marker   = "D02G120"              # at  111.4100 cM
      distance =  0.6900000000 
      marker   = "D02G121"              # at  112.1000 cM
      distance =  0.6900000000 
      marker   = "D02G122"              # at  112.7900 cM
      distance =  2.0300000000 
      marker   = "D02G123"              # at  114.8200 cM
      distance =  0.2900000000 
      marker   = "D02G124"              # at  115.1100 cM
      distance =  0.8100000000 
      marker   = "D02G125"              # at  115.9200 cM
      distance =  2.4100000000 
      marker   = "D02G126"              # at  118.3300 cM
      distance =  2.7100000000 
      marker   = "D02G127"              # at  121.0400 cM
      distance =  0.6700000000 
      marker   = "D02G128"              # at  121.7100 cM
      distance =  2.9100000000 
      marker   = "D02G129"              # at  124.6200 cM
      distance =  0.1500000000 
      marker   = "D02G130"              # at  124.7700 cM
      distance =  0.7400000000 
      marker   = "D02G131"              # at  125.5100 cM
      distance =  0.1300000000 
      marker   = "D02G132"              # at  125.6400 cM
      distance =  1.9100000000 
      marker   = "D02G133"              # at  127.5500 cM
      distance =  0.9700000000 
      marker   = "D02G134"              # at  128.5200 cM
      distance =  0.1200000000 
      marker   = "D02G135"              # at  128.6400 cM
      distance =  0.2000000000 
      marker   = "D02G136"              # at  128.8400 cM
      distance =  1.7900000000 
      marker   = "D02G137"              # at  130.6300 cM
      distance =  1.2200000000 
      marker   = "D02G138"              # at  131.8500 cM
      distance =  0.5200000000 
      marker   = "D02G139"              # at  132.3700 cM
      distance =  0.2700000000 
      marker   = "D02G140"              # at  132.6400 cM
      distance =  2.4300000000 
      marker   = "D02G141"              # at  135.0700 cM
      distance =  3.1600000000 
      marker   = "D02G142"              # at  138.2300 cM
      distance =  0.1200000000 
      marker   = "D02G143"              # at  138.3500 cM
      distance =  0.3000000000 
      marker   = "D02G144"              # at  138.6500 cM
      distance =  1.1300000000 
      marker   = "D02G145"              # at  139.7800 cM
      distance =  1.3900000000 
      marker   = "D02G146"              # at  141.1700 cM
      distance =  3.0600000000 
      marker   = "D02G147"              # at  144.2300 cM
      distance =  0.2400000000 
      marker   = "D02G148"              # at  144.4700 cM
      distance =  3.1600000000 
      marker   = "D02G149"              # at  147.6300 cM
      distance =  1.0900000000 
      marker   = "D02G150"              # at  148.7200 cM
      distance =  0.1400000000 
      marker   = "D02G151"              # at  148.8600 cM
      distance =  0.4600000000 
      marker   = "D02G152"              # at  149.3200 cM
      distance =  2.4500000000 
      marker   = "D02G153"              # at  151.7700 cM
      distance =  0.7300000000 
      marker   = "D02G154"              # at  152.5000 cM
      distance =  0.1300000000 
      marker   = "D02G155"              # at  152.6300 cM
      distance =  0.3000000000 
      marker   = "D02G156"              # at  152.9300 cM
      distance =  0.1700000000 
      marker   = "D02G157"              # at  153.1000 cM
      distance =  1.2800000000 
      marker   = "D02G158"              # at  154.3800 cM
      distance =  1.3700000000 
      marker   = "D02G159"              # at  155.7500 cM
      distance =  1.2500000000 
      marker   = "D02G160"              # at  157.0000 cM
      distance =  0.1900000000 
      marker   = "D02G161"              # at  157.1900 cM
      distance =  0.9700000000 
      marker   = "D02G162"              # at  158.1600 cM
      distance =  1.1000000000 
      marker   = "D02G163"              # at  159.2600 cM
      distance =  0.9500000000 
      marker   = "D02G164"              # at  160.2100 cM
      distance =  0.3600000000 
      marker   = "D02G165"              # at  160.5700 cM
      distance =  2.1400000000 
      marker   = "D02G166"              # at  162.7100 cM
      distance =  7.5800000000 
      marker   = "D02G167"              # at  170.2900 cM
      distance =  0.5200000000 
      marker   = "D02G168"              # at  170.8100 cM
      distance =  0.7700000000 
      marker   = "D02G169"              # at  171.5800 cM
      distance =  0.2100000000 
      marker   = "D02G170"              # at  171.7900 cM
      distance =  0.6700000000 
      marker   = "D02G171"              # at  172.4600 cM
      distance =  1.8600000000 
      marker   = "D02G172"              # at  174.3200 cM
      distance =  0.7900000000 
      marker   = "D02G173"              # at  175.1100 cM
      distance =  0.7500000000 
      marker   = "D02G174"              # at  175.8600 cM
      distance =  1.3500000000 
      marker   = "D02G175"              # at  177.2100 cM
      distance =  1.1700000000 
      marker   = "D02G176"              # at  178.3800 cM
      distance =  0.2800000000 
      marker   = "D02G177"              # at  178.6600 cM
      distance =  0.4200000000 
      marker   = "D02G178"              # at  179.0800 cM
      distance =  0.0400000000 
      marker   = "D02G179"              # at  179.1200 cM
      distance =  1.6200000000 
      marker   = "D02G180"              # at  180.7400 cM
      distance =  2.9100000000 
      marker   = "D02G181"              # at  183.6500 cM
      distance =  0.4200000000 
      marker   = "D02G182"              # at  184.0700 cM
      distance =  0.9700000000 
      marker   = "D02G183"              # at  185.0400 cM
      distance =  0.3500000000 
      marker   = "D02G184"              # at  185.3900 cM
      distance =  0.1900000000 
      marker   = "D02G185"              # at  185.5800 cM
      distance =  1.0200000000 
      marker   = "D02G186"              # at  186.6000 cM
      distance =  0.5700000000 
      marker   = "D02G187"              # at  187.1700 cM
      distance =  1.3300000000 
      marker   = "D02G188"              # at  188.5000 cM
      distance =  1.6000000000 
      marker   = "D02G189"              # at  190.1000 cM
      distance =  0.4300000000 
      marker   = "D02G190"              # at  190.5300 cM
      distance =  0.0200000000 
      marker   = "D02G191"              # at  190.5500 cM
      distance =  0.2000000000 
      marker   = "D02G192"              # at  190.7500 cM
      distance =  0.1900000000 
      marker   = "D02G193"              # at  190.9400 cM
      distance =  0.1700000000 
      marker   = "D02G194"              # at  191.1100 cM
      distance =  1.2700000000 
      marker   = "D02G195"              # at  192.3800 cM
      distance =  1.4000000000 
   }

   region = Region_chr09 {
      marker   = "D09G002"              # at    0.0000 cM
      distance =  0.6300000000 
      marker   = "D09G003"              # at    0.6300 cM
      distance =  3.2700000000 
      marker   = "D09G004"              # at    3.9000 cM
      distance =  0.0700000000 
      marker   = "D09G005"              # at    3.9700 cM
      distance =  0.9000000000 
      marker   = "D09G006"              # at    4.8700 cM
      distance =  1.1400000000 
      marker   = "D09G007"              # at    6.0100 cM
      distance =  0.0600000000 
      marker   = "D09G008"              # at    6.0700 cM
      distance =  1.7100000000 
      marker   = "D09G009"              # at    7.7800 cM
      distance =  0.1700000000 
      marker   = "D09G010"              # at    7.9500 cM
      distance =  0.2100000000 
      marker   = "D09G011"              # at    8.1600 cM
      distance =  0.4600000000 
      marker   = "D09G012"              # at    8.6200 cM
      distance =  0.2100000000 
      marker   = "D09G013"              # at    8.8300 cM
      distance =  0.0500000000 
      marker   = "D09G014"              # at    8.8800 cM
      distance =  3.6100000000 
      marker   = "D09G015"              # at   12.4900 cM
      distance =  0.4400000000 
      marker   = "D09G016"              # at   12.9300 cM
      distance =  4.1500000000 
      marker   = "D09G017"              # at   17.0800 cM
      distance =  2.3400000000 
      marker   = "D09G018"              # at   19.4200 cM
      distance =  4.5400000000 
      marker   = "D09G019"              # at   23.9600 cM
      distance =  1.7800000000 
      marker   = "D09G020"              # at   25.7400 cM
      distance =  0.5700000000 
      marker   = "D09G021"              # at   26.3100 cM
      distance =  0.3300000000 
      marker   = "D09G022"              # at   26.6400 cM
      distance =  0.5900000000 
      marker   = "D09G023"              # at   27.2300 cM
      distance =  0.3300000000 
      marker   = "D09G024"              # at   27.5600 cM
      distance =  1.6800000000 
      marker   = "D09G025"              # at   29.2400 cM
      distance =  1.5700000000 
      marker   = "D09G026"              # at   30.8100 cM
      distance =  4.4700000000 
      marker   = "D09G027"              # at   35.2800 cM
      distance =  1.0900000000 
      marker   = "D09G028"              # at   36.3700 cM
      distance =  1.5200000000 
      marker   = "D09G029"              # at   37.8900 cM
      distance =  2.6000000000 
      marker   = "D09G030"              # at   40.4900 cM
      distance =  0.1000000000 
      marker   = "D09G031"              # at   40.5900 cM
      distance =  0.8400000000 
      marker   = "D09G032"              # at   41.4300 cM
      distance =  0.5700000000 
      marker   = "D09G033"              # at   42.0000 cM
      distance =  0.6700000000 
      marker   = "D09G034"              # at   42.6700 cM
      distance =  0.0500000000 
      marker   = "D09G035"              # at   42.7200 cM
      distance =  0.0200000000 
      marker   = "D09G036"              # at   42.7400 cM
      distance =  3.5900000000 
      marker   = "D09G037"              # at   46.3300 cM
      distance =  3.4900000000 
      marker   = "D09G038"              # at   49.8200 cM
      distance =  0.3700000000 
      marker   = "D09G039"              # at   50.1900 cM
      distance =  0.3800000000 
      marker   = "D09G040"              # at   50.5700 cM
      distance =  0.1000000000 
      marker   = "D09G041"              # at   50.6700 cM
      distance =  1.8600000000 
      marker   = "D09G042"              # at   52.5300 cM
      distance =  0.3100000000 
      marker   = "D09G043"              # at   52.8400 cM
      distance =  0.5500000000 
      marker   = "D09G044"              # at   53.3900 cM
      distance =  0.0300000000 
      marker   = "D09G045"              # at   53.4200 cM
      distance =  0.0700000000 
      marker   = "D09G046"              # at   53.4900 cM
      distance =  0.8400000000 
      marker   = "D09G047"              # at   54.3300 cM
      distance =  0.4200000000 
      marker   = "D09G048"              # at   54.7500 cM
      distance =  0.1400000000 
      marker   = "D09G049"              # at   54.8900 cM
      distance =  0.4500000000 
      marker   = "D09G050"              # at   55.3400 cM
      distance =  1.7700000000 
      marker   = "D09G051"              # at   57.1100 cM
      distance =  0.1400000000 
      marker   = "D09G052"              # at   57.2500 cM
      distance =  0.9900000000 
      marker   = "D09G053"              # at   58.2400 cM
      distance =  0.1400000000 
      marker   = "D09G054"              # at   58.3800 cM
      distance =  0.1100000000 
      marker   = "D09G055"              # at   58.4900 cM
      distance =  0.4500000000 
      marker   = "D09G056"              # at   58.9400 cM
      distance =  0.3400000000 
      marker   = "D09G057"              # at   59.2800 cM
      distance =  0.8400000000 
      marker   = "D09G058"              # at   60.1200 cM
      distance =  0.9000000000 
      marker   = "D09G059"              # at   61.0200 cM
      distance =  1.2700000000 
      marker   = "D09G060"              # at   62.2900 cM
      distance =  0.7800000000 
      marker   = "D09G061"              # at   63.0700 cM
      distance =  1.6800000000 
      marker   = "D09G062"              # at   64.7500 cM
      distance =  0.2500000000 
      marker   = "D09G063"              # at   65.0000 cM
      distance =  0.7400000000 
      marker   = "D09G064"              # at   65.7400 cM
      distance =  0.5800000000 
      marker   = "D09G065"              # at   66.3200 cM
      distance =  2.6600000000 
      marker   = "D09G066"              # at   68.9800 cM
      distance =  0.1700000000 
      marker   = "D09G067"              # at   69.1500 cM
      distance =  0.3000000000 
      marker   = "D09G068"              # at   69.4500 cM
      distance =  0.9600000000 
      marker   = "D09G069"              # at   70.4100 cM
      distance =  1.8000000000 
      marker   = "D09G070"              # at   72.2100 cM
      distance =  0.2800000000 
      marker   = "D09G071"              # at   72.4900 cM
      distance =  1.0000000000 
      marker   = "D09G072"              # at   73.4900 cM
      distance =  0.6100000000 
      marker   = "D09G073"              # at   74.1000 cM
      distance =  0.3600000000 
      marker   = "D09G074"              # at   74.4600 cM
      distance =  0.2100000000 
      marker   = "D09G075"              # at   74.6700 cM
      distance =  0.4600000000 
      marker   = "D09G076"              # at   75.1300 cM
      distance =  0.8100000000 
      marker   = "D09G077"              # at   75.9400 cM
      distance =  0.2900000000 
      marker   = "D09G078"              # at   76.2300 cM
      distance =  0.0800000000 
      marker   = "D09G079"              # at   76.3100 cM
      distance =  4.5700000000 
      marker   = "D09G080"              # at   80.8800 cM
      distance =  0.8700000000 
      marker   = "D09G081"              # at   81.7500 cM
      distance =  3.0000000000 
      marker   = "D09G082"              # at   84.7500 cM
      distance =  0.0500000000 
      marker   = "D09G083"              # at   84.8000 cM
      distance =  0.6400000000 
      marker   = "D09G084"              # at   85.4400 cM
      distance =  1.6400000000 
      marker   = "D09G085"              # at   87.0800 cM
      distance =  1.5600000000 
      marker   = "D09G086"              # at   88.6400 cM
      distance =  0.7300000000 
      marker   = "D09G087"              # at   89.3700 cM
      distance =  0.9100000000 
      marker   = "D09G088"              # at   90.2800 cM
      distance =  0.4300000000 
      marker   = "D09G089"              # at   90.7100 cM
      distance =  0.9200000000 
      marker   = "D09G090"              # at   91.6300 cM
      distance =  1.2000000000 
      marker   = "D09G091"              # at   92.8300 cM
      distance =  0.1200000000 
      marker   = "D09G092"              # at   92.9500 cM
      distance =  1.3800000000 
      marker   = "D09G093"              # at   94.3300 cM
      distance =  0.0900000000 
      marker   = "D09G094"              # at   94.4200 cM
      distance =  0.5200000000 
      marker   = "D09G095"              # at   94.9400 cM
      distance =  0.2300000000 
      marker   = "D09G096"              # at   95.1700 cM
      distance =  0.3700000000 
      marker   = "D09G097"              # at   95.5400 cM
      distance =  0.6800000000 
      marker   = "D09G098"              # at   96.2200 cM
      distance =  0.2000000000 
      marker   = "D09G099"              # at   96.4200 cM
      distance =  0.3400000000 
      marker   = "D09G100"              # at   96.7600 cM
      distance =  0.1200000000 
      marker   = "D09G101"              # at   96.8800 cM
      distance =  0.3500000000 
      marker   = "D09G102"              # at   97.2300 cM
      distance =  0.3400000000 
      marker   = "D09G103"              # at   97.5700 cM
      distance =  4.2600000000 
      marker   = "D09G104"              # at  101.8300 cM
      distance =  0.1800000000 
      marker   = "D09G105"              # at  102.0100 cM
      distance =  1.2900000000 
      marker   = "D09G106"              # at  103.3000 cM
      distance =  0.1000000000 
      marker   = "D09G107"              # at  103.4000 cM
      distance =  0.8500000000 
      marker   = "D09G108"              # at  104.2500 cM
      distance =  0.1100000000 
      marker   = "D09G109"              # at  104.3600 cM
      distance =  1.0500000000 
      marker   = "D09G110"              # at  105.4100 cM
      distance =  1.1600000000 
      marker   = "D09G111"              # at  106.5700 cM
      distance =  0.8200000000 
      marker   = "D09G112"              # at  107.3900 cM
      distance =  1.3800000000 
      marker   = "D09G113"              # at  108.7700 cM
      distance =  1.0900000000 
      marker   = "D09G114"              # at  109.8600 cM
      distance =  0.0400000000 
      marker   = "D09G115"              # at  109.9000 cM
      distance =  1.1900000000 
      marker   = "D09G116"              # at  111.0900 cM
      distance =  1.0700000000 
      marker   = "D09G117"              # at  112.1600 cM
      distance =  0.3900000000 
      marker   = "D09G118"              # at  112.5500 cM
      distance =  1.3500000000 
      marker   = "D09G119"              # at  113.9000 cM
      distance =  1.7300000000 
      marker   = "D09G120"              # at  115.6300 cM
      distance =  1.3800000000 
      marker   = "D09G121"              # at  117.0100 cM
      distance =  1.0400000000 
      marker   = "D09G122"              # at  118.0500 cM
      distance =  0.3900000000 
      marker   = "D09G123"              # at  118.4400 cM
      distance =  1.7500000000 
      marker   = "D09G124"              # at  120.1900 cM
      distance =  0.4800000000 
      marker   = "D09G125"              # at  120.6700 cM
      distance =  0.0400000000 
      marker   = "D09G126"              # at  120.7100 cM
      distance =  0.0400000000 
      marker   = "D09G127"              # at  120.7500 cM
      distance =  1.8300000000 
      marker   = "D09G128"              # at  122.5800 cM
      distance =  0.9000000000 
      marker   = "D09G129"              # at  123.4800 cM
      distance =  2.8200000000 
      marker   = "D09G130"              # at  126.3000 cM
      distance =  0.9800000000 
      marker   = "D09G131"              # at  127.2800 cM
      distance =  1.7400000000 
      marker   = "D09G132"              # at  129.0200 cM
      distance =  2.7800000000 
   }

   region = Region_chr17 {
      marker   = "D17G002"              # at    0.0000 cM
      distance =  5.4400000000 
      marker   = "D17G003"              # at    5.4400 cM
      distance =  0.1500000000 
      marker   = "D17G004"              # at    5.5900 cM
      distance =  3.4000000000 
      marker   = "D17G005"              # at    8.9900 cM
      distance =  0.6300000000 
      marker   = "D17G006"              # at    9.6200 cM
      distance =  0.4500000000 
      marker   = "D17G007"              # at   10.0700 cM
      distance =  0.1400000000 
      marker   = "D17G008"              # at   10.2100 cM
      distance =  0.8300000000 
      marker   = "D17G009"              # at   11.0400 cM
      distance =  0.1300000000 
      marker   = "D17G010"              # at   11.1700 cM
      distance =  1.0200000000 
      marker   = "D17G011"              # at   12.1900 cM
      distance =  0.1500000000 
      marker   = "D17G012"              # at   12.3400 cM
      distance =  0.3000000000 
      marker   = "D17G013"              # at   12.6400 cM
      distance =  1.0100000000 
      marker   = "D17G014"              # at   13.6500 cM
      distance =  0.1500000000 
      marker   = "D17G015"              # at   13.8000 cM
      distance =  0.2200000000 
      marker   = "D17G016"              # at   14.0200 cM
      distance =  0.4300000000 
      marker   = "D17G017"              # at   14.4500 cM
      distance =  3.9200000000 
      marker   = "D17G018"              # at   18.3700 cM
      distance =  3.2600000000 
      marker   = "D17G019"              # at   21.6300 cM
      distance =  0.3600000000 
      marker   = "D17G020"              # at   21.9900 cM
      distance =  0.0600000000 
      marker   = "D17G021"              # at   22.0500 cM
      distance =  0.1700000000 
      marker   = "D17G022"              # at   22.2200 cM
      distance =  0.8200000000 
      marker   = "D17G023"              # at   23.0400 cM
      distance =  2.9300000000 
      marker   = "D17G024"              # at   25.9700 cM
      distance =  1.9200000000 
      marker   = "D17G025"              # at   27.8900 cM
      distance =  0.2500000000 
      marker   = "D17G026"              # at   28.1400 cM
      distance =  0.7000000000 
      marker   = "D17G027"              # at   28.8400 cM
      distance =  0.5400000000 
      marker   = "D17G028"              # at   29.3800 cM
      distance =  1.1900000000 
      marker   = "D17G029"              # at   30.5700 cM
      distance =  0.0600000000 
      marker   = "D17G030"              # at   30.6300 cM
      distance =  1.4600000000 
      marker   = "D17G031"              # at   32.0900 cM
      distance =  0.8900000000 
      marker   = "D17G032"              # at   32.9800 cM
      distance =  1.7400000000 
      marker   = "D17G033"              # at   34.7200 cM
      distance =  0.5200000000 
      marker   = "D17G034"              # at   35.2400 cM
      distance =  0.2500000000 
      marker   = "D17G035"              # at   35.4900 cM
      distance =  0.5400000000 
      marker   = "D17G036"              # at   36.0300 cM
      distance =  2.1000000000 
      marker   = "D17G037"              # at   38.1300 cM
      distance =  0.5200000000 
      marker   = "D17G038"              # at   38.6500 cM
      distance =  0.1400000000 
      marker   = "D17G039"              # at   38.7900 cM
      distance =  1.2400000000 
      marker   = "D17G040"              # at   40.0300 cM
      distance =  0.1300000000 
      marker   = "D17G041"              # at   40.1600 cM
      distance =  0.4500000000 
      marker   = "D17G042"              # at   40.6100 cM
      distance =  0.3000000000 
      marker   = "D17G043"              # at   40.9100 cM
      distance =  0.0800000000 
      marker   = "D17G044"              # at   40.9900 cM
      distance =  2.0700000000 
      marker   = "D17G045"              # at   43.0600 cM
      distance =  1.0600000000 
      marker   = "D17G046"              # at   44.1200 cM
      distance =  1.9500000000 
      marker   = "D17G047"              # at   46.0700 cM
      distance =  1.7600000000 
      marker   = "D17G048"              # at   47.8300 cM
      distance =  0.7500000000 
      marker   = "D17G049"              # at   48.5800 cM
      distance =  0.0900000000 
      marker   = "D17G050"              # at   48.6700 cM
      distance =  0.6400000000 
      marker   = "D17G051"              # at   49.3100 cM
      distance =  3.1800000000 
      marker   = "D17G052"              # at   52.4900 cM
      distance =  0.1200000000 
      marker   = "D17G053"              # at   52.6100 cM
      distance =  0.6100000000 
      marker   = "D17G054"              # at   53.2200 cM
      distance =  0.7900000000 
      marker   = "D17G055"              # at   54.0100 cM
      distance =  0.4900000000 
      marker   = "D17G056"              # at   54.5000 cM
      distance =  0.5100000000 
      marker   = "D17G057"              # at   55.0100 cM
      distance =  0.1200000000 
      marker   = "D17G058"              # at   55.1300 cM
      distance =  4.2700000000 
      marker   = "D17G059"              # at   59.4000 cM
      distance =  0.3800000000 
      marker   = "D17G060"              # at   59.7800 cM
      distance =  0.1400000000 
      marker   = "D17G061"              # at   59.9200 cM
      distance =  0.3300000000 
      marker   = "D17G062"              # at   60.2500 cM
      distance =  3.0500000000 
      marker   = "D17G063"              # at   63.3000 cM
      distance =  2.4200000000 
      marker   = "D17G064"              # at   65.7200 cM
      distance =  0.6600000000 
      marker   = "D17G065"              # at   66.3800 cM
      distance =  0.6200000000 
      marker   = "D17G066"              # at   67.0000 cM
      distance =  0.8200000000 
      marker   = "D17G067"              # at   67.8200 cM
      distance =  0.0000000001 
      marker   = "D17G068"              # at   67.8200 cM
      distance =  0.1700000000 
      marker   = "D17G069"              # at   67.9900 cM
      distance =  0.4100000000 
      marker   = "D17G070"              # at   68.4000 cM
      distance =  1.6500000000 
      marker   = "D17G071"              # at   70.0500 cM
      distance =  2.1000000000 
      marker   = "D17G072"              # at   72.1500 cM
      distance =  1.0300000000 
      marker   = "D17G073"              # at   73.1800 cM
      distance =  1.6200000000 
      marker   = "D17G074"              # at   74.8000 cM
      distance =  1.5500000000 
      marker   = "D17G075"              # at   76.3500 cM
      distance =  1.0100000000 
      marker   = "D17G076"              # at   77.3600 cM
      distance =  1.4500000000 
      marker   = "D17G077"              # at   78.8100 cM
      distance =  1.8200000000 
      marker   = "D17G078"              # at   80.6300 cM
      distance =  0.8100000000 
      marker   = "D17G079"              # at   81.4400 cM
      distance =  0.9700000000 
      marker   = "D17G080"              # at   82.4100 cM
      distance =  0.1900000000 
      marker   = "D17G081"              # at   82.6000 cM
      distance =  0.4300000000 
      marker   = "D17G082"              # at   83.0300 cM
      distance =  0.7900000000 
      marker   = "D17G083"              # at   83.8200 cM
      distance =  0.2100000000 
      marker   = "D17G084"              # at   84.0300 cM
      distance =  0.8400000000 
      marker   = "D17G085"              # at   84.8700 cM
      distance =  0.4300000000 
      marker   = "D17G086"              # at   85.3000 cM
      distance =  0.1300000000 
      marker   = "D17G087"              # at   85.4300 cM
      distance =  0.6700000000 
      marker   = "D17G088"              # at   86.1000 cM
      distance =  0.7100000000 
      marker   = "D17G089"              # at   86.8100 cM
      distance =  1.4200000000 
      marker   = "D17G090"              # at   88.2300 cM
      distance =  0.6100000000 
      marker   = "D17G091"              # at   88.8400 cM
      distance =  0.6700000000 
      marker   = "D17G092"              # at   89.5100 cM
      distance =  0.0100000000 
      marker   = "D17G093"              # at   89.5200 cM
      distance =  0.3400000000 
      marker   = "D17G094"              # at   89.8600 cM
      distance =  0.4700000000 
      marker   = "D17G095"              # at   90.3300 cM
      distance =  1.6400000000 
      marker   = "D17G096"              # at   91.9700 cM
      distance =  3.5400000000 
      marker   = "D17G097"              # at   95.5100 cM
      distance =  0.3900000000 
      marker   = "D17G098"              # at   95.9000 cM
      distance =  1.6600000000 
      marker   = "D17G099"              # at   97.5600 cM
      distance =  0.0900000000 
      marker   = "D17G100"              # at   97.6500 cM
      distance =  0.7700000000 
      marker   = "D17G101"              # at   98.4200 cM
      distance =  1.3100000000 
      marker   = "D17G102"              # at   99.7300 cM
      distance =  0.7000000000 
      marker   = "D17G103"              # at  100.4300 cM
      distance =  0.0300000000 
      marker   = "D17G104"              # at  100.4600 cM
      distance =  0.2400000000 
      marker   = "D17G105"              # at  100.7000 cM
      distance =  0.8300000000 
      marker   = "D17G106"              # at  101.5300 cM
      distance =  1.8600000000 
      marker   = "D17G107"              # at  103.3900 cM
      distance =  0.8100000000 
      marker   = "D17G108"              # at  104.2000 cM
      distance =  0.1600000000 
      marker   = "D17G109"              # at  104.3600 cM
      distance =  0.6500000000 
      marker   = "D17G110"              # at  105.0100 cM
      distance =  0.3400000000 
      marker   = "D17G111"              # at  105.3500 cM
      distance =  2.0100000000 
      marker   = "D17G112"              # at  107.3600 cM
      distance =  0.7800000000 
   }

   region = Region_chr19 {
      marker   = "D19G002"              # at    0.0000 cM
      distance =  1.4200000000 
      marker   = "D19G003"              # at    1.4200 cM
      distance =  1.0900000000 
      marker   = "D19G004"              # at    2.5100 cM
      distance =  1.9900000000 
      marker   = "D19G005"              # at    4.5000 cM
      distance =  0.3700000000 
      marker   = "D19G006"              # at    4.8700 cM
      distance =  1.3700000000 
      marker   = "D19G007"              # at    6.2400 cM
      distance =  0.2200000000 
      marker   = "D19G008"              # at    6.4600 cM
      distance =  0.6300000000 
      marker   = "D19G009"              # at    7.0900 cM
      distance =  3.7600000000 
      marker   = "D19G010"              # at   10.8500 cM
      distance =  0.6600000000 
      marker   = "D19G011"              # at   11.5100 cM
      distance =  1.5300000000 
      marker   = "D19G012"              # at   13.0400 cM
      distance =  1.2800000000 
      marker   = "D19G013"              # at   14.3200 cM
      distance =  0.1100000000 
      marker   = "D19G014"              # at   14.4300 cM
      distance =  1.2600000000 
      marker   = "D19G015"              # at   15.6900 cM
      distance =  3.7100000000 
      marker   = "D19G016"              # at   19.4000 cM
      distance =  0.3700000000 
      marker   = "D19G017"              # at   19.7700 cM
      distance =  0.6600000000 
      marker   = "D19G018"              # at   20.4300 cM
      distance =  0.6400000000 
      marker   = "D19G019"              # at   21.0700 cM
      distance =  0.2300000000 
      marker   = "D19G020"              # at   21.3000 cM
      distance =  1.2200000000 
      marker   = "D19G021"              # at   22.5200 cM
      distance =  1.9500000000 
      marker   = "D19G022"              # at   24.4700 cM
      distance =  2.1800000000 
      marker   = "D19G023"              # at   26.6500 cM
      distance =  1.9900000000 
      marker   = "D19G024"              # at   28.6400 cM
      distance =  0.3900000000 
      marker   = "D19G025"              # at   29.0300 cM
      distance =  4.4400000000 
      marker   = "D19G026"              # at   33.4700 cM
      distance =  0.8300000000 
      marker   = "D19G027"              # at   34.3000 cM
      distance =  0.3800000000 
      marker   = "D19G028"              # at   34.6800 cM
      distance =  0.0900000000 
      marker   = "D19G029"              # at   34.7700 cM
      distance =  0.3000000000 
      marker   = "D19G030"              # at   35.0700 cM
      distance =  1.3000000000 
      marker   = "D19G031"              # at   36.3700 cM
      distance =  3.2600000000 
      marker   = "D19G032"              # at   39.6300 cM
      distance =  4.6000000000 
      marker   = "D19G033"              # at   44.2300 cM
      distance =  2.3500000000 
      marker   = "D19G034"              # at   46.5800 cM
      distance =  0.4500000000 
      marker   = "D19G035"              # at   47.0300 cM
      distance =  1.3700000000 
      marker   = "D19G036"              # at   48.4000 cM
      distance =  0.0800000000 
      marker   = "D19G037"              # at   48.4800 cM
      distance =  1.0700000000 
      marker   = "D19G038"              # at   49.5500 cM
      distance =  0.6100000000 
      marker   = "D19G039"              # at   50.1600 cM
      distance =  0.5300000000 
      marker   = "D19G040"              # at   50.6900 cM
      distance =  0.8600000000 
      marker   = "D19G041"              # at   51.5500 cM
      distance =  0.3100000000 
      marker   = "D19G042"              # at   51.8600 cM
      distance =  0.7400000000 
      marker   = "D19G043"              # at   52.6000 cM
      distance =  0.1200000000 
      marker   = "D19G044"              # at   52.7200 cM
      distance =  1.9300000000 
      marker   = "D19G045"              # at   54.6500 cM
      distance =  0.2800000000 
      marker   = "D19G046"              # at   54.9300 cM
      distance =  0.0200000000 
      marker   = "D19G047"              # at   54.9500 cM
      distance =  0.8100000000 
      marker   = "D19G048"              # at   55.7600 cM
      distance =  1.3500000000 
      marker   = "D19G049"              # at   57.1100 cM
      distance =  0.5000000000 
      marker   = "D19G050"              # at   57.6100 cM
      distance =  2.6300000000 
      marker   = "D19G051"              # at   60.2400 cM
      distance =  1.1700000000 
      marker   = "D19G052"              # at   61.4100 cM
      distance =  0.6100000000 
      marker   = "D19G053"              # at   62.0200 cM
      distance =  1.0500000000 
      marker   = "D19G054"              # at   63.0700 cM
      distance =  1.3600000000 
      marker   = "D19G055"              # at   64.4300 cM
      distance =  0.3100000000 
      marker   = "D19G056"              # at   64.7400 cM
      distance =  0.6800000000 
      marker   = "D19G057"              # at   65.4200 cM
      distance =  1.0600000000 
      marker   = "D19G058"              # at   66.4800 cM
      distance =  1.7900000000 
      marker   = "D19G059"              # at   68.2700 cM
      distance =  0.3000000000 
      marker   = "D19G060"              # at   68.5700 cM
      distance =  0.0900000000 
      marker   = "D19G061"              # at   68.6600 cM
      distance =  3.1800000000 
      marker   = "D19G062"              # at   71.8400 cM
      distance =  1.7800000000 
      marker   = "D19G063"              # at   73.6200 cM
      distance =  0.1100000000 
      marker   = "D19G064"              # at   73.7300 cM
      distance =  0.3600000000 
      marker   = "D19G065"              # at   74.0900 cM
      distance =  0.3700000000 
      marker   = "D19G066"              # at   74.4600 cM
      distance =  1.2300000000 
      marker   = "D19G067"              # at   75.6900 cM
      distance =  0.6600000000 
      marker   = "D19G068"              # at   76.3500 cM
      distance =  0.1300000000 
      marker   = "D19G069"              # at   76.4800 cM
      distance =  2.8700000000 
      marker   = "D19G070"              # at   79.3500 cM
      distance =  0.6700000000 
      marker   = "D19G071"              # at   80.0200 cM
      distance =  0.7000000000 
      marker   = "D19G072"              # at   80.7200 cM
      distance =  0.4100000000 
      marker   = "D19G073"              # at   81.1300 cM
      distance =  2.7900000000 
      marker   = "D19G074"              # at   83.9200 cM
      distance =  0.1700000000 
      marker   = "D19G075"              # at   84.0900 cM
      distance =  0.1300000000 
      marker   = "D19G076"              # at   84.2200 cM
      distance =  2.1800000000 
      marker   = "D19G077"              # at   86.4000 cM
      distance =  1.3800000000 
      marker   = "D19G078"              # at   87.7800 cM
      distance =  2.7200000000 
      marker   = "D19G079"              # at   90.5000 cM
      distance =  0.0700000000 
      marker   = "D19G080"              # at   90.5700 cM
      distance =  0.8300000000 
      marker   = "D19G081"              # at   91.4000 cM
      distance =  1.8800000000 
      marker   = "D19G082"              # at   93.2800 cM
      distance =  0.7500000000 
      marker   = "D19G083"              # at   94.0300 cM
      distance =  1.3100000000 
      marker   = "D19G084"              # at   95.3400 cM
      distance =  0.0700000000 
      marker   = "D19G085"              # at   95.4100 cM
      distance =  1.0400000000 
      marker   = "D19G086"              # at   96.4500 cM
      distance =  0.1700000000 
      marker   = "D19G087"              # at   96.6200 cM
      distance =  0.7900000000 
      marker   = "D19G088"              # at   97.4100 cM
      distance =  2.1700000000 
      marker   = "D19G089"              # at   99.5800 cM
      distance =  3.1600000000 
      marker   = "D19G090"              # at  102.7400 cM
      distance =  0.1900000000 
      marker   = "D19G091"              # at  102.9300 cM
      distance =  0.2200000000 
      marker   = "D19G092"              # at  103.1500 cM
      distance =  0.7000000000 
      marker   = "D19G093"              # at  103.8500 cM
      distance =  0.8800000000 
      marker   = "D19G094"              # at  104.7300 cM
      distance =  0.2500000000 
      marker   = "D19G095"              # at  104.9800 cM
      distance =  1.7700000000 
      marker   = "D19G096"              # at  106.7500 cM
      distance =  1.0600000000 
      marker   = "D19G097"              # at  107.8100 cM
      distance =  0.8500000000 
      marker   = "D19G098"              # at  108.6600 cM
      distance =  1.1700000000 
      marker   = "D19G099"              # at  109.8300 cM
      distance =  0.1700000000 
      marker   = "D19G100"              # at  110.0000 cM
      distance =  0.0500000000 
      marker   = "D19G101"              # at  110.0500 cM
      distance =  0.6700000000 
      marker   = "D19G102"              # at  110.7200 cM
      distance =  0.1000000000 
      marker   = "D19G103"              # at  110.8200 cM
      distance =  0.2700000000 
      marker   = "D19G104"              # at  111.0900 cM
      distance =  1.1500000000 
      marker   = "D19G105"              # at  112.2400 cM
      distance =  1.7600000000 
   }
}
