=================

     Results

=================

Note: P-values for variance components and proportions are one-sided.  All others are two-sided.
The null hypothesis for transformation parameters is 'no transformation.'


==============================
     Analysis description
==============================

  Title                        assoc1                        
  Primary Trait                PHEN (Quantitative)           
  Allow averaging              Disabled                      
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  

======================================
     Transformation configuration
======================================



Note: No transformation applied.

==========================

     Model 'Baseline'

==========================

============================
     Sample description
============================

  Number of individuals in dataset                                   8  
  Number of constituent pedigrees in dataset                         2  
  Number of singletons in dataset                                    0  
                                                                        
  Number of constituent pedigree members with complete information   8  
  Number of singletons with complete information                     0  
                                                                        

===============================================================
     MAXIMIZATION RESULTS Baseline without test covariates
===============================================================

--------------------------------------------------------------------
  Parameter         Estimate   S.E.       P-value    Deriv          
--------------------------------------------------------------------
  Variance components
            Random   0.140311   0.081009   0.083264  -0.0000371567  
            Family   0.117801   0.154215   0.222470  -0.0000251490  

  Other parameters
    Total variance   0.258113   0.164510   0.116652  -0.0000055128  

  Correlations
         Full sibs   0.456396   0.371785   0.219605   0.0000000000  
         Half sibs   0.456396   0.371785   0.219605   0.0000000000  
  Parent offspring   0.456396   0.371785   0.219605   0.0000000000  
           Spouses   0.456396   0.371785   0.219605   0.0000000000  
    Nuclear family   0.456396   0.371785   0.219605   0.0000000000  
           Marital   0.456396   0.371785   0.219605   0.0000000000  
           Sibship   0.456396   0.371785   0.219605   0.0000000000  

         Intercept   0.491715   0.276477   0.075322   0.0000000000  
--------------------------------------------------------------------

Final ln likelihood: -21.508914

=====================================================================
     VARIANCE-COVARIANCE MATRIX Baseline without test covariates
=====================================================================

--------------------------------------------------------------------------------------------------------------------------------------------------------------
                    Random     Family     Total variance  Full sibs  Half sibs  Parent offspring  Spouses    Nuclear family  Marital    Sibship    Intercept  
--------------------------------------------------------------------------------------------------------------------------------------------------------------
  Random             0.006562  -0.001641   0.004922       -0.015059  -0.015059  -0.015059         -0.015059  -0.015059       -0.015059  -0.015059   8.91e-12  
  Family            -0.001641   0.023782   0.022142        0.052988   0.052988   0.052988          0.052988   0.052988        0.052988   0.052988  -2.76e-11  
  Total variance     0.004922   0.022142   0.027063        0.037929   0.037929   0.037929          0.037929   0.037929        0.037929   0.037929  -1.87e-11  
  Full sibs         -0.015059   0.052988   0.037929        0.138224   0.138224   0.138224          0.138224   0.138224        0.138224   0.138224  -7.39e-11  
  Half sibs         -0.015059   0.052988   0.037929        0.138224   0.138224   0.138224          0.138224   0.138224        0.138224   0.138224  -7.39e-11  
  Parent offspring  -0.015059   0.052988   0.037929        0.138224   0.138224   0.138224          0.138224   0.138224        0.138224   0.138224  -7.39e-11  
  Spouses           -0.015059   0.052988   0.037929        0.138224   0.138224   0.138224          0.138224   0.138224        0.138224   0.138224  -7.39e-11  
  Nuclear family    -0.015059   0.052988   0.037929        0.138224   0.138224   0.138224          0.138224   0.138224        0.138224   0.138224  -7.39e-11  
  Marital           -0.015059   0.052988   0.037929        0.138224   0.138224   0.138224          0.138224   0.138224        0.138224   0.138224  -7.39e-11  
  Sibship           -0.015059   0.052988   0.037929        0.138224   0.138224   0.138224          0.138224   0.138224        0.138224   0.138224  -7.39e-11  
  Intercept          8.91e-12  -2.76e-11  -1.87e-11       -7.39e-11  -7.39e-11  -7.39e-11         -7.39e-11  -7.39e-11       -7.39e-11  -7.39e-11   0.076440  

