



Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             1         0             0           
     1             2             2         0             0           
     1             3             2         1             2           
     1             4             2         1             2           
     2             1             1         0             0           
     2             2             2         0             0           
     2             3             1         1             2           
     2             4             1         1             2           
     2             5             2         0             0           
     2             6             2         4             5           


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         sle                   malefam               var                   prin1                 prin2                 prin3                 prin4                 prin5                 prin6                 prin7                 prin8                 prin9                 prin10                prin11                prin12              
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     4                     0                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                   
     1             2             1                     1                     1                     4                     0                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                   
     1             3             1                     1                     0                     4                     1                     0                     1                     1.5657                1.66877               -0.229863             -0.0518561            -0.0325724            0.919188              0.506557              0.582516              -1.89582              -0.694012             0.731451              -0.183308           
     1             4             1                     1                     0                     4                     1                     0                     1                     1.82732               1.59078               0.120055              0.199975              0.837807              -0.404972             -0.443158             -0.112999             0.881188              -0.0403461            -0.358334             -0.22074            
     2             1             0                     1                     1                     7                     0                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                   
     2             2             1                     1                     1                     7                     0                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                   
     2             3             0                     1                     0                     7                     0                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                   
     2             4             0                     1                     0                     7                     1                     1                     0                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                   
     2             5             1                     1                     1                     7                     0                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                     .                   
     2             6             1                     1                     0                     7                     1                     1                     1                     0.852541              -1.01572              1.08528               1.13754               -0.0355396            -0.948703             0.193461              -0.420417             0.135455              0.789932              1.51625               1.07906             

%LODPAL-W: Pedigree '95' has 3 constituent pedigrees which are disjoint from
           one another.  This may not be intended.  Results may be incorrect. 
           See manual for details on constituent pedigrees.

New phenotypes for individuals created by function block(s) :

     PED. ID       IND. ID       malefam2            
     ------------  ------------  --------------------
     1             1                                 
     1             2                                 
     1             3             0                   
     1             4             0                   
     2             1                                 
     2             2                                 
     2             3                                 
     2             4             2                   
     2             5                                 
     2             6             2                   


%LODPAL-W: Trait subset 'var' is not a binary trait!  For this analysis it will
           be dichotomized at 0 (trait values <= 0 will not be included into
           subset and values > 0 will be included into subset).
%LODPAL-W: This option 'two_parameter_model' has been revised.  Please refer to
           the manual.
%LODPAL-W: Trait subset 'var' is not a binary trait!  For this analysis it will
           be dichotomized at 0 (trait values <= 0 will not be included into
           subset and values > 0 will be included into subset).
