


Reading Parameter File....................done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Reading pairs.............................done.
Sorting pairs.............................done.

LODPAL analysis.......  1

Computing multipoint lod scores...........done.

LODPAL analysis.......  2

Computing multipoint lod scores...........done.

Analysis complete!



