


Reading Parameter File....................done.
Reading Marker Locus Description File.....done.
Reading Pedigree File.....................
              from ped....................done.
%GENIBD-E: Error(s) building pedigree '401': 2 errors.
%GENIBD-E: Errors appear in pedigree data. Results may be incomplete.
Sorting Pedigrees.........................done.
Reading Genome Description File...........done.

GENIBD analysis.......  1

===========================================================================
Analysis 1 : Multipoint analysis on region (CHR_1):
        * - Maximum size for exact method is set to 18.
        * - Pedigrees larger than 18 will be simulated.
        * - Pedigrees will be simulated based on pedigree size and the number
            of markers.
===========================================================================

  Processing Region: CHR_1
  =======================================

  Analysis 1: Pedigree 401
        Generating Marker Likelihoods      ....................Done.
        Generating Multipoint Combined Info....................Done.
        Generating Multipoint IBDs         ....................Done.


Analysis complete!



