



Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             1         0             0           
     1             2             2         0             0           
     1             3             1         1             2           
     1             4             1         1             2           
     1             5             2         0             0           
     1             6             1         4             5           


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         rep                 
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     6                     1                   
     1             2             1                     1                     1                     6                     2                   
     1             3             0                     1                     0                     6                     3                   
     1             4             0                     1                     0                     6                     4                   
     1             5             1                     1                     1                     6                     5                   
     1             6             0                     1                     0                     6                     6                   


Markers for the first 10 individuals read from file: ped

     PED. ID       IND. ID       m1            m2            m3            m4          
     ------------  ------------  ------------  ------------  ------------  ------------
     1             1             1/1           1/1           1/2           2/1         
     1             2             1/1           1/2           1/2           2/2         
     1             3             1/1           1/2           1/2           2/1         
     1             4             1/1           1/1           1/2           2/2         
     1             5             1/1           1/2           1/1           1/1         
     1             6             1/1           1/2           1/2           2/1         

%DECIPHER-W: Marker 'm1' has only one allele.  This marker will be unavailable
             for all analyses.
%DECIPHER-I: Mapping function not specified.  Using Haldane Mapping Function.
%DECIPHER-W: Marker 'm1' not found.  Marker will not be used for analysis.
%DECIPHER-W: Marker m2 is the first valid marker in region all.  It will be set
             to a position of 0.

  Performing analysis: Analysis 1
  ===========================================================================

    Total population. 
      Determining possible haplotype combinations ................... done.

  ===========================================================================

