



Family structure information on the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             M         0             0           
     1             2             M         0             0           
     1             3             M         0             0           
     1             4             M         0             0           
     1             5             M         0             0           
     1             6             M         0             0           
     1             7             M         0             0           
     1             8             M         0             0           
     1             9             M         0             0           
     1             10            M         0             0           
     1             11            M         0             0           
     1             12            M         0             0           
     1             13            M         0             0           
     1             14            M         0             0           
     1             15            M         0             0           
     1             16            M         0             0           
     1             17            M         0             0           
     1             18            M         0             0           
     1             19            M         0             0           
     1             20            M         0             0           


Phenotypes for the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE       
     ------------  ------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     50                  
     1             2             0                     1                     1                     50                  
     1             3             0                     1                     1                     50                  
     1             4             0                     1                     1                     50                  
     1             5             0                     1                     1                     50                  
     1             6             0                     1                     1                     50                  
     1             7             0                     1                     1                     50                  
     1             8             0                     1                     1                     50                  
     1             9             0                     1                     1                     50                  
     1             10            0                     1                     1                     50                  
     1             11            0                     1                     1                     50                  
     1             12            0                     1                     1                     50                  
     1             13            0                     1                     1                     50                  
     1             14            0                     1                     1                     50                  
     1             15            0                     1                     1                     50                  
     1             16            0                     1                     1                     50                  
     1             17            0                     1                     1                     50                  
     1             18            0                     1                     1                     50                  
     1             19            0                     1                     1                     50                  
     1             20            0                     1                     1                     50                  


Markers for the first 20 individuals read from file: ped

     PED. ID       IND. ID       M1            M2            M3          
     ------------  ------------  ------------  ------------  ------------
     1             1             a/a           A/a           a/A         
     1             2             a/A           a/a           a/A         
     1             3             A/A           a/a           A/A         
     1             4             a/A           A/A           a/A         
     1             5             a/a           A/A           a/a         
     1             6             a/A           a/a           A/A         
     1             7             a/A           A/a           a/A         
     1             8             A/A           a/a           A/A         
     1             9             A/A           A/a           A/A         
     1             10            A/A           a/a           a/A         
     1             11            A/A           A/a           A/A         
     1             12            A/A           A/a           a/A         
     1             13            a/A           A/A           a/a         
     1             14            A/A           A/a           A/A         
     1             15            a/A           a/a           a/A         
     1             16            A/A           a/a           A/A         
     1             17            a/a           A/a           a/a         
     1             18            A/A           A/a           a/A         
     1             19            a/A           A/a           A/A         
     1             20            A/A           a/a           A/A         

%DECIPHER-I: Mapping function not specified.  Using Haldane Mapping Function.

  Performing analysis: Analysis 1
  ===========================================================================

    Total population. 
      Determining possible haplotype combinations ................... done.
      Maximizing likelihood ......................................... done. 

  ===========================================================================

