



Family structure information on the first 1000 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     0             1                       0_parent1     0_parent2   
     0             2                       0_parent1     0_parent2   
     0             3                       0_parent1     0_parent2   
     0             4                       0_parent1     0_parent2   
     0             5                       0_parent1     0_parent2   
     0             6                       0_parent1     0_parent2   
     0             7                       0_parent1     0_parent2   
     0             8                       0_parent1     0_parent2   
     0             9                       0_parent1     0_parent2   
     0             10                      0_parent1     0_parent2   


Phenotypes for the first 1000 individuals read from file: ped

     PED. ID       IND. ID       FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE       
     ------------  ------------  --------------------  --------------------  --------------------
     0             1             1                     0                     12                  
     0             2             1                     0                     12                  
     0             3             1                     0                     12                  
     0             4             1                     0                     12                  
     0             5             1                     0                     12                  
     0             6             1                     0                     12                  
     0             7             1                     0                     12                  
     0             8             1                     0                     12                  
     0             9             1                     0                     12                  
     0             10            1                     0                     12                  

