
Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             F                                   
     1             2             M                                   
     1             3             M         1             2           
     1             4             F         1             2           
     1             5             M                                   
     1             6             F         4             5           


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         DISEASE               HEMATOCRIT            t                     u                     v                     w                     x                     y                     z                   
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             1                     1                     1                     6                     1                     30                                                                                                                                                                            
     1             2             0                     1                     1                     6                     0                     40                                                                                                                                                                            
     1             3             0                     1                     0                     6                     0                     27.1                                                                                                                                                                          
     1             4             1                     1                     0                     6                     1                     39                                                                                                                                                                            
     1             5             0                     1                     1                     6                     0                     37.6                                                                                                                                                                          
     1             6             1                     1                     0                     6                     1                     41.1                                                                                                                                                                          

%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 1 New Analysis Block 1 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 2 New Analysis Block 2 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 3 New Analysis Block 3 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 4 New Analysis Block 4 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:Unnecessary parameter(s) specified in ascertainment
                        sub-block with cond_val equal to 'actual'.  Ignoring
                        ...
%TESTSEGREGPARSER-Error:---------- 5 New Analysis Block 5 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:Value 'W' for cond_val parameter of ascertainment
                        sub-block not recognized.  Ignoring ...
%TESTSEGREGPARSER-Error:Unnecessary parameter(s) specified in ascertainment
                        sub-block with cond_set equal to 'none'.  Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 6 New Analysis Block 6 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:Bad or missing value for parameter 'thresh_indic'
%TESTSEGREGPARSER-Critical:Required trait not specified for ascertainment
                           sub-block parameter, psf_indic or thresh_indic. 
                           Skipping analysis ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 7 New Analysis Block 7 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Critical:Could not find trait 'abc' specified for
                           ascertainment sub-block parameter, psf_indic or
                           thresh_indic.  Skipping analysis ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 8 New Analysis Block 8 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:Value 'THRESH_INDIC' for  parameter, cond_set, of
                        ascertainment sub-block not recognized.  Ignoring ... 
%TESTSEGREGPARSER-Error:Parameter, cond_val, in ascertainment sub-block not
                        relevant for binary or age of onset traits.  Ignoring
                        ...
%TESTSEGREGPARSER-Error:Unnecessary parameter(s) specified in ascertainment
                        sub-block with cond_set equal to 'none'.  Ignoring ...
