=================

     Results

=================

Note: P-values for variance components and proportions are one-sided.  All others are two-sided.
The null hypothesis for transformation parameters is 'no transformation.'


==============================
     Analysis description
==============================

  Title                        assoc                         
  Primary Trait                affection (Binary)            
  Allow averaging              Disabled                      
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  
-------------------------------------------------------------

Note: This output contains results for a binary trait using an algorithm still in Beta release form. Please verify results before reporting.

======================================
     Transformation configuration
======================================



Note: No transformation applied.

===========================

     Model 'Alternate'

===========================

============================
     Sample description
============================

  Number of individuals in dataset                                   2077  
  Number of constituent pedigrees in dataset                          300  
  Number of singletons in dataset                                       0  
                                                                           
  Number of constituent pedigree members with complete information    666  
  Number of singletons with complete information                        0  
                                                                           

====================
     Covariates
====================

-------------------------------------------------------------
  Name           Mean       Std. dev.  Min        Max        
-------------------------------------------------------------
  C               0.312312   0.463436   0.000000   1.000000  
  G               0.309309   0.462209   0.000000   1.000000  
  J               0.142643   0.349708   0.000000   1.000000  
  C01R0001_1tai   0.462462   0.498589   0.000000   1.000000  

================================================================
     MAXIMIZATION RESULTS Alternate without test covariates
================================================================

----------------------------------------------------------------------
  Parameter       Estimate   S.E.         P-value      Deriv          
----------------------------------------------------------------------
  Variance components
          Random   0.820237   0.044949    < 1.00e-07    0.0001502872  

  Other parameters
  Total variance   0.820237   0.044949    < 1.00e-07   -0.0000130824  

  Variance proportions
          Random   1.000000  Unavailable  Unavailable  -0.0000399215  

       Intercept  -0.030381   0.056843     0.593013     0.0000484183  

  Covariates
               C   0.777559   0.167043    < 1.00e-05   -0.0000341221  
               G   0.849838   0.167613    < 1.00e-06    0.0000000000  
               J   0.006058   0.161590     0.970097     0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -879.025509

======================================================================
     VARIANCE-COVARIANCE MATRIX Alternate without test covariates
======================================================================

----------------------------------------------------------------------------------------------------
                  Random     Total variance  Random     Intercept  C          G          J          
----------------------------------------------------------------------------------------------------
  Random           0.002020   0.002020        0.000000  -1.55e-09  -5.58e-09   5.49e-09  -2.14e-09  
  Total variance   0.002020   0.002020        0.000000  -1.55e-09  -5.58e-09   5.49e-09  -2.14e-09  
  Random           0.000000   0.000000        0.000000   0.000000   0.000000   0.000000   0.000000  
  Intercept       -1.55e-09  -1.55e-09        0.000000   0.003231   0.001174   0.001090   0.000361  
  C               -5.58e-09  -5.58e-09        0.000000   0.001174   0.027903  -0.016667  -0.001074  
  G                5.49e-09   5.49e-09        0.000000   0.001090  -0.016667   0.028094   0.002478  
  J               -2.14e-09  -2.14e-09        0.000000   0.000361  -0.001074   0.002478   0.026111  

=============================================================
     MAXIMIZATION RESULTS Alternate with test covariates
=============================================================

----------------------------------------------------------------------
  Parameter       Estimate   S.E.         P-value      Deriv          
----------------------------------------------------------------------
  Variance components
          Random   0.819945   0.044933    < 1.00e-07    0.0000187515  

  Other parameters
  Total variance   0.819945   0.044933    < 1.00e-07   -0.0000513854  

  Variance proportions
          Random   1.000000  Unavailable  Unavailable   0.0000342570  

       Intercept  -0.029837   0.056876     0.599858    -0.0000561059  

  Covariates
               C   0.780394   0.167284    < 1.00e-05   -0.0000269740  
               G   0.849877   0.167730    < 1.00e-06    0.0000000000  
               J  -0.001411   0.162723     0.993080     0.0000000000  
   C01R0001_1tai  -0.053779   0.110435     0.626279     0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -878.906947

===================================================================
     VARIANCE-COVARIANCE MATRIX Alternate with test covariates
===================================================================

-------------------------------------------------------------------------------------------------------------------
                  Random     Total variance  Random     Intercept  C          G          J          C01R0001_1tai  
-------------------------------------------------------------------------------------------------------------------
  Random           0.002019   0.002019        0.000000  -1.55e-09  -1.56e-09  -3.75e-09  -2.55e-09  -2.65e-09      
  Total variance   0.002019   0.002019        0.000000  -1.55e-09  -1.56e-09  -3.75e-09  -2.55e-09  -2.65e-09      
  Random           0.000000   0.000000        0.000000   0.000000   0.000000   0.000000   0.000000   0.000000      
  Intercept       -1.55e-09  -1.55e-09        0.000000   0.003235   0.001185   0.001096   0.000364  -0.000122      
  C               -1.56e-09  -1.56e-09        0.000000   0.001185   0.027984  -0.016698  -0.001158  -0.000644      
  G               -3.75e-09  -3.75e-09        0.000000   0.001096  -0.016698   0.028133   0.002440  -9.76e-06      
  J               -2.55e-09  -2.55e-09        0.000000   0.000364  -0.001158   0.002440   0.026479   0.001706      
  C01R0001_1tai   -2.65e-09  -2.65e-09        0.000000  -0.000122  -0.000644  -9.76e-06   0.001706   0.012196      

====================
     Joint test
====================

  H0 ln likelihood Alternate without test covariates  -879.025509  
  H1 ln likelihood Alternate with test covariates     -878.906947  
                                                                   
  2 * |H0 - H1|                                          0.237124  
  Degrees of freedom                                            1  
  P-value                                                0.626291  

