=================

     Results

=================

Note: P-values for variance components and proportions are one-sided.  All others are two-sided.
The null hypothesis for transformation parameters is 'no transformation.'


==============================
     Analysis description
==============================

  Title                        assoc                         
  Primary Trait                affection (Binary)            
  Allow averaging              Disabled                      
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  
-------------------------------------------------------------

Note: This output contains results for a binary trait using an algorithm still in Beta release form. Please verify results before reporting.

======================================
     Transformation configuration
======================================



Note: No transformation applied.

===========================

     Model 'Alternate'

===========================

============================
     Sample description
============================

  Number of individuals in dataset                                   2077  
  Number of constituent pedigrees in dataset                          300  
  Number of singletons in dataset                                       0  
                                                                           
  Number of constituent pedigree members with complete information    666  
  Number of singletons with complete information                        0  
                                                                           

====================
     Covariates
====================

-------------------------------------------------------------
  Name           Mean       Std. dev.  Min        Max        
-------------------------------------------------------------
  C               0.312312   0.463436   0.000000   1.000000  
  G               0.309309   0.462209   0.000000   1.000000  
  J               0.142643   0.349708   0.000000   1.000000  
  C01R0001_1tai   0.462462   0.498589   0.000000   1.000000  

================================================================
     MAXIMIZATION RESULTS Alternate without test covariates
================================================================

----------------------------------------------------------------------
  Parameter       Estimate   S.E.         P-value      Deriv          
----------------------------------------------------------------------
  Variance components
          Random   0.820238   0.044949    < 1.00e-07    0.0000163606  

  Other parameters
  Total variance   0.820238   0.044949    < 1.00e-07   -0.0000054622  

  Variance proportions
          Random   1.000000  Unavailable  Unavailable   0.0000031694  

       Intercept  -0.030381   0.056843     0.593018     0.0000060017  

  Covariates
               C   0.777559   0.167042    < 1.00e-05    0.0000042484  
               G   0.849840   0.167613    < 1.00e-06    0.0000000000  
               J   0.006059   0.161590     0.970091     0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -879.025509

======================================================================
     VARIANCE-COVARIANCE MATRIX Alternate without test covariates
======================================================================

----------------------------------------------------------------------------------------------------
                  Random     Total variance  Random     Intercept  C          G          J          
----------------------------------------------------------------------------------------------------
  Random           0.002020   0.002020        0.000000  -3.23e-10   8.64e-09  -1.48e-08  -1.54e-09  
  Total variance   0.002020   0.002020        0.000000  -3.23e-10   8.64e-09  -1.48e-08  -1.54e-09  
  Random           0.000000   0.000000        0.000000   0.000000   0.000000   0.000000   0.000000  
  Intercept       -3.23e-10  -3.23e-10        0.000000   0.003231   0.001174   0.001090   0.000361  
  C                8.64e-09   8.64e-09        0.000000   0.001174   0.027903  -0.016666  -0.001074  
  G               -1.48e-08  -1.48e-08        0.000000   0.001090  -0.016666   0.028094   0.002478  
  J               -1.54e-09  -1.54e-09        0.000000   0.000361  -0.001074   0.002478   0.026111  

=============================================================
     MAXIMIZATION RESULTS Alternate with test covariates
=============================================================

----------------------------------------------------------------------
  Parameter       Estimate   S.E.         P-value      Deriv          
----------------------------------------------------------------------
  Variance components
          Random   0.819945   0.044933    < 1.00e-07    0.0000301010  

  Other parameters
  Total variance   0.819945   0.044933    < 1.00e-07    0.0000118686  

  Variance proportions
          Random   1.000000  Unavailable  Unavailable  -0.0000407307  

       Intercept  -0.029837   0.056876     0.599857    -0.0000430235  

  Covariates
               C   0.780395   0.167284    < 1.00e-05   -0.0000017533  
               G   0.849877   0.167730    < 1.00e-06    0.0000000000  
               J  -0.001411   0.162724     0.993079     0.0000000000  
   C01R0001_1tai  -0.053779   0.110435     0.626279     0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -878.906947

===================================================================
     VARIANCE-COVARIANCE MATRIX Alternate with test covariates
===================================================================

-------------------------------------------------------------------------------------------------------------------
                  Random     Total variance  Random     Intercept  C          G          J          C01R0001_1tai  
-------------------------------------------------------------------------------------------------------------------
  Random           0.002019   0.002019        0.000000  -1.51e-09  -2.81e-09   3.83e-10  -2.94e-09  -1.93e-09      
  Total variance   0.002019   0.002019        0.000000  -1.51e-09  -2.81e-09   3.83e-10  -2.94e-09  -1.93e-09      
  Random           0.000000   0.000000        0.000000   0.000000   0.000000   0.000000   0.000000   0.000000      
  Intercept       -1.51e-09  -1.51e-09        0.000000   0.003235   0.001185   0.001096   0.000364  -0.000122      
  C               -2.81e-09  -2.81e-09        0.000000   0.001185   0.027984  -0.016698  -0.001158  -0.000644      
  G                3.83e-10   3.83e-10        0.000000   0.001096  -0.016698   0.028133   0.002440  -9.73e-06      
  J               -2.94e-09  -2.94e-09        0.000000   0.000364  -0.001158   0.002440   0.026479   0.001706      
  C01R0001_1tai   -1.93e-09  -1.93e-09        0.000000  -0.000122  -0.000644  -9.73e-06   0.001706   0.012196      

====================
     Joint test
====================

  H0 ln likelihood Alternate without test covariates  -879.025509  
  H1 ln likelihood Alternate with test covariates     -878.906947  
                                                                   
  2 * |H0 - H1|                                          0.237124  
  Degrees of freedom                                            1  
  P-value                                                0.626291  

