=================

     Results

=================

==============================
     Analysis description
==============================

  Title                        assoc                         
  Primary Trait                affection (Binary)            
  Allow averaging              Disabled                      
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  
-------------------------------------------------------------

Note: This output contains results for a binary trait using an algorithm still in Beta release form. Please verify results before reporting.

======================================
     Transformation configuration
======================================

  Method                George-Elston  
  Lambda1 is estimated                 
  Lambda2 is fixed at    0.000000      

=======================
     Summary table
=======================

--------------------------------------------------------------------------------------------------------------------------------
  Model       Intercept  C          G          J          Test cov.      Estimate   Std. err.    P-value (Wald)  P-value (LRT)  
--------------------------------------------------------------------------------------------------------------------------------
  Alternate*   0.002271  -0.000954  -0.001265  -5.28e-05  C01R0001_1tai  -0.000776  Unavailable  Unavailable      1.000000      
--------------------------------------------------------------------------------------------------------------------------------

Note: Models with an asterisk (*) may not have converged.

================================
     Complete summary table
================================

--------------------------------------------------------------------------------------------------------------------------------
  Model       Intercept  C          G          J          Test cov.      Estimate   Std. err.    P-value (Wald)  P-value (LRT)  
--------------------------------------------------------------------------------------------------------------------------------
  Alternate*   0.002271  -0.000954  -0.001265  -5.28e-05  C01R0001_1tai  -0.000776  Unavailable  Unavailable      1.000000      
--------------------------------------------------------------------------------------------------------------------------------

Note: Models with an asterisk (*) may not have converged.

Note: See .det file for more information about each model

