





MARKER MODELS:
============================

Reading Pedigree File.....................
              from ped....................done.

Family structure information on the first 1000 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             1         0             0           
     1             2             2         0             0           
     1             3             2         1             2           
     1             4             1         1             2           
     2             2             2         0             0           
     2             1             1         0             0           
     2             3             2         1             2           
     2             4             1         1             2           
     3             2             2         0             0           
     3             1             1         0             0           
     3             3             2         1             2           
     3             4             2         1             2           
     4             2             2         0             0           
     4             1             1         0             0           
     4             3             1         1             2           
     4             4             1         1             2           
     4             5             2         1             2           
     5             2             2         0             0           
     5             1             1         0             0           
     5             3             1         1             2           
     5             4             1         1             2           
     5             5             2         1             2           
     5             6             2         1             2           
     5             7             2         1             2           


Phenotypes for the first 1000 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE       
     ------------  ------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     4                   
     1             2             1                     1                     1                     4                   
     1             3             1                     1                     0                     4                   
     1             4             0                     1                     0                     4                   
     2             2             1                     1                     1                     4                   
     2             1             0                     1                     1                     4                   
     2             3             1                     1                     0                     4                   
     2             4             0                     1                     0                     4                   
     3             2             1                     1                     1                     4                   
     3             1             0                     1                     1                     4                   
     3             3             1                     1                     0                     4                   
     3             4             1                     1                     0                     4                   
     4             2             1                     1                     1                     5                   
     4             1             0                     1                     1                     5                   
     4             3             0                     1                     0                     5                   
     4             4             0                     1                     0                     5                   
     4             5             1                     1                     0                     5                   
     5             2             1                     1                     1                     7                   
     5             1             0                     1                     1                     7                   
     5             3             0                     1                     0                     7                   
     5             4             0                     1                     0                     7                   
     5             5             1                     1                     0                     7                   
     5             6             1                     1                     0                     7                   
     5             7             1                     1                     0                     7                   


Markers for the first 1000 individuals read from file: ped

     PED. ID       IND. ID       M1          
     ------------  ------------  ------------
     1             1             A/M         
     1             2             A/A         
     1             3             A/A         
     1             4             A/M         
     2             2             A/A         
     2             1             B/M         
     2             3             A/B         
     2             4             A/M         
     3             2             A/A         
     3             1             M/M         
     3             3             A/A         
     3             4             A/B         
     4             2             A/B         
     4             1             M/M         
     4             3             A/M         
     4             4             B/M         
     4             5             A/B         
     5             2             M/M         
     5             1             M/M         
     5             3             A/M         
     5             4             B/M         
     5             5             A/B         
     5             6             A/A         
     5             7             B/B         

Sorting pedigrees.........................done.
Analyzing Marker: 0
************************************
Testing penetrance model Remap 1
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Remap 1
  symmetric: false
 codominant: true
    alleles: A ~remap
unphased genotypes: A/A A/~remap ~remap/~remap A/~Y ~remap/~Y
phased genotypes: A<A A<~remap ~remap<A ~remap<~remap A<~Y ~remap<~Y
 phenotypes:  000000 000001 000002 000003

unphased penetrance matrix:
            A/A A/~remap ~remap/~remap A/~Y ~remap/~Y
*missing    1   1   1   1   1   
000000      0   0   0   1   0   
000001      1   0   0   0   0   
000002      1   0   0   0   0   
000003      0   0   0   1   0   

phased penetrance matrix:
            A<A A<~remap ~remap<A ~remap<~remap A<~Y ~remap<~Y
*missing    1   1   1   1   1   1   
000000      0   0   0   0   1   0   
000001      1   0   0   0   0   0   
000002      1   0   0   0   0   0   
000003      0   0   0   0   1   0   

unphased penetrance matrix iteration:
*missing      1 [A/A]  1 [A/~Y]  1 [A/~remap]  1 [~remap/~remap]  1 [~remap/~Y]
000000        1 [A/~Y]
000001        1 [A/A]
000002        1 [A/A]
000003        1 [A/~Y]

phased penetrance matrix iteration:
*missing      1 [A<A]  1 [A<~Y]  1 [A<~remap]  1 [~remap<A]  1 [~remap<~remap]  1 [~remap<~Y]
000000        1 [A<~Y]
000001        1 [A<A]
000002        1 [A<A]
000003        1 [A<~Y]

truetruefalse
************************************
Testing penetrance model Genotype Elimination
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Genotype Elimination
  symmetric: false
 codominant: true
    alleles: A ~remap
unphased genotypes: A/A A/~remap ~remap/~remap A/~Y ~remap/~Y
phased genotypes: A<A A<~remap ~remap<A ~remap<~remap A<~Y ~remap<~Y
 phenotypes:  000000 000001 000002 000003

unphased penetrance matrix:
            A/A A/~remap ~remap/~remap A/~Y ~remap/~Y
*missing    1   1   1   1   1   
000000      0   0   0   1   0   
000001      1   0   0   0   0   
000002      1   0   0   0   0   
000003      0   0   0   1   0   

phased penetrance matrix:
            A<A A<~remap ~remap<A ~remap<~remap A<~Y ~remap<~Y
*missing    1   1   1   1   1   1   
000000      0   0   0   0   1   0   
000001      1   0   0   0   0   0   
000002      1   0   0   0   0   0   
000003      0   0   0   0   1   0   

unphased penetrance matrix iteration:
*missing      1 [A/A]  1 [A/~Y]  1 [A/~remap]  1 [~remap/~remap]  1 [~remap/~Y]
000000        1 [A/~Y]
000001        1 [A/A]
000002        1 [A/A]
000003        1 [A/~Y]

phased penetrance matrix iteration:
*missing      1 [A<A]  1 [A<~Y]  1 [A<~remap]  1 [~remap<A]  1 [~remap<~remap]  1 [~remap<~Y]
000000        1 [A<~Y]
000001        1 [A<A]
000002        1 [A<A]
000003        1 [A<~Y]

truetruefalse
Testing Pedigree Region on 1:1
All Markers
1
************************************
Testing penetrance model Pedigree Region
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Pedigree Region
  symmetric: false
 codominant: true
    alleles: A ~remap
unphased genotypes: A/A A/~remap ~remap/~remap A/~Y ~remap/~Y
phased genotypes: A<A A<~remap ~remap<A ~remap<~remap A<~Y ~remap<~Y
 phenotypes:  000000 000001 000002 000003

unphased penetrance matrix:
            A/A A/~remap ~remap/~remap A/~Y ~remap/~Y
*missing    1   1   1   1   1   
000000      0   0   0   1   0   
000001      1   0   0   0   0   
000002      1   0   0   0   0   
000003      0   0   0   1   0   

phased penetrance matrix:
            A<A A<~remap ~remap<A ~remap<~remap A<~Y ~remap<~Y
*missing    1   1   1   1   1   1   
000000      0   0   0   0   1   0   
000001      1   0   0   0   0   0   
000002      1   0   0   0   0   0   
000003      0   0   0   0   1   0   

unphased penetrance matrix iteration:
*missing      1 [A/A]  1 [A/~Y]  1 [A/~remap]  1 [~remap/~remap]  1 [~remap/~Y]
000000        1 [A/~Y]
000001        1 [A/A]
000002        1 [A/A]
000003        1 [A/~Y]

phased penetrance matrix iteration:
*missing      1 [A<A]  1 [A<~Y]  1 [A<~remap]  1 [~remap<A]  1 [~remap<~remap]  1 [~remap<~Y]
000000        1 [A<~Y]
000001        1 [A<A]
000002        1 [A<A]
000003        1 [A<~Y]

true
Analyzing Marker: 0
************************************
Testing penetrance model Remap 1
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Remap 1
  symmetric: false
 codominant: true
    alleles: A B C
unphased genotypes: A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
phased genotypes: A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
 phenotypes:  000000 000001 000002 000003

unphased penetrance matrix:
            A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
*missing    1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   0   1   0   
000001      1   0   0   0   0   0   0   0   0   
000002      0   1   0   0   0   0   0   0   0   
000003      0   0   0   0   0   0   1   0   0   

phased penetrance matrix:
            A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
*missing    1   1   1   1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   0   0   0   0   1   0   
000001      1   0   0   0   0   0   0   0   0   0   0   0   
000002      0   1   1   0   0   0   0   0   0   0   0   0   
000003      0   0   0   0   0   0   0   0   0   1   0   0   

unphased penetrance matrix iteration:
*missing      1 [A/A]  1 [A/~Y]  1 [A/B]  1 [B/B]  1 [B/~Y]  1 [A/C]  1 [B/C]  1 [C/C]  1 [C/~Y]
000000        1 [B/~Y]
000001        1 [A/A]
000002        1 [A/B]
000003        1 [A/~Y]

phased penetrance matrix iteration:
*missing      1 [A<A]  1 [A<~Y]  1 [A<B]  1 [B<A]  1 [B<B]  1 [B<~Y]  1 [A<C]  1 [C<A]  1 [B<C]  1 [C<B]  1 [C<C]  1 [C<~Y]
000000        1 [B<~Y]
000001        1 [A<A]
000002        1 [A<B]  1 [B<A]
000003        1 [A<~Y]

truetruefalse
************************************
Testing penetrance model Genotype Elimination
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Genotype Elimination
  symmetric: false
 codominant: true
    alleles: A B C
unphased genotypes: A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
phased genotypes: A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
 phenotypes:  000000 000001 000002 000003

unphased penetrance matrix:
            A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
*missing    1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   0   1   0   
000001      1   0   0   0   0   0   0   0   0   
000002      0   1   0   0   0   0   0   0   0   
000003      0   0   0   0   0   0   1   0   0   

phased penetrance matrix:
            A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
*missing    1   1   1   1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   0   0   0   0   1   0   
000001      1   0   0   0   0   0   0   0   0   0   0   0   
000002      0   1   0   0   0   0   0   0   0   0   0   0   
000003      0   0   0   0   0   0   0   0   0   1   0   0   

unphased penetrance matrix iteration:
*missing      1 [A/A]  1 [A/~Y]  1 [A/B]  1 [B/B]  1 [B/~Y]  1 [A/C]  1 [B/C]  1 [C/C]  1 [C/~Y]
000000        1 [B/~Y]
000001        1 [A/A]
000002        1 [A/B]
000003        1 [A/~Y]

phased penetrance matrix iteration:
*missing      1 [A<A]  1 [A<~Y]  1 [A<B]  1 [B<A]  1 [B<B]  1 [B<~Y]  1 [A<C]  1 [C<A]  1 [B<C]  1 [C<B]  1 [C<C]  1 [C<~Y]
000000        1 [B<~Y]
000001        1 [A<A]
000002        1 [A<B]
000003        1 [A<~Y]

truetruefalse
Testing Pedigree Region on 2:2
All Markers
2
************************************
Testing penetrance model Pedigree Region
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Pedigree Region
  symmetric: false
 codominant: true
    alleles: A B C
unphased genotypes: A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
phased genotypes: A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
 phenotypes:  000000 000001 000002 000003

unphased penetrance matrix:
            A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
*missing    1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   0   1   0   
000001      1   0   0   0   0   0   0   0   0   
000002      0   1   0   0   0   0   0   0   0   
000003      0   0   0   0   0   0   1   0   0   

phased penetrance matrix:
            A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
*missing    1   1   1   1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   0   0   0   0   1   0   
000001      1   0   0   0   0   0   0   0   0   0   0   0   
000002      0   1   0   0   0   0   0   0   0   0   0   0   
000003      0   0   0   0   0   0   0   0   0   1   0   0   

unphased penetrance matrix iteration:
*missing      1 [A/A]  1 [A/~Y]  1 [A/B]  1 [B/B]  1 [B/~Y]  1 [A/C]  1 [B/C]  1 [C/C]  1 [C/~Y]
000000        1 [B/~Y]
000001        1 [A/A]
000002        1 [A/B]
000003        1 [A/~Y]

phased penetrance matrix iteration:
*missing      1 [A<A]  1 [A<~Y]  1 [A<B]  1 [B<A]  1 [B<B]  1 [B<~Y]  1 [A<C]  1 [C<A]  1 [B<C]  1 [C<B]  1 [C<C]  1 [C<~Y]
000000        1 [B<~Y]
000001        1 [A<A]
000002        1 [A<B]
000003        1 [A<~Y]

true
Analyzing Marker: 0
************************************
Testing penetrance model Remap 1
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Remap 1
  symmetric: false
 codominant: false
lcodominant: true
    alleles: A B C
unphased genotypes: A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
phased genotypes: A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
 phenotypes:  000000 000001 000002 000003

unphased penetrance matrix:
            A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
*missing    1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   1   1   1   
000001      1   0   0   0   0   0   0   0   0   
000002      1   0   0   0   0   0   0   0   0   
000003      0   1   0   0   0   0   0   0   0   

phased penetrance matrix:
            A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
*missing    1   1   1   1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   0   0   0   1   1   1   
000001      1   0   0   0   0   0   0   0   0   0   0   0   
000002      1   0   0   0   0   0   0   0   0   0   0   0   
000003      0   1   1   0   0   0   0   0   0   0   0   0   

unphased penetrance matrix iteration:
*missing      1 [A/A]  1 [A/~Y]  1 [A/B]  1 [B/B]  1 [B/~Y]  1 [A/C]  1 [B/C]  1 [C/C]  1 [C/~Y]
000000        1 [A/~Y]  1 [B/~Y]  1 [C/~Y]
000001        1 [A/A]
000002        1 [A/A]
000003        1 [A/B]

phased penetrance matrix iteration:
*missing      1 [A<A]  1 [A<~Y]  1 [A<B]  1 [B<A]  1 [B<B]  1 [B<~Y]  1 [A<C]  1 [C<A]  1 [B<C]  1 [C<B]  1 [C<C]  1 [C<~Y]
000000        1 [A<~Y]  1 [B<~Y]  1 [C<~Y]
000001        1 [A<A]
000002        1 [A<A]
000003        1 [A<B]  1 [B<A]

truetruefalse
************************************
Testing penetrance model Genotype Elimination
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Genotype Elimination
  symmetric: false
 codominant: true
    alleles: ~remap
unphased genotypes: ~remap/~remap ~remap/~Y
phased genotypes: ~remap<~remap ~remap<~Y
 phenotypes:  000000 000001 000002 000003

unphased penetrance matrix:
            ~remap/~remap ~remap/~Y
*missing    1   1   
000000      0   1   
000001      1   0   
000002      1   0   
000003      1   0   

phased penetrance matrix:
            ~remap<~remap ~remap<~Y
*missing    1   1   
000000      0   1   
000001      1   0   
000002      1   0   
000003      1   0   

unphased penetrance matrix iteration:
*missing      1 [~remap/~remap]  1 [~remap/~Y]
000000        1 [~remap/~Y]
000001        1 [~remap/~remap]
000002        1 [~remap/~remap]
000003        1 [~remap/~remap]

phased penetrance matrix iteration:
*missing      1 [~remap<~remap]  1 [~remap<~Y]
000000        1 [~remap<~Y]
000001        1 [~remap<~remap]
000002        1 [~remap<~remap]
000003        1 [~remap<~remap]

truetruetrue
Testing Pedigree Region on 3:3
All Markers
3
************************************
Testing penetrance model Pedigree Region
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Pedigree Region
  symmetric: false
 codominant: true
    alleles: ~remap
unphased genotypes: ~remap/~remap ~remap/~Y
phased genotypes: ~remap<~remap ~remap<~Y
 phenotypes:  000000 000001 000002 000003

unphased penetrance matrix:
            ~remap/~remap ~remap/~Y
*missing    1   1   
000000      0   1   
000001      1   0   
000002      1   0   
000003      1   0   

phased penetrance matrix:
            ~remap<~remap ~remap<~Y
*missing    1   1   
000000      0   1   
000001      1   0   
000002      1   0   
000003      1   0   

unphased penetrance matrix iteration:
*missing      1 [~remap/~remap]  1 [~remap/~Y]
000000        1 [~remap/~Y]
000001        1 [~remap/~remap]
000002        1 [~remap/~remap]
000003        1 [~remap/~remap]

phased penetrance matrix iteration:
*missing      1 [~remap<~remap]  1 [~remap<~Y]
000000        1 [~remap<~Y]
000001        1 [~remap<~remap]
000002        1 [~remap<~remap]
000003        1 [~remap<~remap]

true
Analyzing Marker: 0
************************************
Testing penetrance model Remap 1
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Remap 1
  symmetric: false
 codominant: false
lcodominant: true
    alleles: A B C
unphased genotypes: A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
phased genotypes: A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
 phenotypes:  000000 000001 000002 000003 000004

unphased penetrance matrix:
            A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
*missing    1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   1   1   1   
000001      0   1   0   0   0   0   0   0   0   
000002      0   0   0   0   0   0   1   0   0   
000003      0   0   0   0   0   0   0   1   0   
000004      0   1   0   0   0   0   0   0   0   

phased penetrance matrix:
            A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
*missing    1   1   1   1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   0   0   0   1   1   1   
000001      0   1   1   0   0   0   0   0   0   0   0   0   
000002      0   0   0   0   0   0   0   0   0   1   0   0   
000003      0   0   0   0   0   0   0   0   0   0   1   0   
000004      0   1   1   0   0   0   0   0   0   0   0   0   

unphased penetrance matrix iteration:
*missing      1 [A/A]  1 [A/~Y]  1 [A/B]  1 [B/B]  1 [B/~Y]  1 [A/C]  1 [B/C]  1 [C/C]  1 [C/~Y]
000000        1 [A/~Y]  1 [B/~Y]  1 [C/~Y]
000001        1 [A/B]
000002        1 [A/~Y]
000003        1 [B/~Y]
000004        1 [A/B]

phased penetrance matrix iteration:
*missing      1 [A<A]  1 [A<~Y]  1 [A<B]  1 [B<A]  1 [B<B]  1 [B<~Y]  1 [A<C]  1 [C<A]  1 [B<C]  1 [C<B]  1 [C<C]  1 [C<~Y]
000000        1 [A<~Y]  1 [B<~Y]  1 [C<~Y]
000001        1 [A<B]  1 [B<A]
000002        1 [A<~Y]
000003        1 [B<~Y]
000004        1 [A<B]  1 [B<A]

truetruefalse
************************************
Testing penetrance model Genotype Elimination
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Genotype Elimination
  symmetric: false
 codominant: false
lcodominant: true
    alleles: A B C
unphased genotypes: A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
phased genotypes: A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
 phenotypes:  000000 000001 000002 000003 000004

unphased penetrance matrix:
            A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
*missing    1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   1   1   0   
000001      0   1   0   0   0   0   0   0   0   
000002      0   0   0   0   0   0   1   0   0   
000003      0   0   0   0   0   0   0   1   0   
000004      0   1   0   0   0   0   0   0   0   

phased penetrance matrix:
            A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
*missing    1   1   1   1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   0   0   0   1   1   0   
000001      0   1   1   0   0   0   0   0   0   0   0   0   
000002      0   0   0   0   0   0   0   0   0   1   0   0   
000003      0   0   0   0   0   0   0   0   0   0   1   0   
000004      0   1   1   0   0   0   0   0   0   0   0   0   

unphased penetrance matrix iteration:
*missing      1 [A/A]  1 [A/~Y]  1 [A/B]  1 [B/B]  1 [B/~Y]  1 [A/C]  1 [B/C]  1 [C/C]  1 [C/~Y]
000000        1 [A/~Y]  1 [B/~Y]
000001        1 [A/B]
000002        1 [A/~Y]
000003        1 [B/~Y]
000004        1 [A/B]

phased penetrance matrix iteration:
*missing      1 [A<A]  1 [A<~Y]  1 [A<B]  1 [B<A]  1 [B<B]  1 [B<~Y]  1 [A<C]  1 [C<A]  1 [B<C]  1 [C<B]  1 [C<C]  1 [C<~Y]
000000        1 [A<~Y]  1 [B<~Y]
000001        1 [A<B]  1 [B<A]
000002        1 [A<~Y]
000003        1 [B<~Y]
000004        1 [A<B]  1 [B<A]

truetruefalse
Testing Pedigree Region on 4:4
All Markers
4
************************************
Testing penetrance model Pedigree Region
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Pedigree Region
  symmetric: false
 codominant: false
lcodominant: true
    alleles: A B C
unphased genotypes: A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
phased genotypes: A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
 phenotypes:  000000 000001 000002 000003 000004

unphased penetrance matrix:
            A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
*missing    1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   1   1   0   
000001      0   1   0   0   0   0   0   0   0   
000002      0   0   0   0   0   0   1   0   0   
000003      0   0   0   0   0   0   0   1   0   
000004      0   1   0   0   0   0   0   0   0   

phased penetrance matrix:
            A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
*missing    1   1   1   1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   0   0   0   1   1   0   
000001      0   1   1   0   0   0   0   0   0   0   0   0   
000002      0   0   0   0   0   0   0   0   0   1   0   0   
000003      0   0   0   0   0   0   0   0   0   0   1   0   
000004      0   1   1   0   0   0   0   0   0   0   0   0   

unphased penetrance matrix iteration:
*missing      1 [A/A]  1 [A/~Y]  1 [A/B]  1 [B/B]  1 [B/~Y]  1 [A/C]  1 [B/C]  1 [C/C]  1 [C/~Y]
000000        1 [A/~Y]  1 [B/~Y]
000001        1 [A/B]
000002        1 [A/~Y]
000003        1 [B/~Y]
000004        1 [A/B]

phased penetrance matrix iteration:
*missing      1 [A<A]  1 [A<~Y]  1 [A<B]  1 [B<A]  1 [B<B]  1 [B<~Y]  1 [A<C]  1 [C<A]  1 [B<C]  1 [C<B]  1 [C<C]  1 [C<~Y]
000000        1 [A<~Y]  1 [B<~Y]
000001        1 [A<B]  1 [B<A]
000002        1 [A<~Y]
000003        1 [B<~Y]
000004        1 [A<B]  1 [B<A]

true
Analyzing Marker: 0
************************************
Testing penetrance model Remap 1
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Remap 1
  symmetric: false
 codominant: false
lcodominant: true
    alleles: A B C
unphased genotypes: A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
phased genotypes: A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
 phenotypes:  000000 000001 000002 000003 000004 000005 000006

unphased penetrance matrix:
            A/A A/B B/B A/C B/C C/C A/~Y B/~Y C/~Y
*missing    1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   1   1   1   
000001      1   1   1   1   1   1   0   0   0   
000002      0   0   0   0   0   0   1   0   0   
000003      0   0   0   0   0   0   0   1   0   
000004      0   1   0   0   0   0   0   0   0   
000005      1   0   0   0   0   0   0   0   0   
000006      0   0   1   0   0   0   0   0   0   

phased penetrance matrix:
            A<A A<B B<A B<B A<C C<A B<C C<B C<C A<~Y B<~Y C<~Y
*missing    1   1   1   1   1   1   1   1   1   1   1   1   
000000      0   0   0   0   0   0   0   0   0   1   1   1   
000001      1   1   1   1   1   1   1   1   1   0   0   0   
000002      0   0   0   0   0   0   0   0   0   1   0   0   
000003      0   0   0   0   0   0   0   0   0   0   1   0   
000004      0   1   1   0   0   0   0   0   0   0   0   0   
000005      1   0   0   0   0   0   0   0   0   0   0   0   
000006      0   0   0   1   0   0   0   0   0   0   0   0   

unphased penetrance matrix iteration:
*missing      1 [A/A]  1 [A/~Y]  1 [A/B]  1 [B/B]  1 [B/~Y]  1 [A/C]  1 [B/C]  1 [C/C]  1 [C/~Y]
000000        1 [A/~Y]  1 [B/~Y]  1 [C/~Y]
000001        1 [A/A]  1 [A/B]  1 [B/B]  1 [A/C]  1 [B/C]  1 [C/C]
000002        1 [A/~Y]
000003        1 [B/~Y]
000004        1 [A/B]
000005        1 [A/A]
000006        1 [B/B]

phased penetrance matrix iteration:
*missing      1 [A<A]  1 [A<~Y]  1 [A<B]  1 [B<A]  1 [B<B]  1 [B<~Y]  1 [A<C]  1 [C<A]  1 [B<C]  1 [C<B]  1 [C<C]  1 [C<~Y]
000000        1 [A<~Y]  1 [B<~Y]  1 [C<~Y]
000001        1 [A<A]  1 [A<B]  1 [B<A]  1 [B<B]  1 [A<C]  1 [C<A]  1 [B<C]  1 [C<B]  1 [C<C]
000002        1 [A<~Y]
000003        1 [B<~Y]
000004        1 [A<B]  1 [B<A]
000005        1 [A<A]
000006        1 [B<B]

truetruefalse
************************************
Testing penetrance model Genotype Elimination
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Genotype Elimination
  symmetric: false
 codominant: true
    alleles: ~remap
unphased genotypes: ~remap/~remap ~remap/~Y
phased genotypes: ~remap<~remap ~remap<~Y
 phenotypes:  000000 000001 000002 000003 000004 000005 000006

unphased penetrance matrix:
            ~remap/~remap ~remap/~Y
*missing    1   1   
000000      0   1   
000001      1   0   
000002      0   1   
000003      0   1   
000004      1   0   
000005      1   0   
000006      1   0   

phased penetrance matrix:
            ~remap<~remap ~remap<~Y
*missing    1   1   
000000      0   1   
000001      1   0   
000002      0   1   
000003      0   1   
000004      1   0   
000005      1   0   
000006      1   0   

unphased penetrance matrix iteration:
*missing      1 [~remap/~remap]  1 [~remap/~Y]
000000        1 [~remap/~Y]
000001        1 [~remap/~remap]
000002        1 [~remap/~Y]
000003        1 [~remap/~Y]
000004        1 [~remap/~remap]
000005        1 [~remap/~remap]
000006        1 [~remap/~remap]

phased penetrance matrix iteration:
*missing      1 [~remap<~remap]  1 [~remap<~Y]
000000        1 [~remap<~Y]
000001        1 [~remap<~remap]
000002        1 [~remap<~Y]
000003        1 [~remap<~Y]
000004        1 [~remap<~remap]
000005        1 [~remap<~remap]
000006        1 [~remap<~remap]

truetruetrue
Testing Pedigree Region on 5:5
All Markers
5
************************************
Testing penetrance model Pedigree Region
.............allele count OK
............allele lookup OK
..unphased genotype count OK
.unphased genotype lookup OK
....phased genotype count OK
...phased genotype lookup OK

..........phenotype count OK
.........phenotype lookup OK

************************************
Printing penetrance model Pedigree Region
  symmetric: false
 codominant: true
    alleles: ~remap
unphased genotypes: ~remap/~remap ~remap/~Y
phased genotypes: ~remap<~remap ~remap<~Y
 phenotypes:  000000 000001 000002 000003 000004 000005 000006

unphased penetrance matrix:
            ~remap/~remap ~remap/~Y
*missing    1   1   
000000      0   1   
000001      1   0   
000002      0   1   
000003      0   1   
000004      1   0   
000005      1   0   
000006      1   0   

phased penetrance matrix:
            ~remap<~remap ~remap<~Y
*missing    1   1   
000000      0   1   
000001      1   0   
000002      0   1   
000003      0   1   
000004      1   0   
000005      1   0   
000006      1   0   

unphased penetrance matrix iteration:
*missing      1 [~remap/~remap]  1 [~remap/~Y]
000000        1 [~remap/~Y]
000001        1 [~remap/~remap]
000002        1 [~remap/~Y]
000003        1 [~remap/~Y]
000004        1 [~remap/~remap]
000005        1 [~remap/~remap]
000006        1 [~remap/~remap]

phased penetrance matrix iteration:
*missing      1 [~remap<~remap]  1 [~remap<~Y]
000000        1 [~remap<~Y]
000001        1 [~remap<~remap]
000002        1 [~remap<~Y]
000003        1 [~remap<~Y]
000004        1 [~remap<~remap]
000005        1 [~remap<~remap]
000006        1 [~remap<~remap]

true
