


Reading Parameter File....................done.
Reading Pedigree File.....................
              from model2rep1.dat.........done.
Sorting Pedigrees.........................done.
Reading pairs.............................done.
Sorting pairs.............................done.

RELPAL analysis.......  1
  Performing second level score test......done.

RELPAL analysis.......  2
  Performing second level score test......done.

Analysis complete!



