



Family structure information on the first 10 individuals read from file: model2rep1.dat

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             m         0             0           
     1             2             f         0             0           
     1             3             m         1             2           
     1             4             f         1             2           
     2             1             m         0             0           
     2             2             f         0             0           
     2             3             m         1             2           
     2             4             f         1             2           
     3             1             m         0             0           
     3             2             f         0             0           


Phenotypes for the first 10 individuals read from file: model2rep1.dat

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         covariate             X1                    X2                    X3                  
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     4                     -999                  -999                  -999                  -999                
     1             2             1                     1                     1                     4                     -999                  -999                  -999                  -999                
     1             3             0                     1                     0                     4                     0.664272              -1.04572              -0.665403             0.909093            
     1             4             1                     1                     0                     4                     -0.437045             0.398023              1.31696               -2.1747             
     2             1             0                     1                     1                     4                     -999                  -999                  -999                  -999                
     2             2             1                     1                     1                     4                     -999                  -999                  -999                  -999                
     2             3             0                     1                     0                     4                     1.08863               2.3945                4.12877               1.402               
     2             4             1                     1                     0                     4                     0.4857                -0.669353             1.03826               -1.38305            
     3             1             0                     1                     1                     4                     -999                  -999                  -999                  -999                
     3             2             1                     1                     1                     4                     -999                  -999                  -999                  -999                


Markers for the first 10 individuals read from file: model2rep1.dat

     PED. ID       IND. ID       marker      
     ------------  ------------  ------------
     1             1             1/2         
     1             2             3/4         
     1             3             1/4         
     1             4             2/3         
     2             1             1/2         
     2             2             3/4         
     2             3             1/4         
     2             4             1/4         
     3             1             1/2         
     3             2             3/4         


RELPAL analysis.......1  

%RELPAL-I: No Markers are specified for the single_marker model.  Using all
           markers from the ibd file...

=================================
  Relpal Analysis Specification  
=================================

model: multiple traits, single marker

trait:
   trait 1: X1
   trait 2: X2
   trait 3: X3

first_level:
  covariate 1: covariate, adj_t = all

second_level:
  test marker 1: marker

data options:
  use_members = every
  use_pairs = all

output options:
  detailed_out = yes
  export_out = no
  data_out = no
  debug_out = no
  residual_out = no

asymptotic pvalue options:
  seed = 100
  replicates = 0
  min_replicates = 20
  max_replicates = 10000
  threshold = 0.05
  width = 0.2
  confidence = 0.95

variance options:
  naive variance = true
  robust sandwich variance = true
  alternative variance = true
  IBD variance conditional on trait = true



RELPAL analysis.......2  

%RELPAL-I: No Markers are specified for the single_marker model.  Using all
           markers from the ibd file...

=================================
  Relpal Analysis Specification  
=================================

model: multiple traits, single marker

trait:
   trait 1: X1
   trait 2: X2
   trait 3: X3

first_level:
  covariate 1: covariate, adj_t = all

transform residuals from 1st level to 2nd level

second_level:
  test marker 1: marker

data options:
  use_members = every
  use_pairs = all

output options:
  detailed_out = yes
  export_out = yes
  data_out = no
  debug_out = no
  residual_out = no

asymptotic pvalue options:
  seed = 100
  replicates = 0
  min_replicates = 20
  max_replicates = 10000
  threshold = 0.05
  width = 0.2
  confidence = 0.95

variance options:
  naive variance = true
  robust sandwich variance = true
  alternative variance = true
  IBD variance conditional on trait = true


