


==============================================================================================
  Two-Level Haseman-Elston Regression Analysis for General Pedigree 

  - Second (Pedigree) Level Score Tests Detailed Output
==============================================================================================

  Traits : (1) - X1, Quantitative
           (2) - X2, Quantitative
           (3) - X3, Quantitative

  Legend :
    *   - significance  .05 level
    **  - significance  .01 level
    *** - significance .001 level

    nai - naive variance
    sdw - robust sandwich variance
    alt - alternative variance
    ibd - allele sharing variance

    #   - The number of pedigrees is too small for this result to be
          reliable when analyzing this number of traits.

  Empirical p-value options used :
    seed = 100
    min replicates = 20
    max replicates = 10000

==============================================================================================
Test 1
==============================================================================================
-----
Model
-----

H0: X1, X2, X3 ~ [Intercept + covariate] + POLYGENIC_EFF + RANDOM_EFF
H1: X1, X2, X3 ~ [Intercept + covariate] + marker + POLYGENIC_EFF + RANDOM_EFF

------------
Sample Count
------------

Number of individuals used at first level     = 4000
Number of relative pairs used at second level = 2000

-----------------
Estimates from H0
-----------------

Test                                                                             Nominal    
Variable                      Estimate Variance-Covariance             Chi-sq.   P-value    
------------------------- ------------ ----------------------------- --------- ---------    
covariate(1)                    1.0228    0.0028    0.0009    0.0008  660.4803 0.0000000 ***
covariate(2)                    0.9503    0.0009    0.0028    0.0008
covariate(3)                    0.9779    0.0008    0.0008    0.0027

------------------
Score Test Results
------------------

Test                          Unadjusted   Adjusted Empirical     Number of 
Variable                  Var    T-value    T-value   P-value     Replicates
------------------------- --- ---------- ---------- ---------     ----------
marker                    nai   121.0349   119.9349 0.0000000 ***      10000
                          sdw   102.9708   101.8313 0.0000000 ***      10000
                          alt   114.3961   113.2553 0.0000000 ***      10000
                          ibd   124.5934   123.3914 0.0000000 ***      10000

==============================================================================================

==============================================================================================
  Two-Level Haseman-Elston Regression Analysis for General Pedigree 

  - Second (Pedigree) Level Score Tests Detailed Output
==============================================================================================

  Traits : (1) - X1, Quantitative
           (2) - X2, Quantitative
           (3) - X3, Quantitative

  Legend :
    *   - significance  .05 level
    **  - significance  .01 level
    *** - significance .001 level

    nai - naive variance
    sdw - robust sandwich variance
    alt - alternative variance
    ibd - allele sharing variance

    #   - The number of pedigrees is too small for this result to be
          reliable when analyzing this number of traits.

  Empirical p-value options used :
    seed = 100
    min replicates = 20
    max replicates = 10000

==============================================================================================
Test 1
==============================================================================================
-----
Model
-----

H0: X1, X2, X3 ~ [Intercept + covariate] + POLYGENIC_EFF + RANDOM_EFF
H1: X1, X2, X3 ~ [Intercept + covariate] + marker + POLYGENIC_EFF + RANDOM_EFF

------------
Sample Count
------------

Number of individuals used at first level     = 4000
Number of relative pairs used at second level = 2000

-----------------
Estimates from H0
-----------------

Test                                                                             Nominal    
Variable                      Estimate Variance-Covariance             Chi-sq.   P-value    
------------------------- ------------ ----------------------------- --------- ---------    
covariate(1)                    1.0228    0.0028    0.0009    0.0008  660.9220 0.0000000 ***
covariate(2)                    0.9502    0.0009    0.0028    0.0008
covariate(3)                    0.9780    0.0008    0.0008    0.0027

------------------
Score Test Results
------------------

Test                          Unadjusted   Adjusted Empirical     Number of 
Variable                  Var    T-value    T-value   P-value     Replicates
------------------------- --- ---------- ---------- ---------     ----------
marker                    nai   121.3421   120.1032 0.0000000 ***      10000
                          sdw   102.9494   101.6709 0.0000000 ***      10000
                          alt   114.3697   113.0895 0.0000000 ***      10000
                          ibd   125.0300   123.6683 0.0000000 ***      10000

==============================================================================================

