


Reading Parameter File....................done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Reading pairs.............................done.
Sorting pairs.............................done.

SIBPAL analysis.......  1

Computing mean test.......................done.

SIBPAL analysis.......  2

Computing mean test.......................done.

SIBPAL analysis.......  3

Computing trait regression................done.

SIBPAL analysis.......  4

Computing trait regression................done.

SIBPAL analysis.......  5

Computing trait regression................done.

Analysis complete!



