


==========
Analysis 2
==========


Markers in order:
  m1 m2 



                      All Possible Haplotype Combinations


                              Pedigree:Member
                    1:1 
1-1  1-1  2-1  2-1   x  
1-1  1-1  2-1  2-2   x  
1-1  1-1  2-2  2-2   x  
1-1  1-2  2-1  2-1   x  
1-1  1-2  2-1  2-2   x  
1-1  1-2  2-2  2-2   x  
1-2  1-2  2-1  2-1   x  
1-2  1-2  2-1  2-2   x  
1-2  1-2  2-2  2-2   x  


