


==========
Analysis 2
==========


Options Selected
================
Haplotype region                                   all
Minor allele frequency filter                      no
Sliding window                                     no
Four gamete rule blocks                            no
LD blocks                                          no

Subpopulations specified                           no
Analysis unit                                      family founders

Estimate haplotype frequencies                     no
Show all possible haplotype combinations table     yes
List most likely haplotype combinations            no
Do likelihood ratio test                           no
Compute empirical p-value                          no


Results
=======


Markers in order:
  m1 m2 



