


Reading Parameter File....................done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Reading Genome Description File...........done.

Parsing DECIPHER analyses ...


Parsing new analysis block ...


Parsing of Analysis 1 complete.  Analysis valid.
------------------------------------------------------------------------------

  Performing analysis: Analysis 1
  ===========================================================================

    Total population. 
      Determining possible haplotype combinations ................
                                                                  ... done.

  ===========================================================================


Parsing new analysis block ...


Parsing of Analysis 2 complete.  Analysis valid.
------------------------------------------------------------------------------

  Performing analysis: Analysis 2
  ===========================================================================

    Total population. 
      Determining possible haplotype combinations ................
                                                                  ... done.

  ===========================================================================



