# Makefile for globals 
#
#  Author: Geoff Wedig
#
#  History:   1.0   gcw  Initial creation              2004, Aug
#
#  Copyright (c) 2004  R.C. Elston
#

# NOTE:  At present (2004, Aug), there are no ipp or cpp files associated
#        with the S.A.G.E. globals directory.  Despite that, we need the
#        globals to be part of the make system to allow for documentation
#        and other utilities.  Thus we have this directory and this empty
#        Makefile. It is possible that in the future, there will be need for
#        this Makefile directly.

#==========================================================================
# General target options                                                  |
#--------------------------------------------------------------------------
  LSFROOT=..
  SAGEROOT=../..

  include $(SAGEROOT)/config/Global.make

  TARGET_NAME = Global Configuration Options
  TARGET      =
  TARGETS     = 
  TESTTARGETS = 
  VERSION     = 
  TARPREFIX   = 
  TESTS       = true

include $(SAGEROOT)/config/Rules.make

# DO NOT DELETE THIS LINE -- make depend depends on it.

