=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : one mean
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : 
    Transmission                 : homogeneous no transmission

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean                -1.02875000      0.29035969      0.00000000     Independent
  variance             3.36050913      0.75269853      0.00000000     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean            variance   
----------------------------------------------
  mean       |      0.08430875      0.00000000
  variance   |      0.00000000      0.56655508
----------------------------------------------


        LN(Likelihood) : -80.9994
     -2 LN(Likelihood) : 161.999
    Akaike's AIC score : 165.999
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous no transmission

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB          -1.03387467      5.98718588      0.00000000     Independent
  mean_BB             -1.02790565      1.84494847      0.00000000     Independent
  variance             3.36053521      0.75169149     -0.00008219     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.00544592     13.25134364                     Dependent
  prob_AB              0.13670116     153.0633146                     Dependent
  prob_BB              0.85785291     166.3146582                     Dependent
  freq_A               0.07379651     89.78300094      0.00000000     Independent functional
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A     
------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |     35.84639477     -8.80684231      0.08813832     -32.2862152     -372.930870     405.2170857     -218.751650
  mean_BB    |     -8.80684231      3.40383485     -0.03276188     20.77364376     239.9517255     -260.725369     140.7495065
  variance   |      0.08813832     -0.03276188      0.56504009     -0.20413038     -2.35786443      2.56199481     -1.38306259
  prob_AA    |     -32.2862152     20.77364376     -0.20413038     175.5981081     2028.294579     -2203.89268     1189.745397
  prob_AB    |     -372.930870     239.9517255     -2.35786443     2028.294579     23428.37827     -25456.6728     13742.48371
  prob_BB    |     405.2170857     -260.725369      2.56199481     -2203.89268     -25456.6728     27660.56554     -14932.2291
  freq_A     |     -218.751650     140.7495065     -1.38306259     1189.745397     13742.48371     -14932.2291     8060.987256
------------------------------------------------------------------------------------------------------------------------------

 Likelihood Surface Flat: variance matrix near singular and 
 may be affected by rounding error 
 Reducing the number of parameters to be estimated is recommended 

        LN(Likelihood) : -80.9994
     -2 LN(Likelihood) : 161.999
    Akaike's AIC score : 169.999
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous mendelian

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB          -1.17722291      0.27805744     -0.00011732     Independent
  mean_BB              3.70187564      2.58352263     -0.00003731     Independent
  variance             2.65828327      0.69494170     -0.00046758     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.66743398      0.20192274                     Dependent
  prob_AB              0.29906469      0.15668384                     Dependent
  prob_BB              0.03350132      0.04523890                     Dependent
  freq_A               0.81696633      0.12358082      0.00000000     Independent functional
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.50000000                                     Fixed
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A     
------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.07731594      0.12378923      0.02488536      0.01264614     -0.00981289     -0.00283325      0.00773970
  mean_BB    |      0.12378923      6.67458918     -0.08442581      0.23740946     -0.18422009     -0.05318937      0.14529942
  variance   |      0.02488536     -0.08442581      0.48294397      0.02444275     -0.01896658     -0.00547617      0.01495946
  prob_AA    |      0.01264614      0.23740946      0.02444275      0.04077279     -0.03163803     -0.00913476      0.02495378
  prob_AB    |     -0.00981289     -0.18422009     -0.01896658     -0.03163803      0.02454983      0.00708821     -0.01936312
  prob_BB    |     -0.00283325     -0.05318937     -0.00547617     -0.00913476      0.00708821      0.00204656     -0.00559066
  freq_A     |      0.00773970      0.14529942      0.01495946      0.02495378     -0.01936312     -0.00559066      0.01527222
------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -80.3885
     -2 LN(Likelihood) : 160.777
    Akaike's AIC score : 168.777
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous general

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB          -1.16691136      0.26075225     -0.00011835     Independent
  mean_BB              4.40984561      1.77804127      0.00000000     Independent
  variance             2.60905969      0.60898544      0.00000000     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              1.00000000                                     Dependent
  prob_AB              0.00000000                                     Dependent
  prob_BB              0.00000000                                     Dependent
  freq_A               1.00000000                      0.00000000     Ind. func. fixed @ bnd
  transm prob_AA       0.77739666      0.11345473      0.00000000     Independent functional
  transm prob_AB       1.00000000                                     Dependent
  transm prob_BB       1.00000000                      0.00000000     Ind. func. fixed @ bnd
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob     transm prob     transm prob
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.06799174      0.00593477      0.00446533      0.00000000      0.00000000      0.00000000      0.00000000      0.00088838      0.00000000      0.00000000
  mean_BB    |      0.00593477      3.16143077     -0.03726767      0.00000000      0.00000000      0.00000000      0.00000000      0.01448891      0.00000000      0.00000000
  variance   |      0.00446533     -0.03726767      0.37086327      0.00000000      0.00000000      0.00000000      0.00000000      0.00279375      0.00000000      0.00000000
  prob_AA    |      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  prob_AB    |      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  prob_BB    |      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  freq_A     |      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00088838      0.01448891      0.00279375      0.00000000      0.00000000      0.00000000      0.00000000      0.01287198      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.5517
     -2 LN(Likelihood) : 159.103
    Akaike's AIC score : 167.103
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : tau AB free

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB           0.38604343      0.59873477      0.00000000     Independent
  mean_BB             -2.02575585      0.37466081      0.00013635     Independent
  variance             1.94985032      0.64518060      0.00063746     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.12641659      0.08659187                     Dependent
  prob_AB              0.45826903      0.07035894                     Dependent
  prob_BB              0.41531438      0.15695082                     Dependent
  freq_A               0.35555111      0.12177135      0.00000000     Independent functional
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.00000000                      0.00000000     Ind. fixed @ bound
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob
----------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.35848333      0.03622113     -0.16962951     -0.02837770     -0.02305788      0.05143558     -0.03990664      0.00000000
  mean_BB    |      0.03622113      0.14037072      0.04679827     -0.01167223     -0.00948410      0.02115633     -0.01641428      0.00000000
  variance   |     -0.16962951      0.04679827      0.41625801      0.01028992      0.00836092     -0.01865084      0.01447038      0.00000000
  prob_AA    |     -0.02837770     -0.01167223      0.01028992      0.00749815      0.00609251     -0.01359067      0.01054441      0.00000000
  prob_AB    |     -0.02305788     -0.00948410      0.00836092      0.00609251      0.00495038     -0.01104289      0.00856770      0.00000000
  prob_BB    |      0.05143558      0.02115633     -0.01865084     -0.01359067     -0.01104289      0.02463356     -0.01911211      0.00000000
  freq_A     |     -0.03990664     -0.01641428      0.01447038      0.01054441      0.00856770     -0.01911211      0.01482826      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
----------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.0659
     -2 LN(Likelihood) : 158.132
    Akaike's AIC score : 166.132
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : general

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB           0.38606140      0.52002625      0.00027621     Independent
  mean_BB             -2.02568625      0.37236154      0.00027271     Independent
  variance             1.95003144      0.62501576      0.00007082     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.12638649      0.08324680                     Dependent
  prob_AB              0.45824457      0.06766883                     Dependent
  prob_BB              0.41536894      0.15091563                     Dependent
  freq_A               0.35550877      0.11708122      0.00000000     Independent functional
  transm prob_AA       1.00000000                      0.00000000     Ind. fixed @ bound
  transm prob_AB       0.00000000                      0.00000000     Ind. fixed @ bound
  transm prob_BB       0.00000000                      0.00000000     Ind. fixed @ bound
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob     transm prob     transm prob
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.27042730      0.02702409     -0.12582098     -0.02145610     -0.01744102      0.03889711     -0.03017660      0.00000000      0.00000000      0.00000000
  mean_BB    |      0.02702409      0.13865311      0.05039971     -0.01088709     -0.00884979      0.01973689     -0.01531199      0.00000000      0.00000000      0.00000000
  variance   |     -0.12582098      0.05039971      0.39064470      0.00690897      0.00561610     -0.01252507      0.00971702      0.00000000      0.00000000      0.00000000
  prob_AA    |     -0.02145610     -0.01088709      0.00690897      0.00693003      0.00563321     -0.01256324      0.00974664      0.00000000      0.00000000      0.00000000
  prob_AB    |     -0.01744102     -0.00884979      0.00561610      0.00563321      0.00457907     -0.01021228      0.00792275      0.00000000      0.00000000      0.00000000
  prob_BB    |      0.03889711      0.01973689     -0.01252507     -0.01256324     -0.01021228      0.02277553     -0.01766939      0.00000000      0.00000000      0.00000000
  freq_A     |     -0.03017660     -0.01531199      0.00971702      0.00974664      0.00792275     -0.01766939      0.01370801      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.0659
     -2 LN(Likelihood) : 158.132
    Akaike's AIC score : 166.132
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous no transmission

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA              3.94472821      1.63795004     -0.00007002     Independent
  mean_AB              0.22516539      0.37422870      0.00000000     Independent
  mean_BB             -2.30169004      0.36294186      0.00042002     Independent
  variance             0.99256398      0.41197714     -0.00027828     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.05955596      0.03430543                     Dependent
  prob_AB              0.36896988      0.07196160                     Dependent
  prob_BB              0.57147416      0.10626704                     Dependent
  freq_A               0.24404090      0.07028623      0.00000000     Independent functional
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A     
----------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      2.68288034      0.29390375      0.14927513      0.06754235     -0.02207594     -0.04630813      0.06838407     -0.04523001
  mean_AB    |      0.29390375      0.14004712      0.04810630      0.00795646     -0.00618158     -0.01296693      0.01914851     -0.01266504
  mean_BB    |      0.14927513      0.04810630      0.13172679      0.08453855     -0.00666364     -0.01397813      0.02064177     -0.01365270
  variance   |      0.06754235      0.00795646      0.08453855      0.16972517     -0.00484105     -0.01015494      0.01499599     -0.00991852
  prob_AA    |     -0.02207594     -0.00618158     -0.00666364     -0.00484105      0.00117686      0.00246867     -0.00364554      0.00241120
  prob_AB    |     -0.04630813     -0.01296693     -0.01397813     -0.01015494      0.00246867      0.00517847     -0.00764715      0.00505791
  prob_BB    |      0.06838407      0.01914851      0.02064177      0.01499599     -0.00364554     -0.00764715      0.01129268     -0.00746911
  freq_A     |     -0.04523001     -0.01266504     -0.01365270     -0.00991852      0.00241120      0.00505791     -0.00746911      0.00494015
----------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.4468
     -2 LN(Likelihood) : 158.894
    Akaike's AIC score : 168.894
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous no transmission

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA              3.94465234      1.65177090      0.00000000     Independent
  mean_AB              0.22516059      0.37669773      0.00000000     Independent
  mean_BB             -2.30168381      0.36478295      0.00024001     Independent
  variance             0.99255974      0.41513753     -0.00013914     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.05955645      0.03442458                     Dependent
  prob_AB              0.36897090      0.07221096                     Dependent
  prob_BB              0.57147265      0.10663553                     Dependent
  freq_A               0.24404190      0.07053005      0.00000000     Independent functional
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A     
----------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      2.72834711      0.30144321      0.15433295      0.07218238     -0.02256448     -0.04733254      0.06989701     -0.04623075
  mean_AB    |      0.30144321      0.14190118      0.04947329      0.00924485     -0.00629371     -0.01320204      0.01949574     -0.01289473
  mean_BB    |      0.15433295      0.04947329      0.13306660      0.08626239     -0.00676816     -0.01419727      0.02096543     -0.01386679
  variance   |      0.07218238      0.00924485      0.08626239      0.17233917     -0.00496725     -0.01041959      0.01538684     -0.01017704
  prob_AA    |     -0.02256448     -0.00629371     -0.00676816     -0.00496725      0.00118505      0.00248583     -0.00367088      0.00242797
  prob_AB    |     -0.04733254     -0.01320204     -0.01419727     -0.01041959      0.00248583      0.00521442     -0.00770025      0.00509304
  prob_BB    |      0.06989701      0.01949574      0.02096543      0.01538684     -0.00367088     -0.00770025      0.01137114     -0.00752101
  freq_A     |     -0.04623075     -0.01289473     -0.01386679     -0.01017704      0.00242797      0.00509304     -0.00752101      0.00497449
----------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.4468
     -2 LN(Likelihood) : 158.894
    Akaike's AIC score : 168.894
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous mendelian

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA             -2.52802965      0.24124466     -0.00010926     Independent
  mean_AB              0.14927315      0.22829304     -0.00055243     Independent
  mean_BB              4.51960550      0.90794781      0.00024446     Independent
  variance             0.82427475      0.23797749     -0.00067020     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.49456601      0.10424565                     Dependent
  prob_AB              0.41737573      0.06025799                     Dependent
  prob_BB              0.08805827      0.04398766                     Dependent
  freq_A               0.70325387      0.07411665      0.00000000     Independent functional
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.50000000                                     Fixed
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A     
----------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.05819899      0.00599210     -0.00003716      0.01197111      0.00208493     -0.00120517     -0.00087976      0.00148235
  mean_AB    |      0.00599210      0.05211771      0.00002219     -0.00542761      0.00097099     -0.00056127     -0.00040972      0.00069036
  mean_BB    |     -0.00003716      0.00002219      0.82436923     -0.00021552      0.00000035     -0.00000020     -0.00000015      0.00000025
  variance   |      0.01197111     -0.00542761     -0.00021552      0.05663329      0.00143712     -0.00083071     -0.00060641      0.00102177
  prob_AA    |      0.00208493      0.00097099      0.00000035      0.00143712      0.01086716     -0.00628163     -0.00458552      0.00772634
  prob_AB    |     -0.00120517     -0.00056127     -0.00000020     -0.00083071     -0.00628163      0.00363103      0.00265061     -0.00446612
  prob_BB    |     -0.00087976     -0.00040972     -0.00000015     -0.00060641     -0.00458552      0.00265061      0.00193491     -0.00326022
  freq_A     |      0.00148235      0.00069036      0.00000025      0.00102177      0.00772634     -0.00446612     -0.00326022      0.00549328
----------------------------------------------------------------------------------------------------------------------------------------------

 Likelihood Surface Flat: variance matrix near singular and 
 may be affected by rounding error 
 Reducing the number of parameters to be estimated is recommended 

        LN(Likelihood) : -77.8935
     -2 LN(Likelihood) : 155.787
    Akaike's AIC score : 165.787
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous general

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA             -2.52805208      0.24113999     -0.00005463     Independent
  mean_AB              0.14924536      0.22672503      0.00000000     Independent
  mean_BB              4.51981964      0.90705133      0.00000000     Independent
  variance             0.82423397      0.23732784      0.00000000     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.49453729      0.10423955                     Dependent
  prob_AB              0.41739233      0.06025016                     Dependent
  prob_BB              0.08807038      0.04398939                     Dependent
  freq_A               0.70323345      0.07411447      0.00000000     Independent functional
  transm prob_AA       1.00000000                      0.00000000     Ind. func. fixed @ bnd
  transm prob_AB       0.50000000                                     Dependent
  transm prob_BB       0.00000000                      0.00000000     Ind. func. fixed @ bnd
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob     transm prob     transm prob
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.05814849      0.00585710      0.00003637      0.01194388      0.00208118     -0.00120292     -0.00087827      0.00147972      0.00000000      0.00000000      0.00000000
  mean_AB    |      0.00585710      0.05140424      0.00057083     -0.00533329      0.00095663     -0.00055293     -0.00040370      0.00068016      0.00000000      0.00000000      0.00000000
  mean_BB    |      0.00003637      0.00057083      0.82274211     -0.00019035      0.00001258     -0.00000727     -0.00000531      0.00000894      0.00000000      0.00000000      0.00000000
  variance   |      0.01194388     -0.00533329     -0.00019035      0.05632450      0.00143139     -0.00082734     -0.00060405      0.00101772      0.00000000      0.00000000      0.00000000
  prob_AA    |      0.00208118      0.00095663      0.00001258      0.00143139      0.01086588     -0.00628045     -0.00458543      0.00772566      0.00000000      0.00000000      0.00000000
  prob_AB    |     -0.00120292     -0.00055293     -0.00000727     -0.00082734     -0.00628045      0.00363008      0.00265037     -0.00446541      0.00000000      0.00000000      0.00000000
  prob_BB    |     -0.00087827     -0.00040370     -0.00000531     -0.00060405     -0.00458543      0.00265037      0.00193507     -0.00326025      0.00000000      0.00000000      0.00000000
  freq_A     |      0.00147972      0.00068016      0.00000894      0.00101772      0.00772566     -0.00446541     -0.00326025      0.00549296      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 Likelihood Surface Flat: variance matrix near singular and 
 may be affected by rounding error 
 Reducing the number of parameters to be estimated is recommended 

        LN(Likelihood) : -77.8935
     -2 LN(Likelihood) : 155.787
    Akaike's AIC score : 165.787
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : tau AB free

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA             -2.50615356      0.24106902      0.00011021     Independent
  mean_AB              0.17358055      0.22806049      0.00000000     Independent
  mean_BB              4.51982618      0.90587204      0.00000000     Independent
  variance             0.82076740      0.23457730      0.00000000     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.49163334      0.10398381                     Dependent
  prob_AB              0.41906472      0.05966628                     Dependent
  prob_BB              0.08930194      0.04431753                     Dependent
  freq_A               0.70116570      0.07415067      0.00000000     Independent functional
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.60355113      0.11216711      0.00000000     Independent
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob
--------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.05811427      0.00689987     -0.00001912      0.01214349      0.00162642     -0.00093324     -0.00069317      0.00115979      0.00359226
  mean_AB    |      0.00689987      0.05201159      0.00003686     -0.00414024      0.00104820     -0.00060146     -0.00044674      0.00074747      0.00295777
  mean_BB    |     -0.00001912      0.00003686      0.82060415     -0.00012553      0.00000546     -0.00000313     -0.00000233      0.00000389     -0.00000034
  variance   |      0.01214349     -0.00414024     -0.00012553      0.05502651      0.00074599     -0.00042805     -0.00031794      0.00053196      0.00084715
  prob_AA    |      0.00162642      0.00104820      0.00000546      0.00074599      0.01081263     -0.00620433     -0.00460831      0.00771047     -0.00026429
  prob_AB    |     -0.00093324     -0.00060146     -0.00000313     -0.00042805     -0.00620433      0.00356007      0.00264426     -0.00442429      0.00015165
  prob_BB    |     -0.00069317     -0.00044674     -0.00000233     -0.00031794     -0.00460831      0.00264426      0.00196404     -0.00328617      0.00011264
  freq_A     |      0.00115979      0.00074747      0.00000389      0.00053196      0.00771047     -0.00442429     -0.00328617      0.00549832     -0.00018846
  transm prob|      0.00359226      0.00295777     -0.00000034      0.00084715     -0.00026429      0.00015165      0.00011264     -0.00018846      0.01258146
--------------------------------------------------------------------------------------------------------------------------------------------------------------

 Likelihood Surface Flat: variance matrix near singular and 
 may be affected by rounding error 
 Reducing the number of parameters to be estimated is recommended 

        LN(Likelihood) : -77.4811
     -2 LN(Likelihood) : 154.962
    Akaike's AIC score : 166.962
=====================================================================================================

%SEGREG-W: Accumulation of round off errors or boundary problem 
%SEGREG-W: Check results carefully 


=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : general

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA              3.11660103      1.05641916      0.00004431     Independent
  mean_AB              0.00045441      0.27472511      0.00000000     Independent
  mean_BB             -2.54878072      0.23125652      0.00000000     Independent
  variance             0.77768926      0.23213027      0.00017759     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.11218115      0.05677109                     Dependent
  prob_AB              0.44550679      0.05595688                     Dependent
  prob_BB              0.44231207      0.11272796                     Dependent
  freq_A               0.33493454      0.08474953      0.00000000     Independent functional
  transm prob_AA       0.11648562      0.34982243      0.00000000     Independent
  transm prob_AB       0.44638915      0.12678567      0.00000000     Independent
  transm prob_BB       0.00000000                      0.00000000     Ind. fixed @ bound
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob     transm prob     transm prob
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      1.11602143      0.12857052      0.01775422     -0.00879570     -0.02160734     -0.02129745      0.04290479     -0.03225607     -0.14091195     -0.02375207      0.00000000
  mean_AB    |      0.12857052      0.07547389      0.00938165     -0.00590656     -0.00432508     -0.00426305      0.00858812     -0.00645660     -0.02675521     -0.00672495      0.00000000
  mean_BB    |      0.01775422      0.00938165      0.05347958      0.00867376     -0.00111043     -0.00109451      0.00220494     -0.00165769     -0.00589271     -0.00365359      0.00000000
  variance   |     -0.00879570     -0.00590656      0.00867376      0.05388446     -0.00000614     -0.00000605      0.00001219     -0.00000916     -0.00550098     -0.00030869      0.00000000
  prob_AA    |     -0.02160734     -0.00432508     -0.00111043     -0.00000614      0.00322296      0.00317673     -0.00639969      0.00481132      0.00439063      0.00045468      0.00000000
  prob_AB    |     -0.02129745     -0.00426305     -0.00109451     -0.00000605      0.00317673      0.00313117     -0.00630790      0.00474232      0.00432766      0.00044816      0.00000000
  prob_BB    |      0.04290479      0.00858812      0.00220494      0.00001219     -0.00639969     -0.00630790      0.01270759     -0.00955364     -0.00871829     -0.00090285      0.00000000
  freq_A     |     -0.03225607     -0.00645660     -0.00165769     -0.00000916      0.00481132      0.00474232     -0.00955364      0.00718248      0.00655446      0.00067877      0.00000000
  transm prob|     -0.14091195     -0.02675521     -0.00589271     -0.00550098      0.00439063      0.00432766     -0.00871829      0.00655446      0.12237573     -0.00192911      0.00000000
  transm prob|     -0.02375207     -0.00672495     -0.00365359     -0.00030869      0.00045468      0.00044816     -0.00090285      0.00067877     -0.00192911      0.01607461      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -76.5633
     -2 LN(Likelihood) : 153.127
    Akaike's AIC score : 167.127
=====================================================================================================

%SEGREG-W: Accumulation of round off errors or boundary problem 
%SEGREG-W: Check results carefully 


