=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : one mean
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : 
    Transmission                 : homogeneous no transmission

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean                -1.02875087      0.28984865      0.00001032     Independent
  variance             3.36048983      0.75142363      0.00003738     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean            variance   
----------------------------------------------
  mean       |      0.08401224     -0.00000015
  variance   |     -0.00000015      0.56463748
----------------------------------------------


        LN(Likelihood) : -80.9994
     -2 LN(Likelihood) : 161.999
    Akaike's AIC score : 165.999
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous no transmission

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB           3.66434055      2.39149297      0.00003403     Independent
  mean_BB             -1.19375639      0.27818578      0.00014778     Independent
  variance             2.58616938      0.64207600     -0.00003784     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.00029333      0.00075563                     Dependent
  prob_AB              0.03366728      0.04260831                     Dependent
  prob_BB              0.96603938      0.04336395                     Dependent
  freq_A               0.01712698      0.02205979      0.00000000     Independent functional
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A     
------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      5.71923863      0.16556982      0.14746414     -0.00103846     -0.05855609      0.05959455     -0.03031650
  mean_BB    |      0.16556982      0.07738733      0.02177028     -0.00005641     -0.00318089      0.00323730     -0.00164686
  variance   |      0.14746414      0.02177028      0.41226159     -0.00009340     -0.00526660      0.00536000     -0.00272670
  prob_AA    |     -0.00103846     -0.00005641     -0.00009340      0.00000057      0.00003220     -0.00003277      0.00001667
  prob_AB    |     -0.05855609     -0.00318089     -0.00526660      0.00003220      0.00181547     -0.00184766      0.00093993
  prob_BB    |      0.05959455      0.00323730      0.00536000     -0.00003277     -0.00184766      0.00188043     -0.00095660
  freq_A     |     -0.03031650     -0.00164686     -0.00272670      0.00001667      0.00093993     -0.00095660      0.00048663
------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -80.0166
     -2 LN(Likelihood) : 160.033
    Akaike's AIC score : 168.033
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous mendelian

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB          -1.17722833      0.27884244     -0.00025545     Independent
  mean_BB              3.70177310      2.59489768     -0.00004714     Independent
  variance             2.65810160      0.69564763     -0.00010858     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.66740234      0.20230590                     Dependent
  prob_AB              0.29908925      0.15697528                     Dependent
  prob_BB              0.03350842      0.04533062                     Dependent
  freq_A               0.81694696      0.12381826      0.00000000     Independent functional
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.50000000                                     Fixed
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A     
------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.07775311      0.12520035      0.02500072      0.01272877     -0.00987664     -0.00285213      0.00779045
  mean_BB    |      0.12520035      6.73349398     -0.08338440      0.24008869     -0.18629209     -0.05379659      0.14694264
  variance   |      0.02500072     -0.08338440      0.48392562      0.02456271     -0.01905895     -0.00550376      0.01503323
  prob_AA    |      0.01272877      0.24008869      0.02456271      0.04092768     -0.03175703     -0.00917065      0.02504916
  prob_AB    |     -0.00987664     -0.18629209     -0.01905895     -0.03175703      0.02464124      0.00711579     -0.01943641
  prob_BB    |     -0.00285213     -0.05379659     -0.00550376     -0.00917065      0.00711579      0.00205486     -0.00561276
  freq_A     |      0.00779045      0.14694264      0.01503323      0.02504916     -0.01943641     -0.00561276      0.01533096
------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -80.3885
     -2 LN(Likelihood) : 160.777
    Akaike's AIC score : 168.777
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous general

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB          -1.16692048      0.26048437      0.00001457     Independent
  mean_BB              4.40986795      1.76902827      0.00000090     Independent
  variance             2.60905702      0.60823226      0.00000711     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              1.00000000                                     Dependent
  prob_AB              0.00000000                                     Dependent
  prob_BB              0.00000000                                     Dependent
  freq_A               1.00000000                      0.00000000     Ind. func. fixed @ bnd
  transm prob_AA       0.77739746      0.11337795      0.00000000     Independent functional
  transm prob_AB       1.00000000                                     Dependent
  transm prob_BB       1.00000000                      0.00000000     Ind. func. fixed @ bnd
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob     transm prob     transm prob
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.06785210      0.00568593      0.00448202      0.00000000      0.00000000      0.00000000      0.00000000      0.00087438      0.00000000      0.00000000
  mean_BB    |      0.00568593      3.12946102     -0.03771870      0.00000000      0.00000000      0.00000000      0.00000000      0.01438175      0.00000000      0.00000000
  variance   |      0.00448202     -0.03771870      0.36994648      0.00000000      0.00000000      0.00000000      0.00000000      0.00276832      0.00000000      0.00000000
  prob_AA    |      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  prob_AB    |      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  prob_BB    |      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  freq_A     |      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00087438      0.01438175      0.00276832      0.00000000      0.00000000      0.00000000      0.00000000      0.01285456      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.5517
     -2 LN(Likelihood) : 159.103
    Akaike's AIC score : 167.103
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : tau AB free

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB           0.38610202      0.55206378     -0.00001280     Independent
  mean_BB             -2.02569375      0.37329636      0.00049648     Independent
  variance             1.95006583      0.63513202     -0.00012037     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.12637991      0.08453773                     Dependent
  prob_AB              0.45823923      0.06872437                     Dependent
  prob_BB              0.41538086      0.15326210                     Dependent
  freq_A               0.35549953      0.11889991      0.00000000     Independent functional
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.00000000                      0.00000000     Ind. fixed @ bound
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob
----------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.30477441      0.03014937     -0.14360809     -0.02406928     -0.01956696      0.04363624     -0.03385276      0.00000000
  mean_BB    |      0.03014937      0.13935018      0.04952360     -0.01116806     -0.00907900      0.02024706     -0.01570756      0.00000000
  variance   |     -0.14360809      0.04952360      0.40339268      0.00819469      0.00666182     -0.01485652      0.01152560      0.00000000
  prob_AA    |     -0.02406928     -0.01116806      0.00819469      0.00714663      0.00580980     -0.01295643      0.01005153      0.00000000
  prob_AB    |     -0.01956696     -0.00907900      0.00666182      0.00580980      0.00472304     -0.01053284      0.00817132      0.00000000
  prob_BB    |      0.04363624      0.02024706     -0.01485652     -0.01295643     -0.01053284      0.02348927     -0.01822285      0.00000000
  freq_A     |     -0.03385276     -0.01570756      0.01152560      0.01005153      0.00817132     -0.01822285      0.01413719      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
----------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.0659
     -2 LN(Likelihood) : 158.132
    Akaike's AIC score : 166.132
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : general

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB           0.38609961      0.55207125      0.00000393     Independent
  mean_BB             -2.02563858      0.37329886     -0.00004298     Independent
  variance             1.95006357      0.63513568     -0.00002653     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.12638163      0.08453936                     Dependent
  prob_AB              0.45824062      0.06872409                     Dependent
  prob_BB              0.41537775      0.15326346                     Dependent
  freq_A               0.35550194      0.11890141      0.00000000     Independent functional
  transm prob_AA       1.00000000                      0.00000000     Ind. fixed @ bound
  transm prob_AB       0.00000000                      0.00000000     Ind. fixed @ bound
  transm prob_BB       0.00000000                      0.00000000     Ind. fixed @ bound
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob     transm prob     transm prob
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.30478267      0.03014057     -0.14361456     -0.02407006     -0.01956713      0.04363719     -0.03385362      0.00000000      0.00000000      0.00000000
  mean_BB    |      0.03014057      0.13935204      0.04953962     -0.01116775     -0.00907854      0.02024629     -0.01570702      0.00000000      0.00000000      0.00000000
  variance   |     -0.14361456      0.04953962      0.40339733      0.00819451      0.00666151     -0.01485602      0.01152526      0.00000000      0.00000000      0.00000000
  prob_AA    |     -0.02407006     -0.01116775      0.00819451      0.00714690      0.00580989     -0.01295680      0.01005185      0.00000000      0.00000000      0.00000000
  prob_AB    |     -0.01956713     -0.00907854      0.00666151      0.00580989      0.00472300     -0.01053289      0.00817139      0.00000000      0.00000000      0.00000000
  prob_BB    |      0.04363719      0.02024629     -0.01485602     -0.01295680     -0.01053289      0.02348969     -0.01822324      0.00000000      0.00000000      0.00000000
  freq_A     |     -0.03385362     -0.01570702      0.01152526      0.01005185      0.00817139     -0.01822324      0.01413755      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.0659
     -2 LN(Likelihood) : 158.132
    Akaike's AIC score : 166.132
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous no transmission

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA              3.94464163      1.64355563     -0.00000108     Independent
  mean_AB              0.22516266      0.37653456     -0.00000504     Independent
  mean_BB             -2.30167157      0.36394036      0.00001207     Independent
  variance             0.99254439      0.41293803      0.00002820     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.05955549      0.03441133                     Dependent
  prob_AB              0.36896889      0.07218431                     Dependent
  prob_BB              0.57147563      0.10659565                     Dependent
  freq_A               0.24403993      0.07050349      0.00000000     Independent functional
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A     
----------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      2.70127509      0.29901262      0.15306329      0.07214724     -0.02240575     -0.04700032      0.06940607     -0.04590591
  mean_AB    |      0.29901262      0.14177827      0.04942484      0.00950550     -0.00630007     -0.01321560      0.01951568     -0.01290788
  mean_BB    |      0.15306329      0.04942484      0.13245258      0.08536008     -0.00673901     -0.01413635      0.02087536     -0.01380718
  variance   |      0.07214724      0.00950550      0.08536008      0.17051781     -0.00492585     -0.01033291      0.01525876     -0.01009230
  prob_AA    |     -0.02240575     -0.00630007     -0.00673901     -0.00492585      0.00118414      0.00248396     -0.00366810      0.00242612
  prob_AB    |     -0.04700032     -0.01321560     -0.01413635     -0.01033291      0.00248396      0.00521058     -0.00769453      0.00508925
  prob_BB    |      0.06940607      0.01951568      0.02087536      0.01525876     -0.00366810     -0.00769453      0.01136263     -0.00751537
  freq_A     |     -0.04590591     -0.01290788     -0.01380718     -0.01009230      0.00242612      0.00508925     -0.00751537      0.00497074
----------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.4468
     -2 LN(Likelihood) : 158.894
    Akaike's AIC score : 168.894
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous no transmission

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA              3.94464163      1.64355563     -0.00000108     Independent
  mean_AB              0.22516266      0.37653456     -0.00000504     Independent
  mean_BB             -2.30167157      0.36394036      0.00001207     Independent
  variance             0.99254439      0.41293803      0.00002820     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.05955549      0.03441133                     Dependent
  prob_AB              0.36896889      0.07218431                     Dependent
  prob_BB              0.57147563      0.10659565                     Dependent
  freq_A               0.24403993      0.07050349      0.00000000     Independent functional
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A     
----------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      2.70127509      0.29901262      0.15306329      0.07214724     -0.02240575     -0.04700032      0.06940607     -0.04590591
  mean_AB    |      0.29901262      0.14177827      0.04942484      0.00950550     -0.00630007     -0.01321560      0.01951568     -0.01290788
  mean_BB    |      0.15306329      0.04942484      0.13245258      0.08536008     -0.00673901     -0.01413635      0.02087536     -0.01380718
  variance   |      0.07214724      0.00950550      0.08536008      0.17051781     -0.00492585     -0.01033291      0.01525876     -0.01009230
  prob_AA    |     -0.02240575     -0.00630007     -0.00673901     -0.00492585      0.00118414      0.00248396     -0.00366810      0.00242612
  prob_AB    |     -0.04700032     -0.01321560     -0.01413635     -0.01033291      0.00248396      0.00521058     -0.00769453      0.00508925
  prob_BB    |      0.06940607      0.01951568      0.02087536      0.01525876     -0.00366810     -0.00769453      0.01136263     -0.00751537
  freq_A     |     -0.04590591     -0.01290788     -0.01380718     -0.01009230      0.00242612      0.00508925     -0.00751537      0.00497074
----------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.4468
     -2 LN(Likelihood) : 158.894
    Akaike's AIC score : 168.894
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous mendelian

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA             -2.52805489      0.24123307      0.00005514     Independent
  mean_AB              0.14925223      0.22682571     -0.00003543     Independent
  mean_BB              4.51973085      0.90823852      0.00011243     Independent
  variance             0.82423648      0.23778654     -0.00001620     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.49453990      0.10425117                     Dependent
  prob_AB              0.41739082      0.06025727                     Dependent
  prob_BB              0.08806928      0.04399390                     Dependent
  freq_A               0.70323531      0.07412254      0.00000000     Independent functional
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.50000000                                     Fixed
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A     
----------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.05819339      0.00585612     -0.00002271      0.01200112      0.00208243     -0.00120365     -0.00087878      0.00148061
  mean_AB    |      0.00585612      0.05144990      0.00003465     -0.00536398      0.00093854     -0.00054248     -0.00039606      0.00066730
  mean_BB    |     -0.00002271      0.00003465      0.82489722     -0.00013579      0.00000252     -0.00000146     -0.00000107      0.00000179
  variance   |      0.01200112     -0.00536398     -0.00013579      0.05654244      0.00143959     -0.00083209     -0.00060751      0.00102355
  prob_AA    |      0.00208243      0.00093854      0.00000252      0.00143959      0.01086831     -0.00628189     -0.00458642      0.00772736
  prob_AB    |     -0.00120365     -0.00054248     -0.00000146     -0.00083209     -0.00628189      0.00363094      0.00265095     -0.00446642
  prob_BB    |     -0.00087878     -0.00039606     -0.00000107     -0.00060751     -0.00458642      0.00265095      0.00193546     -0.00326094
  freq_A     |      0.00148061      0.00066730      0.00000179      0.00102355      0.00772736     -0.00446642     -0.00326094      0.00549415
----------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -77.8935
     -2 LN(Likelihood) : 155.787
    Akaike's AIC score : 165.787
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous general

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA              4.51982355      0.90823848     -0.00000457     Independent
  mean_AB              0.14925069      0.22682583     -0.00000855     Independent
  mean_BB             -2.52805187      0.24123332     -0.00004673     Independent
  variance             0.82423669      0.23778685     -0.00002040     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.08806993      0.04399416                     Dependent
  prob_AB              0.41739170      0.06025708                     Dependent
  prob_BB              0.49453837      0.10425125                     Dependent
  freq_A               0.29676578      0.07412270      0.00000000     Independent functional
  transm prob_AA       1.00000000                      0.00000000     Ind. func. fixed @ bnd
  transm prob_AB       0.50000000                                     Dependent
  transm prob_BB       0.00000000                      0.00000000     Ind. func. fixed @ bnd
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob     transm prob     transm prob
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.82489713      0.00003404     -0.00002135     -0.00012939     -0.00000113     -0.00000155      0.00000268     -0.00000191      0.00000000      0.00000000      0.00000000
  mean_AB    |      0.00003404      0.05144995      0.00585605     -0.00536413     -0.00039607     -0.00054248      0.00093854     -0.00066730      0.00000000      0.00000000      0.00000000
  mean_BB    |     -0.00002135      0.00585605      0.05819352      0.01200140     -0.00087879     -0.00120365      0.00208244     -0.00148062      0.00000000      0.00000000      0.00000000
  variance   |     -0.00012939     -0.00536413      0.01200140      0.05654259     -0.00060751     -0.00083209      0.00143960     -0.00102356      0.00000000      0.00000000      0.00000000
  prob_AA    |     -0.00000113     -0.00039607     -0.00087879     -0.00060751      0.00193549      0.00265096     -0.00458645      0.00326097      0.00000000      0.00000000      0.00000000
  prob_AB    |     -0.00000155     -0.00054248     -0.00120365     -0.00083209      0.00265096      0.00363092     -0.00628188      0.00446642      0.00000000      0.00000000      0.00000000
  prob_BB    |      0.00000268      0.00093854      0.00208244      0.00143960     -0.00458645     -0.00628188      0.01086832     -0.00772738      0.00000000      0.00000000      0.00000000
  freq_A     |     -0.00000191     -0.00066730     -0.00148062     -0.00102356      0.00326097      0.00446642     -0.00772738      0.00549418      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -77.8935
     -2 LN(Likelihood) : 155.787
    Akaike's AIC score : 165.787
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : tau AB free

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA             -2.50614506      0.24112925     -0.00000846     Independent
  mean_AB              0.17358426      0.22902056      0.00001901     Independent
  mean_BB              4.51982750      0.90632929      0.00000191     Independent
  variance             0.82077151      0.23459037     -0.00004076     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.49163579      0.10396177                     Dependent
  prob_AB              0.41906332      0.05965401                     Dependent
  prob_BB              0.08930090      0.04430776                     Dependent
  freq_A               0.70116745      0.07413477      0.00000000     Independent functional
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.60355252      0.11212767      0.00000000     Independent
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob
--------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.05814332      0.00698396     -0.00002109      0.01215821      0.00162384     -0.00093177     -0.00069207      0.00115796      0.00359302
  mean_AB    |      0.00698396      0.05245042      0.00002807     -0.00412854      0.00106170     -0.00060921     -0.00045249      0.00075710      0.00295891
  mean_BB    |     -0.00002109      0.00002807      0.82143279     -0.00012212      0.00000440     -0.00000252     -0.00000187      0.00000314     -0.00000288
  variance   |      0.01215821     -0.00412854     -0.00012212      0.05503264      0.00074733     -0.00042882     -0.00031851      0.00053292      0.00086135
  prob_AA    |      0.00162384      0.00106170      0.00000440      0.00074733      0.01080805     -0.00620174     -0.00460631      0.00770718     -0.00026591
  prob_AB    |     -0.00093177     -0.00060921     -0.00000252     -0.00042882     -0.00620174      0.00355860      0.00264314     -0.00442244      0.00015258
  prob_BB    |     -0.00069207     -0.00045249     -0.00000187     -0.00031851     -0.00460631      0.00264314      0.00196318     -0.00328475      0.00011333
  freq_A     |      0.00115796      0.00075710      0.00000314      0.00053292      0.00770718     -0.00442244     -0.00328475      0.00549596     -0.00018962
  transm prob|      0.00359302      0.00295891     -0.00000288      0.00086135     -0.00026591      0.00015258      0.00011333     -0.00018962      0.01257261
--------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -77.4811
     -2 LN(Likelihood) : 154.962
    Akaike's AIC score : 166.962
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t1
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : general

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA              3.11660884      1.06200379      0.00000000     Independent
  mean_AB              0.00045297      0.27784088      0.00000000     Independent
  mean_BB             -2.54878001      0.23137513      0.00000000     Independent
  variance             0.77769263      0.23237125      0.00000000     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.11218125      0.05692315                     Dependent
  prob_AB              0.44550689      0.05610668                     Dependent
  prob_BB              0.44231186      0.11302983                     Dependent
  freq_A               0.33493470      0.08497649      0.00000000     Independent functional
  transm prob_AA       0.11649390      0.35359450      0.00000000     Independent
  transm prob_AB       0.44638645      0.12690149      0.00000000     Independent
  transm prob_BB       0.00000000                      0.00000000     Ind. fixed @ bound
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob     transm prob     transm prob
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      1.12785206      0.13257982      0.01849795     -0.00854194     -0.02195010     -0.02163526      0.04358536     -0.03276773     -0.14485751     -0.02418989      0.00000000
  mean_AB    |      0.13257982      0.07719556      0.00961581     -0.00592183     -0.00445550     -0.00439159      0.00884709     -0.00665130     -0.02768991     -0.00689302      0.00000000
  mean_BB    |      0.01849795      0.00961581      0.05353445      0.00868968     -0.00113305     -0.00111680      0.00224985     -0.00169145     -0.00606275     -0.00368359      0.00000000
  variance   |     -0.00854194     -0.00592183      0.00868968      0.05399640     -0.00001370     -0.00001350      0.00002721     -0.00002045     -0.00553271     -0.00031339      0.00000000
  prob_AA    |     -0.02195010     -0.00445550     -0.00113305     -0.00001370      0.00324024      0.00319377     -0.00643401      0.00483713      0.00449958      0.00046503      0.00000000
  prob_AB    |     -0.02163526     -0.00439159     -0.00111680     -0.00001350      0.00319377      0.00314796     -0.00634173      0.00476775      0.00443504      0.00045836      0.00000000
  prob_BB    |      0.04358536      0.00884709      0.00224985      0.00002721     -0.00643401     -0.00634173      0.01277574     -0.00960488     -0.00893461     -0.00092338      0.00000000
  freq_A     |     -0.03276773     -0.00665130     -0.00169145     -0.00002045      0.00483713      0.00476775     -0.00960488      0.00722100      0.00671709      0.00069420      0.00000000
  transm prob|     -0.14485751     -0.02768991     -0.00606275     -0.00553271      0.00449958      0.00443504     -0.00893461      0.00671709      0.12502907     -0.00191608      0.00000000
  transm prob|     -0.02418989     -0.00689302     -0.00368359     -0.00031339      0.00046503      0.00045836     -0.00092338      0.00069420     -0.00191608      0.01610399      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -76.5633
     -2 LN(Likelihood) : 153.127
    Akaike's AIC score : 167.127
=====================================================================================================

