=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : one mean
    Mean covariates              :
          cov1                   : (Mean =      0.52500)
          cov2                   : (Mean =      0.30825)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : 
    Transmission                 : homogeneous no transmission


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean                 1.05424914      0.29795646     -0.00000031     Independent
  cov1                 2.11115644      0.59743818      0.00001385     Independent
  cov2                 3.42119547      0.30628552     -0.00001707     Independent
  variance             3.55112200      0.79405092      0.00002455     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean            cov1            cov2            variance   
------------------------------------------------------------------------------
  mean       |      0.08877805      0.00000000      0.00000000     -0.00000015
  cov1       |      0.00000000      0.35693237      0.00934111     -0.00000124
  cov2       |      0.00000000      0.00934111      0.09381082     -0.00000026
  variance   |     -0.00000015     -0.00000124     -0.00000026      0.63051687
------------------------------------------------------------------------------

 Likelihood Surface Flat: variance matrix near singular and 
 may be affected by rounding error 
 Reducing the number of parameters to be estimated is recommended 

        LN(Likelihood) : -82.1029
     -2 LN(Likelihood) : 164.206
    Akaike's AIC score : 172.206
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Mean covariates              :
          cov1                   : (Mean =      0.52500)
          cov2                   : (Mean =      0.30825)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous no transmission


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB          -0.85278334      0.39399463     -0.00004958     Independent
  mean_BB              2.29611999      0.31819210     -0.00005859     Independent
  cov1                 1.88457014      0.49587831      0.00000952     Independent
  cov2                 3.46592062      0.24599046     -0.00064316     Independent
  variance             1.19805804      0.35495096      0.00001326     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.04918832      0.03074939                     Dependent
  prob_AB              0.34519215      0.07714663                     Dependent
  prob_BB              0.60561953      0.10789602                     Dependent
  freq_A               0.22178439      0.06932270      0.00000000     Independent functional
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A     
--------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.15523177      0.05212275     -0.00313055     -0.01132648     -0.00166438      0.00568691      0.01426781     -0.01995472      0.01282082
  mean_BB    |      0.05212275      0.10124621     -0.02931344     -0.00271229     -0.03091875      0.00469914      0.01178961     -0.01648875      0.01059395
  cov1       |     -0.00313055     -0.02931344      0.24589530     -0.01586000      0.02215384     -0.00171846     -0.00431141      0.00602987     -0.00387416
  cov2       |     -0.01132648     -0.00271229     -0.01586000      0.06051131     -0.00124943     -0.00055294     -0.00138727      0.00194022     -0.00124658
  variance   |     -0.00166438     -0.03091875      0.02215384     -0.00124943      0.12599018     -0.00175414     -0.00440093      0.00615507     -0.00395460
  prob_AA    |      0.00568691      0.00469914     -0.00171846     -0.00055294     -0.00175414      0.00094552      0.00237221     -0.00331774      0.00213163
  prob_AB    |      0.01426781      0.01178961     -0.00431141     -0.00138727     -0.00440093      0.00237221      0.00595160     -0.00832381      0.00534801
  prob_BB    |     -0.01995472     -0.01648875      0.00602987      0.00194022      0.00615507     -0.00331774     -0.00832381      0.01164155     -0.00747964
  freq_A     |      0.01282082      0.01059395     -0.00387416     -0.00124658     -0.00395460      0.00213163      0.00534801     -0.00747964      0.00480564
--------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.7307
     -2 LN(Likelihood) : 159.461
    Akaike's AIC score : 171.461
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Mean covariates              :
          cov1                   : (Mean =      0.52500)
          cov2                   : (Mean =      0.30825)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous mendelian


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB          -1.45698345      0.76586496      0.00000422     Independent
  mean_BB              1.81155598      0.37758794      0.00002024     Independent
  cov1                 1.60152595      0.48800354      0.00000619     Independent
  cov2                 3.64285612      0.33115670      0.00004561     Independent
  variance             1.76636377      0.57556389      0.00000687     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.01539160      0.02202992                     Dependent
  prob_AB              0.21734259      0.13351072                     Dependent
  prob_BB              0.76726581      0.15554063                     Dependent
  freq_A               0.12406290      0.08878528      0.00000000     Independent functional
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.50000000                                     Fixed
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A     
--------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.58654913      0.15631067      0.02761329     -0.14633638     -0.16525056      0.00987850      0.05986791     -0.06974640      0.03981245
  mean_BB    |      0.15631067      0.14257265     -0.03253252     -0.05504319     -0.11124090      0.00496636      0.03009826     -0.03506462      0.02001549
  cov1       |      0.02761329     -0.03253252      0.23814745      0.01057127      0.04416829     -0.00105681     -0.00640470      0.00746151     -0.00425916
  cov2       |     -0.14633638     -0.05504319      0.01057127      0.10966476      0.07350525     -0.00356192     -0.02158675      0.02514867     -0.01435529
  variance   |     -0.16525056     -0.11124090      0.04416829      0.07350525      0.33127379     -0.00629877     -0.03817327      0.04447204     -0.02538541
  prob_AA    |      0.00987850      0.00496636     -0.00105681     -0.00356192     -0.00629877      0.00048532      0.00294123     -0.00342655      0.00195593
  prob_AB    |      0.05986791      0.03009826     -0.00640470     -0.02158675     -0.03817327      0.00294123      0.01782511     -0.02076634      0.01185379
  prob_BB    |     -0.06974640     -0.03506462      0.00746151      0.02514867      0.04447204     -0.00342655     -0.02076634      0.02419289     -0.01380972
  freq_A     |      0.03981245      0.02001549     -0.00425916     -0.01435529     -0.02538541      0.00195593      0.01185379     -0.01380972      0.00788283
--------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -77.9656
     -2 LN(Likelihood) : 155.931
    Akaike's AIC score : 167.931
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Mean covariates              :
          cov1                   : (Mean =      0.52500)
          cov2                   : (Mean =      0.30825)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous general


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB          -0.89107898      0.40641917      0.00000537     Independent
  mean_BB              2.27847423      0.32493933      0.00002410     Independent
  cov1                 1.82332932      0.45197037      0.00000585     Independent
  cov2                 3.38871965      0.27665674      0.00003835     Independent
  variance             1.19081610      0.35728426      0.00000844     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.04504793      0.03398226                     Dependent
  prob_AB              0.33439410      0.09214414                     Dependent
  prob_BB              0.62055796      0.12612640                     Dependent
  freq_A               0.21224498      0.08005433      0.00000000     Independent functional
  transm prob_AA       0.47112608      1.51979644      0.00000000     Independent functional
  transm prob_AB       0.47112135      0.22987624                     Dependent
  transm prob_BB       0.05395391      0.06146424      0.00000000     Independent functional
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob     transm prob     transm prob
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.16517654      0.06012214      0.04086767     -0.02325425     -0.01380318      0.00565948      0.01534587     -0.02100535      0.01333241      0.00845303      0.00845791      0.00219250
  mean_BB    |      0.06012214      0.10558557      0.01080678     -0.01829909     -0.03810451      0.00464704      0.01260062     -0.01724766      0.01094735      0.00496077      0.00496502      0.00301087
  cov1       |      0.04086767      0.01080678      0.20427722     -0.02304473      0.00110331      0.00181114      0.00491097     -0.00672211      0.00426663     -0.00011122     -0.00011100      0.00242443
  cov2       |     -0.02325425     -0.01829909     -0.02304473      0.07653895      0.00677734     -0.00134617     -0.00365019      0.00499636     -0.00317127     -0.00628068     -0.00628262      0.00208983
  variance   |     -0.01380318     -0.03810451      0.00110331      0.00677734      0.12765204     -0.00230491     -0.00624983      0.00855474     -0.00542982      0.00101131      0.00100891     -0.00361608
  prob_AA    |      0.00565948      0.00464704      0.00181114     -0.00134617     -0.00230491      0.00115479      0.00313127     -0.00428606      0.00272043      0.00146842      0.00146881      0.00060447
  prob_AB    |      0.01534587      0.01260062      0.00491097     -0.00365019     -0.00624983      0.00313127      0.00849054     -0.01162181      0.00737654      0.00398167      0.00398273      0.00163904
  prob_BB    |     -0.02100535     -0.01724766     -0.00672211      0.00499636      0.00855474     -0.00428606     -0.01162181      0.01590787     -0.01009696     -0.00545009     -0.00545153     -0.00224350
  freq_A     |      0.01333241      0.01094735      0.00426663     -0.00317127     -0.00542982      0.00272043      0.00737654     -0.01009696      0.00640870      0.00345926      0.00346017      0.00142398
  transm prob|      0.00845303      0.00496077     -0.00011122     -0.00628068      0.00101131      0.00146842      0.00398167     -0.00545009      0.00345926      2.30978122     -0.29853834     -0.00489199
  transm prob|      0.00845791      0.00496502     -0.00011100     -0.00628262      0.00100891      0.00146881      0.00398273     -0.00545153      0.00346017     -0.29853834      0.05284309     -0.00489224
  transm prob|      0.00219250      0.00301087      0.00242443      0.00208983     -0.00361608      0.00060447      0.00163904     -0.00224350      0.00142398     -0.00489199     -0.00489224      0.00377785
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -77.7523
     -2 LN(Likelihood) : 155.505
    Akaike's AIC score : 171.505
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Mean covariates              :
          cov1                   : (Mean =      0.52500)
          cov2                   : (Mean =      0.30825)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : tau AB free


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB          -1.94078939      0.62739569      0.00000476     Independent
  mean_BB              1.62151410      0.25544267      0.00002150     Independent
  cov1                 1.60980077      0.48792825      0.00000601     Independent
  cov2                 3.77733325      0.25401247      0.00005540     Independent
  variance             2.04405122      0.47597255      0.00000770     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.00366188      0.00497807                     Dependent
  prob_AB              0.11370316      0.07230776                     Dependent
  prob_BB              0.88263496      0.07728583                     Dependent
  freq_A               0.06051346      0.04113195      0.00000000     Independent functional
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       1.00000000                      0.00000000     Ind. fixed @ bound
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.39362535     -0.00316860      0.05017078     -0.04572999      0.00526494      0.00016040      0.00232992     -0.00249033      0.00132537      0.00000000
  mean_BB    |     -0.00316860      0.06525096     -0.01124970      0.00799224     -0.00657606      0.00009783      0.00142096     -0.00151878      0.00080830      0.00000000
  cov1       |      0.05017078     -0.01124970      0.23807398      0.00584912      0.00250982     -0.00007018     -0.00101944      0.00108962     -0.00057990      0.00000000
  cov2       |     -0.04572999      0.00799224      0.00584912      0.06452234     -0.00623198      0.00000786      0.00011412     -0.00012197      0.00006492      0.00000000
  variance   |      0.00526494     -0.00657606      0.00250982     -0.00623198      0.22654987     -0.00017771     -0.00258122      0.00275892     -0.00146831      0.00000000
  prob_AA    |      0.00016040      0.00009783     -0.00007018      0.00000786     -0.00017771      0.00002478      0.00035995     -0.00038473      0.00020476      0.00000000
  prob_AB    |      0.00232992      0.00142096     -0.00101944      0.00011412     -0.00258122      0.00035995      0.00522841     -0.00558837      0.00297416      0.00000000
  prob_BB    |     -0.00249033     -0.00151878      0.00108962     -0.00012197      0.00275892     -0.00038473     -0.00558837      0.00597310     -0.00317892      0.00000000
  freq_A     |      0.00132537      0.00080830     -0.00057990      0.00006492     -0.00146831      0.00020476      0.00297416     -0.00317892      0.00169184      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -77.1198
     -2 LN(Likelihood) : 154.24
    Akaike's AIC score : 166.24
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : two means
    Mean covariates              :
          cov1                   : (Mean =      0.52500)
          cov2                   : (Mean =      0.30825)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : general


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA_AB          -1.94078774      0.62739604     -0.00000913     Independent
  mean_BB              1.62151548      0.25544273     -0.00001325     Independent
  cov1                 1.60980213      0.48792821     -0.00000358     Independent
  cov2                 3.77733643      0.25401246     -0.00005433     Independent
  variance             2.04405221      0.47597318     -0.00000768     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.00366193      0.00497814                     Dependent
  prob_AB              0.11370396      0.07230817                     Dependent
  prob_BB              0.88263411      0.07728631                     Dependent
  freq_A               0.06051391      0.04113223      0.00000000     Independent functional
  transm prob_AA       1.00000000                      0.00000000     Ind. fixed @ bound
  transm prob_AB       1.00000000                      0.00000000     Ind. fixed @ bound
  transm prob_BB       0.00000000                      0.00000000     Ind. fixed @ bound
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA_AB      mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob     transm prob     transm prob
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA_AB |      0.39362579     -0.00316860      0.05017084     -0.04573010      0.00526520      0.00016041      0.00232995     -0.00249035      0.00132538      0.00000000      0.00000000      0.00000000
  mean_BB    |     -0.00316860      0.06525099     -0.01124972      0.00799222     -0.00657594      0.00009783      0.00142096     -0.00151879      0.00080831      0.00000000      0.00000000      0.00000000
  cov1       |      0.05017084     -0.01124972      0.23807394      0.00584903      0.00251005     -0.00007019     -0.00101946      0.00108964     -0.00057991      0.00000000      0.00000000      0.00000000
  cov2       |     -0.04573010      0.00799222      0.00584903      0.06452233     -0.00623163      0.00000786      0.00011411     -0.00012196      0.00006491      0.00000000      0.00000000      0.00000000
  variance   |      0.00526520     -0.00657594      0.00251005     -0.00623163      0.22655046     -0.00017771     -0.00258123      0.00275894     -0.00146832      0.00000000      0.00000000      0.00000000
  prob_AA    |      0.00016041      0.00009783     -0.00007019      0.00000786     -0.00017771      0.00002478      0.00035996     -0.00038474      0.00020476      0.00000000      0.00000000      0.00000000
  prob_AB    |      0.00232995      0.00142096     -0.00101946      0.00011411     -0.00258123      0.00035996      0.00522847     -0.00558843      0.00297420      0.00000000      0.00000000      0.00000000
  prob_BB    |     -0.00249035     -0.00151879      0.00108964     -0.00012196      0.00275894     -0.00038474     -0.00558843      0.00597317     -0.00317896      0.00000000      0.00000000      0.00000000
  freq_A     |      0.00132538      0.00080831     -0.00057991      0.00006491     -0.00146832      0.00020476      0.00297420     -0.00317896      0.00169186      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -77.1198
     -2 LN(Likelihood) : 154.24
    Akaike's AIC score : 166.24
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Mean covariates              :
          cov1                   : (Mean =      0.52500)
          cov2                   : (Mean =      0.30825)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous no transmission


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA             -2.42520446      0.62813782     -0.00000607     Independent
  mean_AB             -0.13105753      0.41516353      0.00002672     Independent
  mean_BB              2.60994623      0.24825998     -0.00003070     Independent
  cov1                 1.58526603      0.43874392     -0.00001478     Independent
  cov2                 3.78480324      0.22984351      0.00004104     Independent
  variance             0.68454552      0.25751230     -0.00003736     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.08551942      0.03973463                     Dependent
  prob_AB              0.41383524      0.05640488                     Dependent
  prob_BB              0.50064534      0.09613951                     Dependent
  freq_A               0.29243704      0.06793707      0.00000000     Independent functional
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A     
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.39455712      0.04953689      0.00737690      0.00773855     -0.07441182      0.00977917      0.00566849      0.00804664     -0.01371513      0.00969181
  mean_AB    |      0.04953689      0.17236075      0.05003134     -0.03227671      0.02311949     -0.04341184      0.00904982      0.01284657     -0.02189639      0.01547311
  mean_BB    |      0.00737690      0.05003134      0.06163302     -0.03683085      0.00908649     -0.02504020      0.00391151      0.00555254     -0.00946406      0.00668778
  cov1       |      0.00773855     -0.03227671     -0.03683085      0.19249622      0.00626675      0.03922248     -0.00350362     -0.00497352      0.00847714     -0.00599038
  cov2       |     -0.07441182      0.02311949      0.00908649      0.00626675      0.05282804     -0.01543172      0.00059867      0.00084984     -0.00144851      0.00102359
  variance   |      0.00977917     -0.04341184     -0.02504020      0.03922248     -0.01543172      0.06631258     -0.00327907     -0.00465476      0.00793383     -0.00560645
  prob_AA    |      0.00566849      0.00904982      0.00391151     -0.00350362      0.00059867     -0.00327907      0.00157884      0.00224123     -0.00382007      0.00269945
  prob_AB    |      0.00804664      0.01284657      0.00555254     -0.00497352      0.00084984     -0.00465476      0.00224123      0.00318151     -0.00542274      0.00383198
  prob_BB    |     -0.01371513     -0.02189639     -0.00946406      0.00847714     -0.00144851      0.00793383     -0.00382007     -0.00542274      0.00924281     -0.00653144
  freq_A     |      0.00969181      0.01547311      0.00668778     -0.00599038      0.00102359     -0.00560645      0.00269945      0.00383198     -0.00653144      0.00461545
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.617
     -2 LN(Likelihood) : 159.234
    Akaike's AIC score : 173.234
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Mean covariates              :
          cov1                   : (Mean =      0.52500)
          cov2                   : (Mean =      0.30825)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous no transmission


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA             -2.42520446      0.62813782     -0.00000607     Independent
  mean_AB             -0.13105753      0.41516353      0.00002672     Independent
  mean_BB              2.60994623      0.24825998     -0.00003070     Independent
  cov1                 1.58526603      0.43874392     -0.00001478     Independent
  cov2                 3.78480324      0.22984351      0.00004104     Independent
  variance             0.68454552      0.25751230     -0.00003736     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.08551942      0.03973463                     Dependent
  prob_AB              0.41383524      0.05640488                     Dependent
  prob_BB              0.50064534      0.09613951                     Dependent
  freq_A               0.29243704      0.06793707      0.00000000     Independent functional
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A     
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.39455712      0.04953689      0.00737690      0.00773855     -0.07441182      0.00977917      0.00566849      0.00804664     -0.01371513      0.00969181
  mean_AB    |      0.04953689      0.17236075      0.05003134     -0.03227671      0.02311949     -0.04341184      0.00904982      0.01284657     -0.02189639      0.01547311
  mean_BB    |      0.00737690      0.05003134      0.06163302     -0.03683085      0.00908649     -0.02504020      0.00391151      0.00555254     -0.00946406      0.00668778
  cov1       |      0.00773855     -0.03227671     -0.03683085      0.19249622      0.00626675      0.03922248     -0.00350362     -0.00497352      0.00847714     -0.00599038
  cov2       |     -0.07441182      0.02311949      0.00908649      0.00626675      0.05282804     -0.01543172      0.00059867      0.00084984     -0.00144851      0.00102359
  variance   |      0.00977917     -0.04341184     -0.02504020      0.03922248     -0.01543172      0.06631258     -0.00327907     -0.00465476      0.00793383     -0.00560645
  prob_AA    |      0.00566849      0.00904982      0.00391151     -0.00350362      0.00059867     -0.00327907      0.00157884      0.00224123     -0.00382007      0.00269945
  prob_AB    |      0.00804664      0.01284657      0.00555254     -0.00497352      0.00084984     -0.00465476      0.00224123      0.00318151     -0.00542274      0.00383198
  prob_BB    |     -0.01371513     -0.02189639     -0.00946406      0.00847714     -0.00144851      0.00793383     -0.00382007     -0.00542274      0.00924281     -0.00653144
  freq_A     |      0.00969181      0.01547311      0.00668778     -0.00599038      0.00102359     -0.00560645      0.00269945      0.00383198     -0.00653144      0.00461545
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -79.617
     -2 LN(Likelihood) : 159.234
    Akaike's AIC score : 173.234
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Mean covariates              :
          cov1                   : (Mean =      0.52500)
          cov2                   : (Mean =      0.30825)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous mendelian


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA             -1.58419694      0.36293999      0.00001311     Independent
  mean_AB              0.99625343      0.53588856      0.00000565     Independent
  mean_BB              2.93467709      0.30925797      0.00003043     Independent
  cov1                 1.73497985      0.39292903      0.00001074     Independent
  cov2                 3.50704514      0.17744902      0.00010490     Independent
  variance             0.81778772      0.31147681      0.00001071     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.20905199      0.10028648                     Dependent
  prob_AB              0.49634009      0.01876572                     Dependent
  prob_BB              0.29460792      0.11905221                     Dependent
  freq_A               0.45722204      0.10966934      0.00000000     Independent functional
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.50000000                                     Fixed
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A     
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.13172544      0.07635747      0.01285214      0.00763363     -0.01781532      0.02968623      0.01092681      0.00204464     -0.01297145      0.01194913
  mean_AB    |      0.07635747      0.28717655      0.04300495     -0.07131936     -0.02115812      0.08463446      0.03235440      0.00605419     -0.03840859      0.03538149
  mean_BB    |      0.01285214      0.04300495      0.09564049     -0.01330437     -0.00654446     -0.00552817      0.00850923      0.00159226     -0.01010148      0.00930535
  cov1       |      0.00763363     -0.07131936     -0.01330437      0.15439322      0.00208845     -0.01737462     -0.00755817     -0.00141429      0.00897246     -0.00826532
  cov2       |     -0.01781532     -0.02115812     -0.00654446      0.00208845      0.03148816     -0.00674104     -0.00362993     -0.00067924      0.00430917     -0.00396955
  variance   |      0.02968623      0.08463446     -0.00552817     -0.01737462     -0.00674104      0.09701780      0.00953004      0.00178327     -0.01131331      0.01042167
  prob_AA    |      0.01092681      0.03235440      0.00850923     -0.00755817     -0.00362993      0.00953004      0.01005738      0.00188195     -0.01193933      0.01099835
  prob_AB    |      0.00204464      0.00605419      0.00159226     -0.00141429     -0.00067924      0.00178327      0.00188195      0.00035215     -0.00223410      0.00205802
  prob_BB    |     -0.01297145     -0.03840859     -0.01010148      0.00897246      0.00430917     -0.01131331     -0.01193933     -0.00223410      0.01417343     -0.01305638
  freq_A     |      0.01194913      0.03538149      0.00930535     -0.00826532     -0.00396955      0.01042167      0.01099835      0.00205802     -0.01305638      0.01202737
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -76.3198
     -2 LN(Likelihood) : 152.64
    Akaike's AIC score : 166.64
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Mean covariates              :
          cov1                   : (Mean =      0.52500)
          cov2                   : (Mean =      0.30825)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : homogeneous general


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA             -1.17928369      0.42040902      0.00001175     Independent
  mean_AB              1.67913513      0.54941154      0.00001589     Independent
  mean_BB              3.31049326      0.71396825      0.00001478     Independent
  cov1                 1.83657035      0.46864960      0.00000882     Independent
  cov2                 3.31249197      0.23884468      0.00009117     Independent
  variance             0.82515436      0.25431593      0.00001274     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.33764985      0.17277163                     Dependent
  prob_AB              0.48685322      0.04821297                     Dependent
  prob_BB              0.17549693      0.12455866                     Dependent
  freq_A               0.58107646      0.14866515      0.00000000     Independent functional
  transm prob_AA       1.00000000                      0.00000000     Ind. func. fixed @ bnd
  transm prob_AB       0.37241961      0.13195234                     Dependent
  transm prob_BB       0.35392598      0.39829990      0.00000000     Independent functional
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob     transm prob     transm prob
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.17674374      0.16280963      0.15767895     -0.05066339     -0.04712584      0.00681088      0.04530359     -0.01264224     -0.03266135      0.03898247      0.00000000      0.00269883      0.04919096
  mean_AB    |      0.16280963      0.30185304      0.25681076     -0.09237909     -0.07117432      0.00949658      0.07330299     -0.02045565     -0.05284735      0.06307517      0.00000000      0.00505847      0.07767416
  mean_BB    |      0.15767895      0.25681076      0.50975066     -0.10123675     -0.10992908     -0.03794270      0.08660348     -0.02416723     -0.06243625      0.07451987      0.00000000      0.00981316      0.08112379
  cov1       |     -0.05066339     -0.09237909     -0.10123675      0.21963244      0.02991711     -0.01353172     -0.02732197      0.00762436      0.01969761     -0.02350979      0.00000000      0.01014008     -0.06231166
  cov2       |     -0.04712584     -0.07117432     -0.10992908      0.02991711      0.05704678      0.00933162     -0.02370950      0.00661628      0.01709322     -0.02040136      0.00000000     -0.00133768     -0.02595131
  variance   |      0.00681088      0.00949658     -0.03794270     -0.01353172      0.00933162      0.06467659     -0.00079721      0.00022247      0.00057475     -0.00068598      0.00000000     -0.00208515      0.00478713
  prob_AA    |      0.04530359      0.07330299      0.08660348     -0.02732197     -0.02370950     -0.00079721      0.02985004     -0.00832983     -0.02152020      0.02568512      0.00000000      0.00318002      0.02852261
  prob_AB    |     -0.01264224     -0.02045565     -0.02416723      0.00762436      0.00661628      0.00022247     -0.00832983      0.00232449      0.00600534     -0.00716759      0.00000000     -0.00088741     -0.00795941
  prob_BB    |     -0.03266135     -0.05284735     -0.06243625      0.01969761      0.01709322      0.00057475     -0.02152020      0.00600534      0.01551486     -0.01851753      0.00000000     -0.00229262     -0.02056320
  freq_A     |      0.03898247      0.06307517      0.07451987     -0.02350979     -0.02040136     -0.00068598      0.02568512     -0.00716759     -0.01851753      0.02210133      0.00000000      0.00273632      0.02454290
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00269883      0.00505847      0.00981316      0.01014008     -0.00133768     -0.00208515      0.00318002     -0.00088741     -0.00229262      0.00273632      0.00000000      0.01741142     -0.04432330
  transm prob|      0.04919096      0.07767416      0.08112379     -0.06231166     -0.02595131      0.00478713      0.02852261     -0.00795941     -0.02056320      0.02454290      0.00000000     -0.04432330      0.15864281
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -75.6715
     -2 LN(Likelihood) : 151.343
    Akaike's AIC score : 167.343
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Mean covariates              :
          cov1                   : (Mean =      0.52500)
          cov2                   : (Mean =      0.30825)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : tau AB free


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA             -1.20234375      0.53299042      0.00005947     Independent
  mean_AB              1.70265606      0.68738927      0.00046271     Independent
  mean_BB              3.32595504      1.26986459     -0.00027659     Independent
  cov1                 1.77825722      0.40870382      0.00015091     Independent
  cov2                 3.31526205      0.37836969     -0.00027319     Independent
  variance             0.87569978      0.39764202      0.00001808     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.36033544      0.22142209                     Dependent
  prob_AB              0.47988806      0.07397917                     Dependent
  prob_BB              0.15977650      0.14744291                     Dependent
  freq_A               0.60027947      0.18443250      0.00000000     Independent functional
  transm prob_AA       1.00000000                                     Fixed
  transm prob_AB       0.41022161      0.12848180      0.00000000     Independent
  transm prob_BB       0.00000000                                     Fixed
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.28407878      0.29664350      0.50210582      0.00246677     -0.14253034     -0.11786994      0.08832265     -0.02950942     -0.05881323      0.07356794      0.00108421
  mean_AB    |      0.29664350      0.47250402      0.72566725     -0.00470782     -0.20118806     -0.17408362      0.12766655     -0.04265458     -0.08501197      0.10633926      0.00072294
  mean_BB    |      0.50210582      0.72566725      1.61255609     -0.05197072     -0.41117172     -0.38368986      0.23652870     -0.07902643     -0.15750226      0.19701548     -0.01091117
  cov1       |      0.00246677     -0.00470782     -0.05197072      0.16703881      0.00665783      0.00426764     -0.00627749      0.00209737      0.00418012     -0.00522881      0.00815606
  cov2       |     -0.14253034     -0.20118806     -0.41117172      0.00665783      0.14316362      0.10797127     -0.06494166      0.02169761      0.04324405     -0.05409286      0.00166990
  variance   |     -0.11786994     -0.17408362     -0.38368986      0.00426764      0.10797127      0.15811918     -0.05791808      0.01935097      0.03856711     -0.04824260      0.00296702
  prob_AA    |      0.08832265      0.12766655      0.23652870     -0.00627749     -0.06494166     -0.05791808      0.04902774     -0.01638062     -0.03264712      0.04083743     -0.00274347
  prob_AB    |     -0.02950942     -0.04265458     -0.07902643      0.00209737      0.02169761      0.01935097     -0.01638062      0.00547292      0.01090771     -0.01364416      0.00091662
  prob_BB    |     -0.05881323     -0.08501197     -0.15750226      0.00418012      0.04324405      0.03856711     -0.03264712      0.01090771      0.02173941     -0.02719327      0.00182685
  freq_A     |      0.07356794      0.10633926      0.19701548     -0.00522881     -0.05409286     -0.04824260      0.04083743     -0.01364416     -0.02719327      0.03401535     -0.00228516
  transm prob|      0.00108421      0.00072294     -0.01091117      0.00815606      0.00166990      0.00296702     -0.00274347      0.00091662      0.00182685     -0.00228516      0.01650757
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -76.1383
     -2 LN(Likelihood) : 152.277
    Akaike's AIC score : 168.277
=====================================================================================================

=====================================================================================================
  SEGREG Analysis for Trait : t2
=====================================================================================================
  # Model Specification  

    Model Class A
    Type means                   : three means
    Mean covariates              :
          cov1                   : (Mean =      0.52500)
          cov2                   : (Mean =      0.30825)
    Type variances               : one variance
    Residual correlations        : No spouse correlation, parent-offspring and
                                   sib-sib correlations equal
    Transformation               : none
    Type frequency               : Hardy-Weinberg equilibrium
    Transmission                 : general


    NOTE:  All covariates are centered at mean 0.0 for analysis.  The centering
           means listed are the means of all non-missing values of the covariate,
           regardless of the missingness of other variables used in the analysis.
           It follows that, unless the missingness is the same for the trait and
           all covariates used, these means may not be the appropriate centering
           means for the results below.

  # Number of constituent pedigrees   : 10
  # Number of unconnected individuals : 0

  # Final Estimates : 

  Parameter           Parameter Est.  Standard Err.   First Deriv.   Status
-----------------------------------------------------------------------------------------------------
  mean_AA             -1.18561868      0.43193371      0.00000001     Independent
  mean_AB              1.67079719      0.56705240      0.00000000     Independent
  mean_BB              3.30336595      0.71284718      0.00000000     Independent
  cov1                 1.83704474      0.46491195      0.00000000     Independent
  cov2                 3.31507183      0.24104539      0.00000000     Independent
  variance             0.82498443      0.25495783     -0.00000001     Independent
  marital resid c      0.00000000                                     Fixed
  po = ss resid c      0.00000000                                     Fixed
  prob_AA              0.33809772      0.17315023                     Dependent
  prob_AB              0.48672798      0.04851606                     Dependent
  prob_BB              0.17517430      0.12463418                     Dependent
  freq_A               0.58146171      0.14889221      0.00000000     Independent functional
  transm prob_AA       1.00000000                      0.00000000     Ind. fixed @ bound
  transm prob_AB       0.36726505      0.14981236      0.00000000     Independent
  transm prob_BB       0.33576116      0.46457797      0.00000000     Independent
-----------------------------------------------------------------------------------------------------


  # Variance-Covariance Matrix : 

             |     mean_AA         mean_AB         mean_BB         cov1            cov2            variance        prob_AA         prob_AB         prob_BB         freq_A          transm prob     transm prob     transm prob
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  mean_AA    |      0.18656673      0.17638223      0.16607335     -0.04950745     -0.05070513      0.00759253      0.04528000     -0.01268729     -0.03259271      0.03893636      0.00000000      0.00910719      0.06908072
  mean_AB    |      0.17638223      0.32154842      0.26861025     -0.09087308     -0.07628559      0.01073414      0.07364903     -0.02063619     -0.05301285      0.06333094      0.00000000      0.01391038      0.10189877
  mean_BB    |      0.16607335      0.26861025      0.50815110     -0.09571774     -0.11160321     -0.03612800      0.08480976     -0.02376338     -0.06104638      0.07292807      0.00000000      0.01773958      0.09668597
  cov1       |     -0.04950745     -0.09087308     -0.09571774      0.21614312      0.02833333     -0.01478537     -0.02643623      0.00740734      0.01902890     -0.02273257      0.00000000      0.00912364     -0.05794292
  cov2       |     -0.05070513     -0.07628559     -0.11160321      0.02833333      0.05810288      0.00899329     -0.02342685      0.00656412      0.01686273     -0.02014479      0.00000000     -0.00422049     -0.03260781
  variance   |      0.00759253      0.01073414     -0.03612800     -0.01478537      0.00899329      0.06500350     -0.00037458      0.00010496      0.00026962     -0.00032210      0.00000000     -0.00195150      0.00527568
  prob_AA    |      0.04528000      0.07364903      0.08480976     -0.02643623     -0.02342685     -0.00037458      0.02998100     -0.00840057     -0.02158044      0.02578072      0.00000000      0.00270740      0.02509495
  prob_AB    |     -0.01268729     -0.02063619     -0.02376338      0.00740734      0.00656412      0.00010496     -0.00840057      0.00235381      0.00604676     -0.00722366      0.00000000     -0.00075860     -0.00703151
  prob_BB    |     -0.03259271     -0.05301285     -0.06104638      0.01902890      0.01686273      0.00026962     -0.02158044      0.00604676      0.01553368     -0.01855706      0.00000000     -0.00194880     -0.01806344
  freq_A     |      0.03893636      0.06333094      0.07292807     -0.02273257     -0.02014479     -0.00032210      0.02578072     -0.00722366     -0.01855706      0.02216889      0.00000000      0.00232810      0.02157919
  transm prob|      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000      0.00000000
  transm prob|      0.00910719      0.01391038      0.01773958      0.00912364     -0.00422049     -0.00195150      0.00270740     -0.00075860     -0.00194880      0.00232810      0.00000000      0.02244374     -0.02510220
  transm prob|      0.06908072      0.10189877      0.09668597     -0.05794292     -0.03260781      0.00527568      0.02509495     -0.00703151     -0.01806344      0.02157919      0.00000000     -0.02510220      0.21583269
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


        LN(Likelihood) : -75.669
     -2 LN(Likelihood) : 151.338
    Akaike's AIC score : 169.338
=====================================================================================================

