



Family structure information on the first 10 individuals read from file: ageon.ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             0         0             0           
     1             221           1         0             0           
     1             401           0         1             221         
     2             2             0         0             0           
     2             398           1         0             0           
     2             402           1         2             398         
     2             403           1         2             398         
     2             404           1         2             398         
     3             3             0         0             0           
     3             353           1         0             0           


Phenotypes for the first 10 individuals read from file: ageon.ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         cov1                  cov2                  AE                    AO                    AFF                 
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             1                     1                     1                     3                     MISS                  MISS                  MISS                  -9                    -9                  
     1             221           0                     1                     1                     3                     MISS                  MISS                  MISS                  -9                    -9                  
     1             401           1                     1                     0                     3                     1.602                 0.573                 80                    -9                    0                   
     2             2             1                     1                     1                     5                     MISS                  MISS                  MISS                  -9                    -9                  
     2             398           0                     1                     1                     5                     MISS                  MISS                  MISS                  -9                    -9                  
     2             402           0                     1                     0                     5                     1.129                 1.39                  74                    77                    0                   
     2             403           0                     1                     0                     5                     0.63                  0.321                 77                    76                    1                   
     2             404           0                     1                     0                     5                     -1.029                -0.574                75                    76                    0                   
     3             3             1                     1                     1                     3                     0.321                 -0.888                71                    -9                    0                   
     3             353           0                     1                     1                     3                     MISS                  MISS                  MISS                  -9                    -9                  


Parsing Ageonset Analyses...

Beginning new analysis block....

Parsing Analysis: 'AGEON Analysis 1'....

%AGEON-W: In analysis 'AGEON Analysis 1': Pool statement requires a value (ie:
          'pool="?U=AU"'). Ignoring...
%AGEON-W: In analysis 'AGEON Analysis 1': Pool statements must consist of at
          least two tokens (eg: "?U=AU"). Ignoring badly formed portion of pool
          statement ('foobarfoo')...
%AGEON-W: In analysis 'AGEON Analysis 1': Pool statements must consist of at
          least two tokens (eg: "?U=AU"). Ignoring badly formed portion of pool
          statement ('foobarfoo')...
%AGEON-W: In analysis 'AGEON Analysis 1': Pool statements must consist of at
          least two tokens (eg: "?U=AU"). Ignoring badly formed portion of pool
          statement ('bar')...
%AGEON-W: In analysis 'AGEON Analysis 1': Ignoring badly formed reassignment
          code in portion ('foo') of pool statement ('foo=UU')...
%AGEON-W: In analysis 'AGEON Analysis 1': Ignoring badly formed reassignment
          code ('foo') in portion of pool statement ('UU=foo')...
%AGEON-W: In analysis 'AGEON Analysis 1': Ignoring illogical reassignment from
          class '?U' to '?A'.
Reassigning individuals from class '??' to 'UU'.
Reassigning individuals from class '?U' to 'UU'.
Reassigning individuals from class '?A' to 'AA'.

Analysis parsing complete.    Analysis valid.
==============================================================


