


============================
     SAMPLE DESCRIPTION
============================

  Number of pedigrees in dataset           200  
  Number of analyzable pedigrees           200  
                                                
  Number of individuals in dataset         787  
  Number of sibs in dataset                387  
  Number of analyzable sibs                387  
  Number of sibs with missing age values     0  

===========================
     MODEL DESCRIPTION
===========================

  Title               AGEON Analysis 1  
  Affectedness trait  AFF               
  Age-of-onset trait  AO                
  Age-at-exam trait   AE                

===============================
     CLASSIFICATION SYSTEM
===============================

  Class(es) pooled.
                                                                

      - class ?? pooled with UU                                 
      - class ?A pooled with AA                                 
      - class ?U pooled with UU                                 
  
                                                             
  ??  Both parents are unknown.                                 
  ?A  One of the parents is unknown, the other is affected.     
  ?U  One of the parents is unknown, the other is unaffected.   
  AA  Both parents are affected.                                
  AU  One of the parents is affected, the other is unaffected.  
  UU  Both parents are unaffected.                              

==========================

     CLASS STATISTICS

==========================

==================
     CLASS ??
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS ?A
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS ?U
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS AA
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS           100  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          24  
  MEAN OF AGE OF ONSET                             73.875000  
  VARIANCE OF AGE OF ONSET                          6.027174  
  NUMBER OF INDIVIDUALS AFFECTED                          24  
  PROPORTION OF INDIVIDUALS AFFECTED                0.240000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            75.250000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         4.350000  

==================
     CLASS AU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            89  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          22  
  MEAN OF AGE OF ONSET                             73.681818  
  VARIANCE OF AGE OF ONSET                          4.322511  
  NUMBER OF INDIVIDUALS AFFECTED                          22  
  PROPORTION OF INDIVIDUALS AFFECTED                0.247191  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            75.268657  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         4.532791  

==================
     CLASS UU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS           198  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          38  
  MEAN OF AGE OF ONSET                             74.605263  
  VARIANCE OF AGE OF ONSET                          3.488620  
  NUMBER OF INDIVIDUALS AFFECTED                          38  
  PROPORTION OF INDIVIDUALS AFFECTED                0.191919  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            74.806250  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         5.503105  

====================================================================
     MAXIMIZATION RESULTS susceptibilities equal, no truncation
====================================================================

----------------------------------------------------------------------------
  Parameter           Estimate   S.E.         P-value      Deriv            
----------------------------------------------------------------------------
  Susceptibility intercepts
                  ??  -0.695479   0.133686    < 1.00e-06      0.0995431421  
                  ?A  -0.695479   0.133686    < 1.00e-06     -0.5261912133  
                  ?U  -0.695479   0.133686    < 1.00e-06      0.0000000000  
                  AA  -0.695479   0.133686    < 1.00e-06      0.0000000000  
                  AU  -0.695479   0.133686    < 1.00e-06      0.0000000000  
                  UU  -0.695479   0.133686    < 1.00e-06      0.0000000000  

      Mean intercept   4.544487  Unavailable  Unavailable    73.1340960687  
  Variance intercept   9.45e-07            Ind. fixed near bound            

  Transformation
             Lambda1   0.024678  Unavailable  Unavailable  -738.7425244649  
             Lambda2   0.050000                    Fixed                    
----------------------------------------------------------------------------

Final ln likelihood: -51.278921

========================================================================
     MAXIMIZATION RESULTS susceptibilities as pooled, no truncation
========================================================================

--------------------------------------------------------------------------
  Parameter           Estimate   S.E.         P-value      Deriv          
--------------------------------------------------------------------------
  Susceptibility intercepts
                  ??   0.000000                   Fixed                   
                  ?A   0.000000                   Fixed                   
                  ?U   0.000000                   Fixed                   
                  AA  -0.322430   0.268333     0.229516    -0.0000055002  
                  AU  -0.280296   0.282791     0.321600     0.0000072703  
                  UU  -0.302112   0.214606     0.159204     0.0000371314  

      Mean intercept   4.337378  Unavailable  Unavailable   0.0325632235  
  Variance intercept   9.75e-07           Ind. fixed near bound           

  Transformation
             Lambda1   0.001840  Unavailable  Unavailable  -0.3260510926  
             Lambda2   0.050000                   Fixed                   
--------------------------------------------------------------------------

Final ln likelihood: -35.104843

=======================================================================
     MAXIMIZATION RESULTS susceptibilities equal, using truncation
=======================================================================

----------------------------------------------------------------------------
  Parameter           Estimate   S.E.         P-value      Deriv            
----------------------------------------------------------------------------
  Susceptibility intercepts
                  ??  -0.695479   0.133686    < 1.00e-06      0.0995431421  
                  ?A  -0.695479   0.133686    < 1.00e-06     -0.5261912133  
                  ?U  -0.695479   0.133686    < 1.00e-06      0.0000000000  
                  AA  -0.695479   0.133686    < 1.00e-06      0.0000000000  
                  AU  -0.695479   0.133686    < 1.00e-06      0.0000000000  
                  UU  -0.695479   0.133686    < 1.00e-06      0.0000000000  

      Mean intercept   4.544487  Unavailable  Unavailable    73.1340960687  
  Variance intercept   9.45e-07            Ind. fixed near bound            

  Transformation
             Lambda1   0.024678  Unavailable  Unavailable  -738.7425244649  
             Lambda2   0.050000                    Fixed                    
----------------------------------------------------------------------------

Final ln likelihood: -51.278921

===========================================================================
     MAXIMIZATION RESULTS susceptibilities as pooled, using truncation
===========================================================================

---------------------------------------------------------------------------
  Parameter           Estimate   S.E.         P-value      Deriv           
---------------------------------------------------------------------------
  Susceptibility intercepts
                  ??   0.000000                   Fixed                    
                  ?A   0.000000                   Fixed                    
                  ?U   0.000000                   Fixed                    
                  AA  -0.322389  Unavailable  Unavailable    0.0000833833  
                  AU  -0.280253  Unavailable  Unavailable    0.0000781150  
                  UU  -0.302029  Unavailable  Unavailable    0.0002611545  

      Mean intercept   4.320146  Unavailable  Unavailable   -1.4028339420  
  Variance intercept   9.41e-07           Ind. fixed near bound            

  Transformation
             Lambda1   3.33e-07  Unavailable  Unavailable   14.5316556176  
             Lambda2   0.050000                   Fixed                    
---------------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final ln likelihood: -34.344166

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities as pooled, no truncation  -35.104843  
  H1 ln likelihood susceptibilities equal, no truncation      -51.278921  
                                                                          
  2 * |H0 - H1|                                                32.348156  
  Degrees of freedom                                                   2  
  P-value                                                       9.46e-08  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities as pooled, using truncation  -34.344166  (possible non-convergence)  
  H1 ln likelihood susceptibilities equal, using truncation      -51.278921                              
                                                                                                         
  2 * |H0 - H1|                                                   33.869509                              
  Degrees of freedom                                                      2                              
  P-value                                                          4.42e-08                              

==========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, no truncation
==========================================================================

---------------------------------------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  Lambda1    ??         ?A         ?U         AA         AU         UU         
---------------------------------------------------------------------------------------------------------------------------------------
  Mean intercept      -4.27e-07        0.000000           -1.00e-07   1.13e-06   1.13e-06   1.13e-06   1.13e-06   1.13e-06   1.13e-06  
  Variance intercept   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  Lambda1             -1.00e-07        0.000000           -4.32e-09  -1.07e-07  -1.07e-07  -1.07e-07  -1.07e-07  -1.07e-07  -1.07e-07  
  ??                   1.13e-06        0.000000           -1.07e-07   0.017872   0.017872   0.017872   0.017872   0.017872   0.017872  
  ?A                   1.13e-06        0.000000           -1.07e-07   0.017872   0.017872   0.017872   0.017872   0.017872   0.017872  
  ?U                   1.13e-06        0.000000           -1.07e-07   0.017872   0.017872   0.017872   0.017872   0.017872   0.017872  
  AA                   1.13e-06        0.000000           -1.07e-07   0.017872   0.017872   0.017872   0.017872   0.017872   0.017872  
  AU                   1.13e-06        0.000000           -1.07e-07   0.017872   0.017872   0.017872   0.017872   0.017872   0.017872  
  UU                   1.13e-06        0.000000           -1.07e-07   0.017872   0.017872   0.017872   0.017872   0.017872   0.017872  

==============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities as pooled, no truncation
==============================================================================

------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  Lambda1    AA         AU         UU         
------------------------------------------------------------------------------------------------------
  Mean intercept      -0.000851        0.000000           -9.17e-05   7.48e-05   7.70e-05   0.000149  
  Variance intercept   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000  
  Lambda1             -9.17e-05        0.000000           -9.89e-06   7.62e-06   7.84e-06   1.52e-05  
  AA                   7.48e-05        0.000000            7.62e-06   0.072002   3.49e-05   6.81e-05  
  AU                   7.70e-05        0.000000            7.84e-06   3.49e-05   0.079971   6.91e-05  
  UU                   0.000149        0.000000            1.52e-05   6.81e-05   6.91e-05   0.046056  

=============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, using truncation
=============================================================================

---------------------------------------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  Lambda1    ??         ?A         ?U         AA         AU         UU         
---------------------------------------------------------------------------------------------------------------------------------------
  Mean intercept      -4.27e-07        0.000000           -1.00e-07   1.13e-06   1.13e-06   1.13e-06   1.13e-06   1.13e-06   1.13e-06  
  Variance intercept   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  Lambda1             -1.00e-07        0.000000           -4.32e-09  -1.07e-07  -1.07e-07  -1.07e-07  -1.07e-07  -1.07e-07  -1.07e-07  
  ??                   1.13e-06        0.000000           -1.07e-07   0.017872   0.017872   0.017872   0.017872   0.017872   0.017872  
  ?A                   1.13e-06        0.000000           -1.07e-07   0.017872   0.017872   0.017872   0.017872   0.017872   0.017872  
  ?U                   1.13e-06        0.000000           -1.07e-07   0.017872   0.017872   0.017872   0.017872   0.017872   0.017872  
  AA                   1.13e-06        0.000000           -1.07e-07   0.017872   0.017872   0.017872   0.017872   0.017872   0.017872  
  AU                   1.13e-06        0.000000           -1.07e-07   0.017872   0.017872   0.017872   0.017872   0.017872   0.017872  
  UU                   1.13e-06        0.000000           -1.07e-07   0.017872   0.017872   0.017872   0.017872   0.017872   0.017872  

=================================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities as pooled, using truncation
=================================================================================



Error: Matrix is not available.

