


============================
     SAMPLE DESCRIPTION
============================

  Number of pedigrees in dataset           200  
  Number of analyzable pedigrees           200  
                                                
  Number of individuals in dataset         787  
  Number of sibs in dataset                387  
  Number of analyzable sibs                387  
  Number of sibs with missing age values     0  

===========================
     MODEL DESCRIPTION
===========================

  Title               AGEON Analysis 1  
  Affectedness trait  AFF               
  Age-of-onset trait  AO                
  Age-at-exam trait   AE                

===============================
     CLASSIFICATION SYSTEM
===============================

  Class(es) pooled.
                                                                

      - class ?? pooled with UU                                 
      - class ?A pooled with AA                                 
      - class ?U pooled with UU                                 
  
                                                             
  ??  Both parents are unknown.                                 
  ?A  One of the parents is unknown, the other is affected.     
  ?U  One of the parents is unknown, the other is unaffected.   
  AA  Both parents are affected.                                
  AU  One of the parents is affected, the other is unaffected.  
  UU  Both parents are unaffected.                              

==========================

     CLASS STATISTICS

==========================

==================
     CLASS ??
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS ?A
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS ?U
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS AA
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS           100  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          24  
  MEAN OF AGE OF ONSET                             73.875000  
  VARIANCE OF AGE OF ONSET                          6.027174  
  NUMBER OF INDIVIDUALS AFFECTED                          24  
  PROPORTION OF INDIVIDUALS AFFECTED                0.240000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            75.250000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         4.350000  

==================
     CLASS AU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            89  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          22  
  MEAN OF AGE OF ONSET                             73.681818  
  VARIANCE OF AGE OF ONSET                          4.322511  
  NUMBER OF INDIVIDUALS AFFECTED                          22  
  PROPORTION OF INDIVIDUALS AFFECTED                0.247191  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            75.268657  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         4.532791  

==================
     CLASS UU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS           198  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          38  
  MEAN OF AGE OF ONSET                             74.605263  
  VARIANCE OF AGE OF ONSET                          3.488620  
  NUMBER OF INDIVIDUALS AFFECTED                          38  
  PROPORTION OF INDIVIDUALS AFFECTED                0.191919  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            74.806250  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         5.503105  

====================================================================
     MAXIMIZATION RESULTS susceptibilities equal, no truncation
====================================================================

-----------------------------------------------------------
  Parameter           Estimate   S.E.         P-value      
-----------------------------------------------------------
  Susceptibility intercepts
                  ??  -0.302322   0.144311     0.036176    
                  ?A  -0.302322   0.144311     0.036176    
                  ?U  -0.302322   0.144311     0.036176    
                  AA  -0.302322   0.144311     0.036176    
                  AU  -0.302322   0.144311     0.036176    
                  UU  -0.302322   0.144311     0.036176    

      Mean intercept   4.338833  Unavailable  Unavailable  
  Variance intercept   9.78e-07   Ind. fixed near bound    

  Transformation
             Lambda1   0.001995  Unavailable  Unavailable  
             Lambda2   0.050000           Fixed            
-----------------------------------------------------------

Final ln likelihood: -35.170856

========================================================================
     MAXIMIZATION RESULTS susceptibilities as pooled, no truncation
========================================================================

--------------------------------------------------------
  Parameter           Estimate   S.E.       P-value     
--------------------------------------------------------
  Susceptibility intercepts
                  ??   0.000000          Fixed          
                  ?A   0.000000          Fixed          
                  ?U   0.000000          Fixed          
                  AA  -0.605851   7.83e-10  < 1.00e-07  
                  AU  -0.573851   6.65e-10  < 1.00e-07  
                  UU  -0.803724   1.19e-09  < 1.00e-07  

      Mean intercept   6.150521   1.27e-05  < 1.00e-07  
  Variance intercept   2.44e-06   5.40e-07  < 1.00e-05  

  Transformation
             Lambda1   0.156645   0.000181  < 1.00e-07  
             Lambda2   0.050000          Fixed          
--------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final ln likelihood: -83.739177

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities as pooled, no truncation  -83.739177  (possible non-convergence)  
  H1 ln likelihood susceptibilities equal, no truncation      -35.170856                              
                                                                                                      
  2 * |H0 - H1|                                                97.136641                              
  Degrees of freedom                                                   2                              
  P-value                                                       8.07e-22                              

