


============================
     SAMPLE DESCRIPTION
============================

  Number of pedigrees in dataset           200  
  Number of analyzable pedigrees           200  
                                                
  Number of individuals in dataset         787  
  Number of sibs in dataset                387  
  Number of analyzable sibs                387  
  Number of sibs with missing age values     0  

===========================
     MODEL DESCRIPTION
===========================

  Title               AGEON Analysis 1  
  Affectedness trait  AFF               
  Age-of-onset trait  AO                
  Age-at-exam trait   AE                

===============================
     CLASSIFICATION SYSTEM
===============================

  Class(es) pooled.
                                                                

      - class ?? pooled with UU                                 
      - class ?A pooled with AA                                 
      - class ?U pooled with UU                                 
  
                                                             
  ??  Both parents are unknown.                                 
  ?A  One of the parents is unknown, the other is affected.     
  ?U  One of the parents is unknown, the other is unaffected.   
  AA  Both parents are affected.                                
  AU  One of the parents is affected, the other is unaffected.  
  UU  Both parents are unaffected.                              

==========================

     CLASS STATISTICS

==========================

==================
     CLASS ??
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS ?A
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS ?U
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS AA
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS           100  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          24  
  MEAN OF AGE OF ONSET                             73.875000  
  VARIANCE OF AGE OF ONSET                          6.027174  
  NUMBER OF INDIVIDUALS AFFECTED                          24  
  PROPORTION OF INDIVIDUALS AFFECTED                0.240000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            75.250000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         4.350000  

==================
     CLASS AU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            89  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          22  
  MEAN OF AGE OF ONSET                             73.681818  
  VARIANCE OF AGE OF ONSET                          4.322511  
  NUMBER OF INDIVIDUALS AFFECTED                          22  
  PROPORTION OF INDIVIDUALS AFFECTED                0.247191  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            75.268657  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         4.532791  

==================
     CLASS UU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS           198  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          38  
  MEAN OF AGE OF ONSET                             74.605263  
  VARIANCE OF AGE OF ONSET                          3.488620  
  NUMBER OF INDIVIDUALS AFFECTED                          38  
  PROPORTION OF INDIVIDUALS AFFECTED                0.191919  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            74.806250  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         5.503105  

====================================================================
     MAXIMIZATION RESULTS susceptibilities equal, no truncation
====================================================================

--------------------------------------------------------------------------
  Parameter           Estimate   S.E.         P-value      Deriv          
--------------------------------------------------------------------------
  Susceptibility intercepts
                  ??  -0.301953   0.144277     0.036360     0.0009379823  
                  ?A  -0.301953   0.144277     0.036360     0.0000000000  
                  ?U  -0.301953   0.144277     0.036360     0.0000000000  
                  AA  -0.301953   0.144277     0.036360     0.0000000000  
                  AU  -0.301953   0.144277     0.036360     0.0000000000  
                  UU  -0.301953   0.144277     0.036360     0.0000000000  

      Mean intercept   4.222585  Unavailable  Unavailable  -0.5893797846  
  Variance intercept   7.86e-07           Ind. fixed near bound           

  Transformation
             Lambda1  -0.010608  Unavailable  Unavailable   5.3094193569  
             Lambda2   0.050000                   Fixed                   
--------------------------------------------------------------------------

Final ln likelihood: -30.459080

========================================================================
     MAXIMIZATION RESULTS susceptibilities as pooled, no truncation
========================================================================

--------------------------------------------------------------------------
  Parameter           Estimate   S.E.         P-value      Deriv          
--------------------------------------------------------------------------
  Susceptibility intercepts
                  ??   0.000000                   Fixed                   
                  ?A   0.000000                   Fixed                   
                  ?U   0.000000                   Fixed                   
                  AA  -0.322406   0.268332     0.229550    -0.0002093181  
                  AU  -0.280293   0.282791     0.321604     0.0000891069  
                  UU  -0.302074   0.214605     0.159254    -0.0004064136  

      Mean intercept   4.334287  Unavailable  Unavailable  -0.3941082999  
  Variance intercept   9.70e-07           Ind. fixed near bound           

  Transformation
             Lambda1   0.001511  Unavailable  Unavailable   3.6780770933  
             Lambda2   0.050000                   Fixed                   
--------------------------------------------------------------------------

Final ln likelihood: -34.982774

=======================================================================
     MAXIMIZATION RESULTS susceptibilities equal, using truncation
=======================================================================

-----------------------------------------------------------------------------
  Parameter           Estimate   S.E.         P-value      Deriv             
-----------------------------------------------------------------------------
  Susceptibility intercepts
                  ??  -0.302208  Unavailable  Unavailable     -0.0324279370  
                  ?A  -0.302208  Unavailable  Unavailable      0.0000000000  
                  ?U  -0.302208  Unavailable  Unavailable      0.0000000000  
                  AA  -0.302208  Unavailable  Unavailable      0.0000000000  
                  AU  -0.302208  Unavailable  Unavailable      0.0000000000  
                  UU  -0.302208  Unavailable  Unavailable      0.0000000000  

      Mean intercept   4.319934  Unavailable  Unavailable    138.4526396246  
  Variance intercept   7.86e-07            Ind. fixed near bound             

  Transformation
             Lambda1   8.96e-08  Unavailable  Unavailable  -1325.6871263582  
             Lambda2   0.050000                    Fixed                     
-----------------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final ln likelihood: -30.639479

===========================================================================
     MAXIMIZATION RESULTS susceptibilities as pooled, using truncation
===========================================================================

--------------------------------------------------------------------------
  Parameter           Estimate   S.E.         P-value      Deriv          
--------------------------------------------------------------------------
  Susceptibility intercepts
                  ??   0.000000                   Fixed                   
                  ?A   0.000000                   Fixed                   
                  ?U   0.000000                   Fixed                   
                  AA  -0.322401   0.268332     0.229557    -0.0000001349  
                  AU  -0.280265   0.282790     0.321651    -0.0000001897  
                  UU  -0.302052   0.214602     0.159279    -0.0000001180  

      Mean intercept   4.325100  Unavailable  Unavailable  -0.0328470360  
  Variance intercept   9.53e-07           Ind. fixed near bound           

  Transformation
             Lambda1   0.000530  Unavailable  Unavailable   0.2990090002  
             Lambda2   0.050000                   Fixed                   
--------------------------------------------------------------------------

Final ln likelihood: -34.616473

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities as pooled, no truncation  -34.982774  
  H1 ln likelihood susceptibilities equal, no truncation      -30.459080  
                                                                          
  2 * |H0 - H1|                                                 9.047387  
  Degrees of freedom                                                   2  
  P-value                                                       0.010849  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities as pooled, using truncation  -34.616473                              
  H1 ln likelihood susceptibilities equal, using truncation      -30.639479  (possible non-convergence)  
                                                                                                         
  2 * |H0 - H1|                                                    7.953987                              
  Degrees of freedom                                                      2                              
  P-value                                                          0.018742                              

==========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, no truncation
==========================================================================

---------------------------------------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  Lambda1    ??         ?A         ?U         AA         AU         UU         
---------------------------------------------------------------------------------------------------------------------------------------
  Mean intercept      -0.000864        0.000000           -9.67e-05   0.000131   0.000131   0.000131   0.000131   0.000131   0.000131  
  Variance intercept   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  Lambda1             -9.67e-05        0.000000           -1.08e-05   1.40e-05   1.40e-05   1.40e-05   1.40e-05   1.40e-05   1.40e-05  
  ??                   0.000131        0.000000            1.40e-05   0.020816   0.020816   0.020816   0.020816   0.020816   0.020816  
  ?A                   0.000131        0.000000            1.40e-05   0.020816   0.020816   0.020816   0.020816   0.020816   0.020816  
  ?U                   0.000131        0.000000            1.40e-05   0.020816   0.020816   0.020816   0.020816   0.020816   0.020816  
  AA                   0.000131        0.000000            1.40e-05   0.020816   0.020816   0.020816   0.020816   0.020816   0.020816  
  AU                   0.000131        0.000000            1.40e-05   0.020816   0.020816   0.020816   0.020816   0.020816   0.020816  
  UU                   0.000131        0.000000            1.40e-05   0.020816   0.020816   0.020816   0.020816   0.020816   0.020816  

==============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities as pooled, no truncation
==============================================================================

------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  Lambda1    AA         AU         UU         
------------------------------------------------------------------------------------------------------
  Mean intercept      -0.000849        0.000000           -9.17e-05   7.51e-05   7.72e-05   0.000149  
  Variance intercept   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000  
  Lambda1             -9.17e-05        0.000000           -9.89e-06   7.66e-06   7.88e-06   1.52e-05  
  AA                   7.51e-05        0.000000            7.66e-06   0.072002   3.48e-05   6.78e-05  
  AU                   7.72e-05        0.000000            7.88e-06   3.48e-05   0.079971   6.88e-05  
  UU                   0.000149        0.000000            1.52e-05   6.78e-05   6.88e-05   0.046055  

=============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, using truncation
=============================================================================



Error: Matrix is not available.

=================================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities as pooled, using truncation
=================================================================================

------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  Lambda1    AA         AU         UU         
------------------------------------------------------------------------------------------------------
  Mean intercept      -0.000847        0.000000           -9.17e-05   7.60e-05   7.82e-05   0.000151  
  Variance intercept   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000  
  Lambda1             -9.17e-05        0.000000           -9.93e-06   7.78e-06   8.01e-06   1.55e-05  
  AA                   7.60e-05        0.000000            7.78e-06   0.072002   3.45e-05   6.72e-05  
  AU                   7.82e-05        0.000000            8.01e-06   3.45e-05   0.079970   6.82e-05  
  UU                   0.000151        0.000000            1.55e-05   6.72e-05   6.82e-05   0.046054  

