=======================

     Freq Analysis

=======================

=======================
     Configuration
=======================

  Output file:                 freq       
  Founder weight:              Disabled   
  Max. likelihood estimation:  Enabled    
  Inbreeding coefficient:      Estimated  

Note: A '*' by an MLE column indicates that the corresponding maximization may not have converged. Please review the detailed output file for more information.
=================================
     Allele frequencies 'm1'
=================================

--------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  *MLE (inbreeding = -1)  
--------------------------------------------------------------------------------------
  5        0.500000       0.500000        0.500000             0.500000               
  2        0.500000       0.500000        0.500000             0.500000               

=================================
     MAXIMIZATION RESULTS m1
=================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          5   0.500000   0.353562            0.0000000001  
          2   0.500000   0.353562            0.0000000000  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -0.693147

=================================
     MAXIMIZATION RESULTS m1
=================================

---------------------------------------------------------------------
  Parameter          Estimate   S.E.         P-value  Deriv          
---------------------------------------------------------------------
  Alleles
                  5   0.500000  Unavailable            0.0000000000  
                  2   0.500000  Unavailable            0.0000000000  

  Inbreeding coeff.  -1.000000          Ind. fixed @ bound           
---------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final Log likelihood with inbreeding:  0.000000

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m1  -0.693147                              
  H1 Log likelihood with inbreeding m1      0.000000  (possible non-convergence)  
                                                                                  
  2 * |H0 - H1|                             1.386294                              
  Degrees of freedom                               1                              
  P-value                                   0.239032                              

=================================
     Allele frequencies 'm2'
=================================

---------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  *MLE (inbreeding = -0.333224)  
---------------------------------------------------------------------------------------------
  1        0.250000       0.222222        0.250000             0.249962                      
  5        0.250000       0.277778        0.250000             0.249976                      
  2        0.250000       0.277778        0.250000             0.250124                      
  3        0.250000       0.222222        0.250000             0.249938                      

=================================
     MAXIMIZATION RESULTS m2
=================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          1   0.250000   0.216506           -0.0000008217  
          5   0.250000   0.216507           -0.0000010647  
          2   0.250000   0.216507            0.0000000104  
          3   0.250000   0.216506           -0.0000006278  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -13.862944

=================================
     MAXIMIZATION RESULTS m2
=================================

---------------------------------------------------------------------
  Parameter          Estimate   S.E.         P-value  Deriv          
---------------------------------------------------------------------
  Alleles
                  1   0.249962  Unavailable           -1.5001237997  
                  5   0.249976  Unavailable            0.0000000000  
                  2   0.250124  Unavailable            0.0000000000  
                  3   0.249938  Unavailable            0.0000000000  

  Inbreeding coeff.  -0.333224  Unavailable            0.0000000000  
---------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final Log likelihood with inbreeding: -13.287744

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m2  -13.862944                              
  H1 Log likelihood with inbreeding m2     -13.287744  (possible non-convergence)  
                                                                                   
  2 * |H0 - H1|                              1.150399                              
  Degrees of freedom                                1                              
  P-value                                    0.283466                              

=================================
     Allele frequencies 'm3'
=================================

---------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  *MLE (inbreeding = -0.300424)  
---------------------------------------------------------------------------------------------
  1        0.750000       0.800000        0.749944             0.768980                      
  5        0.250000       0.200000        0.250056             0.231020                      

=================================
     MAXIMIZATION RESULTS m3
=================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          1   0.749944   0.204779            0.0000813176  
          5   0.250056   0.204779           -0.0002438804  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -7.101371

=================================
     MAXIMIZATION RESULTS m3
=================================

---------------------------------------------------------------------
  Parameter          Estimate   S.E.         P-value  Deriv          
---------------------------------------------------------------------
  Alleles
                  1   0.768980  Unavailable           -0.4387513093  
                  5   0.231020  Unavailable            0.0000000000  

  Inbreeding coeff.  -0.300424  Unavailable            0.0000000000  
---------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final Log likelihood with inbreeding: -6.937252

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m3  -7.101371                              
  H1 Log likelihood with inbreeding m3     -6.937252  (possible non-convergence)  
                                                                                  
  2 * |H0 - H1|                             0.328237                              
  Degrees of freedom                               1                              
  P-value                                   0.566699                              

=================================
     Allele frequencies 'm4'
=================================

---------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  *MLE (inbreeding = -0.333288)  
---------------------------------------------------------------------------------------------
  4        0.500000       0.550000        0.500000             0.499954                      
  3        0.250000       0.200000        0.250000             0.249975                      
  7        0.250000       0.250000        0.250000             0.250072                      

=================================
     MAXIMIZATION RESULTS m4
=================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          4   0.500000   0.250002            0.0000003114  
          3   0.250000   0.216509           -0.0000012873  
          7   0.250000   0.216509           -0.0000008925  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -13.862944

=================================
     MAXIMIZATION RESULTS m4
=================================

---------------------------------------------------------------------
  Parameter          Estimate   S.E.         P-value  Deriv          
---------------------------------------------------------------------
  Alleles
                  4   0.499954  Unavailable           -1.5000513703  
                  3   0.249975  Unavailable            0.0000000000  
                  7   0.250072  Unavailable            0.0000000000  

  Inbreeding coeff.  -0.333288  Unavailable            0.0000000000  
---------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final Log likelihood with inbreeding: -13.287647

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m4  -13.862944                              
  H1 Log likelihood with inbreeding m4     -13.287647  (possible non-convergence)  
                                                                                   
  2 * |H0 - H1|                              1.150592                              
  Degrees of freedom                                1                              
  P-value                                    0.283425                              

=================================
     Allele frequencies 'm5'
=================================

---------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  *MLE (inbreeding = -0.333333)  
---------------------------------------------------------------------------------------------
  2        0.250000       0.250000        0.250000             0.250000                      
  9        0.250000       0.250000        0.250000             0.250000                      
  3        0.250000       0.250000        0.250000             0.250000                      
  6        0.250000       0.250000        0.250000             0.250000                      

=================================
     MAXIMIZATION RESULTS m5
=================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          2   0.250000   0.216514            0.0000000000  
          9   0.250000   0.216514            0.0000000000  
          3   0.250000   0.216514            0.0000000000  
          6   0.250000   0.216514            0.0000000000  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -15.249238

=================================
     MAXIMIZATION RESULTS m5
=================================

---------------------------------------------------------------------
  Parameter          Estimate   S.E.         P-value  Deriv          
---------------------------------------------------------------------
  Alleles
                  2   0.250000  Unavailable           -1.5000004822  
                  9   0.250000  Unavailable            0.0000000000  
                  3   0.250000  Unavailable            0.0000000000  
                  6   0.250000  Unavailable            0.0000000000  

  Inbreeding coeff.  -0.333333  Unavailable            0.0000000000  
---------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final Log likelihood with inbreeding: -14.673874

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m5  -15.249238                              
  H1 Log likelihood with inbreeding m5     -14.673874  (possible non-convergence)  
                                                                                   
  2 * |H0 - H1|                              1.150728                              
  Degrees of freedom                                1                              
  P-value                                    0.283397                              

=================================
     Allele frequencies 'm6'
=================================

--------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  *MLE (inbreeding = -0.33355)  
--------------------------------------------------------------------------------------------
  5        0.250000       0.300000        0.249999             0.275419                     
  1        0.500000       0.450000        0.500000             0.474459                     
  7        0.250000       0.250000        0.250000             0.250122                     

=================================
     MAXIMIZATION RESULTS m6
=================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          5   0.249999   0.216496            0.0000008634  
          1   0.500000   0.249992           -0.0000012518  
          7   0.250000   0.216497           -0.0000028721  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -13.862944

=================================
     MAXIMIZATION RESULTS m6
=================================

---------------------------------------------------------------------
  Parameter          Estimate   S.E.         P-value  Deriv          
---------------------------------------------------------------------
  Alleles
                  5   0.275419  Unavailable           -1.4997563276  
                  1   0.474459  Unavailable            0.0000000000  
                  7   0.250122  Unavailable            0.0000000000  

  Inbreeding coeff.  -0.333550  Unavailable            0.0000000000  
---------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final Log likelihood with inbreeding: -13.294799

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m6  -13.862944                              
  H1 Log likelihood with inbreeding m6     -13.294799  (possible non-convergence)  
                                                                                   
  2 * |H0 - H1|                              1.136289                              
  Degrees of freedom                                1                              
  P-value                                    0.286438                              

=================================
     Allele frequencies 'm7'
=================================

----------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  MLE (inbreeding = 1e-06)  
----------------------------------------------------------------------------------------
  7        0.250000       0.300000        0.250000             0.250000                 
  5        0.250000       0.200000        0.250000             0.250000                 
  4        0.500000       0.500000        0.500000             0.500000                 

=================================
     MAXIMIZATION RESULTS m7
=================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          7   0.250000   0.216530            0.0000008605  
          5   0.250000   0.216530            0.0000008735  
          4   0.500000   0.250021            0.0000012983  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -9.010913

=================================
     MAXIMIZATION RESULTS m7
=================================

-------------------------------------------------------------------
  Parameter          Estimate   S.E.       P-value  Deriv          
-------------------------------------------------------------------
  Alleles
                  7   0.250000   0.250035            0.0000006153  
                  5   0.250000   0.250035            0.0000003448  
                  4   0.500000   0.353630            0.0000003568  

  Inbreeding coeff.   1.00e-06   1.000302            0.0000002660  
-------------------------------------------------------------------

Final Log likelihood with inbreeding: -9.010913

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m7  -9.010913  
  H1 Log likelihood with inbreeding m7     -9.010913  
                                                      
  2 * |H0 - H1|                             3.89e-12  
  Degrees of freedom                               1  
  P-value                                   0.999998  

=================================
     Allele frequencies 'm8'
=================================

--------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  *MLE (inbreeding = -0.33355)  
--------------------------------------------------------------------------------------------
  3        0.250000       0.300000        0.249999             0.275419                     
  2        0.500000       0.450000        0.500000             0.474459                     
  4        0.250000       0.250000        0.250000             0.250122                     

=================================
     MAXIMIZATION RESULTS m8
=================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          3   0.249999   0.216496            0.0000008634  
          2   0.500000   0.249992           -0.0000012518  
          4   0.250000   0.216497           -0.0000028721  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -13.862944

=================================
     MAXIMIZATION RESULTS m8
=================================

---------------------------------------------------------------------
  Parameter          Estimate   S.E.         P-value  Deriv          
---------------------------------------------------------------------
  Alleles
                  3   0.275419  Unavailable           -1.4997563276  
                  2   0.474459  Unavailable            0.0000000000  
                  4   0.250122  Unavailable            0.0000000000  

  Inbreeding coeff.  -0.333550  Unavailable            0.0000000000  
---------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final Log likelihood with inbreeding: -13.294799

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m8  -13.862944                              
  H1 Log likelihood with inbreeding m8     -13.294799  (possible non-convergence)  
                                                                                   
  2 * |H0 - H1|                              1.136289                              
  Degrees of freedom                                1                              
  P-value                                    0.286438                              

=================================
     Allele frequencies 'm9'
=================================

---------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  *MLE (inbreeding = -0.344414)  
---------------------------------------------------------------------------------------------
  4        0.250000       0.300000        0.249999             0.267142                      
  1        0.500000       0.500000        0.500001             0.476677                      
  3        0.250000       0.200000        0.249999             0.256181                      

=================================
     MAXIMIZATION RESULTS m9
=================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          4   0.249999   0.216542            0.0000056159  
          1   0.500001   0.250032           -0.0000014821  
          3   0.249999   0.216542            0.0000057794  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -13.862944

=================================
     MAXIMIZATION RESULTS m9
=================================

---------------------------------------------------------------------
  Parameter          Estimate   S.E.         P-value  Deriv          
---------------------------------------------------------------------
  Alleles
                  4   0.267142  Unavailable           -1.4704960740  
                  1   0.476677  Unavailable            0.0000000000  
                  3   0.256181  Unavailable            0.0000000000  

  Inbreeding coeff.  -0.344414  Unavailable            0.0000000000  
---------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final Log likelihood with inbreeding: -13.275823

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m9  -13.862944                              
  H1 Log likelihood with inbreeding m9     -13.275823  (possible non-convergence)  
                                                                                   
  2 * |H0 - H1|                              1.174241                              
  Degrees of freedom                                1                              
  P-value                                    0.278531                              

==================================
     Allele frequencies 'm10'
==================================

---------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  *MLE (inbreeding = -0.300424)  
---------------------------------------------------------------------------------------------
  4        0.750000       0.800000        0.749944             0.768980                      
  1        0.250000       0.200000        0.250056             0.231020                      

==================================
     MAXIMIZATION RESULTS m10
==================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          4   0.749944   0.204779            0.0000813176  
          1   0.250056   0.204779           -0.0002438804  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -7.101371

==================================
     MAXIMIZATION RESULTS m10
==================================

---------------------------------------------------------------------
  Parameter          Estimate   S.E.         P-value  Deriv          
---------------------------------------------------------------------
  Alleles
                  4   0.768980  Unavailable           -0.4387513093  
                  1   0.231020  Unavailable            0.0000000000  

  Inbreeding coeff.  -0.300424  Unavailable            0.0000000000  
---------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final Log likelihood with inbreeding: -6.937252

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m10  -7.101371                              
  H1 Log likelihood with inbreeding m10     -6.937252  (possible non-convergence)  
                                                                                   
  2 * |H0 - H1|                              0.328237                              
  Degrees of freedom                                1                              
  P-value                                    0.566699                              

==================================
     Allele frequencies 'm11'
==================================

----------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  MLE (inbreeding = 1e-06)  
----------------------------------------------------------------------------------------
  8        0.250000       0.300000        0.250000             0.250000                 
  5        0.250000       0.200000        0.250000             0.250000                 
  2        0.500000       0.500000        0.500000             0.500000                 

==================================
     MAXIMIZATION RESULTS m11
==================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          8   0.250000   0.216530            0.0000008605  
          5   0.250000   0.216530            0.0000008735  
          2   0.500000   0.250021            0.0000012983  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -9.010913

==================================
     MAXIMIZATION RESULTS m11
==================================

-------------------------------------------------------------------
  Parameter          Estimate   S.E.       P-value  Deriv          
-------------------------------------------------------------------
  Alleles
                  8   0.250000   0.250035            0.0000006153  
                  5   0.250000   0.250035            0.0000003448  
                  2   0.500000   0.353630            0.0000003568  

  Inbreeding coeff.   1.00e-06   1.000302            0.0000002660  
-------------------------------------------------------------------

Final Log likelihood with inbreeding: -9.010913

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m11  -9.010913  
  H1 Log likelihood with inbreeding m11     -9.010913  
                                                       
  2 * |H0 - H1|                              3.89e-12  
  Degrees of freedom                                1  
  P-value                                    0.999998  

==================================
     Allele frequencies 'm12'
==================================

---------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  *MLE (inbreeding = -0.333126)  
---------------------------------------------------------------------------------------------
  1        0.250000       0.300000        0.250000             0.250129                      
  3        0.250000       0.200000        0.250000             0.249884                      
  6        0.250000       0.300000        0.250000             0.250000                      
  4        0.250000       0.200000        0.250000             0.249987                      

==================================
     MAXIMIZATION RESULTS m12
==================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          1   0.250000   0.216514            0.0000000000  
          3   0.250000   0.216514            0.0000000000  
          6   0.250000   0.216514            0.0000000000  
          4   0.250000   0.216514            0.0000000000  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -15.249238

==================================
     MAXIMIZATION RESULTS m12
==================================

---------------------------------------------------------------------
  Parameter          Estimate   S.E.         P-value  Deriv          
---------------------------------------------------------------------
  Alleles
                  1   0.250129  Unavailable           -1.5002334531  
                  3   0.249884  Unavailable            0.0000000000  
                  6   0.250000  Unavailable            0.0000000000  
                  4   0.249987  Unavailable            0.0000000000  

  Inbreeding coeff.  -0.333126  Unavailable            0.0000000000  
---------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final Log likelihood with inbreeding: -14.674185

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m12  -15.249238                              
  H1 Log likelihood with inbreeding m12     -14.674185  (possible non-convergence)  
                                                                                    
  2 * |H0 - H1|                               1.150107                              
  Degrees of freedom                                 1                              
  P-value                                     0.283527                              

==================================
     Allele frequencies 'm13'
==================================

---------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  *MLE (inbreeding = -0.333126)  
---------------------------------------------------------------------------------------------
  5        0.250000       0.300000        0.250000             0.250129                      
  3        0.250000       0.200000        0.250000             0.249884                      
  2        0.250000       0.300000        0.250000             0.250000                      
  4        0.250000       0.200000        0.250000             0.249987                      

==================================
     MAXIMIZATION RESULTS m13
==================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          5   0.250000   0.216514            0.0000000000  
          3   0.250000   0.216514            0.0000000000  
          2   0.250000   0.216514            0.0000000000  
          4   0.250000   0.216514            0.0000000000  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -15.249238

==================================
     MAXIMIZATION RESULTS m13
==================================

---------------------------------------------------------------------
  Parameter          Estimate   S.E.         P-value  Deriv          
---------------------------------------------------------------------
  Alleles
                  5   0.250129  Unavailable           -1.5002334531  
                  3   0.249884  Unavailable            0.0000000000  
                  2   0.250000  Unavailable            0.0000000000  
                  4   0.249987  Unavailable            0.0000000000  

  Inbreeding coeff.  -0.333126  Unavailable            0.0000000000  
---------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final Log likelihood with inbreeding: -14.674185

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m13  -15.249238                              
  H1 Log likelihood with inbreeding m13     -14.674185  (possible non-convergence)  
                                                                                    
  2 * |H0 - H1|                               1.150107                              
  Degrees of freedom                                 1                              
  P-value                                     0.283527                              

==================================
     Allele frequencies 'm14'
==================================

---------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  *MLE (inbreeding = -0.300424)  
---------------------------------------------------------------------------------------------
  4        0.750000       0.800000        0.749944             0.768980                      
  1        0.250000       0.200000        0.250056             0.231020                      

==================================
     MAXIMIZATION RESULTS m14
==================================

-----------------------------------------------------------
  Parameter  Estimate   S.E.       P-value  Deriv          
-----------------------------------------------------------
  Alleles
          4   0.749944   0.204779            0.0000813176  
          1   0.250056   0.204779           -0.0002438804  
-----------------------------------------------------------

Final Log likelihood without inbreeding: -7.101371

==================================
     MAXIMIZATION RESULTS m14
==================================

---------------------------------------------------------------------
  Parameter          Estimate   S.E.         P-value  Deriv          
---------------------------------------------------------------------
  Alleles
                  4   0.768980  Unavailable           -0.4387513093  
                  1   0.231020  Unavailable            0.0000000000  

  Inbreeding coeff.  -0.300424  Unavailable            0.0000000000  
---------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final Log likelihood with inbreeding: -6.937252

====================
     Joint test
====================

  H0 Log likelihood without inbreeding m14  -7.101371                              
  H1 Log likelihood with inbreeding m14     -6.937252  (possible non-convergence)  
                                                                                   
  2 * |H0 - H1|                              0.328237                              
  Degrees of freedom                                1                              
  P-value                                    0.566699                              


