pedigree 1, subpedigree 1:2, member 1, log likelihood -5.3538, lod score  0.0578182
pedigree 1, subpedigree 1:2, member 2, log likelihood -5.3538, lod score  0.0578182
pedigree 1, subpedigree 1:2, member 3, log likelihood -5.3538, lod score  0.0578182
pedigree 1, subpedigree 1:2, member 4, log likelihood -5.3538, lod score  0.0578182
pedigree 1, subpedigree 1:2, member 5, log likelihood -5.3538, lod score  0.0578182
pedigree 1, subpedigree 1:2, member 6, log likelihood -5.3538, lod score  0.0578182
pedigree 1, subpedigree 1:2, member 7, log likelihood -5.3538, lod score  0.0578182
