
Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             F                                   
     1             2             M                                   
     1             3             M         1             2           
     1             4             F         1             2           
     1             5             M                                   
     1             6             F         4             5           
     2             1                                                 
     2             2                                                 
     3             1                                                 
     3             2                                                 


Markers for the first 10 individuals read from file: ped

     PED. ID       IND. ID       loc1          loc2        
     ------------  ------------  ------------  ------------
     1             1             a/b           c/d         
     1             2             b/b           d/d         
     1             3             a/b           d/d         
     1             4             b/b           c/c         
     1             5             a/a           c/c         
     1             6             a/a           c/d         
     2             1             ?/?           ?/?         
     2             2             ?/?           ?/?         
     3             1             ?/?           ?/?         
     3             2             ?/?           ?/?         

%TESTPARSER-E: 
%TESTPARSER-E: ---------- 1 New Analysis Block 1 ---------- 
%TESTPARSER-E: 
%TESTPARSER-C: No valid trait or marker locus specified for analysis.  Skipping
               analysis ...
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 2 New Analysis Block 2 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: No trait locus description read for trait, HEMATOCRIT.  Ignoring
               ...
%TESTPARSER-C: No valid trait or marker locus specified for analysis.  Skipping
               analysis ...
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 3 New Analysis Block 3 ---------- 
%TESTPARSER-E: 
%TESTPARSER-W: Trait, loc1, is a  marker, not a trait locus produced by
               segregation analysis.
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 4 New Analysis Block 4 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 5 New Analysis Block 5 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 6 New Analysis Block 6 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 7 New Analysis Block 7 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: average thetas must be specified in lods sub-block with option
               'specified' chosen and sex_specific equal to 'false'.  Ignoring
               lods sub-block ...
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 8 New Analysis Block 8 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 9 New Analysis Block 9 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: Marker to marker linkage not compatible with calculation of
               genotype probabilities.  Not calculating genotype probabilities
               ...
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 10 New Analysis Block 10 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: No trait locus description read for trait, t.  Ignoring ...
%TESTPARSER-C: No valid trait or marker locus specified for analysis.  Skipping
               analysis ...
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 11 New Analysis Block 11 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: No trait locus description read for trait, t.  Ignoring ...
%TESTPARSER-C: No valid trait or marker locus specified for analysis.  Skipping
               analysis ...
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 12 New Analysis Block 12 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: Marker to marker linkage not compatible with Smith's
               heterogeneity model.  Not performing linkage test.
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 13 New Analysis Block 13 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 14 New Analysis Block 14 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: Marker to marker linkage not compatible with Smith's test.  Not
               performing Smith's test.
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 15 New Analysis Block 15 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: Marker to marker linkage not compatible with Smith's test.  Not
               performing Smith's test.
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 16 New Analysis Block 16 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: 1.2 not a valid value for theta.  Ignoring ...
%TESTPARSER-E: -0.2 not a valid value for theta.  Ignoring ...
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 17 New Analysis Block 17 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: Duplicate pedigree_id given in group sub-block.  Ignoring
               duplicate pedigree_id ...
%TESTPARSER-E: Marker to marker linkage not compatible with Smith's test.  Not
               performing Smith's test.
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 18 New Analysis Block 18 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: Pedigree included in more than one group.  Skipping Morton's
               test ...
%TESTPARSER-E: Marker to marker linkage not compatible with Smith's test.  Not
               performing Smith's test.
%TESTPARSER-E: 
%TESTPARSER-E: ---------- 19 New Analysis Block 19 ---------- 
%TESTPARSER-E: 
%TESTPARSER-E: Duplicate group name 'one' given in mortons test sub-block. 
               Ignoring second group ...
%TESTPARSER-E: Not all pedigrees included in groups.  Skipping Morton's test
               ...
%TESTPARSER-E: Marker to marker linkage not compatible with Smith's test.  Not
               performing Smith's test.
