



Family structure information on the first 10 individuals read from file: myped1

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             F                                   
     1             2             M                                   
     1             3             M         1             2           
     1             4             F         1             2           
     1             5             M                                   
     1             6             F         4             5           


Phenotypes for the first 10 individuals read from file: myped1

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         DISEASE               HEMATOCRIT          
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             1                     1                     1                     6                     1                     30                  
     1             2             0                     1                     1                     6                     0                     40                  
     1             3             0                     1                     0                     6                     0                     27.1                
     1             4             1                     1                     0                     6                     1                     39                  
     1             5             0                     1                     1                     6                     0                     37.6                
     1             6             1                     1                     0                     6                     1                     41.1                

