


===============================
LODLINK Analysis 1 SUMMARY FILE
===============================


Options Selected
================
Main locus type                          trait
Main locus name                          segreg_analysis1

Lod scores                               no

Linkage tests                            yes
  Sex specific recombination fractions   yes
  Assume homogeneity                     yes

Smith's test for homogeneity             no
  Sex specific recombination fractions   yes

Morton's test for homogeneity            no
  Sex specific recombination fractions   yes

Genotype probabilities                   yes
  Sex specific recombination fractions   no


Results
=======




                  MLE                                             Lod Score and Linkage Test    
                                                                  Using Recom. Fract. in [0, .5]
                                                                                                
Locus             Male Rc     Female Rc   Male Rc     Female Rc   Lod         Chi         P-Value     P-Value     
                  Fract in    Fract in    Fract in    Fract in    Score       Square                  Upper       
                  [0, .5]     [0, .5]     [0, 1]      [0, 1]                  Stat                    Bound       
---------------   ---------   ---------   ---------   ---------   ---------   ---------   ---------   ---------   
T1                   0.0000      0.0000        ---         ---          162         747   < 1.0e-20   < 1.0e-20   
M1                   0.0000      0.0000        ---         ---          135         622   < 1.0e-20   < 1.0e-20   
M2                   0.4819      0.5000      0.4819      0.5000      0.0498        ---         ---         ---    



                  Cleves-Elston Linkage Test   
                                               
                                               
Locus             Male Rc     Female Rc   Lod         Chi         P-Value     
                  Fract in    Fract in    Score       Square                  
                  [0, 1]      [0, 1]                  Stat                    
---------------   ---------   ---------   ---------   ---------   ---------   
T1                   0.0000      0.0000           0           0         0.5   
M1                   0.0000      0.0000           0           0         0.5   
M2                   0.4819      0.5001     0.00114     0.00525      0.4711   
