



Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             F                                   
     1             2             M                                   
     1             3             F         1             2           
     1             4             M         1             2           
     1             5             F         3             4           
     2             1             F                                   
     2             2             M                                   
     2             3             M                                   
     2             4             F         1             2           
     2             5             M         1             2           


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         DISEASE               HEMATOCRIT          
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             1                     1                     1                     5                     1                     30                  
     1             2             0                     1                     1                     5                     0                     40                  
     1             3             1                     1                     0                     5                     0                     27.1                
     1             4             0                     1                     0                     5                     1                     39                  
     1             5             1                     1                     0                     5                     0                     37.6                
     2             1             1                     1                     1                     9                     1                     30                  
     2             2             0                     1                     1                     9                     0                     40                  
     2             3             0                     1                     1                     9                     0                     27.1                
     2             4             1                     1                     0                     9                     1                     39                  
     2             5             0                     1                     0                     9                     0                     37.6                

