


Maximizing total population...

Note:  Haplotypes listed have estimated frequencies greater than or equal to
       the cutoff or have the greatest frequency estimate.

Markers in order:
  rs175138 rs175139 



run 1
start point
Haplotype          Frequency
---------          ---------
      1-1          0.4682087
      2-2          0.2612551
      2-1          0.1352681
      1-2          0.1352681
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.6034768
      2-2          0.3965232
                   ---------
             Total 1.0000000

Ln likelihood    -608.173

run 2
start point
Haplotype          Frequency
---------          ---------
      1-1          0.4148271
      2-2          0.2078734
      2-1          0.1886497
      1-2          0.1886497
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.6034768
      2-2          0.3965232
                   ---------
             Total 1.0000000

Ln likelihood    -608.173

run 3
start point
Haplotype          Frequency
---------          ---------
      1-1          0.3900331
      2-1          0.2134437
      1-2          0.2134437
      2-2          0.1830795
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.6034768
      2-2          0.3965232
                   ---------
             Total 1.0000000

Ln likelihood    -608.173

run 4
start point
Haplotype          Frequency
---------          ---------
      1-1          0.4322653
      2-2          0.2253116
      2-1          0.1712115
      1-2          0.1712115
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.6034768
      2-2          0.3965232
                   ---------
             Total 1.0000000

Ln likelihood    -608.173

run 5
start point
Haplotype          Frequency
---------          ---------
      1-1          0.3700800
      2-1          0.2333969
      1-2          0.2333969
      2-2          0.1631263
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.6034768
      2-2          0.3965232
                   ---------
             Total 1.0000000

Ln likelihood    -608.173

run 6
start point
Haplotype          Frequency
---------          ---------
      1-1          0.3818882
      2-1          0.2215886
      1-2          0.2215886
      2-2          0.1749346
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.6034768
      2-2          0.3965232
                   ---------
             Total 1.0000000

Ln likelihood    -608.173

run 7
start point
Haplotype          Frequency
---------          ---------
      1-1          0.4262290
      2-2          0.2192753
      2-1          0.1772478
      1-2          0.1772478
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.6034768
      2-2          0.3965232
                   ---------
             Total 1.0000000

Ln likelihood    -608.173

run 8
start point
Haplotype          Frequency
---------          ---------
      1-1          0.5012595
      2-2          0.2943058
      2-1          0.1022174
      1-2          0.1022174
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.6034768
      2-2          0.3965232
                   ---------
             Total 1.0000000

Ln likelihood    -608.173

run 9
start point
Haplotype          Frequency
---------          ---------
      1-1          0.4902870
      2-2          0.2833333
      2-1          0.1131898
      1-2          0.1131898
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.6034768
      2-2          0.3965232
                   ---------
             Total 1.0000000

Ln likelihood    -608.173

run 10
start point
Haplotype          Frequency
---------          ---------
      1-1          0.4528020
      2-2          0.2458484
      2-1          0.1506748
      1-2          0.1506748
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.6034768
      2-2          0.3965232
                   ---------
             Total 1.0000000

Ln likelihood    -608.173

Maximizing total population...

Note:  Haplotypes listed have estimated frequencies greater than or equal to
       the cutoff or have the greatest frequency estimate.

Markers in order:
  rs135223 rs8136406 



run 1
start point
Haplotype          Frequency
---------          ---------
      2-1          0.5583866
      1-1          0.3894611
      1-2          0.0269296
      2-2          0.0252227
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      2-1          0.5733675
      1-1          0.3744802
      1-2          0.0419105
      2-2          0.0102418
                   ---------
             Total 1.0000000

Ln likelihood    -814.281

run 2
start point
Haplotype          Frequency
---------          ---------
      2-1          0.5469134
      1-1          0.4009342
      2-2          0.0366958
      1-2          0.0154565
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      2-1          0.5733669
      1-1          0.3744808
      1-2          0.0419099
      2-2          0.0102424
                   ---------
             Total 1.0000000

Ln likelihood    -814.281

run 3
start point
Haplotype          Frequency
---------          ---------
      2-1          0.5729545
      1-1          0.3748932
      1-2          0.0414975
      2-2          0.0106548
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      2-1          0.5733689
      1-1          0.3744788
      1-2          0.0419119
      2-2          0.0102404
                   ---------
             Total 1.0000000

Ln likelihood    -814.281

run 4
start point
Haplotype          Frequency
---------          ---------
      2-1          0.5614264
      1-1          0.3864213
      1-2          0.0299694
      2-2          0.0221829
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      2-1          0.5733692
      1-1          0.3744785
      1-2          0.0419122
      2-2          0.0102401
                   ---------
             Total 1.0000000

Ln likelihood    -814.281

run 5
start point
Haplotype          Frequency
---------          ---------
      2-1          0.5752923
      1-1          0.3725554
      1-2          0.0438354
      2-2          0.0083169
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      2-1          0.5733796
      1-1          0.3744681
      1-2          0.0419227
      2-2          0.0102296
                   ---------
             Total 1.0000000

Ln likelihood    -814.281

run 6
start point
Haplotype          Frequency
---------          ---------
      2-1          0.5616722
      1-1          0.3861755
      1-2          0.0302152
      2-2          0.0219371
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      2-1          0.5733693
      1-1          0.3744784
      1-2          0.0419124
      2-2          0.0102400
                   ---------
             Total 1.0000000

Ln likelihood    -814.281

run 7
start point
Haplotype          Frequency
---------          ---------
      2-1          0.5609138
      1-1          0.3869339
      1-2          0.0294569
      2-2          0.0226955
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      2-1          0.5733689
      1-1          0.3744788
      1-2          0.0419120
      2-2          0.0102403
                   ---------
             Total 1.0000000

Ln likelihood    -814.281

run 8
start point
Haplotype          Frequency
---------          ---------
      2-1          0.5582376
      1-1          0.3896100
      1-2          0.0267807
      2-2          0.0253716
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      2-1          0.5733674
      1-1          0.3744803
      1-2          0.0419105
      2-2          0.0102419
                   ---------
             Total 1.0000000

Ln likelihood    -814.281

run 9
start point
Haplotype          Frequency
---------          ---------
      2-1          0.5686960
      1-1          0.3791517
      1-2          0.0372390
      2-2          0.0149133
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      2-1          0.5733669
      1-1          0.3744807
      1-2          0.0419100
      2-2          0.0102423
                   ---------
             Total 1.0000000

Ln likelihood    -814.281

run 10
start point
Haplotype          Frequency
---------          ---------
      2-1          0.5638734
      1-1          0.3839743
      1-2          0.0324165
      2-2          0.0197359
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      2-1          0.5733664
      1-1          0.3744813
      1-2          0.0419094
      2-2          0.0102429
                   ---------
             Total 1.0000000

Ln likelihood    -814.281

Maximizing total population...

Note:  Haplotypes listed have estimated frequencies greater than or equal to
       the cutoff or have the greatest frequency estimate.

Markers in order:
  rs138853 rs2092982 



run 1
start point
Haplotype          Frequency
---------          ---------
      1-1          0.7033150
      1-2          0.1891008
      2-1          0.0673803
      2-2          0.0402039
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.7697304
      1-2          0.1230971
      2-2          0.1062075
                   ---------
             Total 0.9990350

Ln likelihood    -677.488

run 2
start point
Haplotype          Frequency
---------          ---------
      1-1          0.6985133
      1-2          0.1935379
      2-1          0.0721821
      2-2          0.0357667
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.7697302
      1-2          0.1230972
      2-2          0.1062074
                   ---------
             Total 0.9990349

Ln likelihood    -677.488

run 3
start point
Haplotype          Frequency
---------          ---------
      1-1          0.7564102
      1-2          0.1361159
      2-2          0.0931887
      2-1          0.0142852
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.7697298
      1-2          0.1230977
      2-2          0.1062069
                   ---------
             Total 0.9990344

Ln likelihood    -677.488

run 4
start point
Haplotype          Frequency
---------          ---------
      1-1          0.7241135
      1-2          0.1682761
      2-2          0.0610286
      2-1          0.0465818
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.7697297
      1-2          0.1230978
      2-2          0.1062068
                   ---------
             Total 0.9990343

Ln likelihood    -677.488

run 5
start point
Haplotype          Frequency
---------          ---------
      1-1          0.7447833
      1-2          0.1475155
      2-2          0.0817892
      2-1          0.0259120
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.7697305
      1-2          0.1230970
      2-2          0.1062076
                   ---------
             Total 0.9990351

Ln likelihood    -677.488

run 6
start point
Haplotype          Frequency
---------          ---------
      1-1          0.7446109
      1-2          0.1477375
      2-2          0.0815672
      2-1          0.0260845
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.7697305
      1-2          0.1230970
      2-2          0.1062076
                   ---------
             Total 0.9990351

Ln likelihood    -677.488

run 7
start point
Haplotype          Frequency
---------          ---------
      1-1          0.6817300
      1-2          0.2106774
      2-1          0.0889654
      2-2          0.0186273
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.7697306
      1-2          0.1230969
      2-2          0.1062077
                   ---------
             Total 0.9990352

Ln likelihood    -677.488

run 8
start point
Haplotype          Frequency
---------          ---------
      1-1          0.7190476
      1-2          0.1734744
      2-2          0.0558302
      2-1          0.0516477
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.7697294
      1-2          0.1230981
      2-2          0.1062065
                   ---------
             Total 0.9990340

Ln likelihood    -677.488

run 9
start point
Haplotype          Frequency
---------          ---------
      1-1          0.7003551
      1-2          0.1921874
      2-1          0.0703403
      2-2          0.0371172
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.7697303
      1-2          0.1230972
      2-2          0.1062074
                   ---------
             Total 0.9990349

Ln likelihood    -677.488

run 10
start point
Haplotype          Frequency
---------          ---------
      1-1          0.6991811
      1-2          0.1932888
      2-1          0.0715143
      2-2          0.0360158
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.7697302
      1-2          0.1230972
      2-2          0.1062074
                   ---------
             Total 0.9990349

Ln likelihood    -677.488

Maximizing total population...

Note:  Haplotypes listed have estimated frequencies greater than or equal to
       the cutoff or have the greatest frequency estimate.

Markers in order:
  rs6712 rs6520165 



run 1
start point
Haplotype          Frequency
---------          ---------
      1-1          0.6134106
      1-2          0.2533113
      2-1          0.0894040
      2-2          0.0438742
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.5763337
      1-2          0.2903882
      2-1          0.1264809
      2-2          0.0067973
                   ---------
             Total 1.0000000

Ln likelihood    -903.495

run 2
start point
Haplotype          Frequency
---------          ---------
      1-1          0.6001279
      1-2          0.2665939
      2-1          0.1026866
      2-2          0.0305915
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.5763296
      1-2          0.2903922
      2-1          0.1264849
      2-2          0.0067932
                   ---------
             Total 1.0000000

Ln likelihood    -903.495

run 3
start point
Haplotype          Frequency
---------          ---------
      1-1          0.5932644
      1-2          0.2734575
      2-1          0.1095502
      2-2          0.0237280
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.5763318
      1-2          0.2903900
      2-1          0.1264828
      2-2          0.0067954
                   ---------
             Total 1.0000000

Ln likelihood    -903.495

run 4
start point
Haplotype          Frequency
---------          ---------
      1-1          0.5974015
      1-2          0.2693204
      2-1          0.1054131
      2-2          0.0278651
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.5763343
      1-2          0.2903875
      2-1          0.1264802
      2-2          0.0067979
                   ---------
             Total 1.0000000

Ln likelihood    -903.495

run 5
start point
Haplotype          Frequency
---------          ---------
      1-1          0.5760837
      1-2          0.2906382
      2-1          0.1267309
      2-2          0.0065473
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.5763054
      1-2          0.2904165
      2-1          0.1265092
      2-2          0.0067690
                   ---------
             Total 1.0000000

Ln likelihood    -903.495

run 6
start point
Haplotype          Frequency
---------          ---------
      1-1          0.5892129
      1-2          0.2775089
      2-1          0.1136016
      2-2          0.0196765
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.5763351
      1-2          0.2903868
      2-1          0.1264795
      2-2          0.0067986
                   ---------
             Total 1.0000000

Ln likelihood    -903.495

run 7
start point
Haplotype          Frequency
---------          ---------
      1-1          0.5776076
      1-2          0.2891142
      2-1          0.1252070
      2-2          0.0080712
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.5763307
      1-2          0.2903912
      2-1          0.1264839
      2-2          0.0067943
                   ---------
             Total 1.0000000

Ln likelihood    -903.495

run 8
start point
Haplotype          Frequency
---------          ---------
      1-1          0.5994421
      1-2          0.2672798
      2-1          0.1033725
      2-2          0.0299057
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.5763355
      1-2          0.2903863
      2-1          0.1264791
      2-2          0.0067991
                   ---------
             Total 1.0000000

Ln likelihood    -903.495

run 9
start point
Haplotype          Frequency
---------          ---------
      1-1          0.6148397
      1-2          0.2518822
      2-1          0.0879749
      2-2          0.0453032
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.5763340
      1-2          0.2903878
      2-1          0.1264805
      2-2          0.0067976
                   ---------
             Total 1.0000000

Ln likelihood    -903.495

run 10
start point
Haplotype          Frequency
---------          ---------
      1-1          0.5865571
      1-2          0.2801648
      2-1          0.1162575
      2-2          0.0170207
                   ---------
             Total 1.0000000


end point
Haplotype          Frequency
---------          ---------
      1-1          0.5763321
      1-2          0.2903898
      2-1          0.1264825
      2-2          0.0067957
                   ---------
             Total 1.0000000

Ln likelihood    -903.495

