


============================
     SAMPLE DESCRIPTION
============================

  Number of pedigrees in dataset           123  
  Number of analyzable pedigrees           123  
                                                
  Number of individuals in dataset         922  
  Number of sibs in dataset                591  
  Number of analyzable sibs                547  
  Number of sibs with missing age values    44  

===========================
     MODEL DESCRIPTION
===========================

  Title               AGEON Analysis 1  
  Affectedness trait  aff               
  Age-of-onset trait  onset             
  Age-at-exam trait   exam              

===============================
     CLASSIFICATION SYSTEM
===============================

  Using default classification system:
                                                                

  ??  Both parents are unknown.                                 
  ?A  One of the parents is unknown, the other is affected.     
  ?U  One of the parents is unknown, the other is unaffected.   
  AA  Both parents are affected.                                
  AU  One of the parents is affected, the other is unaffected.  
  UU  Both parents are unaffected.                              

==========================

     CLASS STATISTICS

==========================

==================
     CLASS ??
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            10  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           6  
  MEAN OF AGE OF ONSET                             20.500000  
  VARIANCE OF AGE OF ONSET                         22.300000  
  NUMBER OF INDIVIDUALS AFFECTED                           6  
  PROPORTION OF INDIVIDUALS AFFECTED                0.600000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            35.750000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        18.916667  

==================
     CLASS ?A
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            12  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           6  
  MEAN OF AGE OF ONSET                             22.000000  
  VARIANCE OF AGE OF ONSET                         20.400000  
  NUMBER OF INDIVIDUALS AFFECTED                           6  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            27.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        15.600000  

==================
     CLASS ?U
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS             94  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           56  
  MEAN OF AGE OF ONSET                              20.285714  
  VARIANCE OF AGE OF ONSET                          39.480519  
  NUMBER OF INDIVIDUALS AFFECTED                           57  
  PROPORTION OF INDIVIDUALS AFFECTED                 0.606383  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED             44.243243  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        317.022523  

==================
     CLASS AA
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS AU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            33  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          18  
  MEAN OF AGE OF ONSET                             23.500000  
  VARIANCE OF AGE OF ONSET                         57.676471  
  NUMBER OF INDIVIDUALS AFFECTED                          19  
  PROPORTION OF INDIVIDUALS AFFECTED                0.575758  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            45.214286  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        74.181319  

==================
     CLASS UU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            398  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          192  
  MEAN OF AGE OF ONSET                              21.520833  
  VARIANCE OF AGE OF ONSET                          41.496946  
  NUMBER OF INDIVIDUALS AFFECTED                          200  
  PROPORTION OF INDIVIDUALS AFFECTED                 0.502513  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED             48.358586  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        355.835230  

====================================================================
     MAXIMIZATION RESULTS susceptibilities equal, no truncation
====================================================================

-----------------------------------------------------------
  Parameter           Estimate     S.E.        P-value     
-----------------------------------------------------------
  Susceptibility intercepts
                  ??     0.576996    0.115908  < 1.00e-06  
                  ?A     0.576996    0.115908  < 1.00e-06  
                  ?U     0.576996    0.115908  < 1.00e-06  
                  AA     0.576996    0.115908  < 1.00e-06  
                  AU     0.576996    0.115908  < 1.00e-06  
                  UU     0.576996    0.115908  < 1.00e-06  

      Mean intercept    21.643803    0.304864  < 1.00e-07  
  Variance intercept   650.716889   96.067815  < 1.00e-07  

  Transformation
             Lambda1     1.000000          Fixed           
             Lambda2     1.000000          Fixed           
-----------------------------------------------------------

Final ln likelihood: -1699.592583

===================================================================
     MAXIMIZATION RESULTS susceptibilities free, no truncation
===================================================================

-----------------------------------------------------------
  Parameter           Estimate     S.E.        P-value     
-----------------------------------------------------------
  Susceptibility intercepts
                  ??     1.673909    1.626600   0.303440   
                  ?A     1.747094    1.929722   0.365274   
                  ?U     1.090960    0.314501   0.000523   
                  AA     0.000000          Fixed           
                  AU     0.851868    0.496590   0.086266   
                  UU     0.427395    0.127524   0.000804   

      Mean intercept    21.653625    0.305297  < 1.00e-07  
  Variance intercept   653.827287   96.108179  < 1.00e-07  

  Transformation
             Lambda1     1.000000          Fixed           
             Lambda2     1.000000          Fixed           
-----------------------------------------------------------

Final ln likelihood: -1696.292828

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities free, no truncation   -1696.292828  
  H1 ln likelihood susceptibilities equal, no truncation  -1699.592583  
                                                                        
  2 * |H0 - H1|                                               6.599511  
  Degrees of freedom                                                 4  
  P-value                                                     0.158627  

