


============================
     SAMPLE DESCRIPTION
============================

  Number of pedigrees in dataset           123  
  Number of analyzable pedigrees           123  
                                                
  Number of individuals in dataset         922  
  Number of sibs in dataset                591  
  Number of analyzable sibs                537  
  Number of sibs with missing age values    54  

===========================
     MODEL DESCRIPTION
===========================

  Title               AGEON Analysis 2  
  Affectedness trait  aff               
  Age-of-onset trait  onset_exam        
  Age-at-exam trait   onset_exam        

===============================
     CLASSIFICATION SYSTEM
===============================

  Using default classification system:
                                                                

  ??  Both parents are unknown.                                 
  ?A  One of the parents is unknown, the other is affected.     
  ?U  One of the parents is unknown, the other is unaffected.   
  AA  Both parents are affected.                                
  AU  One of the parents is affected, the other is unaffected.  
  UU  Both parents are unaffected.                              

==========================

     CLASS STATISTICS

==========================

==================
     CLASS ??
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            10  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           6  
  MEAN OF AGE OF ONSET                             20.500000  
  VARIANCE OF AGE OF ONSET                         22.300000  
  NUMBER OF INDIVIDUALS AFFECTED                           6  
  PROPORTION OF INDIVIDUALS AFFECTED                0.600000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            35.750000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        18.916667  

==================
     CLASS ?A
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            12  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           6  
  MEAN OF AGE OF ONSET                             22.000000  
  VARIANCE OF AGE OF ONSET                         20.400000  
  NUMBER OF INDIVIDUALS AFFECTED                           6  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            27.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        15.600000  

==================
     CLASS ?U
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS             93  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           56  
  MEAN OF AGE OF ONSET                              20.285714  
  VARIANCE OF AGE OF ONSET                          39.480519  
  NUMBER OF INDIVIDUALS AFFECTED                           56  
  PROPORTION OF INDIVIDUALS AFFECTED                 0.602151  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED             44.243243  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        317.022523  

==================
     CLASS AA
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS AU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            32  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          18  
  MEAN OF AGE OF ONSET                             23.500000  
  VARIANCE OF AGE OF ONSET                         57.676471  
  NUMBER OF INDIVIDUALS AFFECTED                          18  
  PROPORTION OF INDIVIDUALS AFFECTED                0.562500  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            45.214286  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        74.181319  

==================
     CLASS UU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            390  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          192  
  MEAN OF AGE OF ONSET                              21.520833  
  VARIANCE OF AGE OF ONSET                          41.496946  
  NUMBER OF INDIVIDUALS AFFECTED                          192  
  PROPORTION OF INDIVIDUALS AFFECTED                 0.492308  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED             48.358586  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        355.835230  

====================================================================
     MAXIMIZATION RESULTS susceptibilities equal, no truncation
====================================================================

--------------------------------------------------------------------------
  Parameter           Estimate     S.E.        P-value     Deriv          
--------------------------------------------------------------------------
  Susceptibility intercepts
                  ??     0.535126    0.115746  < 1.00e-05  -0.0000181464  
                  ?A     0.535126    0.115746  < 1.00e-05   0.0000000000  
                  ?U     0.535126    0.115746  < 1.00e-05   0.0000000000  
                  AA     0.535126    0.115746  < 1.00e-05   0.0000000000  
                  AU     0.535126    0.115746  < 1.00e-05   0.0000000000  
                  UU     0.535126    0.115746  < 1.00e-05   0.0000000000  

      Mean intercept    21.649389    0.305233  < 1.00e-07  -0.0000002741  
  Variance intercept   653.432109   96.277000  < 1.00e-07   0.0000000080  

  Transformation
             Lambda1     1.000000                  Fixed                  
             Lambda2     1.000000                  Fixed                  
--------------------------------------------------------------------------

Final ln likelihood: -1692.520619

===================================================================
     MAXIMIZATION RESULTS susceptibilities free, no truncation
===================================================================

--------------------------------------------------------------------------
  Parameter           Estimate     S.E.        P-value     Deriv          
--------------------------------------------------------------------------
  Susceptibility intercepts
                  ??     1.677711    1.631675   0.303849   -0.0000000804  
                  ?A     1.749947    1.934468   0.365670    0.0000000000  
                  ?U     1.068251    0.313960   0.000668    0.0000018938  
                  AA     0.000000                  Fixed                  
                  AU     0.779942    0.493050   0.113679   -0.0000000865  
                  UU     0.380248    0.127689   0.002902   -0.0000020230  

      Mean intercept    21.659260    0.305629  < 1.00e-07  -0.0000002927  
  Variance intercept   656.275365   96.255528  < 1.00e-07  -0.0000000040  

  Transformation
             Lambda1     1.000000                  Fixed                  
             Lambda2     1.000000                  Fixed                  
--------------------------------------------------------------------------

Final ln likelihood: -1688.996611

=======================================================================
     MAXIMIZATION RESULTS susceptibilities equal, using truncation
=======================================================================

-----------------------------------------------------------------------------
  Parameter           Estimate      S.E.         P-value      Deriv          
-----------------------------------------------------------------------------
  Susceptibility intercepts
                  ??     21.801419  Unavailable  Unavailable   0.0000000464  
                  ?A     21.801419  Unavailable  Unavailable   0.0000000000  
                  ?U     21.801419  Unavailable  Unavailable   0.0000000000  
                  AA     21.801419  Unavailable  Unavailable   0.0000000000  
                  AU     21.801419  Unavailable  Unavailable   0.0000000000  
                  UU     21.801419  Unavailable  Unavailable   0.0000000000  

      Mean intercept     21.146948  Unavailable  Unavailable   0.0000066073  
  Variance intercept   5478.714872  Unavailable  Unavailable  -0.0000000035  

  Transformation
             Lambda1      1.000000                   Fixed                   
             Lambda2      1.000000                   Fixed                   
-----------------------------------------------------------------------------

Final ln likelihood: -1533.604912

======================================================================
     MAXIMIZATION RESULTS susceptibilities free, using truncation
======================================================================

-----------------------------------------------------------------------------
  Parameter           Estimate      S.E.         P-value      Deriv          
-----------------------------------------------------------------------------
  Susceptibility intercepts
                  ??     31.893750  Unavailable  Unavailable   0.0000000000  
                  ?A     31.893750  Unavailable  Unavailable   0.0000000000  
                  ?U     31.893750  Unavailable  Unavailable   0.0000000000  
                  AA      0.000000                   Fixed                   
                  AU     31.893750  Unavailable  Unavailable   0.0000000000  
                  UU     21.626528  Unavailable  Unavailable  -0.0000000125  

      Mean intercept     21.146932  Unavailable  Unavailable  -0.0000008738  
  Variance intercept   5478.709581  Unavailable  Unavailable   0.0000000013  

  Transformation
             Lambda1      1.000000                   Fixed                   
             Lambda2      1.000000                   Fixed                   
-----------------------------------------------------------------------------

Final ln likelihood: -1533.604912

====================
     Joint test
====================

  H0 ln likelihood susceptibilities free, no truncation   -1688.996611  
  H1 ln likelihood susceptibilities equal, no truncation  -1692.520619  
                                                                        
  2 * |H0 - H1|                                               7.048015  
  Degrees of freedom                                                 4  
  P-value                                                     0.133372  

====================
     Joint test
====================

  H0 ln likelihood susceptibilities free, using truncation   -1533.604912  
  H1 ln likelihood susceptibilities equal, using truncation  -1533.604912  
                                                                           
  2 * |H0 - H1|                                                  2.69e-08  
  Degrees of freedom                                                    4  
  P-value                                                        1.000000  

==========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, no truncation
==========================================================================

----------------------------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  ??         ?A         ?U         AA         AU         UU         
----------------------------------------------------------------------------------------------------------------------------
  Mean intercept       0.093167           1.944195         0.003012   0.003012   0.003012   0.003012   0.003012   0.003012  
  Variance intercept   1.944195        9269.260805         3.723825   3.723825   3.723825   3.723825   3.723825   3.723825  
  ??                   0.003012           3.723825         0.013397   0.013397   0.013397   0.013397   0.013397   0.013397  
  ?A                   0.003012           3.723825         0.013397   0.013397   0.013397   0.013397   0.013397   0.013397  
  ?U                   0.003012           3.723825         0.013397   0.013397   0.013397   0.013397   0.013397   0.013397  
  AA                   0.003012           3.723825         0.013397   0.013397   0.013397   0.013397   0.013397   0.013397  
  AU                   0.003012           3.723825         0.013397   0.013397   0.013397   0.013397   0.013397   0.013397  
  UU                   0.003012           3.723825         0.013397   0.013397   0.013397   0.013397   0.013397   0.013397  

=========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities free, no truncation
=========================================================================

----------------------------------------------------------------------------------------------------------------------------------
                                      Mean intercept  Variance intercept  ??          ?A         ?U         AU         UU         
----------------------------------------------------------------------------------------------------------------------------------
  Mean intercept                       0.093409           1.931774          0.013312   0.017467   0.004278   0.004599   0.002632  
  Variance intercept                   1.931774        9265.126752         12.145102   7.466801   5.175392   6.020851   3.302676  
  ??                                   0.013312          12.145102          2.662362   0.011632   0.007155   0.008280   0.004555  
  ?A                                   0.017467           7.466801          0.011632   3.742165   0.004718   0.005424   0.002994  
  ?U                                   0.004278           5.175392          0.007155   0.004718   0.098571   0.003478   0.001912  
  AU                                   0.004599           6.020851          0.008280   0.005424   0.003478   0.243099   0.002216  
  UU                                   0.002632           3.302676          0.004555   0.002994   0.001912   0.002216   0.016304  
                                                                                                                                  
  Likelihood Surface flat                                                                                                         
  variance matrix near singular and                                                                                               
  may be affected by rounding error.                                                                                              
  Reducing the number of parameters                                                                                               
  to be estimated is recommended                                                                                                  

=============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, using truncation
=============================================================================



Error: Matrix is not available.

============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities free, using truncation
============================================================================



Error: Matrix is not available.

