


============================
     SAMPLE DESCRIPTION
============================

  Number of pedigrees in dataset           123  
  Number of analyzable pedigrees           123  
                                                
  Number of individuals in dataset         922  
  Number of sibs in dataset                591  
  Number of analyzable sibs                537  
  Number of sibs with missing age values    54  

===========================
     MODEL DESCRIPTION
===========================

  Title               AGEON Analysis 2  
  Affectedness trait  aff               
  Age-of-onset trait  onset_exam        
  Age-at-exam trait   onset_exam        

===============================
     CLASSIFICATION SYSTEM
===============================

  Using default classification system:
                                                                

  ??  Both parents are unknown.                                 
  ?A  One of the parents is unknown, the other is affected.     
  ?U  One of the parents is unknown, the other is unaffected.   
  AA  Both parents are affected.                                
  AU  One of the parents is affected, the other is unaffected.  
  UU  Both parents are unaffected.                              

==========================

     CLASS STATISTICS

==========================

==================
     CLASS ??
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            10  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           6  
  MEAN OF AGE OF ONSET                             20.500000  
  VARIANCE OF AGE OF ONSET                         22.300000  
  NUMBER OF INDIVIDUALS AFFECTED                           6  
  PROPORTION OF INDIVIDUALS AFFECTED                0.600000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            35.750000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        18.916667  

==================
     CLASS ?A
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            12  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           6  
  MEAN OF AGE OF ONSET                             22.000000  
  VARIANCE OF AGE OF ONSET                         20.400000  
  NUMBER OF INDIVIDUALS AFFECTED                           6  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            27.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        15.600000  

==================
     CLASS ?U
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS             93  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           56  
  MEAN OF AGE OF ONSET                              20.285714  
  VARIANCE OF AGE OF ONSET                          39.480519  
  NUMBER OF INDIVIDUALS AFFECTED                           56  
  PROPORTION OF INDIVIDUALS AFFECTED                 0.602151  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED             44.243243  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        317.022523  

==================
     CLASS AA
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS AU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            32  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          18  
  MEAN OF AGE OF ONSET                             23.500000  
  VARIANCE OF AGE OF ONSET                         57.676471  
  NUMBER OF INDIVIDUALS AFFECTED                          18  
  PROPORTION OF INDIVIDUALS AFFECTED                0.562500  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            45.214286  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        74.181319  

==================
     CLASS UU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            390  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          192  
  MEAN OF AGE OF ONSET                              21.520833  
  VARIANCE OF AGE OF ONSET                          41.496946  
  NUMBER OF INDIVIDUALS AFFECTED                          192  
  PROPORTION OF INDIVIDUALS AFFECTED                 0.492308  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED             48.358586  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        355.835230  

====================================================================
     MAXIMIZATION RESULTS susceptibilities equal, no truncation
====================================================================

--------------------------------------------------------------------------
  Parameter           Estimate     S.E.        P-value     Deriv          
--------------------------------------------------------------------------
  Susceptibility intercepts
                  ??     0.535126    0.115746  < 1.00e-05  -0.0000153741  
                  ?A     0.535126    0.115746  < 1.00e-05   0.0000000000  
                  ?U     0.535126    0.115746  < 1.00e-05   0.0000000000  
                  AA     0.535126    0.115746  < 1.00e-05   0.0000000000  
                  AU     0.535126    0.115746  < 1.00e-05   0.0000000000  
                  UU     0.535126    0.115746  < 1.00e-05   0.0000000000  

      Mean intercept    21.649389    0.305233  < 1.00e-07  -0.0000002367  
  Variance intercept   653.432101   96.277255  < 1.00e-07   0.0000000087  

  Transformation
             Lambda1     1.000000                  Fixed                  
             Lambda2     1.000000                  Fixed                  
--------------------------------------------------------------------------

Final ln likelihood: -1692.520619

===================================================================
     MAXIMIZATION RESULTS susceptibilities free, no truncation
===================================================================

--------------------------------------------------------------------------
  Parameter           Estimate     S.E.        P-value     Deriv          
--------------------------------------------------------------------------
  Susceptibility intercepts
                  ??     1.677711    1.631729   0.303865    0.0000000000  
                  ?A     1.749946    1.934300   0.365628    0.0000001927  
                  ?U     1.068251    0.313958   0.000668    0.0000010100  
                  AA     0.000000                  Fixed                  
                  AU     0.779942    0.493059   0.113685    0.0000001729  
                  UU     0.380248    0.127691   0.002902   -0.0000002697  

      Mean intercept    21.659259    0.305629  < 1.00e-07  -0.0000000405  
  Variance intercept   656.275364   96.255441  < 1.00e-07  -0.0000000049  

  Transformation
             Lambda1     1.000000                  Fixed                  
             Lambda2     1.000000                  Fixed                  
--------------------------------------------------------------------------

Final ln likelihood: -1688.996611

=======================================================================
     MAXIMIZATION RESULTS susceptibilities equal, using truncation
=======================================================================

-----------------------------------------------------------------------------
  Parameter           Estimate      S.E.         P-value      Deriv          
-----------------------------------------------------------------------------
  Susceptibility intercepts
                  ??     25.039557  Unavailable  Unavailable   0.0000000000  
                  ?A     25.039557  Unavailable  Unavailable   0.0000000000  
                  ?U     25.039557  Unavailable  Unavailable   0.0000000000  
                  AA     25.039557  Unavailable  Unavailable   0.0000000000  
                  AU     25.039557  Unavailable  Unavailable   0.0000000000  
                  UU     25.039557  Unavailable  Unavailable   0.0000000000  

      Mean intercept     21.146931  Unavailable  Unavailable   0.0000030549  
  Variance intercept   5478.707208  Unavailable  Unavailable   0.0000000071  

  Transformation
             Lambda1      1.000000                   Fixed                   
             Lambda2      1.000000                   Fixed                   
-----------------------------------------------------------------------------

Final ln likelihood: -1533.604912

======================================================================
     MAXIMIZATION RESULTS susceptibilities free, using truncation
======================================================================

-----------------------------------------------------------------------------
  Parameter           Estimate      S.E.         P-value      Deriv          
-----------------------------------------------------------------------------
  Susceptibility intercepts
                  ??     31.893750  Unavailable  Unavailable   0.0000000000  
                  ?A     31.893750  Unavailable  Unavailable   0.0000000000  
                  ?U     31.893750  Unavailable  Unavailable   0.0000000000  
                  AA      0.000000                   Fixed                   
                  AU     31.893750  Unavailable  Unavailable   0.0000000000  
                  UU     23.319886  Unavailable  Unavailable  -0.0000000087  

      Mean intercept     21.146946  Unavailable  Unavailable   0.0000126566  
  Variance intercept   5478.711369  Unavailable  Unavailable   0.0000000054  

  Transformation
             Lambda1      1.000000                   Fixed                   
             Lambda2      1.000000                   Fixed                   
-----------------------------------------------------------------------------

Final ln likelihood: -1533.604912

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities free, no truncation   -1688.996611  
  H1 ln likelihood susceptibilities equal, no truncation  -1692.520619  
                                                                        
  2 * |H0 - H1|                                               7.048015  
  Degrees of freedom                                                 4  
  P-value                                                     0.133372  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities free, using truncation   -1533.604912  
  H1 ln likelihood susceptibilities equal, using truncation  -1533.604912  
                                                                           
  2 * |H0 - H1|                                                  9.77e-10  
  Degrees of freedom                                                    4  
  P-value                                                        1.000000  

==========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, no truncation
==========================================================================

----------------------------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  ??         ?A         ?U         AA         AU         UU         
----------------------------------------------------------------------------------------------------------------------------
  Mean intercept       0.093167           1.944212         0.003012   0.003012   0.003012   0.003012   0.003012   0.003012  
  Variance intercept   1.944212        9269.309741         3.723761   3.723761   3.723761   3.723761   3.723761   3.723761  
  ??                   0.003012           3.723761         0.013397   0.013397   0.013397   0.013397   0.013397   0.013397  
  ?A                   0.003012           3.723761         0.013397   0.013397   0.013397   0.013397   0.013397   0.013397  
  ?U                   0.003012           3.723761         0.013397   0.013397   0.013397   0.013397   0.013397   0.013397  
  AA                   0.003012           3.723761         0.013397   0.013397   0.013397   0.013397   0.013397   0.013397  
  AU                   0.003012           3.723761         0.013397   0.013397   0.013397   0.013397   0.013397   0.013397  
  UU                   0.003012           3.723761         0.013397   0.013397   0.013397   0.013397   0.013397   0.013397  

=========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities free, no truncation
=========================================================================

----------------------------------------------------------------------------------------------------------------------------------
                                      Mean intercept  Variance intercept  ??          ?A         ?U         AU         UU         
----------------------------------------------------------------------------------------------------------------------------------
  Mean intercept                       0.093409           1.931781          0.013313   0.017463   0.004278   0.004599   0.002632  
  Variance intercept                   1.931781        9265.109979         12.146108   7.465531   5.175335   6.021039   3.302784  
  ??                                   0.013313          12.146108          2.662541   0.011631   0.007155   0.008281   0.004555  
  ?A                                   0.017463           7.465531          0.011631   3.741515   0.004717   0.005423   0.002994  
  ?U                                   0.004278           5.175335          0.007155   0.004717   0.098570   0.003478   0.001912  
  AU                                   0.004599           6.021039          0.008281   0.005423   0.003478   0.243107   0.002216  
  UU                                   0.002632           3.302784          0.004555   0.002994   0.001912   0.002216   0.016305  
                                                                                                                                  
  Likelihood Surface flat                                                                                                         
  variance matrix near singular and                                                                                               
  may be affected by rounding error.                                                                                              
  Reducing the number of parameters                                                                                               
  to be estimated is recommended                                                                                                  

=============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, using truncation
=============================================================================



Error: Matrix is not available.

============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities free, using truncation
============================================================================



Error: Matrix is not available.

