


============================
     SAMPLE DESCRIPTION
============================

  Number of pedigrees in dataset           123  
  Number of analyzable pedigrees           123  
                                                
  Number of individuals in dataset         922  
  Number of sibs in dataset                591  
  Number of analyzable sibs                547  
  Number of sibs with missing age values    44  

===========================
     MODEL DESCRIPTION
===========================

  Title               AGEON Analysis 1  
  Affectedness trait  aff               
  Age-of-onset trait  onset             
  Age-at-exam trait   exam              

===============================
     CLASSIFICATION SYSTEM
===============================

  Using default classification system:
                                                                

  ??  Both parents are unknown.                                 
  ?A  One of the parents is unknown, the other is affected.     
  ?U  One of the parents is unknown, the other is unaffected.   
  AA  Both parents are affected.                                
  AU  One of the parents is affected, the other is unaffected.  
  UU  Both parents are unaffected.                              

==========================

     CLASS STATISTICS

==========================

==================
     CLASS ??
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            10  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           6  
  MEAN OF AGE OF ONSET                             20.500000  
  VARIANCE OF AGE OF ONSET                         22.300000  
  NUMBER OF INDIVIDUALS AFFECTED                           6  
  PROPORTION OF INDIVIDUALS AFFECTED                0.600000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            35.750000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        18.916667  

==================
     CLASS ?A
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            12  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           6  
  MEAN OF AGE OF ONSET                             22.000000  
  VARIANCE OF AGE OF ONSET                         20.400000  
  NUMBER OF INDIVIDUALS AFFECTED                           6  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            27.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        15.600000  

==================
     CLASS ?U
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS             94  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           56  
  MEAN OF AGE OF ONSET                              20.285714  
  VARIANCE OF AGE OF ONSET                          39.480519  
  NUMBER OF INDIVIDUALS AFFECTED                           57  
  PROPORTION OF INDIVIDUALS AFFECTED                 0.606383  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED             44.243243  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        317.022523  

==================
     CLASS AA
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS AU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            33  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          18  
  MEAN OF AGE OF ONSET                             23.500000  
  VARIANCE OF AGE OF ONSET                         57.676471  
  NUMBER OF INDIVIDUALS AFFECTED                          19  
  PROPORTION OF INDIVIDUALS AFFECTED                0.575758  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            45.214286  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        74.181319  

==================
     CLASS UU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            398  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          192  
  MEAN OF AGE OF ONSET                              21.520833  
  VARIANCE OF AGE OF ONSET                          41.496946  
  NUMBER OF INDIVIDUALS AFFECTED                          200  
  PROPORTION OF INDIVIDUALS AFFECTED                 0.502513  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED             48.358586  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        355.835230  

====================================================================
     MAXIMIZATION RESULTS susceptibilities equal, no truncation
====================================================================

--------------------------------------------------------------------------
  Parameter           Estimate     S.E.        P-value     Deriv          
--------------------------------------------------------------------------
  Susceptibility intercepts
                  ??     0.576996    0.115904  < 1.00e-06   0.0000025712  
                  ?A     0.576996    0.115904  < 1.00e-06   0.0000000000  
                  ?U     0.576996    0.115904  < 1.00e-06   0.0000000000  
                  AA     0.576996    0.115904  < 1.00e-06   0.0000000000  
                  AU     0.576996    0.115904  < 1.00e-06   0.0000000000  
                  UU     0.576996    0.115904  < 1.00e-06   0.0000000000  

      Mean intercept    21.643803    0.304864  < 1.00e-07   0.0000050661  
  Variance intercept   650.716886   96.066319  < 1.00e-07   0.0000000139  

  Transformation
             Lambda1     1.000000                  Fixed                  
             Lambda2     1.000000                  Fixed                  
--------------------------------------------------------------------------

Final ln likelihood: -1699.592583

===================================================================
     MAXIMIZATION RESULTS susceptibilities free, no truncation
===================================================================

--------------------------------------------------------------------------
  Parameter           Estimate     S.E.        P-value     Deriv          
--------------------------------------------------------------------------
  Susceptibility intercepts
                  ??     1.673907    1.626613   0.303444   -0.0000008057  
                  ?A     1.747093    1.929663   0.365260   -0.0000000772  
                  ?U     1.090960    0.314500   0.000523   -0.0000021016  
                  AA     0.000000                  Fixed                  
                  AU     0.851868    0.496572   0.086254    0.0000003166  
                  UU     0.427395    0.127523   0.000804   -0.0000002697  

      Mean intercept    21.653625    0.305297  < 1.00e-07  -0.0000003301  
  Variance intercept   653.827328   96.108369  < 1.00e-07   0.0000000029  

  Transformation
             Lambda1     1.000000                  Fixed                  
             Lambda2     1.000000                  Fixed                  
--------------------------------------------------------------------------

Final ln likelihood: -1696.292828

=======================================================================
     MAXIMIZATION RESULTS susceptibilities equal, using truncation
=======================================================================

-----------------------------------------------------------------------------
  Parameter           Estimate      S.E.         P-value      Deriv          
-----------------------------------------------------------------------------
  Susceptibility intercepts
                  ??    709.651794  Unavailable  Unavailable   0.0000000000  
                  ?A    709.651794  Unavailable  Unavailable   0.0000000000  
                  ?U    709.651794  Unavailable  Unavailable   0.0000000000  
                  AA    709.651794  Unavailable  Unavailable   0.0000000000  
                  AU    709.651794  Unavailable  Unavailable   0.0000000000  
                  UU    709.651794  Unavailable  Unavailable   0.0000000000  

      Mean intercept     21.139913  Unavailable  Unavailable   0.0000000064  
  Variance intercept   5196.237283  Unavailable  Unavailable   0.0000000001  

  Transformation
             Lambda1      1.000000                   Fixed                   
             Lambda2      1.000000                   Fixed                   
-----------------------------------------------------------------------------

Final ln likelihood: -1543.461798

======================================================================
     MAXIMIZATION RESULTS susceptibilities free, using truncation
======================================================================

-----------------------------------------------------------------------------
  Parameter           Estimate      S.E.         P-value      Deriv          
-----------------------------------------------------------------------------
  Susceptibility intercepts
                  ??     25.531335  Unavailable  Unavailable   0.0000000000  
                  ?A     43.200000  Unavailable  Unavailable   0.0000000000  
                  ?U    128.042929  Unavailable  Unavailable   0.0000000000  
                  AA      0.000000                   Fixed                   
                  AU     16.250676  Unavailable  Unavailable   0.0000008216  
                  UU     75.505215  Unavailable  Unavailable   0.0000000000  

      Mean intercept     21.139913  Unavailable  Unavailable  -0.0000000319  
  Variance intercept   5196.233408  Unavailable  Unavailable   0.0000000106  

  Transformation
             Lambda1      1.000000                   Fixed                   
             Lambda2      1.000000                   Fixed                   
-----------------------------------------------------------------------------

Final ln likelihood: -1543.461799

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities free, no truncation   -1696.292828  
  H1 ln likelihood susceptibilities equal, no truncation  -1699.592583  
                                                                        
  2 * |H0 - H1|                                               6.599511  
  Degrees of freedom                                                 4  
  P-value                                                     0.158627  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities free, using truncation   -1543.461799  
  H1 ln likelihood susceptibilities equal, using truncation  -1543.461798  
                                                                           
  2 * |H0 - H1|                                                  1.65e-06  
  Degrees of freedom                                                    4  
  P-value                                                        1.000000  

==========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, no truncation
==========================================================================

----------------------------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  ??         ?A         ?U         AA         AU         UU         
----------------------------------------------------------------------------------------------------------------------------
  Mean intercept       0.092942           1.934883         0.003063   0.003063   0.003063   0.003063   0.003063   0.003063  
  Variance intercept   1.934883        9228.737707         3.810174   3.810174   3.810174   3.810174   3.810174   3.810174  
  ??                   0.003063           3.810174         0.013434   0.013434   0.013434   0.013434   0.013434   0.013434  
  ?A                   0.003063           3.810174         0.013434   0.013434   0.013434   0.013434   0.013434   0.013434  
  ?U                   0.003063           3.810174         0.013434   0.013434   0.013434   0.013434   0.013434   0.013434  
  AA                   0.003063           3.810174         0.013434   0.013434   0.013434   0.013434   0.013434   0.013434  
  AU                   0.003063           3.810174         0.013434   0.013434   0.013434   0.013434   0.013434   0.013434  
  UU                   0.003063           3.810174         0.013434   0.013434   0.013434   0.013434   0.013434   0.013434  

=========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities free, no truncation
=========================================================================

----------------------------------------------------------------------------------------------------------------------------------
                                      Mean intercept  Variance intercept  ??          ?A         ?U         AU         UU         
----------------------------------------------------------------------------------------------------------------------------------
  Mean intercept                       0.093206           1.926841          0.013258   0.017413   0.004317   0.004808   0.002682  
  Variance intercept                   1.926841        9236.818680         12.126222   7.468205   5.247522   6.326210   3.389327  
  ??                                   0.013258          12.126222          2.645869   0.011637   0.007262   0.008708   0.004678  
  ?A                                   0.017413           7.468205          0.011637   3.723598   0.004793   0.005711   0.003078  
  ?U                                   0.004317           5.247522          0.007262   0.004793   0.098910   0.003715   0.001994  
  AU                                   0.004808           6.326210          0.008708   0.005711   0.003715   0.246584   0.002396  
  UU                                   0.002682           3.389327          0.004678   0.003078   0.001994   0.002396   0.016262  
                                                                                                                                  
  Likelihood Surface flat                                                                                                         
  variance matrix near singular and                                                                                               
  may be affected by rounding error.                                                                                              
  Reducing the number of parameters                                                                                               
  to be estimated is recommended                                                                                                  

=============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, using truncation
=============================================================================



Error: Matrix is not available.

============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities free, using truncation
============================================================================



Error: Matrix is not available.

