=======================

     Freq Analysis

=======================

=======================
     Configuration
=======================

  Output file:                 FREQ1      
  Founder weight:              Disabled   
  Max. likelihood estimation:  Enabled    
  Inbreeding coefficient:      Estimated  

Note: A '*' by an MLE column indicates that the corresponding maximization may not have converged. Please review the detailed output file for more information.
====================================
     Allele frequencies 'cdx01'
====================================

--------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  MLE (inbreeding = 0.0774318)  
--------------------------------------------------------------------------------------------
  0        0.770161       0.770161        0.770161             0.770161                     
  1        0.229839       0.229839        0.229839             0.229839                     

====================================
     Allele frequencies 'taq01'
====================================

--------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  MLE (inbreeding = 0.0484695)  
--------------------------------------------------------------------------------------------
  0        0.602823       0.602823        0.602823             0.602823                     
  1        0.397177       0.397177        0.397177             0.397177                     

====================================
     Allele frequencies 'fok01'
====================================

---------------------------------------------------------------------------------------------
  Allele  Founders only  Entire dataset  MLE (no inbreeding)  MLE (inbreeding = 0.00635229)  
---------------------------------------------------------------------------------------------
  0        0.597782       0.597782        0.597782             0.597782                      
  1        0.402218       0.402218        0.402218             0.402218                      


