


%TDTEX-W: [7] Unable to read sex of individual I7 in pedigree F1.  Found ''. 
          Setting sex to unknown.
%TDTEX-W: The sex of individual 'I5' in pedigree 'F1' is believed to be male. 
          Sex code will be reset.
%TDTEX-W: The sex of individual 'I7' in pedigree 'F1' is believed to be male. 
          Sex code will be reset.
%TDTEX-W: [6] Unrecognized value for marker 'm' of individual 'I6' in pedigree
          'F1': Found '***'. Marker will be set to missing for this individual.
%TDTEX-W: [16] Unrecognized value for marker 'm' of individual 'I16' in
          pedigree 'F1': Found 'A'. Marker will be set to missing for this
          individual.
%TDTEX-W: [23] Unrecognized value for marker 'm' of individual 'I6' in pedigree
          'F2': Found '***'. Marker will be set to missing for this individual.

Family structure information on the first 100 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     F1            I1            M         0             0           
     F1            I2            F         0             0           
     F1            I3            M         0             0           
     F1            I4            F         0             0           
     F1            I5            M         I1            I2          
     F1            I6            F         0             0           
     F1            I7            M         I3            I4          
     F1            I8            ?         I3            I4          
     F1            I9            F         I3            I4          
     F1            I10           F         I5            I6          
     F1            I11           M         I6            I7          
     F1            I12           F         I6            I7          
     F1            I13           M         I6            I7          
     F1            I14           F         I6            I7          
     F1            I15           M         I6            I7          
     F1            I16           M         0             0           
     F1            I17           M         I16           I9          
     F2            I1            M         0             0           
     F2            I2            F         0             0           
     F2            I3            M         0             0           
     F2            I4            F         0             0           
     F2            I5            M         I1            I2          
     F2            I6            F         0             0           
     F2            I7            M         I3            I4          
     F2            I8            M         I3            I4          
     F2            I9            F         I3            I4          
     F2            I10           F         I5            I6          
     F2            I11           M         I6            I7          
     F2            I12           F         I6            I7          
     F2            I13           M         I6            I7          
     F2            I14           F         I6            I7          
     F2            I15           M         I6            I7          
     F2            I16           M         0             0           
     F2            I17           M         I16           I9          


Phenotypes for the first 100 individuals read from file: ped

     PED. ID       IND. ID       Trait1              
     ------------  ------------  --------------------
     F1            I1            2                   
     F1            I2            6                   
     F1            I3            4                   
     F1            I4            4                   
     F1            I5            4                   
     F1            I6            6                   
     F1            I7            4                   
     F1            I8            2                   
     F1            I9            6                   
     F1            I10           6                   
     F1            I11           6                   
     F1            I12           4                   
     F1            I13           4                   
     F1            I14           6                   
     F1            I15           4                   
     F1            I16           2                   
     F1            I17           4                   
     F2            I1            4                   
     F2            I2            2                   
     F2            I3            4                   
     F2            I4            6                   
     F2            I5            4                   
     F2            I6            4                   
     F2            I7            4                   
     F2            I8            6                   
     F2            I9            6                   
     F2            I10           2                   
     F2            I11           6                   
     F2            I12           4                   
     F2            I13           4                   
     F2            I14           4                   
     F2            I15           XXX                 
     F2            I16           6                   
     F2            I17           6                   


Markers for the first 100 individuals read from file: ped

     PED. ID       IND. ID       m           
     ------------  ------------  ------------
     F1            I1            ?/?         
     F1            I2            A/C         
     F1            I3            A/D         
     F1            I4            A/E         
     F1            I5            A/F         
     F1            I6            ?/?         
     F1            I7            A/G         
     F1            I8            A/H         
     F1            I9            A/I         
     F1            I10           A/J         
     F1            I11           A/L         
     F1            I12           A/M         
     F1            I13           A/N         
     F1            I14           A/O         
     F1            I15           B/P         
     F1            I16           ?/?         
     F1            I17           D/R         
     F2            I1            A/B         
     F2            I2            A/C         
     F2            I3            A/D         
     F2            I4            A/E         
     F2            I5            F/F         
     F2            I6            ?/?         
     F2            I7            G/G         
     F2            I8            H/H         
     F2            I9            I/Z         
     F2            I10           A/B         
     F2            I11           A/C         
     F2            I12           C/C         
     F2            I13           A/C         
     F2            I14           C/C         
     F2            I15           A/C         
     F2            I16           B/B         
     F2            I17           C/B         

%TDTEX-W: Mendelian inheritance errors in pedigree 'F1' for parents 'I16' (?/?)
          and 'I9' (A/I) with child 'I17' (D/R).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F1' for parents 'I3' (A/D)
          and 'I4' (A/E) with child 'I9' (A/I).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F1' for parents 'I3' (A/D)
          and 'I4' (A/E) with child 'I8' (A/H).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F1' for parents 'I3' (A/D)
          and 'I4' (A/E) with child 'I7' (A/G).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F1' for parents 'I6' (?/?)
          and 'I7' (A/G) with child 'I15' (B/P).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F2' for parents 'I1' (A/B)
          and 'I2' (A/C) with child 'I5' (F/F).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F2' for parents 'I16' (B/B)
          and 'I9' (I/Z) with child 'I17' (C/B).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F2' for parents 'I3' (A/D)
          and 'I4' (A/E) with child 'I9' (I/Z).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F2' for parents 'I3' (A/D)
          and 'I4' (A/E) with child 'I8' (H/H).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F2' for parents 'I3' (A/D)
          and 'I4' (A/E) with child 'I7' (G/G).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F2' for parents 'I5' (F/F)
          and 'I6' (?/?) with child 'I10' (A/B).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F2' for parents 'I6' (?/?)
          and 'I7' (G/G) with child 'I14' (C/C).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F2' for parents 'I6' (?/?)
          and 'I7' (G/G) with child 'I13' (A/C).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F2' for parents 'I6' (?/?)
          and 'I7' (G/G) with child 'I12' (C/C).
%TDTEX-W: Mendelian inheritance errors in pedigree 'F2' for parents 'I6' (?/?)
          and 'I7' (G/G) with child 'I11' (A/C).
