
Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             M         0             0           
     1             2             F         0             0           
     1             3             M         1             2           
     1             4             M         1             2           
     1             5             M         1             2           
     1             6             M         1             2           
     1             7             M         1             2           
     1             8             F         1             2           
     1             9             F         1             2           
     1             10            F         1             2           


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         TRAIT                 COV                   AGE                   AFFECTION           
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     10                    3                     0                     3                     0                   
     1             2             1                     1                     1                     10                    3                     1                     3                     1                   
     1             3             0                     1                     0                     10                    3                     0                     3                     0                   
     1             4             0                     1                     0                     10                    3                     1                     3                     1                   
     1             5             0                     1                     0                     10                    4                     0                     4                     0                   
     1             6             0                     1                     0                     10                    4                     1                     4                     1                   
     1             7             0                     1                     0                     10                    2                     0                     2                     0                   
     1             8             1                     1                     0                     10                    2                     1                     2                     1                   
     1             9             1                     1                     0                     10                    1                     0                     1                     0                   
     1             10            1                     1                     0                     10                    5                     1                     5                     1                   

%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 1 New Analysis Block 1 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Critical:Cannot specify more than one variance with age of 
                           onset model ... Ignoring Analysis 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 2 New Analysis Block 2 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:Age of onset requires FPMM model class. Ignoring
                          class 'A' given.
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 3 New Analysis Block 3 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 4 New Analysis Block 4 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:Age of onset requires FPMM model class. Ignoring
                          class 'A' given.
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 5 New Analysis Block 5 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 6 New Analysis Block 6 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 7 New Analysis Block 7 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 8 New Analysis Block 8 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 9 New Analysis Block 9 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 10 New Analysis Block 10 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 11 New Analysis Block 11 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 12 New Analysis Block 12 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 13 New Analysis Block 13 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 14 New Analysis Block 14 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:Age of onset requires FPMM model class. Ignoring
                          class 'A' given.
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 15 New Analysis Block 15 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Critical:Cannot specify polygenic locus frequency with zero
                           polygenic loci ... Skipping analysis 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 16 New Analysis Block 16 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Critical:Cannot specify if polygenic loci affect age of onset
                           or susceptibility with zero polygenic loci ...
                           Ignoring
