


===============================
LODLINK Analysis 1 SUMMARY FILE
===============================


Options Selected
================
Main locus type                          trait
Main locus name                          dbh

Lod scores                               no

Linkage tests                            yes
  Sex specific recombination fractions   no
  Assume homogeneity                     yes

Smith's test for homogeneity             no
  Sex specific recombination fractions   no

Morton's test for homogeneity            no
  Sex specific recombination fractions   no

Genotype probabilities                   no
  Sex specific recombination fractions   no


Results
=======




                  MLE                     Lod Score and Linkage Test    
                                          Using Recom. Fract. in [0, .5]
                                                                        
Locus             Recom       Recom       Lod         Chi         P-Value     P-Value     
                  Fract in    Fract in    Score       Square                  Upper       
                  [0, .5]     [0, 1]                  Stat                    Bound       
---------------   ---------   ---------   ---------   ---------   ---------   ---------   
ABO                  0.0357        ---         5.04        23.2   7.208e-07   9.055e-06   
KELL                 0.4200        ---       0.0392       0.181      0.3355      0.9137   
P                    0.5000      0.4945           0        ---         ---         ---    
FY                   0.5000      0.5128           0        ---         ---         ---    
JK                   0.5000      0.6943           0        ---         ---         ---    
PGD                  0.2601        ---        0.075       0.345      0.2784      0.8414   
ADA                  0.5000      0.4900           0        ---         ---         ---    
AK1                  0.0000        ---        0.763        3.51     0.03042      0.1725   
ACP1                 0.5000      0.5928           0        ---         ---         ---    
PGM1                 0.5000      0.4941           0        ---         ---         ---    
HBB                  0.5000      0.5823           0        ---         ---         ---    
GPT                  0.3850        ---       0.0665       0.306        0.29       0.858   
C3                   0.2688      0.7991        0.21       0.967      0.1627      0.6166   
HP                   0.2254        ---         0.53        2.44     0.05909      0.2951   
TF                   0.0000        ---        0.292        ---         ---         ---    
GC                   0.5000      0.6288           0        ---         ---         ---    
ORM                  0.2837        ---        0.281         1.3      0.1276      0.5233   
GM                   0.5000      0.4913           0        ---         ---         ---    
KM                   0.5000      0.5510           0        ---         ---         ---    
BF                   0.1278        ---        0.852        3.92     0.02384      0.1408   
ESD                  0.4814        ---      0.00284      0.0131      0.4544      0.9935   
GLO1                 0.2745      0.7940       0.145       0.666      0.2072      0.7167   
LE                   0.5000      0.6457           0        ---         ---         ---    
