



Family structure information on the first 1000 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     0             1             1         0             0           
     0             2             2         0             0           
     0             3             1         1             2           
     0             4             2         1             2           
     0             5             1         1             2           
     0             6             2         1             2           
     0             7             1         1             2           
     0             8             2         1             2           
     0             9             1         1             2           
     0             10            2         1             2           


Phenotypes for the first 1000 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE            
     ------------  ------------  --------------------
     0             1             0                   
     0             2             1                   
     0             3             0                   
     0             4             1                   
     0             5             0                   
     0             6             1                   
     0             7             0                   
     0             8             1                   
     0             9             0                   
     0             10            1                   

