



Family structure information on the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             M         0             0           
     1             2             M         0             0           
     1             3             M         0             0           
     1             4             M         0             0           
     1             5             M         0             0           
     1             6             F         0             0           
     1             7             F         0             0           
     1             8             F         0             0           
     1             9             F         0             0           
     1             10            F         0             0           


Phenotypes for the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE       
     ------------  ------------  --------------------  --------------------  --------------------  --------------------
     1             1             0                     1                     1                     10                  
     1             2             0                     1                     1                     10                  
     1             3             0                     1                     1                     10                  
     1             4             0                     1                     1                     10                  
     1             5             0                     1                     1                     10                  
     1             6             1                     1                     1                     10                  
     1             7             1                     1                     1                     10                  
     1             8             1                     1                     1                     10                  
     1             9             1                     1                     1                     10                  
     1             10            1                     1                     1                     10                  


Markers for the first 20 individuals read from file: ped

     PED. ID       IND. ID       M1            M2          
     ------------  ------------  ------------  ------------
     1             1             a;a           A;a         
     1             2             A;A           A;a         
     1             3             A;A           a;a         
     1             4             a;A           A;a         
     1             5             a;A           A;a         
     1             6             a;a           A;A         
     1             7             a;A           A;a         
     1             8             a;A           A;a         
     1             9             a;A           a;a         
     1             10            a;A           a;a         

%DECIPHER-I: Mapping function not specified.  Using Haldane Mapping Function.

  Performing analysis: Analysis 1
  ===========================================================================

    Total population. 
      Determining possible haplotype combinations ................... done.
      Maximizing likelihood ......................................... done. 

  ===========================================================================

