=================

     Results

=================

Note: P-values for variance components and proportions are one-sided.  All others are two-sided.
The null hypothesis for transformation parameters is 'no transformation.'


==============================
     Analysis description
==============================

  Title                        pe_________                   
  Primary Trait                sqrtdbh (Quantitative)        
  Allow averaging              Enabled                       
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  

======================================
     Transformation configuration
======================================



Note: No transformation applied.

===========================

     Model 'Alternate'

===========================

============================
     Sample description
============================

  Number of individuals in dataset                                   942  
  Number of constituent pedigrees in dataset                           7  
  Number of singletons in dataset                                      0  
                                                                          
  Number of constituent pedigree members with complete information   499  
  Number of singletons with complete information                       0  
                                                                          

====================
     Covariates
====================

-----------------------------------------------------
  Name   Mean       Std. dev.  Min        Max        
-----------------------------------------------------
  apres   0.512146   0.499852   0.000000   1.000000  

================================================================
     MAXIMIZATION RESULTS Alternate without test covariates
================================================================

------------------------------------------------------------------------------
  Parameter                  Estimate   S.E.       P-value     Deriv          
------------------------------------------------------------------------------
  Variance components
                     Random   0.531347   0.144271   0.000231    0.0000395969  
                  Polygenic   2.090583   0.280185  < 1.00e-07  -0.0000023225  

  Other parameters
             Total variance   2.621930   0.197306  < 1.00e-07   0.0000000000  
               Heritability   0.797345   0.061752  < 1.00e-07   0.0000000000  

  Residual familial correlations
         Res full sibs corr   0.398673   0.030876  < 1.00e-07   0.0000000000  
         Res half sibs corr   0.199336   0.015438  < 1.00e-07   0.0000000000  
  Res parent offspring corr   0.398673   0.030876  < 1.00e-07   0.0000000000  

                  Intercept   4.955565   0.133382  < 1.00e-07   0.0000000000  
------------------------------------------------------------------------------

Final ln likelihood: -6526.721593

======================================================================
     VARIANCE-COVARIANCE MATRIX Alternate without test covariates
======================================================================

---------------------------------------------------------------------------------------------------------------------------------------------------------------
                             Random     Polygenic  Total variance  Heritability  Res full sibs corr  Res half sibs corr  Res parent offspring corr  Intercept  
---------------------------------------------------------------------------------------------------------------------------------------------------------------
  Random                      0.020814  -0.030194  -0.009380       -0.008663     -0.004332           -0.002166           -0.004332                   0.001583  
  Polygenic                  -0.030194   0.078504   0.048309        0.015250      0.007625            0.003812            0.007625                  -0.002787  
  Total variance             -0.009380   0.048309   0.038930        0.006586      0.003293            0.001647            0.003293                  -0.001204  
  Heritability               -0.008663   0.015250   0.006586        0.003813      0.001907            0.000953            0.001907                  -0.000697  
  Res full sibs corr         -0.004332   0.007625   0.003293        0.001907      0.000953            0.000477            0.000953                  -0.000348  
  Res half sibs corr         -0.002166   0.003812   0.001647        0.000953      0.000477            0.000238            0.000477                  -0.000174  
  Res parent offspring corr  -0.004332   0.007625   0.003293        0.001907      0.000953            0.000477            0.000953                  -0.000348  
  Intercept                   0.001583  -0.002787  -0.001204       -0.000697     -0.000348           -0.000174           -0.000348                   0.017791  

=============================================================
     MAXIMIZATION RESULTS Alternate with test covariates
=============================================================

------------------------------------------------------------------------------
  Parameter                  Estimate   S.E.       P-value     Deriv          
------------------------------------------------------------------------------
  Variance components
                     Random   0.542085   0.145651   0.000198    0.0000000000  
                  Polygenic   2.070202   0.280800  < 1.00e-07   0.0001377233  

  Other parameters
             Total variance   2.612286   0.196861  < 1.00e-07   0.0000339872  
               Heritability   0.792487   0.062669  < 1.00e-07   0.0000000000  

  Residual familial correlations
         Res full sibs corr   0.396243   0.031335  < 1.00e-07   0.0000000000  
         Res half sibs corr   0.198122   0.015667  < 1.00e-07   0.0000000000  
  Res parent offspring corr   0.396243   0.031335  < 1.00e-07   0.0000000000  

                  Intercept   4.961044   0.133440  < 1.00e-07   0.0000000000  

  Covariates
                      apres   0.071793   0.143768   0.617524    0.0000000000  
------------------------------------------------------------------------------

Final ln likelihood: -6526.596941

===================================================================
     VARIANCE-COVARIANCE MATRIX Alternate with test covariates
===================================================================

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                             Random     Polygenic  Total variance  Heritability  Res full sibs corr  Res half sibs corr  Res parent offspring corr  Intercept  apres      
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Random                      0.021214  -0.030654  -0.009440       -0.008871     -0.004435           -0.002218           -0.004435                   0.001786   0.003154  
  Polygenic                  -0.030654   0.078849   0.048195        0.015563      0.007782            0.003891            0.007782                  -0.003133  -0.005534  
  Total variance             -0.009440   0.048195   0.038754        0.006692      0.003346            0.001673            0.003346                  -0.001347  -0.002380  
  Heritability               -0.008871   0.015563   0.006692        0.003927      0.001964            0.000982            0.001964                  -0.000791  -0.001397  
  Res full sibs corr         -0.004435   0.007782   0.003346        0.001964      0.000982            0.000491            0.000982                  -0.000395  -0.000698  
  Res half sibs corr         -0.002218   0.003891   0.001673        0.000982      0.000491            0.000245            0.000491                  -0.000198  -0.000349  
  Res parent offspring corr  -0.004435   0.007782   0.003346        0.001964      0.000982            0.000491            0.000982                  -0.000395  -0.000698  
  Intercept                   0.001786  -0.003133  -0.001347       -0.000791     -0.000395           -0.000198           -0.000395                   0.017806   0.001572  
  apres                       0.003154  -0.005534  -0.002380       -0.001397     -0.000698           -0.000349           -0.000698                   0.001572   0.020669  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood Alternate without test covariates  -6526.721593  
  H1 ln likelihood Alternate with test covariates     -6526.596941  
                                                                    
  2 * |H0 - H1|                                           0.249305  
  Degrees of freedom                                             1  
  P-value                                                 0.617565  

