=================

     Results

=================

==============================
     Analysis description
==============================

  Title                        pe_________                   
  Primary Trait                sqrtdbh (Quantitative)        
  Allow averaging              Enabled                       
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  

======================================
     Transformation configuration
======================================



Note: No transformation applied.

=======================
     Summary table
=======================

----------------------------------------------------------------------------------------
  Model      Intercept  Test cov.  Estimate   Std. err.  P-value (Wald)  P-value (LRT)  
----------------------------------------------------------------------------------------
  Alternate   4.961041  apres       0.071791   0.143768   0.617530        0.617565      
----------------------------------------------------------------------------------------

Note: Models with an asterisk (*) may not have converged.

================================
     Complete summary table
================================

----------------------------------------------------------------------------------------
  Model      Intercept  Test cov.  Estimate   Std. err.  P-value (Wald)  P-value (LRT)  
----------------------------------------------------------------------------------------
  Alternate   4.961041  apres       0.071791   0.143768   0.617530        0.617565      
----------------------------------------------------------------------------------------

Note: Models with an asterisk (*) may not have converged.

Note: See .det file for more information about each model

