


============================
     SAMPLE DESCRIPTION
============================

  Number of pedigrees in dataset            27  
  Number of analyzable pedigrees            27  
                                                
  Number of individuals in dataset         135  
  Number of sibs in dataset                 81  
  Number of analyzable sibs                 54  
  Number of sibs with missing age values    27  

===========================
     MODEL DESCRIPTION
===========================

  Title               AGEON Analysis 1  
  Affectedness trait  a                 
  Age-of-onset trait  o                 
  Age-at-exam trait   e                 

===============================
     CLASSIFICATION SYSTEM
===============================

  Using default classification system:
                                                                

  ??  Both parents are unknown.                                 
  ?A  One of the parents is unknown, the other is affected.     
  ?U  One of the parents is unknown, the other is unaffected.   
  AA  Both parents are affected.                                
  AU  One of the parents is affected, the other is unaffected.  
  UU  Both parents are unaffected.                              

==========================

     CLASS STATISTICS

==========================

==================
     CLASS ??
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            4  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          2  
  MEAN OF AGE OF ONSET                             5.000000  
  VARIANCE OF AGE OF ONSET                         0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                          2  
  PROPORTION OF INDIVIDUALS AFFECTED               0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            7.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        0.000000  

==================
     CLASS ?A
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            6  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          3  
  MEAN OF AGE OF ONSET                             6.000000  
  VARIANCE OF AGE OF ONSET                         0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                          3  
  PROPORTION OF INDIVIDUALS AFFECTED               0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            8.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        0.000000  

==================
     CLASS ?U
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS             8  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           4  
  MEAN OF AGE OF ONSET                              9.000000  
  VARIANCE OF AGE OF ONSET                          0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           4  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            11.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         0.000000  

==================
     CLASS AA
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            10  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           5  
  MEAN OF AGE OF ONSET                             10.000000  
  VARIANCE OF AGE OF ONSET                          0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           5  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            12.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         0.000000  

==================
     CLASS AU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            12  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           6  
  MEAN OF AGE OF ONSET                             11.000000  
  VARIANCE OF AGE OF ONSET                          0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           6  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            13.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         0.000000  

==================
     CLASS UU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            14  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           7  
  MEAN OF AGE OF ONSET                             12.000000  
  VARIANCE OF AGE OF ONSET                          0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           7  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            14.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         0.000000  

====================================================================
     MAXIMIZATION RESULTS susceptibilities equal, no truncation
====================================================================

-----------------------------------------------------------------------
  Parameter           Estimate   S.E.       P-value     Deriv          
-----------------------------------------------------------------------
  Susceptibility intercepts
                  ??   0.204793   0.287213   0.475825    0.0000185931  
                  ?A   0.204793   0.287213   0.475825    0.0000000000  
                  ?U   0.204793   0.287213   0.475825    0.0000000000  
                  AA   0.204793   0.287213   0.475825    0.0000000000  
                  AU   0.204793   0.287213   0.475825    0.0000000000  
                  UU   0.204793   0.287213   0.475825    0.0000000000  

      Mean intercept   0.867887   0.040278  < 1.00e-07  -0.0332470261  
  Variance intercept   8.79e-07         Ind. fixed near bound          

  Transformation
             Lambda1  -1.035421   0.063618  < 1.00e-07   0.0419123538  
             Lambda2   0.050000                 Fixed                  
-----------------------------------------------------------------------

Final ln likelihood: -9.142022

===================================================================
     MAXIMIZATION RESULTS susceptibilities free, no truncation
===================================================================

---------------------------------------------------------------------------
  Parameter           Estimate    S.E.         P-value      Deriv          
---------------------------------------------------------------------------
  Susceptibility intercepts
                  ??    0.000000                   Fixed                   
                  ?A   50.400000  Unavailable  Unavailable   0.0000000000  
                  ?U   -2.31e-07  Unavailable  Unavailable   0.0000004626  
                  AA    2.19e-06  Unavailable  Unavailable  -0.0000054780  
                  AU    3.02e-06  Unavailable  Unavailable  -0.0000090595  
                  UU    5.77e-07  Unavailable  Unavailable  -0.0000020220  

      Mean intercept    0.877531  Unavailable  Unavailable  -0.0010534414  
  Variance intercept    9.94e-07           Ind. fixed near bound           

  Transformation
             Lambda1   -1.020160  Unavailable  Unavailable   0.0007026514  
             Lambda2    0.050000                   Fixed                   
---------------------------------------------------------------------------

Final ln likelihood: -8.053750

=======================================================================
     MAXIMIZATION RESULTS susceptibilities equal, using truncation
=======================================================================

---------------------------------------------------------------------------
  Parameter           Estimate   S.E.         P-value      Deriv           
---------------------------------------------------------------------------
  Susceptibility intercepts
                  ??   0.204827  Unavailable  Unavailable   -0.0003086245  
                  ?A   0.204827  Unavailable  Unavailable    0.0000000000  
                  ?U   0.204827  Unavailable  Unavailable    0.0000000000  
                  AA   0.204827  Unavailable  Unavailable    0.0000000000  
                  AU   0.204827  Unavailable  Unavailable    0.0000000000  
                  UU   0.204827  Unavailable  Unavailable    0.0000000000  

      Mean intercept   2.252827  Unavailable  Unavailable    0.0006789063  
  Variance intercept   0.001328  Unavailable  Unavailable    0.1040416914  

  Transformation
             Lambda1   2.27e-09  Unavailable  Unavailable  -52.9673599075  
             Lambda2   0.050000                   Fixed                    
---------------------------------------------------------------------------

Final ln likelihood: -56.915085

======================================================================
     MAXIMIZATION RESULTS susceptibilities free, using truncation
======================================================================

-----------------------------------------------------------------------------
  Parameter           Estimate    S.E.         P-value      Deriv            
-----------------------------------------------------------------------------
  Susceptibility intercepts
                  ??    0.000000                    Fixed                    
                  ?A   45.562626  Unavailable  Unavailable     0.0000000000  
                  ?U   -0.097979  Unavailable  Unavailable     0.1958000968  
                  AA   -0.104052  Unavailable  Unavailable     0.2598954646  
                  AU    0.060457  Unavailable  Unavailable    -0.1813166105  
                  UU   -0.033959  Unavailable  Unavailable     0.1188441830  

      Mean intercept    2.212698  Unavailable  Unavailable    30.7831544587  
  Variance intercept    0.001242  Unavailable  Unavailable   612.9365863779  

  Transformation
             Lambda1    1.30e-09  Unavailable  Unavailable  -140.0702615508  
             Lambda2    0.050000                    Fixed                    
-----------------------------------------------------------------------------

Error: Please note that this maximization did not fully converge. The final estimates may be incorrect - check that the first derivatives are close to zero.
Final ln likelihood: -55.753850

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities free, no truncation   -8.053750  
  H1 ln likelihood susceptibilities equal, no truncation  -9.142022  
                                                                     
  2 * |H0 - H1|                                            2.176545  
  Degrees of freedom                                              4  
  P-value                                                  0.703326  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities free, using truncation   -55.753850  (possible non-convergence)  
  H1 ln likelihood susceptibilities equal, using truncation  -56.915085                              
                                                                                                     
  2 * |H0 - H1|                                                2.322472                              
  Degrees of freedom                                                  4                              
  P-value                                                      0.676681                              

==========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, no truncation
==========================================================================

-------------------------------------------------------------------------------------------------------------------------------------------------------
                                      Mean intercept  Variance intercept  Lambda1    ??         ?A         ?U         AA         AU         UU         
-------------------------------------------------------------------------------------------------------------------------------------------------------
  Mean intercept                       0.001622        0.000000            0.002535   1.43e-12   1.43e-12   1.43e-12   1.43e-12   1.43e-12   1.43e-12  
  Variance intercept                   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  Lambda1                              0.002535        0.000000            0.004047   2.29e-12   2.29e-12   2.29e-12   2.29e-12   2.29e-12   2.29e-12  
  ??                                   1.43e-12        0.000000            2.29e-12   0.082492   0.082492   0.082492   0.082492   0.082492   0.082492  
  ?A                                   1.43e-12        0.000000            2.29e-12   0.082492   0.082492   0.082492   0.082492   0.082492   0.082492  
  ?U                                   1.43e-12        0.000000            2.29e-12   0.082492   0.082492   0.082492   0.082492   0.082492   0.082492  
  AA                                   1.43e-12        0.000000            2.29e-12   0.082492   0.082492   0.082492   0.082492   0.082492   0.082492  
  AU                                   1.43e-12        0.000000            2.29e-12   0.082492   0.082492   0.082492   0.082492   0.082492   0.082492  
  UU                                   1.43e-12        0.000000            2.29e-12   0.082492   0.082492   0.082492   0.082492   0.082492   0.082492  
                                                                                                                                                       
  Likelihood Surface flat                                                                                                                              
  variance matrix near singular and                                                                                                                    
  may be affected by rounding error.                                                                                                                   
  Reducing the number of parameters                                                                                                                    
  to be estimated is recommended                                                                                                                       

=========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities free, no truncation
=========================================================================



Error: Matrix is not available.

=============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, using truncation
=============================================================================



Error: Matrix is not available.

============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities free, using truncation
============================================================================



Error: Matrix is not available.

