


============================
     SAMPLE DESCRIPTION
============================

  Number of pedigrees in dataset            27  
  Number of analyzable pedigrees            27  
                                                
  Number of individuals in dataset         135  
  Number of sibs in dataset                 81  
  Number of analyzable sibs                 44  
  Number of sibs with missing age values    37  

===========================
     MODEL DESCRIPTION
===========================

  Title               AGEON Analysis 2  
  Affectedness trait  a                 
  Age-of-onset trait  o                 
  Age-at-exam trait   e                 

===============================
     CLASSIFICATION SYSTEM
===============================

  Using default classification system:
                                                                

  ??  Both parents are unknown.                                 
  ?A  One of the parents is unknown, the other is affected.     
  ?U  One of the parents is unknown, the other is unaffected.   
  AA  Both parents are affected.                                
  AU  One of the parents is affected, the other is unaffected.  
  UU  Both parents are unaffected.                              

==========================

     CLASS STATISTICS

==========================

==================
     CLASS ??
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS ?A
==================



Note: Contains no valid individuals for analysis.

==================
     CLASS ?U
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS             8  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           4  
  MEAN OF AGE OF ONSET                              9.000000  
  VARIANCE OF AGE OF ONSET                          0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           4  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            11.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         0.000000  

==================
     CLASS AA
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            10  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           5  
  MEAN OF AGE OF ONSET                             10.000000  
  VARIANCE OF AGE OF ONSET                          0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           5  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            12.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         0.000000  

==================
     CLASS AU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            12  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           6  
  MEAN OF AGE OF ONSET                             11.000000  
  VARIANCE OF AGE OF ONSET                          0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           6  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            13.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         0.000000  

==================
     CLASS UU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            14  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           7  
  MEAN OF AGE OF ONSET                             12.000000  
  VARIANCE OF AGE OF ONSET                          0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           7  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            14.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         0.000000  

====================================================================
     MAXIMIZATION RESULTS susceptibilities equal, no truncation
====================================================================

-----------------------------------------------------------------------
  Parameter           Estimate   S.E.       P-value     Deriv          
-----------------------------------------------------------------------
  Susceptibility intercepts
                  ??  -2.92e-07   0.301512   0.999999    0.0000032116  
                  ?A  -2.92e-07   0.301512   0.999999    0.0000000000  
                  ?U  -2.92e-07   0.301512   0.999999    0.0000000000  
                  AA  -2.92e-07   0.301512   0.999999    0.0000000000  
                  AU  -2.92e-07   0.301512   0.999999    0.0000000000  
                  UU  -2.92e-07   0.301512   0.999999    0.0000000000  

      Mean intercept   6.198790   0.226984  < 1.00e-07  -0.1115949914  

  Mean covariates
                   c   1.711701   0.172615  < 1.00e-07  -0.5550886427  

  Variance intercept   8.89e-07         Ind. fixed near bound          

  Transformation
             Lambda1   1.227657   0.042675  < 1.00e-07   2.8677047549  
             Lambda2   0.050000                 Fixed                  
-----------------------------------------------------------------------

Final ln likelihood:  110.561129

===================================================================
     MAXIMIZATION RESULTS susceptibilities free, no truncation
===================================================================

-----------------------------------------------------------------------
  Parameter           Estimate   S.E.       P-value     Deriv          
-----------------------------------------------------------------------
  Susceptibility intercepts
                  ??   0.000000                 Fixed                  
                  ?A   0.000000                 Fixed                  
                  ?U   5.16e-07   0.707106   0.999999   -0.0000010368  
                  AA   4.34e-07   0.632456   0.999999   -0.0000010790  
                  AU   2.02e-06   0.577351   0.999997   -0.0000060776  
                  UU  -3.56e-07   0.534523   0.999999    0.0000012475  

      Mean intercept   6.179618   0.224730  < 1.00e-07  -0.0001260228  

  Mean covariates
                   c   1.697066   0.169605  < 1.00e-07  -0.0006157845  

  Variance intercept   8.22e-07         Ind. fixed near bound          

  Transformation
             Lambda1   1.224021   0.042293  < 1.00e-07   0.0031461280  
             Lambda2   0.050000                 Fixed                  
-----------------------------------------------------------------------

Final ln likelihood:  111.277706

=======================================================================
     MAXIMIZATION RESULTS susceptibilities equal, using truncation
=======================================================================

-------------------------------------------------------------------------
  Parameter           Estimate   S.E.       P-value     Deriv            
-------------------------------------------------------------------------
  Susceptibility intercepts
                  ??   0.000403   0.301511   0.998934     -0.0044308982  
                  ?A   0.000403   0.301511   0.998934      0.0000000000  
                  ?U   0.000403   0.301511   0.998934      0.0000000000  
                  AA   0.000403   0.301511   0.998934      0.0000000000  
                  AU   0.000403   0.301511   0.998934      0.0000000000  
                  UU   0.000403   0.301511   0.998934      0.0000000000  

      Mean intercept   6.044215   0.143773  < 1.00e-07    20.6935768730  

  Mean covariates
                   c   1.596629   0.101607  < 1.00e-07   103.3193810189  

  Variance intercept   8.89e-07          Ind. fixed near bound           

  Transformation
             Lambda1   1.198240   0.026899  < 1.00e-07  -483.5024220756  
             Lambda2   0.050000                  Fixed                   
-------------------------------------------------------------------------

Final ln likelihood:  110.329674

======================================================================
     MAXIMIZATION RESULTS susceptibilities free, using truncation
======================================================================

-------------------------------------------------------------------------
  Parameter           Estimate   S.E.       P-value     Deriv            
-------------------------------------------------------------------------
  Susceptibility intercepts
                  ??   0.000000                  Fixed                   
                  ?A   0.000000                  Fixed                   
                  ?U   0.012205   0.707120   0.986229     -0.0244102745  
                  AA  -0.039427   0.632566   0.950301      0.0985539652  
                  AU  -0.013940   0.577364   0.980738      0.0418194687  
                  UU  -0.009920   0.534529   0.985194      0.0347193347  

      Mean intercept   6.007242   0.183016  < 1.00e-07     9.1717112731  

  Mean covariates
                   c   1.570327   0.128481  < 1.00e-07    45.7441071614  

  Variance intercept   8.22e-07          Ind. fixed near bound           

  Transformation
             Lambda1   1.191176   0.034610  < 1.00e-07  -201.5767951805  
             Lambda2   0.050000                  Fixed                   
-------------------------------------------------------------------------

Final ln likelihood:  110.994635

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities free, no truncation    111.277706  
  H1 ln likelihood susceptibilities equal, no truncation   110.561129  
                                                                       
  2 * |H0 - H1|                                              1.433154  
  Degrees of freedom                                                3  
  P-value                                                    0.697782  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities free, using truncation    110.994635  
  H1 ln likelihood susceptibilities equal, using truncation   110.329674  
                                                                          
  2 * |H0 - H1|                                                 1.329920  
  Degrees of freedom                                                   3  
  P-value                                                       0.722041  

==========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, no truncation
==========================================================================

--------------------------------------------------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  Lambda1    c          ??         ?A         ?U         AA         AU         UU         
--------------------------------------------------------------------------------------------------------------------------------------------------
  Mean intercept       0.051522        0.000000            0.009607   0.038667   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  Variance intercept   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  Lambda1              0.009607        0.000000            0.001821   0.007362   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  c                    0.038667        0.000000            0.007362   0.029796   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  ??                   0.000000        0.000000            0.000000   0.000000   0.090909   0.090909   0.090909   0.090909   0.090909   0.090909  
  ?A                   0.000000        0.000000            0.000000   0.000000   0.090909   0.090909   0.090909   0.090909   0.090909   0.090909  
  ?U                   0.000000        0.000000            0.000000   0.000000   0.090909   0.090909   0.090909   0.090909   0.090909   0.090909  
  AA                   0.000000        0.000000            0.000000   0.000000   0.090909   0.090909   0.090909   0.090909   0.090909   0.090909  
  AU                   0.000000        0.000000            0.000000   0.000000   0.090909   0.090909   0.090909   0.090909   0.090909   0.090909  
  UU                   0.000000        0.000000            0.000000   0.000000   0.090909   0.090909   0.090909   0.090909   0.090909   0.090909  

=========================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities free, no truncation
=========================================================================

--------------------------------------------------------------------------------------------------------------------------------------------
                                      Mean intercept  Variance intercept  Lambda1    c          ?U         AA         AU         UU         
--------------------------------------------------------------------------------------------------------------------------------------------
  Mean intercept                       0.050504        0.000000            0.009428   0.037623   0.000000   0.000000   8.40e-10   0.000000  
  Variance intercept                   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  Lambda1                              0.009428        0.000000            0.001789   0.007169   0.000000   0.000000   1.60e-10   0.000000  
  c                                    0.037623        0.000000            0.007169   0.028766   0.000000   0.000000   6.42e-10   0.000000  
  ?U                                   0.000000        0.000000            0.000000   0.000000   0.499999   0.000000   0.000000   0.000000  
  AA                                   0.000000        0.000000            0.000000   0.000000   0.000000   0.400001   0.000000   0.000000  
  AU                                   8.40e-10        0.000000            1.60e-10   6.42e-10   0.000000   0.000000   0.333334   0.000000  
  UU                                   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000   0.000000   0.285715  
                                                                                                                                            
  Likelihood Surface flat                                                                                                                   
  variance matrix near singular and                                                                                                         
  may be affected by rounding error.                                                                                                        
  Reducing the number of parameters                                                                                                         
  to be estimated is recommended                                                                                                            

=============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities equal, using truncation
=============================================================================

--------------------------------------------------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  Lambda1    c          ??         ?A         ?U         AA         AU         UU         
--------------------------------------------------------------------------------------------------------------------------------------------------
  Mean intercept       0.020671        0.000000            0.003788   0.014114   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  Variance intercept   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  Lambda1              0.003788        0.000000            0.000724   0.002728   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  c                    0.014114        0.000000            0.002728   0.010324   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  ??                   0.000000        0.000000            0.000000   0.000000   0.090909   0.090909   0.090909   0.090909   0.090909   0.090909  
  ?A                   0.000000        0.000000            0.000000   0.000000   0.090909   0.090909   0.090909   0.090909   0.090909   0.090909  
  ?U                   0.000000        0.000000            0.000000   0.000000   0.090909   0.090909   0.090909   0.090909   0.090909   0.090909  
  AA                   0.000000        0.000000            0.000000   0.000000   0.090909   0.090909   0.090909   0.090909   0.090909   0.090909  
  AU                   0.000000        0.000000            0.000000   0.000000   0.090909   0.090909   0.090909   0.090909   0.090909   0.090909  
  UU                   0.000000        0.000000            0.000000   0.000000   0.090909   0.090909   0.090909   0.090909   0.090909   0.090909  

============================================================================
     VARIANCE-COVARIANCE MATRIX susceptibilities free, using truncation
============================================================================

----------------------------------------------------------------------------------------------------------------------------
                      Mean intercept  Variance intercept  Lambda1    c          ?U         AA         AU         UU         
----------------------------------------------------------------------------------------------------------------------------
  Mean intercept       0.033495        0.000000            0.006257   0.023041   0.000000   0.000000   0.000000   0.000000  
  Variance intercept   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000   0.000000   0.000000  
  Lambda1              0.006257        0.000000            0.001198   0.004442   0.000000   0.000000   0.000000   0.000000  
  c                    0.023041        0.000000            0.004442   0.016507   0.000000   0.000000   0.000000   0.000000  
  ?U                   0.000000        0.000000            0.000000   0.000000   0.500019   0.000000   0.000000   0.000000  
  AA                   0.000000        0.000000            0.000000   0.000000   0.000000   0.400139   0.000000   0.000000  
  AU                   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000   0.333349   0.000000  
  UU                   0.000000        0.000000            0.000000   0.000000   0.000000   0.000000   0.000000   0.285721  

