


============================
     SAMPLE DESCRIPTION
============================

  Number of pedigrees in dataset            27  
  Number of analyzable pedigrees            27  
                                                
  Number of individuals in dataset         135  
  Number of sibs in dataset                 81  
  Number of analyzable sibs                 54  
  Number of sibs with missing age values    27  

===========================
     MODEL DESCRIPTION
===========================

  Title               AGEON Analysis 3  
  Affectedness trait  a                 
  Age-of-onset trait  o                 
  Age-at-exam trait   e                 

===============================
     CLASSIFICATION SYSTEM
===============================

  Using default classification system:
                                                                

  ??  Both parents are unknown.                                 
  ?A  One of the parents is unknown, the other is affected.     
  ?U  One of the parents is unknown, the other is unaffected.   
  AA  Both parents are affected.                                
  AU  One of the parents is affected, the other is unaffected.  
  UU  Both parents are unaffected.                              

==========================

     CLASS STATISTICS

==========================

==================
     CLASS ??
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            4  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          2  
  MEAN OF AGE OF ONSET                             5.000000  
  VARIANCE OF AGE OF ONSET                         0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                          2  
  PROPORTION OF INDIVIDUALS AFFECTED               0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            7.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        0.000000  

==================
     CLASS ?A
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            6  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET          3  
  MEAN OF AGE OF ONSET                             6.000000  
  VARIANCE OF AGE OF ONSET                         0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                          3  
  PROPORTION OF INDIVIDUALS AFFECTED               0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            8.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED        0.000000  

==================
     CLASS ?U
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS             8  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           4  
  MEAN OF AGE OF ONSET                              9.000000  
  VARIANCE OF AGE OF ONSET                          0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           4  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            11.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         0.000000  

==================
     CLASS AA
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            10  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           5  
  MEAN OF AGE OF ONSET                             10.000000  
  VARIANCE OF AGE OF ONSET                          0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           5  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            12.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         0.000000  

==================
     CLASS AU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            12  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           6  
  MEAN OF AGE OF ONSET                             11.000000  
  VARIANCE OF AGE OF ONSET                          0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           6  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            13.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         0.000000  

==================
     CLASS UU
==================

  TOTAL NUMBER OF INDIVIDUALS USED IN ANALYSIS            14  
  NUMBER OF AFF INDIVIDUALS WITH AN AGE OF ONSET           7  
  MEAN OF AGE OF ONSET                             12.000000  
  VARIANCE OF AGE OF ONSET                          0.000000  
  NUMBER OF INDIVIDUALS AFFECTED                           7  
  PROPORTION OF INDIVIDUALS AFFECTED                0.500000  
  MEAN OF AGE OF EXAM OF THE UNAFFECTED            14.000000  
  VARIANCE OF AGE OF EXAM OF THE UNAFFECTED         0.000000  

====================================================================
     MAXIMIZATION RESULTS susceptibilities equal, no truncation
====================================================================

--------------------------------------------------------
  Parameter           Estimate   S.E.       P-value     
--------------------------------------------------------
  Susceptibility intercepts
                  ??   0.204729   0.287213   0.475960   
                  ?A   0.204729   0.287213   0.475960   
                  ?U   0.204729   0.287213   0.475960   
                  AA   0.204729   0.287213   0.475960   
                  AU   0.204729   0.287213   0.475960   
                  UU   0.204729   0.287213   0.475960   

      Mean intercept   0.847312   0.046250  < 1.00e-07  

  Mean covariates
                   c   0.007746   0.006198   0.211385   

  Variance intercept   9.54e-07  Ind. fixed near bound  

  Transformation
             Lambda1  -1.010006   0.063935  < 1.00e-07  
             Lambda2   0.050000          Fixed          
--------------------------------------------------------

Final ln likelihood: -8.849249

===================================================================
     MAXIMIZATION RESULTS susceptibilities free, no truncation
===================================================================

------------------------------------------------------------
  Parameter           Estimate    S.E.         P-value      
------------------------------------------------------------
  Susceptibility intercepts
                  ??    0.000000           Fixed            
                  ?A   48.750000  Unavailable  Unavailable  
                  ?U   48.750000  Unavailable  Unavailable  
                  AA   -3.82e-07  Unavailable  Unavailable  
                  AU   -3.91e-08  Unavailable  Unavailable  
                  UU   -7.98e-07  Unavailable  Unavailable  

      Mean intercept    0.887564  Unavailable  Unavailable  

  Mean covariates
                   c   -0.006429  Unavailable  Unavailable  

  Variance intercept    9.76e-07   Ind. fixed near bound    

  Transformation
             Lambda1   -1.065036  Unavailable  Unavailable  
             Lambda2    0.050000           Fixed            
------------------------------------------------------------

Final ln likelihood: -5.164082

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood susceptibilities free, no truncation   -5.164082  
  H1 ln likelihood susceptibilities equal, no truncation  -8.849249  
                                                                     
  2 * |H0 - H1|                                            7.370335  
  Degrees of freedom                                              4  
  P-value                                                  0.117565  

