


Reading Parameter File....................done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Reading pairs.............................done.
Sorting pairs.............................done.

SIBPAL analysis.......  1

Computing trait regression................done.

SIBPAL analysis.......  2

Reading Pair Information File.............
              from pair.in................done.
Computing trait regression................done.

Analysis complete!



