


==============================================================================
  Haseman-Elston Regression Analysis of Full Sibs
  - single marker regression
==============================================================================

    Binary trait : bpn, affected = '2' , unaffected = '1'

    Dependent variate : Mean-corrected trait cross-product

    w1 : 0.5

    Other options used :
      Identity weights = no
      Robust variance  = no
      Use sibship mean = no
      Use BLUP mean    = yes

    Legend :
      Note - kurtosis = coefficient of kurtosis - 3
      *   - significance  .05 level;
      **  - significance  .01 level;
      *** - significance .001 level;
      #   - Negative intercept set to 0;

==============================================================================
Test  Independent                                                 Nominal     
No.   variable      cM  Pairs   Parameter    Estimate Std Error   P-value     
----- ----------- ----- ----- ----------- ----------- --------- ---------     
1     D16S3127      0.0  1996 (A+D)GenVar     0.0142 #   0.0098 0.0745512     
2     D16S405       0.1  1996 (A+D)GenVar     0.0143 #   0.0094 0.0647468     
3     D16S3103      1.7  1996 (A+D)GenVar     0.0032 #   0.0089 0.3609275     
4     D16S3017      1.8  1996 (A+D)GenVar    -0.0049 #   0.0093 0.7004167     
5     D16S668       2.2  1996 (A+D)GenVar    -0.0032 #   0.0105 0.6202690     
6     D16S683       2.3  1996 (A+D)GenVar     0.0117 #   0.0103 0.1288244     
7     D16S501       2.4  1996 (A+D)GenVar     0.0110 #   0.0098 0.1291457     
8     D16S499       2.5  1996 (A+D)GenVar     0.0130 #   0.0094 0.0829040     
9     D16S3056      3.2  1996 (A+D)GenVar     0.0141 #   0.0096 0.0707934     
==============================================================================


==============================================================================
  Haseman-Elston Regression Analysis of Full Sibs
  - single marker regression
==============================================================================

    Binary trait : bpn, affected = '2' , unaffected = '1'

    Dependent variate : Mean-corrected trait cross-product

    w1 : 0.5

    Other options used :
      Identity weights = no
      Robust variance  = no
      Use sibship mean = no
      Use BLUP mean    = yes

    Legend :
      Note - kurtosis = coefficient of kurtosis - 3
      *   - significance  .05 level;
      **  - significance  .01 level;
      *** - significance .001 level;
      #   - Negative intercept set to 0;

==============================================================================
Test  Independent                                                 Nominal     
No.   variable      cM  Pairs   Parameter    Estimate Std Error   P-value     
----- ----------- ----- ----- ----------- ----------- --------- ---------     
1     D16S3127      0.0   190 (A+D)GenVar     0.0569 #   0.0451 0.1046776     
      probability             Cov,pair        0.0647 #   0.1305 0.6207420     
2     D16S405       0.1   190 (A+D)GenVar     0.0425 #   0.0433 0.1638005     
      probability             Cov,pair        0.0627 #   0.1308 0.6322267     
3     D16S3103      1.7   190 (A+D)GenVar     0.0394 #   0.0418 0.1738541     
      probability             Cov,pair        0.0666 #   0.1308 0.6114725     
4     D16S3017      1.8   190 (A+D)GenVar     0.0410 #   0.0432 0.1719419     
      probability             Cov,pair        0.0777 #   0.1316 0.5556431     
5     D16S668       2.2   190 (A+D)GenVar     0.0183 #   0.0497 0.3565400     
      probability             Cov,pair        0.0646 #   0.1310 0.6227717     
6     D16S683       2.3   190 (A+D)GenVar     0.0341 #   0.0496 0.2460803     
      probability             Cov,pair        0.0683 #   0.1311 0.6029092     
7     D16S501       2.4   190 (A+D)GenVar     0.0452 #   0.0533 0.1986742     
      probability             Cov,pair        0.0764 #   0.1317 0.5621665     
8     D16S499       2.5   190 (A+D)GenVar     0.0410 #   0.0462 0.1881324     
      probability             Cov,pair        0.0676 #   0.1309 0.6061003     
9     D16S3056      3.2   190 (A+D)GenVar     0.0408 #   0.0464 0.1898026     
      probability             Cov,pair        0.0712 #   0.1311 0.5878204     
==============================================================================


