=================

     Results

=================

Note: P-values for variance components and proportions are one-sided.  All others are two-sided.
The null hypothesis for transformation parameters is 'no transformation.'


==============================
     Analysis description
==============================

  Title                        assoc                         
  Primary Trait                sbpd_rand10 (Quantitative)    
  Allow averaging              Disabled                      
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  

======================================
     Transformation configuration
======================================



Note: No transformation applied.

====================================

     Model 'FAMILIAL_INDICATOR'

====================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

------------------------------------------------------------------
  Name                Mean       Std. dev.  Min        Max        
------------------------------------------------------------------
  sex_code             0.559908   0.496398   0.000000   1.000000  
  FAMILIAL_INDICATOR   0.995392   0.067728   0.000000   1.000000  

=========================================================================
     MAXIMIZATION RESULTS FAMILIAL_INDICATOR without test covariates
=========================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036047   20.367758  < 1.00e-07   0.0000000103  

  Other parameters
  Total variance   300.036047   20.367758  < 1.00e-07   0.0000000576  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323939    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

===============================================================================
     VARIANCE-COVARIANCE MATRIX FAMILIAL_INDICATOR without test covariates
===============================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845585   414.845585     -0.000153  -4.74e-05  
  Total variance   414.845585   414.845585     -0.000153  -4.74e-05  
  Intercept         -0.000153    -0.000153      0.691327   1.75e-11  
  sex_code          -4.74e-05    -4.74e-05      1.75e-11   2.805586  

======================================================================
     MAXIMIZATION RESULTS FAMILIAL_INDICATOR with test covariates
======================================================================

--------------------------------------------------------------------------
  Parameter           Estimate     S.E.        P-value     Deriv          
--------------------------------------------------------------------------
  Variance components
              Random   300.035877   20.367761  < 1.00e-07  -0.0000000094  

  Other parameters
      Total variance   300.035877   20.367761  < 1.00e-07   0.0000000005  

           Intercept   131.181106    0.831461  < 1.00e-07   0.0000001349  

  Covariates
            sex_code    -4.327102    1.679942   0.010002    0.0000000000  
  FAMILIAL_INDICATOR     0.305280   12.312722   0.980219    0.0000000000  
--------------------------------------------------------------------------

Final ln likelihood: -1853.566067

============================================================================
     VARIANCE-COVARIANCE MATRIX FAMILIAL_INDICATOR with test covariates
============================================================================

---------------------------------------------------------------------------------------------
                      Random       Total variance  Intercept  sex_code   FAMILIAL_INDICATOR  
---------------------------------------------------------------------------------------------
  Random               414.845670   414.845670      0.000000   0.000000     0.000000         
  Total variance       414.845670   414.845670      0.000000   0.000000     0.000000         
  Intercept              0.000000     0.000000      0.691327   0.000000     0.000000         
  sex_code               0.000000     0.000000      0.000000   2.822207    -1.587473         
  FAMILIAL_INDICATOR     0.000000     0.000000      0.000000  -1.587473   151.603111         

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood FAMILIAL_INDICATOR without test covariates  -1853.566375  
  H1 ln likelihood FAMILIAL_INDICATOR with test covariates     -1853.566067  
                                                                             
  2 * |H0 - H1|                                                    0.000615  
  Degrees of freedom                                                      1  
  P-value                                                          0.980219  

===================================

     Model 'FOUNDER_INDICATOR'

===================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

-----------------------------------------------------------------
  Name               Mean       Std. dev.  Min        Max        
-----------------------------------------------------------------
  sex_code            0.559908   0.496398   0.000000   1.000000  
  FOUNDER_INDICATOR   0.050691   0.219366   0.000000   1.000000  

========================================================================
     MAXIMIZATION RESULTS FOUNDER_INDICATOR without test covariates
========================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036047   20.367758  < 1.00e-07   0.0000000103  

  Other parameters
  Total variance   300.036047   20.367758  < 1.00e-07   0.0000000576  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323939    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==============================================================================
     VARIANCE-COVARIANCE MATRIX FOUNDER_INDICATOR without test covariates
==============================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845585   414.845585     -0.000153  -4.74e-05  
  Total variance   414.845585   414.845585     -0.000153  -4.74e-05  
  Intercept         -0.000153    -0.000153      0.691327   1.75e-11  
  sex_code          -4.74e-05    -4.74e-05      1.75e-11   2.805586  

=====================================================================
     MAXIMIZATION RESULTS FOUNDER_INDICATOR with test covariates
=====================================================================

-------------------------------------------------------------------------
  Parameter          Estimate     S.E.        P-value     Deriv          
-------------------------------------------------------------------------
  Variance components
             Random   298.922216   20.292141  < 1.00e-07   0.0000001137  

  Other parameters
     Total variance   298.922216   20.292141  < 1.00e-07   0.0000000411  

          Intercept   131.180995    0.829916  < 1.00e-07   0.0000392302  

  Covariates
           sex_code    -4.354595    1.672050   0.009205    0.0000000000  
  FOUNDER_INDICATOR     4.811298    3.783632   0.203512    0.0000000000  
-------------------------------------------------------------------------

Final ln likelihood: -1852.759343

===========================================================================
     VARIANCE-COVARIANCE MATRIX FOUNDER_INDICATOR with test covariates
===========================================================================

-------------------------------------------------------------------------------------------
                     Random       Total variance  Intercept  sex_code   FOUNDER_INDICATOR  
-------------------------------------------------------------------------------------------
  Random              411.770967   411.770967     -0.000152  -6.85e-06   -0.000174         
  Total variance      411.770967   411.770967     -0.000152  -6.85e-06   -0.000174         
  Intercept            -0.000152    -0.000152      0.688761   2.54e-12    6.46e-11         
  sex_code             -6.85e-06    -6.85e-06      2.54e-12   2.795752   -0.091297         
  FOUNDER_INDICATOR    -0.000174    -0.000174      6.46e-11  -0.091297   14.315870         

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood FOUNDER_INDICATOR without test covariates  -1853.566375  
  H1 ln likelihood FOUNDER_INDICATOR with test covariates     -1852.759343  
                                                                            
  2 * |H0 - H1|                                                   1.614064  
  Degrees of freedom                                                     1  
  P-value                                                         0.203921  

===============================

     Model 'PEDIGREE_SIZE'

===============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

--------------------------------------------------------------
  Name           Mean       Std. dev.  Min        Max         
--------------------------------------------------------------
  sex_code        0.559908   0.496398   0.000000    1.000000  
  PEDIGREE_SIZE   9.523041   3.699629   1.000000   20.000000  

====================================================================
     MAXIMIZATION RESULTS PEDIGREE_SIZE without test covariates
====================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036047   20.367758  < 1.00e-07   0.0000000103  

  Other parameters
  Total variance   300.036047   20.367758  < 1.00e-07   0.0000000576  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323939    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==========================================================================
     VARIANCE-COVARIANCE MATRIX PEDIGREE_SIZE without test covariates
==========================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845585   414.845585     -0.000153  -4.74e-05  
  Total variance   414.845585   414.845585     -0.000153  -4.74e-05  
  Intercept         -0.000153    -0.000153      0.691327   1.75e-11  
  sex_code          -4.74e-05    -4.74e-05      1.75e-11   2.805586  

=================================================================
     MAXIMIZATION RESULTS PEDIGREE_SIZE with test covariates
=================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   298.703476   20.277294  < 1.00e-07   0.0000000194  

  Other parameters
  Total variance   298.703476   20.277294  < 1.00e-07   0.0000000401  

       Intercept   131.180995    0.829612  < 1.00e-07  -0.0000558375  

  Covariates
        sex_code    -4.166278    1.675099   0.012876    0.0000000000  
   PEDIGREE_SIZE    -0.312727    0.224757   0.164103    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1852.600463

=======================================================================
     VARIANCE-COVARIANCE MATRIX PEDIGREE_SIZE with test covariates
=======================================================================

------------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   PEDIGREE_SIZE  
------------------------------------------------------------------------------------
  Random           411.168649   411.168649     -0.000152   4.63e-06   1.37e-05      
  Total variance   411.168649   411.168649     -0.000152   4.63e-06   1.37e-05      
  Intercept         -0.000152    -0.000152      0.688257  -1.71e-12  -5.09e-12      
  sex_code           4.63e-06     4.63e-06     -1.71e-12   2.805956  -0.025461      
  PEDIGREE_SIZE      1.37e-05     1.37e-05     -5.09e-12  -0.025461   0.050516      

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood PEDIGREE_SIZE without test covariates  -1853.566375  
  H1 ln likelihood PEDIGREE_SIZE with test covariates     -1852.600463  
                                                                        
  2 * |H0 - H1|                                               1.931824  
  Degrees of freedom                                                 1  
  P-value                                                     0.164559  

===============================

     Model 'foo_selection'

===============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

-------------------------------------------------------------
  Name           Mean       Std. dev.  Min        Max        
-------------------------------------------------------------
  sex_code        0.559908   0.496398   0.000000   1.000000  
  foo_selection   1.615207   0.486546   1.000000   2.000000  

====================================================================
     MAXIMIZATION RESULTS foo_selection without test covariates
====================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036047   20.367758  < 1.00e-07   0.0000000103  

  Other parameters
  Total variance   300.036047   20.367758  < 1.00e-07   0.0000000576  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323939    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==========================================================================
     VARIANCE-COVARIANCE MATRIX foo_selection without test covariates
==========================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845585   414.845585     -0.000153  -4.74e-05  
  Total variance   414.845585   414.845585     -0.000153  -4.74e-05  
  Intercept         -0.000153    -0.000153      0.691327   1.75e-11  
  sex_code          -4.74e-05    -4.74e-05      1.75e-11   2.805586  

=================================================================
     MAXIMIZATION RESULTS foo_selection with test covariates
=================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   226.207728   15.355958  < 1.00e-07   0.0000006374  

  Other parameters
  Total variance   226.207728   15.355958  < 1.00e-07   0.0000084080  

       Intercept   131.180991    0.721953  < 1.00e-07  -0.0000001253  

  Covariates
        sex_code    -5.400090    1.457191   0.000211    0.0000000000  
   foo_selection    17.693938    1.486697  < 1.00e-07   0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1792.275111

=======================================================================
     VARIANCE-COVARIANCE MATRIX foo_selection with test covariates
=======================================================================

------------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_selection  
------------------------------------------------------------------------------------
  Random           235.805438   235.805438     -0.000120   2.36e-05  -1.70e-05      
  Total variance   235.805438   235.805438     -0.000120   2.36e-05  -1.70e-05      
  Intercept         -0.000120    -0.000120      0.521216  -1.20e-11   8.63e-12      
  sex_code           2.36e-05     2.36e-05     -1.20e-11   2.123407  -0.134436      
  foo_selection     -1.70e-05    -1.70e-05      8.63e-12  -0.134436   2.210269      

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_selection without test covariates  -1853.566375  
  H1 ln likelihood foo_selection with test covariates     -1792.275111  
                                                                        
  2 * |H0 - H1|                                             122.582527  
  Degrees of freedom                                                 1  
  P-value                                                     1.72e-28  

=========================

     Model 'foo_age'

=========================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

------------------------------------------------------------
  Name      Mean        Std. dev.   Min         Max         
------------------------------------------------------------
  sex_code    0.559908    0.496398    0.000000    1.000000  
  foo_age    47.456221   12.045581   19.000000   84.000000  

==============================================================
     MAXIMIZATION RESULTS foo_age without test covariates
==============================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036047   20.367758  < 1.00e-07   0.0000000103  

  Other parameters
  Total variance   300.036047   20.367758  < 1.00e-07   0.0000000576  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323939    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

====================================================================
     VARIANCE-COVARIANCE MATRIX foo_age without test covariates
====================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845585   414.845585     -0.000153  -4.74e-05  
  Total variance   414.845585   414.845585     -0.000153  -4.74e-05  
  Intercept         -0.000153    -0.000153      0.691327   1.75e-11  
  sex_code          -4.74e-05    -4.74e-05      1.75e-11   2.805586  

===========================================================
     MAXIMIZATION RESULTS foo_age with test covariates
===========================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   273.728880   18.581911  < 1.00e-07  -0.0000000734  

  Other parameters
  Total variance   273.728880   18.581911  < 1.00e-07   0.0000005809  

       Intercept   131.180995    0.794174  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -5.368967    1.608035   0.000841    0.0000000000  
         foo_age     0.427976    0.066267  < 1.00e-07   0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1833.653463

=================================================================
     VARIANCE-COVARIANCE MATRIX foo_age with test covariates
=================================================================

--------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_age    
--------------------------------------------------------------------------------
  Random           345.287420   345.287420     -0.000140  -6.17e-06  -4.22e-07  
  Total variance   345.287420   345.287420     -0.000140  -6.17e-06  -4.22e-07  
  Intercept         -0.000140    -0.000140      0.630712   2.50e-12   1.71e-13  
  sex_code          -6.17e-06    -6.17e-06      2.50e-12   2.585775  -0.010723  
  foo_age           -4.22e-07    -4.22e-07      1.71e-13  -0.010723   0.004391  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_age without test covariates  -1853.566375  
  H1 ln likelihood foo_age with test covariates     -1833.653463  
                                                                  
  2 * |H0 - H1|                                        39.825823  
  Degrees of freedom                                           1  
  P-value                                               2.78e-10  

=========================

     Model 'foo_bmi'

=========================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

-----------------------------------------------------------
  Name      Mean        Std. dev.  Min         Max         
-----------------------------------------------------------
  sex_code    0.559908   0.496398    0.000000    1.000000  
  foo_bmi    28.584562   5.176045   16.100000   48.400000  

==============================================================
     MAXIMIZATION RESULTS foo_bmi without test covariates
==============================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036047   20.367758  < 1.00e-07   0.0000000103  

  Other parameters
  Total variance   300.036047   20.367758  < 1.00e-07   0.0000000576  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323939    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

====================================================================
     VARIANCE-COVARIANCE MATRIX foo_bmi without test covariates
====================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845585   414.845585     -0.000153  -4.74e-05  
  Total variance   414.845585   414.845585     -0.000153  -4.74e-05  
  Intercept         -0.000153    -0.000153      0.691327   1.75e-11  
  sex_code          -4.74e-05    -4.74e-05      1.75e-11   2.805586  

===========================================================
     MAXIMIZATION RESULTS foo_bmi with test covariates
===========================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   297.594319   20.202002  < 1.00e-07   0.0000000884  

  Other parameters
  Total variance   297.594319   20.202002  < 1.00e-07   0.0000000154  

       Intercept   131.180995    0.828071  < 1.00e-07  -0.0000003373  

  Covariates
        sex_code    -5.013024    1.707659   0.003329    0.0000000000  
         foo_bmi     0.309039    0.163770   0.059156    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1851.793200

=================================================================
     VARIANCE-COVARIANCE MATRIX foo_bmi with test covariates
=================================================================

--------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_bmi    
--------------------------------------------------------------------------------
  Random           408.120879   408.120879     -0.000152  -7.16e-05   1.47e-06  
  Total variance   408.120879   408.120879     -0.000152  -7.16e-05   1.47e-06  
  Intercept         -0.000152    -0.000152      0.685701   2.66e-11  -5.46e-13  
  sex_code          -7.16e-05    -7.16e-05      2.66e-11   2.916098  -0.059802  
  foo_bmi            1.47e-06     1.47e-06     -5.46e-13  -0.059802   0.026821  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_bmi without test covariates  -1853.566375  
  H1 ln likelihood foo_bmi with test covariates     -1851.793200  
                                                                  
  2 * |H0 - H1|                                         3.546350  
  Degrees of freedom                                           1  
  P-value                                               0.059677  

=================================

     Model 'foo_sbpd_rand10'

=================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

---------------------------------------------------------------------
  Name             Mean         Std. dev.   Min         Max          
---------------------------------------------------------------------
  sex_code            0.559908    0.496398    0.000000     1.000000  
  foo_sbpd_rand10   132.181106   17.454032   84.900000   191.000000  

======================================================================
     MAXIMIZATION RESULTS foo_sbpd_rand10 without test covariates
======================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036047   20.367758  < 1.00e-07   0.0000000103  

  Other parameters
  Total variance   300.036047   20.367758  < 1.00e-07   0.0000000576  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323939    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

============================================================================
     VARIANCE-COVARIANCE MATRIX foo_sbpd_rand10 without test covariates
============================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845585   414.845585     -0.000153  -4.74e-05  
  Total variance   414.845585   414.845585     -0.000153  -4.74e-05  
  Intercept         -0.000153    -0.000153      0.691327   1.75e-11  
  sex_code          -4.74e-05    -4.74e-05      1.75e-11   2.805586  

===================================================================
     MAXIMIZATION RESULTS foo_sbpd_rand10 with test covariates
===================================================================

-------------------------------------------------------------------------
  Parameter        Estimate     S.E.         P-value      Deriv          
-------------------------------------------------------------------------
  Variance components
           Random     1.00e-07          Ind. func. fixed @ bnd           

  Other parameters
   Total variance     1.00e-07  Unavailable  Unavailable  -0.0003209074  

        Intercept   131.180995   1.52e-05    < 1.00e-07    0.0001857145  

  Covariates
         sex_code    -4.56e-06   3.08e-05     0.882276     0.0000000000  
  foo_sbpd_rand10     0.999999   8.76e-07    < 1.00e-07    0.0000000000  
-------------------------------------------------------------------------

Final ln likelihood:  3071.793415

=========================================================================
     VARIANCE-COVARIANCE MATRIX foo_sbpd_rand10 with test covariates
=========================================================================

-------------------------------------------------------------------------------------
                   Random     Total variance  Intercept  sex_code   foo_sbpd_rand10  
-------------------------------------------------------------------------------------
  Random            0.000000   0.000000        0.000000   0.000000   0.000000        
  Total variance    0.000000   0.000000        0.000000   0.000000   0.000000        
  Intercept         0.000000   0.000000        2.30e-10   3.10e-19   1.01e-21        
  sex_code          0.000000   0.000000        3.10e-19   9.49e-10   3.32e-12        
  foo_sbpd_rand10   0.000000   0.000000        1.01e-21   3.32e-12   7.68e-13        

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_sbpd_rand10 without test covariates  -1853.566375  
  H1 ln likelihood foo_sbpd_rand10 with test covariates      3071.793415  
                                                                          
  2 * |H0 - H1|                                              9850.719580  
  Degrees of freedom                                                   1  
  P-value                                                       1.000000  

=============================

     Model 'foo_na_u24c'

=============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   423  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

----------------------------------------------------------------
  Name         Mean         Std. dev.   Min        Max          
----------------------------------------------------------------
  sex_code        0.555294    0.496933   0.000000     1.000000  
  foo_na_u24c   106.973341   54.015420   4.130000   329.110000  

==================================================================
     MAXIMIZATION RESULTS foo_na_u24c without test covariates
==================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   297.732691   20.424276  < 1.00e-07   0.0000005975  

  Other parameters
  Total variance   297.732691   20.424276  < 1.00e-07   0.0001577998  

       Intercept   131.133772    0.836987  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.010429    1.684306   0.017263    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1813.490721

========================================================================
     VARIANCE-COVARIANCE MATRIX foo_na_u24c without test covariates
========================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           417.151056   417.151056     -0.000155  -1.04e-05  
  Total variance   417.151056   417.151056     -0.000155  -1.04e-05  
  Intercept         -0.000155    -0.000155      0.700548   3.88e-12  
  sex_code          -1.04e-05    -1.04e-05      3.88e-12   2.836885  

===============================================================
     MAXIMIZATION RESULTS foo_na_u24c with test covariates
===============================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   294.751899   20.219795  < 1.00e-07   0.0000000069  

  Other parameters
  Total variance   294.751899   20.219795  < 1.00e-07  -0.0000000113  

       Intercept   131.133772    0.832787  < 1.00e-07  -0.0000011692  

  Covariates
        sex_code    -3.781232    1.679495   0.024360    0.0000000000  
     foo_na_u24c     0.032032    0.015451   0.038158    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1811.352533

=====================================================================
     VARIANCE-COVARIANCE MATRIX foo_na_u24c with test covariates
=====================================================================

----------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_na_u24c  
----------------------------------------------------------------------------------
  Random           408.840122   408.840122     -0.000153   0.000000   0.000000    
  Total variance   408.840122   408.840122     -0.000153   0.000000   0.000000    
  Intercept         -0.000153    -0.000153      0.693534   0.000000   0.000000    
  sex_code           0.000000     0.000000      0.000000   2.820703   0.001708    
  foo_na_u24c        0.000000     0.000000      0.000000   0.001708   0.000239    

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_na_u24c without test covariates  -1813.490721  
  H1 ln likelihood foo_na_u24c with test covariates     -1811.352533  
                                                                      
  2 * |H0 - H1|                                             4.276377  
  Degrees of freedom                                               1  
  P-value                                                   0.038646  

============================

     Model 'foo_k_u24c'

============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   423  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

--------------------------------------------------------------
  Name        Mean        Std. dev.   Min        Max          
--------------------------------------------------------------
  sex_code      0.555294    0.496933   0.000000     1.000000  
  foo_k_u24c   45.255247   19.190001   4.920000   188.790000  

=================================================================
     MAXIMIZATION RESULTS foo_k_u24c without test covariates
=================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   297.732691   20.424276  < 1.00e-07   0.0000005975  

  Other parameters
  Total variance   297.732691   20.424276  < 1.00e-07   0.0001577998  

       Intercept   131.133772    0.836987  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.010429    1.684306   0.017263    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1813.490721

=======================================================================
     VARIANCE-COVARIANCE MATRIX foo_k_u24c without test covariates
=======================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           417.151056   417.151056     -0.000155  -1.04e-05  
  Total variance   417.151056   417.151056     -0.000155  -1.04e-05  
  Intercept         -0.000155    -0.000155      0.700548   3.88e-12  
  sex_code          -1.04e-05    -1.04e-05      3.88e-12   2.836885  

==============================================================
     MAXIMIZATION RESULTS foo_k_u24c with test covariates
==============================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   294.560146   20.206638  < 1.00e-07   0.0000000673  

  Other parameters
  Total variance   294.560146   20.206638  < 1.00e-07  -0.0000001450  

       Intercept   131.133772    0.832516  < 1.00e-07  -0.0000446817  

  Covariates
        sex_code    -3.722320    1.680710   0.026779    0.0000000000  
      foo_k_u24c     0.093118    0.043523   0.032393    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1811.214262

====================================================================
     VARIANCE-COVARIANCE MATRIX foo_k_u24c with test covariates
====================================================================

---------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_k_u24c  
---------------------------------------------------------------------------------
  Random           408.308206   408.308206     -0.000153   5.96e-05   2.20e-06   
  Total variance   408.308206   408.308206     -0.000153   5.96e-05   2.20e-06   
  Intercept         -0.000153    -0.000153      0.693083  -2.24e-11  -8.26e-13   
  sex_code           5.96e-05     5.96e-05     -2.24e-11   2.824785   0.005860   
  foo_k_u24c         2.20e-06     2.20e-06     -8.26e-13   0.005860   0.001894   

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_k_u24c without test covariates  -1813.490721  
  H1 ln likelihood foo_k_u24c with test covariates     -1811.214262  
                                                                     
  2 * |H0 - H1|                                            4.552918  
  Degrees of freedom                                              1  
  P-value                                                  0.032863  

==============================

     Model 'foo_SEX_CODE'

==============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

------------------------------------------------------------
  Name          Mean       Std. dev.  Min        Max        
------------------------------------------------------------
  sex_code       0.559908   0.496398   0.000000   1.000000  
  foo_SEX_CODE   1.559908   0.496398   1.000000   2.000000  

===================================================================
     MAXIMIZATION RESULTS foo_SEX_CODE without test covariates
===================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036047   20.367758  < 1.00e-07   0.0000000103  

  Other parameters
  Total variance   300.036047   20.367758  < 1.00e-07   0.0000000576  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323939    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

=========================================================================
     VARIANCE-COVARIANCE MATRIX foo_SEX_CODE without test covariates
=========================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845585   414.845585     -0.000153  -4.74e-05  
  Total variance   414.845585   414.845585     -0.000153  -4.74e-05  
  Intercept         -0.000153    -0.000153      0.691327   1.75e-11  
  sex_code          -4.74e-05    -4.74e-05      1.75e-11   2.805586  

================================================================
     MAXIMIZATION RESULTS foo_SEX_CODE with test covariates
================================================================

-----------------------------------------------------------------------
  Parameter       Estimate     S.E.         P-value     Deriv          
-----------------------------------------------------------------------
  Variance components
          Random   300.036300    20.367790  < 1.00e-07  -0.0000000029  

  Other parameters
  Total variance   300.036300    20.367790  < 1.00e-07   0.0000000072  

       Intercept   131.181106     0.831461  < 1.00e-07   0.0000002697  

  Covariates
        sex_code    -4.323905   248.342215   0.986109    0.0000000000  
    foo_SEX_CODE     3.00e-11   248.336713   1.000000    0.0000000000  
-----------------------------------------------------------------------

Final ln likelihood: -1853.566375

======================================================================
     VARIANCE-COVARIANCE MATRIX foo_SEX_CODE with test covariates
======================================================================

----------------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code       foo_SEX_CODE   
----------------------------------------------------------------------------------------
  Random           414.846880   414.846880      0.000000       0.000000       0.000000  
  Total variance   414.846880   414.846880      0.000000       0.000000       0.000000  
  Intercept          0.000000     0.000000      0.691328       0.000000       0.000000  
  sex_code           0.000000     0.000000      0.000000   61673.855770  -61671.086504  
  foo_SEX_CODE       0.000000     0.000000      0.000000  -61671.086504   61671.122824  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_SEX_CODE without test covariates  -1853.566375  
  H1 ln likelihood foo_SEX_CODE with test covariates     -1853.566375  
                                                                       
  2 * |H0 - H1|                                              1.83e-08  
  Degrees of freedom                                                1  
  P-value                                                    0.999892  

========================================

     Model 'foo_FAMILIAL_INDICATOR'

========================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

----------------------------------------------------------------------
  Name                    Mean       Std. dev.  Min        Max        
----------------------------------------------------------------------
  sex_code                 0.559908   0.496398   0.000000   1.000000  
  foo_FAMILIAL_INDICATOR   1.995392   0.067728   1.000000   2.000000  

=============================================================================
     MAXIMIZATION RESULTS foo_FAMILIAL_INDICATOR without test covariates
=============================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036047   20.367758  < 1.00e-07   0.0000000103  

  Other parameters
  Total variance   300.036047   20.367758  < 1.00e-07   0.0000000576  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323939    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

===================================================================================
     VARIANCE-COVARIANCE MATRIX foo_FAMILIAL_INDICATOR without test covariates
===================================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845585   414.845585     -0.000153  -4.74e-05  
  Total variance   414.845585   414.845585     -0.000153  -4.74e-05  
  Intercept         -0.000153    -0.000153      0.691327   1.75e-11  
  sex_code          -4.74e-05    -4.74e-05      1.75e-11   2.805586  

==========================================================================
     MAXIMIZATION RESULTS foo_FAMILIAL_INDICATOR with test covariates
==========================================================================

------------------------------------------------------------------------------
  Parameter               Estimate     S.E.        P-value     Deriv          
------------------------------------------------------------------------------
  Variance components
                  Random   300.035877   20.367761  < 1.00e-07  -0.0000000094  

  Other parameters
          Total variance   300.035877   20.367761  < 1.00e-07   0.0000000005  

               Intercept   131.181106    0.831461  < 1.00e-07   0.0000001349  

  Covariates
                sex_code    -4.327102    1.679942   0.010002    0.0000000000  
  foo_FAMILIAL_INDICATOR     0.305280   12.312722   0.980219    0.0000000000  
------------------------------------------------------------------------------

Final ln likelihood: -1853.566067

================================================================================
     VARIANCE-COVARIANCE MATRIX foo_FAMILIAL_INDICATOR with test covariates
================================================================================

-----------------------------------------------------------------------------------------------------
                          Random       Total variance  Intercept  sex_code   foo_FAMILIAL_INDICATOR  
-----------------------------------------------------------------------------------------------------
  Random                   414.845670   414.845670      0.000000   0.000000     0.000000             
  Total variance           414.845670   414.845670      0.000000   0.000000     0.000000             
  Intercept                  0.000000     0.000000      0.691327   0.000000     0.000000             
  sex_code                   0.000000     0.000000      0.000000   2.822207    -1.587473             
  foo_FAMILIAL_INDICATOR     0.000000     0.000000      0.000000  -1.587473   151.603111             

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_FAMILIAL_INDICATOR without test covariates  -1853.566375  
  H1 ln likelihood foo_FAMILIAL_INDICATOR with test covariates     -1853.566067  
                                                                                 
  2 * |H0 - H1|                                                        0.000615  
  Degrees of freedom                                                          1  
  P-value                                                              0.980219  

=======================================

     Model 'foo_FOUNDER_INDICATOR'

=======================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

---------------------------------------------------------------------
  Name                   Mean       Std. dev.  Min        Max        
---------------------------------------------------------------------
  sex_code                0.559908   0.496398   0.000000   1.000000  
  foo_FOUNDER_INDICATOR   1.050691   0.219366   1.000000   2.000000  

============================================================================
     MAXIMIZATION RESULTS foo_FOUNDER_INDICATOR without test covariates
============================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036047   20.367758  < 1.00e-07   0.0000000103  

  Other parameters
  Total variance   300.036047   20.367758  < 1.00e-07   0.0000000576  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323939    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==================================================================================
     VARIANCE-COVARIANCE MATRIX foo_FOUNDER_INDICATOR without test covariates
==================================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845585   414.845585     -0.000153  -4.74e-05  
  Total variance   414.845585   414.845585     -0.000153  -4.74e-05  
  Intercept         -0.000153    -0.000153      0.691327   1.75e-11  
  sex_code          -4.74e-05    -4.74e-05      1.75e-11   2.805586  

=========================================================================
     MAXIMIZATION RESULTS foo_FOUNDER_INDICATOR with test covariates
=========================================================================

-----------------------------------------------------------------------------
  Parameter              Estimate     S.E.        P-value     Deriv          
-----------------------------------------------------------------------------
  Variance components
                 Random   298.920550   20.291915  < 1.00e-07   0.0000042051  

  Other parameters
         Total variance   298.920550   20.291915  < 1.00e-07   0.0000007752  

              Intercept   131.180995    0.829914  < 1.00e-07   0.0000245346  

  Covariates
               sex_code    -4.354590    1.672046   0.009205    0.0000000000  
  foo_FOUNDER_INDICATOR     4.811342    3.783627   0.203508    0.0000000000  
-----------------------------------------------------------------------------

Final ln likelihood: -1852.759343

===============================================================================
     VARIANCE-COVARIANCE MATRIX foo_FOUNDER_INDICATOR with test covariates
===============================================================================

---------------------------------------------------------------------------------------------------
                         Random       Total variance  Intercept  sex_code   foo_FOUNDER_INDICATOR  
---------------------------------------------------------------------------------------------------
  Random                  411.761831   411.761831     -0.000153   7.84e-07   -0.000123             
  Total variance          411.761831   411.761831     -0.000153   7.84e-07   -0.000123             
  Intercept                -0.000153    -0.000153      0.688757  -2.91e-13    4.57e-11             
  sex_code                  7.84e-07     7.84e-07     -2.91e-13   2.795736   -0.091298             
  foo_FOUNDER_INDICATOR    -0.000123    -0.000123      4.57e-11  -0.091298   14.315831             

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_FOUNDER_INDICATOR without test covariates  -1853.566375  
  H1 ln likelihood foo_FOUNDER_INDICATOR with test covariates     -1852.759343  
                                                                                
  2 * |H0 - H1|                                                       1.614064  
  Degrees of freedom                                                         1  
  P-value                                                             0.203921  

===================================

     Model 'foo_PEDIGREE_SIZE'

===================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

-------------------------------------------------------------------
  Name               Mean        Std. dev.  Min        Max         
-------------------------------------------------------------------
  sex_code             0.559908   0.496398   0.000000    1.000000  
  foo_PEDIGREE_SIZE   10.523041   3.699629   2.000000   21.000000  

========================================================================
     MAXIMIZATION RESULTS foo_PEDIGREE_SIZE without test covariates
========================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036047   20.367758  < 1.00e-07   0.0000000103  

  Other parameters
  Total variance   300.036047   20.367758  < 1.00e-07   0.0000000576  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323939    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==============================================================================
     VARIANCE-COVARIANCE MATRIX foo_PEDIGREE_SIZE without test covariates
==============================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845585   414.845585     -0.000153  -4.74e-05  
  Total variance   414.845585   414.845585     -0.000153  -4.74e-05  
  Intercept         -0.000153    -0.000153      0.691327   1.75e-11  
  sex_code          -4.74e-05    -4.74e-05      1.75e-11   2.805586  

=====================================================================
     MAXIMIZATION RESULTS foo_PEDIGREE_SIZE with test covariates
=====================================================================

-------------------------------------------------------------------------
  Parameter          Estimate     S.E.        P-value     Deriv          
-------------------------------------------------------------------------
  Variance components
             Random   298.703476   20.277294  < 1.00e-07   0.0000000194  

  Other parameters
     Total variance   298.703476   20.277294  < 1.00e-07   0.0000000401  

          Intercept   131.180995    0.829612  < 1.00e-07  -0.0000558375  

  Covariates
           sex_code    -4.166278    1.675099   0.012876    0.0000000000  
  foo_PEDIGREE_SIZE    -0.312727    0.224757   0.164103    0.0000000000  
-------------------------------------------------------------------------

Final ln likelihood: -1852.600463

===========================================================================
     VARIANCE-COVARIANCE MATRIX foo_PEDIGREE_SIZE with test covariates
===========================================================================

-------------------------------------------------------------------------------------------
                     Random       Total variance  Intercept  sex_code   foo_PEDIGREE_SIZE  
-------------------------------------------------------------------------------------------
  Random              411.168649   411.168649     -0.000152   4.63e-06   1.37e-05          
  Total variance      411.168649   411.168649     -0.000152   4.63e-06   1.37e-05          
  Intercept            -0.000152    -0.000152      0.688257  -1.71e-12  -5.09e-12          
  sex_code              4.63e-06     4.63e-06     -1.71e-12   2.805956  -0.025461          
  foo_PEDIGREE_SIZE     1.37e-05     1.37e-05     -5.09e-12  -0.025461   0.050516          

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_PEDIGREE_SIZE without test covariates  -1853.566375  
  H1 ln likelihood foo_PEDIGREE_SIZE with test covariates     -1852.600463  
                                                                            
  2 * |H0 - H1|                                                   1.931824  
  Degrees of freedom                                                     1  
  P-value                                                         0.164559  

