=================

     Results

=================

Note: P-values for variance components and proportions are one-sided.  All others are two-sided.
The null hypothesis for transformation parameters is 'no transformation.'


==============================
     Analysis description
==============================

  Title                        assoc                         
  Primary Trait                sbpd_rand10 (Quantitative)    
  Allow averaging              Disabled                      
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  

======================================
     Transformation configuration
======================================



Note: No transformation applied.

====================================

     Model 'FAMILIAL_INDICATOR'

====================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

------------------------------------------------------------------
  Name                Mean       Std. dev.  Min        Max        
------------------------------------------------------------------
  sex_code             0.559908   0.496398   0.000000   1.000000  
  FAMILIAL_INDICATOR   0.995392   0.067728   0.000000   1.000000  

=========================================================================
     MAXIMIZATION RESULTS FAMILIAL_INDICATOR without test covariates
=========================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036058   20.367757  < 1.00e-07  -0.0000000450  

  Other parameters
  Total variance   300.036058   20.367757  < 1.00e-07  -0.0000000565  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323915    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

===============================================================================
     VARIANCE-COVARIANCE MATRIX FAMILIAL_INDICATOR without test covariates
===============================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845507   414.845507     -0.000153  -1.12e-05  
  Total variance   414.845507   414.845507     -0.000153  -1.12e-05  
  Intercept         -0.000153    -0.000153      0.691327   4.14e-12  
  sex_code          -1.12e-05    -1.12e-05      4.14e-12   2.805586  

======================================================================
     MAXIMIZATION RESULTS FAMILIAL_INDICATOR with test covariates
======================================================================

--------------------------------------------------------------------------
  Parameter           Estimate     S.E.        P-value     Deriv          
--------------------------------------------------------------------------
  Variance components
              Random   300.035877   20.367761  < 1.00e-07  -0.0000000092  

  Other parameters
      Total variance   300.035877   20.367761  < 1.00e-07   0.0000000087  

           Intercept   131.181106    0.831461  < 1.00e-07   0.0000022928  

  Covariates
            sex_code    -4.327102    1.679943   0.010002    0.0000000000  
  FAMILIAL_INDICATOR     0.305280   12.312570   0.980219    0.0000000000  
--------------------------------------------------------------------------

Final ln likelihood: -1853.566067

============================================================================
     VARIANCE-COVARIANCE MATRIX FAMILIAL_INDICATOR with test covariates
============================================================================

---------------------------------------------------------------------------------------------
                      Random       Total variance  Intercept  sex_code   FAMILIAL_INDICATOR  
---------------------------------------------------------------------------------------------
  Random               414.845675   414.845675      0.000000   0.000000     0.000000         
  Total variance       414.845675   414.845675      0.000000   0.000000     0.000000         
  Intercept              0.000000     0.000000      0.691327   0.000000     0.000000         
  sex_code               0.000000     0.000000      0.000000   2.822207    -1.587448         
  FAMILIAL_INDICATOR     0.000000     0.000000      0.000000  -1.587448   151.599384         

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood FAMILIAL_INDICATOR without test covariates  -1853.566375  
  H1 ln likelihood FAMILIAL_INDICATOR with test covariates     -1853.566067  
                                                                             
  2 * |H0 - H1|                                                    0.000615  
  Degrees of freedom                                                      1  
  P-value                                                          0.980219  

===================================

     Model 'FOUNDER_INDICATOR'

===================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

-----------------------------------------------------------------
  Name               Mean       Std. dev.  Min        Max        
-----------------------------------------------------------------
  sex_code            0.559908   0.496398   0.000000   1.000000  
  FOUNDER_INDICATOR   0.050691   0.219366   0.000000   1.000000  

========================================================================
     MAXIMIZATION RESULTS FOUNDER_INDICATOR without test covariates
========================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036058   20.367757  < 1.00e-07  -0.0000000450  

  Other parameters
  Total variance   300.036058   20.367757  < 1.00e-07  -0.0000000565  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323915    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==============================================================================
     VARIANCE-COVARIANCE MATRIX FOUNDER_INDICATOR without test covariates
==============================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845507   414.845507     -0.000153  -1.12e-05  
  Total variance   414.845507   414.845507     -0.000153  -1.12e-05  
  Intercept         -0.000153    -0.000153      0.691327   4.14e-12  
  sex_code          -1.12e-05    -1.12e-05      4.14e-12   2.805586  

=====================================================================
     MAXIMIZATION RESULTS FOUNDER_INDICATOR with test covariates
=====================================================================

-------------------------------------------------------------------------
  Parameter          Estimate     S.E.        P-value     Deriv          
-------------------------------------------------------------------------
  Variance components
             Random   298.924000   20.292385  < 1.00e-07  -0.0000042132  

  Other parameters
     Total variance   298.924000   20.292385  < 1.00e-07  -0.0000001450  

          Intercept   131.180996    0.829919  < 1.00e-07  -0.0000461281  

  Covariates
           sex_code    -4.354616    1.672055   0.009205    0.0000000000  
  FOUNDER_INDICATOR     4.811565    3.783639   0.203488    0.0000000000  
-------------------------------------------------------------------------

Final ln likelihood: -1852.759343

===========================================================================
     VARIANCE-COVARIANCE MATRIX FOUNDER_INDICATOR with test covariates
===========================================================================

-------------------------------------------------------------------------------------------
                     Random       Total variance  Intercept  sex_code   FOUNDER_INDICATOR  
-------------------------------------------------------------------------------------------
  Random              411.780872   411.780872     -0.000152  -3.72e-05    0.000195         
  Total variance      411.780872   411.780872     -0.000152  -3.72e-05    0.000195         
  Intercept            -0.000152    -0.000152      0.688765   1.37e-11   -7.20e-11         
  sex_code             -3.72e-05    -3.72e-05      1.37e-11   2.795767   -0.091298         
  FOUNDER_INDICATOR     0.000195     0.000195     -7.20e-11  -0.091298   14.315928         

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood FOUNDER_INDICATOR without test covariates  -1853.566375  
  H1 ln likelihood FOUNDER_INDICATOR with test covariates     -1852.759343  
                                                                            
  2 * |H0 - H1|                                                   1.614064  
  Degrees of freedom                                                     1  
  P-value                                                         0.203921  

===============================

     Model 'PEDIGREE_SIZE'

===============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

--------------------------------------------------------------
  Name           Mean       Std. dev.  Min        Max         
--------------------------------------------------------------
  sex_code        0.559908   0.496398   0.000000    1.000000  
  PEDIGREE_SIZE   9.523041   3.699629   1.000000   20.000000  

====================================================================
     MAXIMIZATION RESULTS PEDIGREE_SIZE without test covariates
====================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036058   20.367757  < 1.00e-07  -0.0000000450  

  Other parameters
  Total variance   300.036058   20.367757  < 1.00e-07  -0.0000000565  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323915    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==========================================================================
     VARIANCE-COVARIANCE MATRIX PEDIGREE_SIZE without test covariates
==========================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845507   414.845507     -0.000153  -1.12e-05  
  Total variance   414.845507   414.845507     -0.000153  -1.12e-05  
  Intercept         -0.000153    -0.000153      0.691327   4.14e-12  
  sex_code          -1.12e-05    -1.12e-05      4.14e-12   2.805586  

=================================================================
     MAXIMIZATION RESULTS PEDIGREE_SIZE with test covariates
=================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   298.703466   20.277293  < 1.00e-07   0.0000000411  

  Other parameters
  Total variance   298.703466   20.277293  < 1.00e-07   0.0000000720  

       Intercept   131.180995    0.829612  < 1.00e-07   0.0000194666  

  Covariates
        sex_code    -4.166390    1.675099   0.012874    0.0000000000  
   PEDIGREE_SIZE    -0.312740    0.224756   0.164085    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1852.600463

=======================================================================
     VARIANCE-COVARIANCE MATRIX PEDIGREE_SIZE with test covariates
=======================================================================

------------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   PEDIGREE_SIZE  
------------------------------------------------------------------------------------
  Random           411.168614   411.168614     -0.000152  -0.000153  -3.80e-06      
  Total variance   411.168614   411.168614     -0.000152  -0.000153  -3.80e-06      
  Intercept         -0.000152    -0.000152      0.688257   5.65e-11   1.41e-12      
  sex_code          -0.000153    -0.000153      5.65e-11   2.805958  -0.025460      
  PEDIGREE_SIZE     -3.80e-06    -3.80e-06      1.41e-12  -0.025460   0.050515      

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood PEDIGREE_SIZE without test covariates  -1853.566375  
  H1 ln likelihood PEDIGREE_SIZE with test covariates     -1852.600463  
                                                                        
  2 * |H0 - H1|                                               1.931824  
  Degrees of freedom                                                 1  
  P-value                                                     0.164559  

===============================

     Model 'foo_selection'

===============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

-------------------------------------------------------------
  Name           Mean       Std. dev.  Min        Max        
-------------------------------------------------------------
  sex_code        0.559908   0.496398   0.000000   1.000000  
  foo_selection   1.615207   0.486546   1.000000   2.000000  

====================================================================
     MAXIMIZATION RESULTS foo_selection without test covariates
====================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036058   20.367757  < 1.00e-07  -0.0000000450  

  Other parameters
  Total variance   300.036058   20.367757  < 1.00e-07  -0.0000000565  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323915    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==========================================================================
     VARIANCE-COVARIANCE MATRIX foo_selection without test covariates
==========================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845507   414.845507     -0.000153  -1.12e-05  
  Total variance   414.845507   414.845507     -0.000153  -1.12e-05  
  Intercept         -0.000153    -0.000153      0.691327   4.14e-12  
  sex_code          -1.12e-05    -1.12e-05      4.14e-12   2.805586  

=================================================================
     MAXIMIZATION RESULTS foo_selection with test covariates
=================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   226.207938   15.355986  < 1.00e-07  -0.0000002629  

  Other parameters
  Total variance   226.207938   15.355986  < 1.00e-07   0.0000143413  

       Intercept   131.180988    0.721953  < 1.00e-07   0.0000024596  

  Covariates
        sex_code    -5.400102    1.457192   0.000211    0.0000000000  
   foo_selection    17.693936    1.486698  < 1.00e-07   0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1792.275111

=======================================================================
     VARIANCE-COVARIANCE MATRIX foo_selection with test covariates
=======================================================================

------------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_selection  
------------------------------------------------------------------------------------
  Random           235.806296   235.806296     -0.000123   1.07e-05  -1.93e-05      
  Total variance   235.806296   235.806296     -0.000123   1.07e-05  -1.93e-05      
  Intercept         -0.000123    -0.000123      0.521216  -5.60e-12   1.01e-11      
  sex_code           1.07e-05     1.07e-05     -5.60e-12   2.123408  -0.134436      
  foo_selection     -1.93e-05    -1.93e-05      1.01e-11  -0.134436   2.210271      

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_selection without test covariates  -1853.566375  
  H1 ln likelihood foo_selection with test covariates     -1792.275111  
                                                                        
  2 * |H0 - H1|                                             122.582527  
  Degrees of freedom                                                 1  
  P-value                                                     1.72e-28  

=========================

     Model 'foo_age'

=========================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

------------------------------------------------------------
  Name      Mean        Std. dev.   Min         Max         
------------------------------------------------------------
  sex_code    0.559908    0.496398    0.000000    1.000000  
  foo_age    47.456221   12.045581   19.000000   84.000000  

==============================================================
     MAXIMIZATION RESULTS foo_age without test covariates
==============================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036058   20.367757  < 1.00e-07  -0.0000000450  

  Other parameters
  Total variance   300.036058   20.367757  < 1.00e-07  -0.0000000565  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323915    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

====================================================================
     VARIANCE-COVARIANCE MATRIX foo_age without test covariates
====================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845507   414.845507     -0.000153  -1.12e-05  
  Total variance   414.845507   414.845507     -0.000153  -1.12e-05  
  Intercept         -0.000153    -0.000153      0.691327   4.14e-12  
  sex_code          -1.12e-05    -1.12e-05      4.14e-12   2.805586  

===========================================================
     MAXIMIZATION RESULTS foo_age with test covariates
===========================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   273.728871   18.581913  < 1.00e-07  -0.0000000089  

  Other parameters
  Total variance   273.728871   18.581913  < 1.00e-07   0.0000002313  

       Intercept   131.180995    0.794174  < 1.00e-07  -0.0000003401  

  Covariates
        sex_code    -5.368961    1.608035   0.000841    0.0000000000  
         foo_age     0.427976    0.066267  < 1.00e-07   0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1833.653463

=================================================================
     VARIANCE-COVARIANCE MATRIX foo_age with test covariates
=================================================================

--------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_age    
--------------------------------------------------------------------------------
  Random           345.287497   345.287497     -0.000140   1.06e-06  -4.33e-07  
  Total variance   345.287497   345.287497     -0.000140   1.06e-06  -4.33e-07  
  Intercept         -0.000140    -0.000140      0.630712  -4.28e-13   1.75e-13  
  sex_code           1.06e-06     1.06e-06     -4.28e-13   2.585776  -0.010723  
  foo_age           -4.33e-07    -4.33e-07      1.75e-13  -0.010723   0.004391  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_age without test covariates  -1853.566375  
  H1 ln likelihood foo_age with test covariates     -1833.653463  
                                                                  
  2 * |H0 - H1|                                        39.825823  
  Degrees of freedom                                           1  
  P-value                                               2.78e-10  

=========================

     Model 'foo_bmi'

=========================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

-----------------------------------------------------------
  Name      Mean        Std. dev.  Min         Max         
-----------------------------------------------------------
  sex_code    0.559908   0.496398    0.000000    1.000000  
  foo_bmi    28.584562   5.176045   16.100000   48.400000  

==============================================================
     MAXIMIZATION RESULTS foo_bmi without test covariates
==============================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036058   20.367757  < 1.00e-07  -0.0000000450  

  Other parameters
  Total variance   300.036058   20.367757  < 1.00e-07  -0.0000000565  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323915    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

====================================================================
     VARIANCE-COVARIANCE MATRIX foo_bmi without test covariates
====================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845507   414.845507     -0.000153  -1.12e-05  
  Total variance   414.845507   414.845507     -0.000153  -1.12e-05  
  Intercept         -0.000153    -0.000153      0.691327   4.14e-12  
  sex_code          -1.12e-05    -1.12e-05      4.14e-12   2.805586  

===========================================================
     MAXIMIZATION RESULTS foo_bmi with test covariates
===========================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   297.593980   20.201955  < 1.00e-07   0.0000009182  

  Other parameters
  Total variance   297.593980   20.201955  < 1.00e-07   0.0000021940  

       Intercept   131.180994    0.828070  < 1.00e-07  -0.0000020236  

  Covariates
        sex_code    -5.012989    1.707657   0.003329    0.0000000000  
         foo_bmi     0.309038    0.163769   0.059156    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1851.793200

=================================================================
     VARIANCE-COVARIANCE MATRIX foo_bmi with test covariates
=================================================================

--------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_bmi    
--------------------------------------------------------------------------------
  Random           408.118998   408.118998     -0.000154  -2.18e-05   4.47e-07  
  Total variance   408.118998   408.118998     -0.000154  -2.18e-05   4.47e-07  
  Intercept         -0.000154    -0.000154      0.685700   8.21e-12  -1.68e-13  
  sex_code          -2.18e-05    -2.18e-05      8.21e-12   2.916092  -0.059802  
  foo_bmi            4.47e-07     4.47e-07     -1.68e-13  -0.059802   0.026820  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_bmi without test covariates  -1853.566375  
  H1 ln likelihood foo_bmi with test covariates     -1851.793200  
                                                                  
  2 * |H0 - H1|                                         3.546350  
  Degrees of freedom                                           1  
  P-value                                               0.059677  

=================================

     Model 'foo_sbpd_rand10'

=================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

---------------------------------------------------------------------
  Name             Mean         Std. dev.   Min         Max          
---------------------------------------------------------------------
  sex_code            0.559908    0.496398    0.000000     1.000000  
  foo_sbpd_rand10   132.181106   17.454032   84.900000   191.000000  

======================================================================
     MAXIMIZATION RESULTS foo_sbpd_rand10 without test covariates
======================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036058   20.367757  < 1.00e-07  -0.0000000450  

  Other parameters
  Total variance   300.036058   20.367757  < 1.00e-07  -0.0000000565  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323915    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

============================================================================
     VARIANCE-COVARIANCE MATRIX foo_sbpd_rand10 without test covariates
============================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845507   414.845507     -0.000153  -1.12e-05  
  Total variance   414.845507   414.845507     -0.000153  -1.12e-05  
  Intercept         -0.000153    -0.000153      0.691327   4.14e-12  
  sex_code          -1.12e-05    -1.12e-05      4.14e-12   2.805586  

===================================================================
     MAXIMIZATION RESULTS foo_sbpd_rand10 with test covariates
===================================================================

-------------------------------------------------------------------------
  Parameter        Estimate     S.E.         P-value      Deriv          
-------------------------------------------------------------------------
  Variance components
           Random     1.00e-07          Ind. func. fixed @ bnd           

  Other parameters
   Total variance     1.00e-07  Unavailable  Unavailable  -0.0000798768  

        Intercept   131.180995   1.52e-05    < 1.00e-07   -0.0000900523  

  Covariates
         sex_code    -4.56e-06   3.08e-05     0.882279     0.0000000000  
  foo_sbpd_rand10     0.999999   8.76e-07    < 1.00e-07    0.0000000000  
-------------------------------------------------------------------------

Final ln likelihood:  3071.793416

=========================================================================
     VARIANCE-COVARIANCE MATRIX foo_sbpd_rand10 with test covariates
=========================================================================

-------------------------------------------------------------------------------------
                   Random     Total variance  Intercept  sex_code   foo_sbpd_rand10  
-------------------------------------------------------------------------------------
  Random            0.000000   0.000000        0.000000   0.000000   0.000000        
  Total variance    0.000000   0.000000        0.000000   0.000000   0.000000        
  Intercept         0.000000   0.000000        2.30e-10  -4.14e-18  -1.45e-20        
  sex_code          0.000000   0.000000       -4.14e-18   9.49e-10   3.32e-12        
  foo_sbpd_rand10   0.000000   0.000000       -1.45e-20   3.32e-12   7.68e-13        

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_sbpd_rand10 without test covariates  -1853.566375  
  H1 ln likelihood foo_sbpd_rand10 with test covariates      3071.793416  
                                                                          
  2 * |H0 - H1|                                              9850.719581  
  Degrees of freedom                                                   1  
  P-value                                                       1.000000  

=============================

     Model 'foo_na_u24c'

=============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   423  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

----------------------------------------------------------------
  Name         Mean         Std. dev.   Min        Max          
----------------------------------------------------------------
  sex_code        0.555294    0.496933   0.000000     1.000000  
  foo_na_u24c   106.973341   54.015420   4.130000   329.110000  

==================================================================
     MAXIMIZATION RESULTS foo_na_u24c without test covariates
==================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   297.732700   20.424277  < 1.00e-07  -0.0000000349  

  Other parameters
  Total variance   297.732700   20.424277  < 1.00e-07  -0.0000000031  

       Intercept   131.133772    0.836987  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.010442    1.684304   0.017263    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1813.490721

========================================================================
     VARIANCE-COVARIANCE MATRIX foo_na_u24c without test covariates
========================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           417.151086   417.151086     -0.000155  -2.83e-05  
  Total variance   417.151086   417.151086     -0.000155  -2.83e-05  
  Intercept         -0.000155    -0.000155      0.700548   1.05e-11  
  sex_code          -2.83e-05    -2.83e-05      1.05e-11   2.836880  

===============================================================
     MAXIMIZATION RESULTS foo_na_u24c with test covariates
===============================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   294.751917   20.219796  < 1.00e-07  -0.0000000384  

  Other parameters
  Total variance   294.751917   20.219796  < 1.00e-07  -0.0000000309  

       Intercept   131.133772    0.832787  < 1.00e-07  -0.0000007795  

  Covariates
        sex_code    -3.781230    1.679494   0.024360    0.0000000000  
     foo_na_u24c     0.032032    0.015451   0.038158    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1811.352533

=====================================================================
     VARIANCE-COVARIANCE MATRIX foo_na_u24c with test covariates
=====================================================================

----------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_na_u24c  
----------------------------------------------------------------------------------
  Random           408.840163   408.840163     -0.000153   0.000000   0.000000    
  Total variance   408.840163   408.840163     -0.000153   0.000000   0.000000    
  Intercept         -0.000153    -0.000153      0.693534   0.000000   0.000000    
  sex_code           0.000000     0.000000      0.000000   2.820701   0.001708    
  foo_na_u24c        0.000000     0.000000      0.000000   0.001708   0.000239    

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_na_u24c without test covariates  -1813.490721  
  H1 ln likelihood foo_na_u24c with test covariates     -1811.352533  
                                                                      
  2 * |H0 - H1|                                             4.276377  
  Degrees of freedom                                               1  
  P-value                                                   0.038646  

============================

     Model 'foo_k_u24c'

============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   423  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

--------------------------------------------------------------
  Name        Mean        Std. dev.   Min        Max          
--------------------------------------------------------------
  sex_code      0.555294    0.496933   0.000000     1.000000  
  foo_k_u24c   45.255247   19.190001   4.920000   188.790000  

=================================================================
     MAXIMIZATION RESULTS foo_k_u24c without test covariates
=================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   297.732700   20.424277  < 1.00e-07  -0.0000000349  

  Other parameters
  Total variance   297.732700   20.424277  < 1.00e-07  -0.0000000031  

       Intercept   131.133772    0.836987  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.010442    1.684304   0.017263    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1813.490721

=======================================================================
     VARIANCE-COVARIANCE MATRIX foo_k_u24c without test covariates
=======================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           417.151086   417.151086     -0.000155  -2.83e-05  
  Total variance   417.151086   417.151086     -0.000155  -2.83e-05  
  Intercept         -0.000155    -0.000155      0.700548   1.05e-11  
  sex_code          -2.83e-05    -2.83e-05      1.05e-11   2.836880  

==============================================================
     MAXIMIZATION RESULTS foo_k_u24c with test covariates
==============================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   294.560127   20.206639  < 1.00e-07   0.0000001360  

  Other parameters
  Total variance   294.560127   20.206639  < 1.00e-07  -0.0000001779  

       Intercept   131.133772    0.832516  < 1.00e-07  -0.0000048305  

  Covariates
        sex_code    -3.722360    1.680709   0.026777    0.0000000000  
      foo_k_u24c     0.093116    0.043523   0.032396    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1811.214262

====================================================================
     VARIANCE-COVARIANCE MATRIX foo_k_u24c with test covariates
====================================================================

---------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_k_u24c  
---------------------------------------------------------------------------------
  Random           408.308247   408.308247     -0.000153   5.27e-06   1.99e-07   
  Total variance   408.308247   408.308247     -0.000153   5.27e-06   1.99e-07   
  Intercept         -0.000153    -0.000153      0.693083  -1.98e-12  -7.44e-14   
  sex_code           5.27e-06     5.27e-06     -1.98e-12   2.824782   0.005860   
  foo_k_u24c         1.99e-07     1.99e-07     -7.44e-14   0.005860   0.001894   

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_k_u24c without test covariates  -1813.490721  
  H1 ln likelihood foo_k_u24c with test covariates     -1811.214262  
                                                                     
  2 * |H0 - H1|                                            4.552918  
  Degrees of freedom                                              1  
  P-value                                                  0.032863  

==============================

     Model 'foo_SEX_CODE'

==============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

------------------------------------------------------------
  Name          Mean       Std. dev.  Min        Max        
------------------------------------------------------------
  sex_code       0.559908   0.496398   0.000000   1.000000  
  foo_SEX_CODE   1.559908   0.496398   1.000000   2.000000  

===================================================================
     MAXIMIZATION RESULTS foo_SEX_CODE without test covariates
===================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036058   20.367757  < 1.00e-07  -0.0000000450  

  Other parameters
  Total variance   300.036058   20.367757  < 1.00e-07  -0.0000000565  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323915    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

=========================================================================
     VARIANCE-COVARIANCE MATRIX foo_SEX_CODE without test covariates
=========================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845507   414.845507     -0.000153  -1.12e-05  
  Total variance   414.845507   414.845507     -0.000153  -1.12e-05  
  Intercept         -0.000153    -0.000153      0.691327   4.14e-12  
  sex_code          -1.12e-05    -1.12e-05      4.14e-12   2.805586  

================================================================
     MAXIMIZATION RESULTS foo_SEX_CODE with test covariates
================================================================

-----------------------------------------------------------------------
  Parameter       Estimate     S.E.         P-value     Deriv          
-----------------------------------------------------------------------
  Variance components
          Random   300.036300    20.367789  < 1.00e-07  -0.0000000011  

  Other parameters
  Total variance   300.036300    20.367789  < 1.00e-07  -0.0000000036  

       Intercept   131.181106     0.831461  < 1.00e-07  -0.0000001349  

  Covariates
        sex_code    -4.323905   252.758891   0.986351    0.0000000000  
    foo_SEX_CODE     1.17e-10   252.753903   1.000000    0.0000000000  
-----------------------------------------------------------------------

Final ln likelihood: -1853.566375

======================================================================
     VARIANCE-COVARIANCE MATRIX foo_SEX_CODE with test covariates
======================================================================

----------------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code       foo_SEX_CODE   
----------------------------------------------------------------------------------------
  Random           414.846836   414.846836      0.000000       0.000000       0.000000  
  Total variance   414.846836   414.846836      0.000000       0.000000       0.000000  
  Intercept          0.000000     0.000000      0.691328       0.000000       0.000000  
  sex_code           0.000000     0.000000      0.000000   63887.056772  -63884.393306  
  foo_SEX_CODE       0.000000     0.000000      0.000000  -63884.393306   63884.535423  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_SEX_CODE without test covariates  -1853.566375  
  H1 ln likelihood foo_SEX_CODE with test covariates     -1853.566375  
                                                                       
  2 * |H0 - H1|                                              1.79e-08  
  Degrees of freedom                                                1  
  P-value                                                    0.999893  

========================================

     Model 'foo_FAMILIAL_INDICATOR'

========================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

----------------------------------------------------------------------
  Name                    Mean       Std. dev.  Min        Max        
----------------------------------------------------------------------
  sex_code                 0.559908   0.496398   0.000000   1.000000  
  foo_FAMILIAL_INDICATOR   1.995392   0.067728   1.000000   2.000000  

=============================================================================
     MAXIMIZATION RESULTS foo_FAMILIAL_INDICATOR without test covariates
=============================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036058   20.367757  < 1.00e-07  -0.0000000450  

  Other parameters
  Total variance   300.036058   20.367757  < 1.00e-07  -0.0000000565  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323915    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

===================================================================================
     VARIANCE-COVARIANCE MATRIX foo_FAMILIAL_INDICATOR without test covariates
===================================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845507   414.845507     -0.000153  -1.12e-05  
  Total variance   414.845507   414.845507     -0.000153  -1.12e-05  
  Intercept         -0.000153    -0.000153      0.691327   4.14e-12  
  sex_code          -1.12e-05    -1.12e-05      4.14e-12   2.805586  

==========================================================================
     MAXIMIZATION RESULTS foo_FAMILIAL_INDICATOR with test covariates
==========================================================================

------------------------------------------------------------------------------
  Parameter               Estimate     S.E.        P-value     Deriv          
------------------------------------------------------------------------------
  Variance components
                  Random   300.035877   20.367761  < 1.00e-07  -0.0000000092  

  Other parameters
          Total variance   300.035877   20.367761  < 1.00e-07   0.0000000087  

               Intercept   131.181106    0.831461  < 1.00e-07   0.0000022928  

  Covariates
                sex_code    -4.327102    1.679943   0.010002    0.0000000000  
  foo_FAMILIAL_INDICATOR     0.305280   12.312570   0.980219    0.0000000000  
------------------------------------------------------------------------------

Final ln likelihood: -1853.566067

================================================================================
     VARIANCE-COVARIANCE MATRIX foo_FAMILIAL_INDICATOR with test covariates
================================================================================

-----------------------------------------------------------------------------------------------------
                          Random       Total variance  Intercept  sex_code   foo_FAMILIAL_INDICATOR  
-----------------------------------------------------------------------------------------------------
  Random                   414.845675   414.845675      0.000000   0.000000     0.000000             
  Total variance           414.845675   414.845675      0.000000   0.000000     0.000000             
  Intercept                  0.000000     0.000000      0.691327   0.000000     0.000000             
  sex_code                   0.000000     0.000000      0.000000   2.822207    -1.587448             
  foo_FAMILIAL_INDICATOR     0.000000     0.000000      0.000000  -1.587448   151.599384             

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_FAMILIAL_INDICATOR without test covariates  -1853.566375  
  H1 ln likelihood foo_FAMILIAL_INDICATOR with test covariates     -1853.566067  
                                                                                 
  2 * |H0 - H1|                                                        0.000615  
  Degrees of freedom                                                          1  
  P-value                                                              0.980219  

=======================================

     Model 'foo_FOUNDER_INDICATOR'

=======================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

---------------------------------------------------------------------
  Name                   Mean       Std. dev.  Min        Max        
---------------------------------------------------------------------
  sex_code                0.559908   0.496398   0.000000   1.000000  
  foo_FOUNDER_INDICATOR   1.050691   0.219366   1.000000   2.000000  

============================================================================
     MAXIMIZATION RESULTS foo_FOUNDER_INDICATOR without test covariates
============================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036058   20.367757  < 1.00e-07  -0.0000000450  

  Other parameters
  Total variance   300.036058   20.367757  < 1.00e-07  -0.0000000565  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323915    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==================================================================================
     VARIANCE-COVARIANCE MATRIX foo_FOUNDER_INDICATOR without test covariates
==================================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845507   414.845507     -0.000153  -1.12e-05  
  Total variance   414.845507   414.845507     -0.000153  -1.12e-05  
  Intercept         -0.000153    -0.000153      0.691327   4.14e-12  
  sex_code          -1.12e-05    -1.12e-05      4.14e-12   2.805586  

=========================================================================
     MAXIMIZATION RESULTS foo_FOUNDER_INDICATOR with test covariates
=========================================================================

-----------------------------------------------------------------------------
  Parameter              Estimate     S.E.        P-value     Deriv          
-----------------------------------------------------------------------------
  Variance components
                 Random   298.924000   20.292385  < 1.00e-07  -0.0000042132  

  Other parameters
         Total variance   298.924000   20.292385  < 1.00e-07  -0.0000001450  

              Intercept   131.180996    0.829919  < 1.00e-07  -0.0000461281  

  Covariates
               sex_code    -4.354616    1.672055   0.009205    0.0000000000  
  foo_FOUNDER_INDICATOR     4.811565    3.783639   0.203488    0.0000000000  
-----------------------------------------------------------------------------

Final ln likelihood: -1852.759343

===============================================================================
     VARIANCE-COVARIANCE MATRIX foo_FOUNDER_INDICATOR with test covariates
===============================================================================

---------------------------------------------------------------------------------------------------
                         Random       Total variance  Intercept  sex_code   foo_FOUNDER_INDICATOR  
---------------------------------------------------------------------------------------------------
  Random                  411.780872   411.780872     -0.000152  -3.72e-05    0.000195             
  Total variance          411.780872   411.780872     -0.000152  -3.72e-05    0.000195             
  Intercept                -0.000152    -0.000152      0.688765   1.37e-11   -7.20e-11             
  sex_code                 -3.72e-05    -3.72e-05      1.37e-11   2.795767   -0.091298             
  foo_FOUNDER_INDICATOR     0.000195     0.000195     -7.20e-11  -0.091298   14.315928             

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_FOUNDER_INDICATOR without test covariates  -1853.566375  
  H1 ln likelihood foo_FOUNDER_INDICATOR with test covariates     -1852.759343  
                                                                                
  2 * |H0 - H1|                                                       1.614064  
  Degrees of freedom                                                         1  
  P-value                                                             0.203921  

===================================

     Model 'foo_PEDIGREE_SIZE'

===================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

-------------------------------------------------------------------
  Name               Mean        Std. dev.  Min        Max         
-------------------------------------------------------------------
  sex_code             0.559908   0.496398   0.000000    1.000000  
  foo_PEDIGREE_SIZE   10.523041   3.699629   2.000000   21.000000  

========================================================================
     MAXIMIZATION RESULTS foo_PEDIGREE_SIZE without test covariates
========================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036058   20.367757  < 1.00e-07  -0.0000000450  

  Other parameters
  Total variance   300.036058   20.367757  < 1.00e-07  -0.0000000565  

       Intercept   131.180995    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323915    1.674988   0.009838    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==============================================================================
     VARIANCE-COVARIANCE MATRIX foo_PEDIGREE_SIZE without test covariates
==============================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.845507   414.845507     -0.000153  -1.12e-05  
  Total variance   414.845507   414.845507     -0.000153  -1.12e-05  
  Intercept         -0.000153    -0.000153      0.691327   4.14e-12  
  sex_code          -1.12e-05    -1.12e-05      4.14e-12   2.805586  

=====================================================================
     MAXIMIZATION RESULTS foo_PEDIGREE_SIZE with test covariates
=====================================================================

-------------------------------------------------------------------------
  Parameter          Estimate     S.E.        P-value     Deriv          
-------------------------------------------------------------------------
  Variance components
             Random   298.703466   20.277293  < 1.00e-07   0.0000000411  

  Other parameters
     Total variance   298.703466   20.277293  < 1.00e-07   0.0000000720  

          Intercept   131.180995    0.829612  < 1.00e-07   0.0000194666  

  Covariates
           sex_code    -4.166390    1.675099   0.012874    0.0000000000  
  foo_PEDIGREE_SIZE    -0.312740    0.224756   0.164085    0.0000000000  
-------------------------------------------------------------------------

Final ln likelihood: -1852.600463

===========================================================================
     VARIANCE-COVARIANCE MATRIX foo_PEDIGREE_SIZE with test covariates
===========================================================================

-------------------------------------------------------------------------------------------
                     Random       Total variance  Intercept  sex_code   foo_PEDIGREE_SIZE  
-------------------------------------------------------------------------------------------
  Random              411.168614   411.168614     -0.000152  -0.000153  -3.80e-06          
  Total variance      411.168614   411.168614     -0.000152  -0.000153  -3.80e-06          
  Intercept            -0.000152    -0.000152      0.688257   5.65e-11   1.41e-12          
  sex_code             -0.000153    -0.000153      5.65e-11   2.805958  -0.025460          
  foo_PEDIGREE_SIZE    -3.80e-06    -3.80e-06      1.41e-12  -0.025460   0.050515          

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood foo_PEDIGREE_SIZE without test covariates  -1853.566375  
  H1 ln likelihood foo_PEDIGREE_SIZE with test covariates     -1852.600463  
                                                                            
  2 * |H0 - H1|                                                   1.931824  
  Degrees of freedom                                                     1  
  P-value                                                         0.164559  

