=================

     Results

=================

==============================
     Analysis description
==============================

  Title                        assoc                         
  Primary Trait                sbpd_rand10 (Quantitative)    
  Allow averaging              Disabled                      
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  

======================================
     Transformation configuration
======================================



Note: No transformation applied.

=======================
     Summary table
=======================

-------------------------------------------------------------------------------------------------------------------------------
  Model                  Intercept    sex_code   Test cov.              Estimate    Std. err.   P-value (Wald)  P-value (LRT)  
-------------------------------------------------------------------------------------------------------------------------------
  foo_selection           131.180991  -5.400090  foo_selection           17.693938    1.486697   2.23e-308       1.72e-28      
  foo_age                 131.180995  -5.368967  foo_age                  0.427976    0.066267   1.06e-10        2.78e-10      
  foo_k_u24c              131.133772  -3.722320  foo_k_u24c               0.093118    0.043523   0.032393        0.032863      
  foo_na_u24c             131.133772  -3.781232  foo_na_u24c              0.032032    0.015451   0.038158        0.038646      
  foo_bmi                 131.180995  -5.013024  foo_bmi                  0.309039    0.163770   0.059156        0.059677      
  PEDIGREE_SIZE           131.180995  -4.166278  PEDIGREE_SIZE           -0.312727    0.224757   0.164103        0.164559      
  foo_PEDIGREE_SIZE       131.180995  -4.166278  foo_PEDIGREE_SIZE       -0.312727    0.224757   0.164103        0.164559      
  FOUNDER_INDICATOR       131.180995  -4.354595  FOUNDER_INDICATOR        4.811298    3.783632   0.203512        0.203921      
  foo_FOUNDER_INDICATOR   131.180995  -4.354590  foo_FOUNDER_INDICATOR    4.811342    3.783627   0.203508        0.203921      
  FAMILIAL_INDICATOR      131.181106  -4.327102  FAMILIAL_INDICATOR       0.305280   12.312722   0.980219        0.980219      
-------------------------------------------------------------------------------------------------------------------------------

Note: Models with an asterisk (*) may not have converged.

================================
     Complete summary table
================================

----------------------------------------------------------------------------------------------------------------------------------
  Model                   Intercept    sex_code   Test cov.               Estimate    Std. err.    P-value (Wald)  P-value (LRT)  
----------------------------------------------------------------------------------------------------------------------------------
  FAMILIAL_INDICATOR       131.181106  -4.327102  FAMILIAL_INDICATOR        0.305280    12.312722   0.980219        0.980219      
  FOUNDER_INDICATOR        131.180995  -4.354595  FOUNDER_INDICATOR         4.811298     3.783632   0.203512        0.203921      
  PEDIGREE_SIZE            131.180995  -4.166278  PEDIGREE_SIZE            -0.312727     0.224757   0.164103        0.164559      
  foo_selection            131.180991  -5.400090  foo_selection            17.693938     1.486697   2.23e-308       1.72e-28      
  foo_age                  131.180995  -5.368967  foo_age                   0.427976     0.066267   1.06e-10        2.78e-10      
  foo_bmi                  131.180995  -5.013024  foo_bmi                   0.309039     0.163770   0.059156        0.059677      
  foo_sbpd_rand10          131.180995  -4.56e-06  foo_sbpd_rand10           0.999999     8.76e-07   2.23e-308       1.000000      
  foo_na_u24c              131.133772  -3.781232  foo_na_u24c               0.032032     0.015451   0.038158        0.038646      
  foo_k_u24c               131.133772  -3.722320  foo_k_u24c                0.093118     0.043523   0.032393        0.032863      
  foo_SEX_CODE             131.181106  -4.323905  foo_SEX_CODE              3.00e-11   248.336713   1.000000        0.999892      
  foo_FAMILIAL_INDICATOR   131.181106  -4.327102  foo_FAMILIAL_INDICATOR    0.305280    12.312722   0.980219        0.980219      
  foo_FOUNDER_INDICATOR    131.180995  -4.354590  foo_FOUNDER_INDICATOR     4.811342     3.783627   0.203508        0.203921      
  foo_PEDIGREE_SIZE        131.180995  -4.166278  foo_PEDIGREE_SIZE        -0.312727     0.224757   0.164103        0.164559      
----------------------------------------------------------------------------------------------------------------------------------

Note: Models with an asterisk (*) may not have converged.

Note: See .det file for more information about each model

