=================

     Results

=================

Note: P-values for variance components and proportions are one-sided.  All others are two-sided.
The null hypothesis for transformation parameters is 'no transformation.'


==============================
     Analysis description
==============================

  Title                        assoc                         
  Primary Trait                sbpd_rand10 (Quantitative)    
  Allow averaging              Disabled                      
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  

======================================
     Transformation configuration
======================================



Note: No transformation applied.

====================================

     Model 'FAMILIAL_INDICATOR'

====================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

------------------------------------------------------------------
  Name                Mean       Std. dev.  Min        Max        
------------------------------------------------------------------
  sex_code             0.559908   0.496398   0.000000   1.000000  
  FAMILIAL_INDICATOR   0.995392   0.067728   0.000000   1.000000  

=========================================================================
     MAXIMIZATION RESULTS FAMILIAL_INDICATOR without test covariates
=========================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036330   20.367820  < 1.00e-07  -0.0000000739  

  Other parameters
  Total variance   300.036330   20.367820  < 1.00e-07   0.0000005084  

       Intercept   131.181106    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323906    1.674965   0.009837    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

===============================================================================
     VARIANCE-COVARIANCE MATRIX FAMILIAL_INDICATOR without test covariates
===============================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.848096   414.848096      0.000000   0.000000  
  Total variance   414.848096   414.848096      0.000000   0.000000  
  Intercept          0.000000     0.000000      0.691328   1.87e-08  
  sex_code           0.000000     0.000000      1.87e-08   2.805508  

======================================================================
     MAXIMIZATION RESULTS FAMILIAL_INDICATOR with test covariates
======================================================================

--------------------------------------------------------------------------
  Parameter           Estimate     S.E.        P-value     Deriv          
--------------------------------------------------------------------------
  Variance components
              Random   300.035876   20.367732  < 1.00e-07  -0.0000000065  

  Other parameters
      Total variance   300.035876   20.367732  < 1.00e-07   0.0000000046  

           Intercept   131.181106    0.831461  < 1.00e-07  -0.0000009441  

  Covariates
            sex_code    -4.327102    1.679920   0.010001    0.0000000000  
  FAMILIAL_INDICATOR     0.305291   12.307223   0.980210    0.0000000000  
--------------------------------------------------------------------------

Final ln likelihood: -1853.566067

============================================================================
     VARIANCE-COVARIANCE MATRIX FAMILIAL_INDICATOR with test covariates
============================================================================

---------------------------------------------------------------------------------------------
                      Random       Total variance  Intercept  sex_code   FAMILIAL_INDICATOR  
---------------------------------------------------------------------------------------------
  Random               414.844497   414.844497     -1.00e-14  -6.75e-08     6.45e-06         
  Total variance       414.844497   414.844497     -1.00e-14  -6.75e-08     6.45e-06         
  Intercept             -1.00e-14    -1.00e-14      0.691327  -3.21e-07    -2.35e-07         
  sex_code              -6.75e-08    -6.75e-08     -3.21e-07   2.822133    -1.585491         
  FAMILIAL_INDICATOR     6.45e-06     6.45e-06     -2.35e-07  -1.585491   151.467749         

====================
     Joint test
====================

  H0 ln likelihood FAMILIAL_INDICATOR without test covariates  -1853.566375  
  H1 ln likelihood FAMILIAL_INDICATOR with test covariates     -1853.566067  
                                                                             
  2 * |H0 - H1|                                                    0.000615  
  Degrees of freedom                                                      1  
  P-value                                                          0.980219  

===================================

     Model 'FOUNDER_INDICATOR'

===================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

-----------------------------------------------------------------
  Name               Mean       Std. dev.  Min        Max        
-----------------------------------------------------------------
  sex_code            0.559908   0.496398   0.000000   1.000000  
  FOUNDER_INDICATOR   0.050691   0.219366   0.000000   1.000000  

========================================================================
     MAXIMIZATION RESULTS FOUNDER_INDICATOR without test covariates
========================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036330   20.367820  < 1.00e-07  -0.0000000739  

  Other parameters
  Total variance   300.036330   20.367820  < 1.00e-07   0.0000005084  

       Intercept   131.181106    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323906    1.674965   0.009837    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==============================================================================
     VARIANCE-COVARIANCE MATRIX FOUNDER_INDICATOR without test covariates
==============================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.848096   414.848096      0.000000   0.000000  
  Total variance   414.848096   414.848096      0.000000   0.000000  
  Intercept          0.000000     0.000000      0.691328   1.87e-08  
  sex_code           0.000000     0.000000      1.87e-08   2.805508  

=====================================================================
     MAXIMIZATION RESULTS FOUNDER_INDICATOR with test covariates
=====================================================================

-------------------------------------------------------------------------
  Parameter          Estimate     S.E.        P-value     Deriv          
-------------------------------------------------------------------------
  Variance components
             Random   298.922645   20.292185  < 1.00e-07  -0.0000002967  

  Other parameters
     Total variance   298.922645   20.292185  < 1.00e-07  -0.0000016111  

          Intercept   131.181107    0.829917  < 1.00e-07   0.0000028112  

  Covariates
           sex_code    -4.354606    1.672063   0.009205    0.0000000000  
  FOUNDER_INDICATOR     4.811416    3.783713   0.203511    0.0000000000  
-------------------------------------------------------------------------

Final ln likelihood: -1852.759343

===========================================================================
     VARIANCE-COVARIANCE MATRIX FOUNDER_INDICATOR with test covariates
===========================================================================

-------------------------------------------------------------------------------------------
                     Random       Total variance  Intercept  sex_code   FOUNDER_INDICATOR  
-------------------------------------------------------------------------------------------
  Random              411.772783   411.772783     -4.14e-13  -2.22e-05   -2.54e-05         
  Total variance      411.772783   411.772783     -4.14e-13  -2.22e-05   -2.54e-05         
  Intercept            -4.14e-13    -4.14e-13      0.688762   4.90e-08    1.26e-08         
  sex_code             -2.22e-05    -2.22e-05      4.90e-08   2.795794   -0.091254         
  FOUNDER_INDICATOR    -2.54e-05    -2.54e-05      1.26e-08  -0.091254   14.316484         

====================
     Joint test
====================

  H0 ln likelihood FOUNDER_INDICATOR without test covariates  -1853.566375  
  H1 ln likelihood FOUNDER_INDICATOR with test covariates     -1852.759343  
                                                                            
  2 * |H0 - H1|                                                   1.614064  
  Degrees of freedom                                                     1  
  P-value                                                         0.203921  

===============================

     Model 'PEDIGREE_SIZE'

===============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

--------------------------------------------------------------
  Name           Mean       Std. dev.  Min        Max         
--------------------------------------------------------------
  sex_code        0.559908   0.496398   0.000000    1.000000  
  PEDIGREE_SIZE   9.523041   3.699629   1.000000   20.000000  

====================================================================
     MAXIMIZATION RESULTS PEDIGREE_SIZE without test covariates
====================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036330   20.367820  < 1.00e-07  -0.0000000739  

  Other parameters
  Total variance   300.036330   20.367820  < 1.00e-07   0.0000005084  

       Intercept   131.181106    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323906    1.674965   0.009837    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==========================================================================
     VARIANCE-COVARIANCE MATRIX PEDIGREE_SIZE without test covariates
==========================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.848096   414.848096      0.000000   0.000000  
  Total variance   414.848096   414.848096      0.000000   0.000000  
  Intercept          0.000000     0.000000      0.691328   1.87e-08  
  sex_code           0.000000     0.000000      1.87e-08   2.805508  

=================================================================
     MAXIMIZATION RESULTS PEDIGREE_SIZE with test covariates
=================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   298.703548   20.277290  < 1.00e-07  -0.0000001449  

  Other parameters
  Total variance   298.703548   20.277290  < 1.00e-07  -0.0000000206  

       Intercept   131.180995    0.829613  < 1.00e-07  -0.0000016319  

  Covariates
        sex_code    -4.166279    1.675111   0.012877    0.0000000000  
   PEDIGREE_SIZE    -0.312738    0.224757   0.164090    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1852.600463

=======================================================================
     VARIANCE-COVARIANCE MATRIX PEDIGREE_SIZE with test covariates
=======================================================================

------------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   PEDIGREE_SIZE  
------------------------------------------------------------------------------------
  Random           411.168503   411.168503     -0.000152   4.08e-07  -8.09e-07      
  Total variance   411.168503   411.168503     -0.000152   4.08e-07  -8.09e-07      
  Intercept         -0.000152    -0.000152      0.688257   2.14e-08   1.92e-09      
  sex_code           4.08e-07     4.08e-07      2.14e-08   2.805998  -0.025464      
  PEDIGREE_SIZE     -8.09e-07    -8.09e-07      1.92e-09  -0.025464   0.050516      

====================
     Joint test
====================

  H0 ln likelihood PEDIGREE_SIZE without test covariates  -1853.566375  
  H1 ln likelihood PEDIGREE_SIZE with test covariates     -1852.600463  
                                                                        
  2 * |H0 - H1|                                               1.931824  
  Degrees of freedom                                                 1  
  P-value                                                     0.164559  

===============================

     Model 'foo_selection'

===============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

-------------------------------------------------------------
  Name           Mean       Std. dev.  Min        Max        
-------------------------------------------------------------
  sex_code        0.559908   0.496398   0.000000   1.000000  
  foo_selection   1.615207   0.486546   1.000000   2.000000  

====================================================================
     MAXIMIZATION RESULTS foo_selection without test covariates
====================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036330   20.367820  < 1.00e-07  -0.0000000739  

  Other parameters
  Total variance   300.036330   20.367820  < 1.00e-07   0.0000005084  

       Intercept   131.181106    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323906    1.674965   0.009837    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==========================================================================
     VARIANCE-COVARIANCE MATRIX foo_selection without test covariates
==========================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.848096   414.848096      0.000000   0.000000  
  Total variance   414.848096   414.848096      0.000000   0.000000  
  Intercept          0.000000     0.000000      0.691328   1.87e-08  
  sex_code           0.000000     0.000000      1.87e-08   2.805508  

=================================================================
     MAXIMIZATION RESULTS foo_selection with test covariates
=================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   226.207879   15.355959  < 1.00e-07  -0.0000000101  

  Other parameters
  Total variance   226.207879   15.355959  < 1.00e-07  -0.0000000298  

       Intercept   131.180995    0.721953  < 1.00e-07  -0.0000003290  

  Covariates
        sex_code    -5.400116    1.457187   0.000211    0.0000000000  
   foo_selection    17.693940    1.486697  < 1.00e-07   0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1792.275111

=======================================================================
     VARIANCE-COVARIANCE MATRIX foo_selection with test covariates
=======================================================================

------------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_selection  
------------------------------------------------------------------------------------
  Random           235.805489   235.805489     -0.000115  -3.97e-06  -1.42e-05      
  Total variance   235.805489   235.805489     -0.000115  -3.97e-06  -1.42e-05      
  Intercept         -0.000115    -0.000115      0.521216   1.05e-09   2.78e-10      
  sex_code          -3.97e-06    -3.97e-06      1.05e-09   2.123395  -0.134435      
  foo_selection     -1.42e-05    -1.42e-05      2.78e-10  -0.134435   2.210269      

====================
     Joint test
====================

  H0 ln likelihood foo_selection without test covariates  -1853.566375  
  H1 ln likelihood foo_selection with test covariates     -1792.275111  
                                                                        
  2 * |H0 - H1|                                             122.582527  
  Degrees of freedom                                                 1  
  P-value                                                     1.72e-28  

=========================

     Model 'foo_age'

=========================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

------------------------------------------------------------
  Name      Mean        Std. dev.   Min         Max         
------------------------------------------------------------
  sex_code    0.559908    0.496398    0.000000    1.000000  
  foo_age    47.456221   12.045581   19.000000   84.000000  

==============================================================
     MAXIMIZATION RESULTS foo_age without test covariates
==============================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036330   20.367820  < 1.00e-07  -0.0000000739  

  Other parameters
  Total variance   300.036330   20.367820  < 1.00e-07   0.0000005084  

       Intercept   131.181106    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323906    1.674965   0.009837    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

====================================================================
     VARIANCE-COVARIANCE MATRIX foo_age without test covariates
====================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.848096   414.848096      0.000000   0.000000  
  Total variance   414.848096   414.848096      0.000000   0.000000  
  Intercept          0.000000     0.000000      0.691328   1.87e-08  
  sex_code           0.000000     0.000000      1.87e-08   2.805508  

===========================================================
     MAXIMIZATION RESULTS foo_age with test covariates
===========================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   273.728858   18.581911  < 1.00e-07  -0.0000000099  

  Other parameters
  Total variance   273.728858   18.581911  < 1.00e-07  -0.0000000206  

       Intercept   131.180995    0.794174  < 1.00e-07  -0.0000003663  

  Covariates
        sex_code    -5.368966    1.608033   0.000841    0.0000000000  
         foo_age     0.427976    0.066267  < 1.00e-07   0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1833.653463

=================================================================
     VARIANCE-COVARIANCE MATRIX foo_age with test covariates
=================================================================

--------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_age    
--------------------------------------------------------------------------------
  Random           345.287405   345.287405     -0.000139   3.87e-06  -4.65e-07  
  Total variance   345.287405   345.287405     -0.000139   3.87e-06  -4.65e-07  
  Intercept         -0.000139    -0.000139      0.630712   3.16e-08  -1.31e-10  
  sex_code           3.87e-06     3.87e-06      3.16e-08   2.585769  -0.010723  
  foo_age           -4.65e-07    -4.65e-07     -1.31e-10  -0.010723   0.004391  

====================
     Joint test
====================

  H0 ln likelihood foo_age without test covariates  -1853.566375  
  H1 ln likelihood foo_age with test covariates     -1833.653463  
                                                                  
  2 * |H0 - H1|                                        39.825823  
  Degrees of freedom                                           1  
  P-value                                               2.78e-10  

=========================

     Model 'foo_bmi'

=========================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

-----------------------------------------------------------
  Name      Mean        Std. dev.  Min         Max         
-----------------------------------------------------------
  sex_code    0.559908   0.496398    0.000000    1.000000  
  foo_bmi    28.584562   5.176045   16.100000   48.400000  

==============================================================
     MAXIMIZATION RESULTS foo_bmi without test covariates
==============================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036330   20.367820  < 1.00e-07  -0.0000000739  

  Other parameters
  Total variance   300.036330   20.367820  < 1.00e-07   0.0000005084  

       Intercept   131.181106    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323906    1.674965   0.009837    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

====================================================================
     VARIANCE-COVARIANCE MATRIX foo_bmi without test covariates
====================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.848096   414.848096      0.000000   0.000000  
  Total variance   414.848096   414.848096      0.000000   0.000000  
  Intercept          0.000000     0.000000      0.691328   1.87e-08  
  sex_code           0.000000     0.000000      1.87e-08   2.805508  

===========================================================
     MAXIMIZATION RESULTS foo_bmi with test covariates
===========================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   297.594613   20.202073  < 1.00e-07  -0.0000000410  

  Other parameters
  Total variance   297.594613   20.202073  < 1.00e-07  -0.0000000175  

       Intercept   131.181106    0.828071  < 1.00e-07   0.0000000422  

  Covariates
        sex_code    -5.012972    1.707649   0.003329    0.0000000000  
         foo_bmi     0.309038    0.163773   0.059162    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1851.793200

=================================================================
     VARIANCE-COVARIANCE MATRIX foo_bmi with test covariates
=================================================================

--------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_bmi    
--------------------------------------------------------------------------------
  Random           408.123758   408.123758      4.23e-13  -2.12e-05   9.53e-06  
  Total variance   408.123758   408.123758      4.23e-13  -2.12e-05   9.53e-06  
  Intercept          4.23e-13     4.23e-13      0.685702  -5.30e-09   1.19e-09  
  sex_code          -2.12e-05    -2.12e-05     -5.30e-09   2.916065  -0.059805  
  foo_bmi            9.53e-06     9.53e-06      1.19e-09  -0.059805   0.026822  

====================
     Joint test
====================

  H0 ln likelihood foo_bmi without test covariates  -1853.566375  
  H1 ln likelihood foo_bmi with test covariates     -1851.793200  
                                                                  
  2 * |H0 - H1|                                         3.546350  
  Degrees of freedom                                           1  
  P-value                                               0.059677  

=================================

     Model 'foo_sbpd_rand10'

=================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

---------------------------------------------------------------------
  Name             Mean         Std. dev.   Min         Max          
---------------------------------------------------------------------
  sex_code            0.559908    0.496398    0.000000     1.000000  
  foo_sbpd_rand10   132.181106   17.454032   84.900000   191.000000  

======================================================================
     MAXIMIZATION RESULTS foo_sbpd_rand10 without test covariates
======================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036330   20.367820  < 1.00e-07  -0.0000000739  

  Other parameters
  Total variance   300.036330   20.367820  < 1.00e-07   0.0000005084  

       Intercept   131.181106    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323906    1.674965   0.009837    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

============================================================================
     VARIANCE-COVARIANCE MATRIX foo_sbpd_rand10 without test covariates
============================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.848096   414.848096      0.000000   0.000000  
  Total variance   414.848096   414.848096      0.000000   0.000000  
  Intercept          0.000000     0.000000      0.691328   1.87e-08  
  sex_code           0.000000     0.000000      1.87e-08   2.805508  

===================================================================
     MAXIMIZATION RESULTS foo_sbpd_rand10 with test covariates
===================================================================

-------------------------------------------------------------------------
  Parameter        Estimate     S.E.         P-value      Deriv          
-------------------------------------------------------------------------
  Variance components
           Random     1.00e-07          Ind. func. fixed @ bnd           

  Other parameters
   Total variance     1.00e-07  Unavailable  Unavailable   0.0000000000  

        Intercept   131.181106   1.52e-05    < 1.00e-07    0.0000008654  

  Covariates
         sex_code     9.37e-15   3.08e-05     1.000000     0.0000000000  
  foo_sbpd_rand10     1.000000   8.76e-07    < 1.00e-07    0.0000000000  
-------------------------------------------------------------------------

Final ln likelihood:  3098.807433

=========================================================================
     VARIANCE-COVARIANCE MATRIX foo_sbpd_rand10 with test covariates
=========================================================================

-------------------------------------------------------------------------------------
                   Random     Total variance  Intercept  sex_code   foo_sbpd_rand10  
-------------------------------------------------------------------------------------
  Random            0.000000   0.000000        0.000000   0.000000   0.000000        
  Total variance    0.000000   0.000000        0.000000   0.000000   0.000000        
  Intercept         0.000000   0.000000        2.30e-10   6.27e-20   2.19e-22        
  sex_code          0.000000   0.000000        6.27e-20   9.49e-10   3.32e-12        
  foo_sbpd_rand10   0.000000   0.000000        2.19e-22   3.32e-12   7.68e-13        

====================
     Joint test
====================

  H0 ln likelihood foo_sbpd_rand10 without test covariates  -1853.566375  
  H1 ln likelihood foo_sbpd_rand10 with test covariates      3098.807433  
                                                                          
  2 * |H0 - H1|                                              9904.747615  
  Degrees of freedom                                                   1  
  P-value                                                       1.000000  

=============================

     Model 'foo_na_u24c'

=============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   423  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

----------------------------------------------------------------
  Name         Mean         Std. dev.   Min        Max          
----------------------------------------------------------------
  sex_code        0.555294    0.496933   0.000000     1.000000  
  foo_na_u24c   106.973341   54.015420   4.130000   329.110000  

==================================================================
     MAXIMIZATION RESULTS foo_na_u24c without test covariates
==================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   297.733111   20.424339  < 1.00e-07  -0.0000004023  

  Other parameters
  Total variance   297.733111   20.424339  < 1.00e-07  -0.0000003739  

       Intercept   131.133883    0.836988  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.010400    1.684335   0.017266    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1813.490721

========================================================================
     VARIANCE-COVARIANCE MATRIX foo_na_u24c without test covariates
========================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           417.153642   417.153642     -3.44e-14   1.62e-05  
  Total variance   417.153642   417.153642     -3.44e-14   1.62e-05  
  Intercept         -3.44e-14    -3.44e-14      0.700548  -6.01e-09  
  sex_code           1.62e-05     1.62e-05     -6.01e-09   2.836983  

===============================================================
     MAXIMIZATION RESULTS foo_na_u24c with test covariates
===============================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   294.751905   20.219850  < 1.00e-07   0.0000000302  

  Other parameters
  Total variance   294.751905   20.219850  < 1.00e-07   0.0000001903  

       Intercept   131.133772    0.832787  < 1.00e-07   0.0000052226  

  Covariates
        sex_code    -3.781238    1.679522   0.024362    0.0000000000  
     foo_na_u24c     0.032032    0.015451   0.038163    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1811.352533

=====================================================================
     VARIANCE-COVARIANCE MATRIX foo_na_u24c with test covariates
=====================================================================

----------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_na_u24c  
----------------------------------------------------------------------------------
  Random           408.842318   408.842318     -0.000154  -1.07e-05  -8.61e-08    
  Total variance   408.842318   408.842318     -0.000154  -1.07e-05  -8.61e-08    
  Intercept         -0.000154    -0.000154      0.693534   7.70e-08   9.76e-09    
  sex_code          -1.07e-05    -1.07e-05      7.70e-08   2.820793   0.001708    
  foo_na_u24c       -8.61e-08    -8.61e-08      9.76e-09   0.001708   0.000239    

====================
     Joint test
====================

  H0 ln likelihood foo_na_u24c without test covariates  -1813.490721  
  H1 ln likelihood foo_na_u24c with test covariates     -1811.352533  
                                                                      
  2 * |H0 - H1|                                             4.276377  
  Degrees of freedom                                               1  
  P-value                                                   0.038646  

============================

     Model 'foo_k_u24c'

============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   423  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

--------------------------------------------------------------
  Name        Mean        Std. dev.   Min        Max          
--------------------------------------------------------------
  sex_code      0.555294    0.496933   0.000000     1.000000  
  foo_k_u24c   45.255247   19.190001   4.920000   188.790000  

=================================================================
     MAXIMIZATION RESULTS foo_k_u24c without test covariates
=================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   297.733111   20.424339  < 1.00e-07  -0.0000004023  

  Other parameters
  Total variance   297.733111   20.424339  < 1.00e-07  -0.0000003739  

       Intercept   131.133883    0.836988  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.010400    1.684335   0.017266    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1813.490721

=======================================================================
     VARIANCE-COVARIANCE MATRIX foo_k_u24c without test covariates
=======================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           417.153642   417.153642     -3.44e-14   1.62e-05  
  Total variance   417.153642   417.153642     -3.44e-14   1.62e-05  
  Intercept         -3.44e-14    -3.44e-14      0.700548  -6.01e-09  
  sex_code           1.62e-05     1.62e-05     -6.01e-09   2.836983  

==============================================================
     MAXIMIZATION RESULTS foo_k_u24c with test covariates
==============================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   294.560204   20.206615  < 1.00e-07  -0.0000000733  

  Other parameters
  Total variance   294.560204   20.206615  < 1.00e-07  -0.0000005502  

       Intercept   131.133772    0.832516  < 1.00e-07   0.0000052834  

  Covariates
        sex_code    -3.722376    1.680717   0.026777    0.0000000000  
      foo_k_u24c     0.093116    0.043522   0.032393    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1811.214262

====================================================================
     VARIANCE-COVARIANCE MATRIX foo_k_u24c with test covariates
====================================================================

---------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   foo_k_u24c  
---------------------------------------------------------------------------------
  Random           408.307287   408.307287     -0.000153  -6.52e-05  -1.86e-07   
  Total variance   408.307287   408.307287     -0.000153  -6.52e-05  -1.86e-07   
  Intercept         -0.000153    -0.000153      0.693083   1.53e-08   2.50e-10   
  sex_code          -6.52e-05    -6.52e-05      1.53e-08   2.824808   0.005859   
  foo_k_u24c        -1.86e-07    -1.86e-07      2.50e-10   0.005859   0.001894   

====================
     Joint test
====================

  H0 ln likelihood foo_k_u24c without test covariates  -1813.490721  
  H1 ln likelihood foo_k_u24c with test covariates     -1811.214262  
                                                                     
  2 * |H0 - H1|                                            4.552918  
  Degrees of freedom                                              1  
  P-value                                                  0.032863  

==============================

     Model 'foo_SEX_CODE'

==============================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

------------------------------------------------------------
  Name          Mean       Std. dev.  Min        Max        
------------------------------------------------------------
  sex_code       0.559908   0.496398   0.000000   1.000000  
  foo_SEX_CODE   1.559908   0.496398   1.000000   2.000000  

===================================================================
     MAXIMIZATION RESULTS foo_SEX_CODE without test covariates
===================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036330   20.367820  < 1.00e-07  -0.0000000739  

  Other parameters
  Total variance   300.036330   20.367820  < 1.00e-07   0.0000005084  

       Intercept   131.181106    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323906    1.674965   0.009837    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

=========================================================================
     VARIANCE-COVARIANCE MATRIX foo_SEX_CODE without test covariates
=========================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.848096   414.848096      0.000000   0.000000  
  Total variance   414.848096   414.848096      0.000000   0.000000  
  Intercept          0.000000     0.000000      0.691328   1.87e-08  
  sex_code           0.000000     0.000000      1.87e-08   2.805508  

================================================================
     MAXIMIZATION RESULTS foo_SEX_CODE with test covariates
================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036329   20.367759  < 1.00e-07  -0.0000000730  

  Other parameters
  Total variance   300.036329   20.367759  < 1.00e-07   0.0000010389  

       Intercept   131.181105    0.831461  < 1.00e-07  -0.0000009441  

  Covariates
        sex_code    -4.323906   92.018604   0.962522    0.0000000000  
    foo_SEX_CODE     2.74e-09   92.002215   1.000000    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

======================================================================
     VARIANCE-COVARIANCE MATRIX foo_SEX_CODE with test covariates
======================================================================

--------------------------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code      foo_SEX_CODE  
--------------------------------------------------------------------------------------
  Random           414.845598   414.845598      1.03e-09     -0.078384      0.078385  
  Total variance   414.845598   414.845598      1.03e-09     -0.078384      0.078385  
  Intercept          1.03e-09     1.03e-09      0.691328     -0.000111      0.000111  
  sex_code          -0.078384    -0.078384     -0.000111   8467.423559  -8464.512764  
  foo_SEX_CODE       0.078385     0.078385      0.000111  -8464.512764   8464.407563  

====================
     Joint test
====================

  H0 ln likelihood foo_SEX_CODE without test covariates  -1853.566375  
  H1 ln likelihood foo_SEX_CODE with test covariates     -1853.566375  
                                                                       
  2 * |H0 - H1|                                              1.50e-11  
  Degrees of freedom                                                1  
  P-value                                                    0.999997  

========================================

     Model 'foo_FAMILIAL_INDICATOR'

========================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

----------------------------------------------------------------------
  Name                    Mean       Std. dev.  Min        Max        
----------------------------------------------------------------------
  sex_code                 0.559908   0.496398   0.000000   1.000000  
  foo_FAMILIAL_INDICATOR   1.995392   0.067728   1.000000   2.000000  

=============================================================================
     MAXIMIZATION RESULTS foo_FAMILIAL_INDICATOR without test covariates
=============================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036330   20.367820  < 1.00e-07  -0.0000000739  

  Other parameters
  Total variance   300.036330   20.367820  < 1.00e-07   0.0000005084  

       Intercept   131.181106    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323906    1.674965   0.009837    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

===================================================================================
     VARIANCE-COVARIANCE MATRIX foo_FAMILIAL_INDICATOR without test covariates
===================================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.848096   414.848096      0.000000   0.000000  
  Total variance   414.848096   414.848096      0.000000   0.000000  
  Intercept          0.000000     0.000000      0.691328   1.87e-08  
  sex_code           0.000000     0.000000      1.87e-08   2.805508  

==========================================================================
     MAXIMIZATION RESULTS foo_FAMILIAL_INDICATOR with test covariates
==========================================================================

------------------------------------------------------------------------------
  Parameter               Estimate     S.E.        P-value     Deriv          
------------------------------------------------------------------------------
  Variance components
                  Random   300.035876   20.367732  < 1.00e-07  -0.0000000065  

  Other parameters
          Total variance   300.035876   20.367732  < 1.00e-07   0.0000000046  

               Intercept   131.181106    0.831461  < 1.00e-07  -0.0000009441  

  Covariates
                sex_code    -4.327102    1.679920   0.010001    0.0000000000  
  foo_FAMILIAL_INDICATOR     0.305291   12.307223   0.980210    0.0000000000  
------------------------------------------------------------------------------

Final ln likelihood: -1853.566067

================================================================================
     VARIANCE-COVARIANCE MATRIX foo_FAMILIAL_INDICATOR with test covariates
================================================================================

-----------------------------------------------------------------------------------------------------
                          Random       Total variance  Intercept  sex_code   foo_FAMILIAL_INDICATOR  
-----------------------------------------------------------------------------------------------------
  Random                   414.844497   414.844497     -1.00e-14  -6.75e-08     6.45e-06             
  Total variance           414.844497   414.844497     -1.00e-14  -6.75e-08     6.45e-06             
  Intercept                 -1.00e-14    -1.00e-14      0.691327  -3.21e-07    -2.35e-07             
  sex_code                  -6.75e-08    -6.75e-08     -3.21e-07   2.822133    -1.585491             
  foo_FAMILIAL_INDICATOR     6.45e-06     6.45e-06     -2.35e-07  -1.585491   151.467749             

====================
     Joint test
====================

  H0 ln likelihood foo_FAMILIAL_INDICATOR without test covariates  -1853.566375  
  H1 ln likelihood foo_FAMILIAL_INDICATOR with test covariates     -1853.566067  
                                                                                 
  2 * |H0 - H1|                                                        0.000615  
  Degrees of freedom                                                          1  
  P-value                                                              0.980219  

=======================================

     Model 'foo_FOUNDER_INDICATOR'

=======================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

---------------------------------------------------------------------
  Name                   Mean       Std. dev.  Min        Max        
---------------------------------------------------------------------
  sex_code                0.559908   0.496398   0.000000   1.000000  
  foo_FOUNDER_INDICATOR   1.050691   0.219366   1.000000   2.000000  

============================================================================
     MAXIMIZATION RESULTS foo_FOUNDER_INDICATOR without test covariates
============================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036330   20.367820  < 1.00e-07  -0.0000000739  

  Other parameters
  Total variance   300.036330   20.367820  < 1.00e-07   0.0000005084  

       Intercept   131.181106    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323906    1.674965   0.009837    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==================================================================================
     VARIANCE-COVARIANCE MATRIX foo_FOUNDER_INDICATOR without test covariates
==================================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.848096   414.848096      0.000000   0.000000  
  Total variance   414.848096   414.848096      0.000000   0.000000  
  Intercept          0.000000     0.000000      0.691328   1.87e-08  
  sex_code           0.000000     0.000000      1.87e-08   2.805508  

=========================================================================
     MAXIMIZATION RESULTS foo_FOUNDER_INDICATOR with test covariates
=========================================================================

-----------------------------------------------------------------------------
  Parameter              Estimate     S.E.        P-value     Deriv          
-----------------------------------------------------------------------------
  Variance components
                 Random   298.922545   20.292168  < 1.00e-07  -0.0000000510  

  Other parameters
         Total variance   298.922545   20.292168  < 1.00e-07  -0.0000001208  

              Intercept   131.181106    0.829917  < 1.00e-07   0.0000007028  

  Covariates
               sex_code    -4.354590    1.672073   0.009206    0.0000000000  
  foo_FOUNDER_INDICATOR     4.811425    3.783663   0.203504    0.0000000000  
-----------------------------------------------------------------------------

Final ln likelihood: -1852.759343

===============================================================================
     VARIANCE-COVARIANCE MATRIX foo_FOUNDER_INDICATOR with test covariates
===============================================================================

---------------------------------------------------------------------------------------------------
                         Random       Total variance  Intercept  sex_code   foo_FOUNDER_INDICATOR  
---------------------------------------------------------------------------------------------------
  Random                  411.772070   411.772070      0.000000   0.000000    0.000000             
  Total variance          411.772070   411.772070      0.000000   0.000000    0.000000             
  Intercept                 0.000000     0.000000      0.688762  -9.05e-11    1.42e-08             
  sex_code                  0.000000     0.000000     -9.05e-11   2.795828   -0.091211             
  foo_FOUNDER_INDICATOR     0.000000     0.000000      1.42e-08  -0.091211   14.316107             

====================
     Joint test
====================

  H0 ln likelihood foo_FOUNDER_INDICATOR without test covariates  -1853.566375  
  H1 ln likelihood foo_FOUNDER_INDICATOR with test covariates     -1852.759343  
                                                                                
  2 * |H0 - H1|                                                       1.614064  
  Degrees of freedom                                                         1  
  P-value                                                             0.203921  

===================================

     Model 'foo_PEDIGREE_SIZE'

===================================

============================
     Sample description
============================

  Number of individuals in dataset                                   604  
  Number of constituent pedigrees in dataset                          73  
  Number of singletons in dataset                                      3  
                                                                          
  Number of constituent pedigree members with complete information   432  
  Number of singletons with complete information                       2  
                                                                          

====================
     Covariates
====================

-------------------------------------------------------------------
  Name               Mean        Std. dev.  Min        Max         
-------------------------------------------------------------------
  sex_code             0.559908   0.496398   0.000000    1.000000  
  foo_PEDIGREE_SIZE   10.523041   3.699629   2.000000   21.000000  

========================================================================
     MAXIMIZATION RESULTS foo_PEDIGREE_SIZE without test covariates
========================================================================

----------------------------------------------------------------------
  Parameter       Estimate     S.E.        P-value     Deriv          
----------------------------------------------------------------------
  Variance components
          Random   300.036330   20.367820  < 1.00e-07  -0.0000000739  

  Other parameters
  Total variance   300.036330   20.367820  < 1.00e-07   0.0000005084  

       Intercept   131.181106    0.831461  < 1.00e-07   0.0000000000  

  Covariates
        sex_code    -4.323906    1.674965   0.009837    0.0000000000  
----------------------------------------------------------------------

Final ln likelihood: -1853.566375

==============================================================================
     VARIANCE-COVARIANCE MATRIX foo_PEDIGREE_SIZE without test covariates
==============================================================================

---------------------------------------------------------------------
                  Random       Total variance  Intercept  sex_code   
---------------------------------------------------------------------
  Random           414.848096   414.848096      0.000000   0.000000  
  Total variance   414.848096   414.848096      0.000000   0.000000  
  Intercept          0.000000     0.000000      0.691328   1.87e-08  
  sex_code           0.000000     0.000000      1.87e-08   2.805508  

=====================================================================
     MAXIMIZATION RESULTS foo_PEDIGREE_SIZE with test covariates
=====================================================================

-------------------------------------------------------------------------
  Parameter          Estimate     S.E.        P-value     Deriv          
-------------------------------------------------------------------------
  Variance components
             Random   298.703548   20.277290  < 1.00e-07  -0.0000001449  

  Other parameters
     Total variance   298.703548   20.277290  < 1.00e-07  -0.0000000206  

          Intercept   131.180995    0.829613  < 1.00e-07  -0.0000016319  

  Covariates
           sex_code    -4.166279    1.675111   0.012877    0.0000000000  
  foo_PEDIGREE_SIZE    -0.312738    0.224757   0.164090    0.0000000000  
-------------------------------------------------------------------------

Final ln likelihood: -1852.600463

===========================================================================
     VARIANCE-COVARIANCE MATRIX foo_PEDIGREE_SIZE with test covariates
===========================================================================

-------------------------------------------------------------------------------------------
                     Random       Total variance  Intercept  sex_code   foo_PEDIGREE_SIZE  
-------------------------------------------------------------------------------------------
  Random              411.168503   411.168503     -0.000152   4.08e-07  -8.09e-07          
  Total variance      411.168503   411.168503     -0.000152   4.08e-07  -8.09e-07          
  Intercept            -0.000152    -0.000152      0.688257   2.14e-08   1.92e-09          
  sex_code              4.08e-07     4.08e-07      2.14e-08   2.805998  -0.025464          
  foo_PEDIGREE_SIZE    -8.09e-07    -8.09e-07      1.92e-09  -0.025464   0.050516          

====================
     Joint test
====================

  H0 ln likelihood foo_PEDIGREE_SIZE without test covariates  -1853.566375  
  H1 ln likelihood foo_PEDIGREE_SIZE with test covariates     -1852.600463  
                                                                            
  2 * |H0 - H1|                                                   1.931824  
  Degrees of freedom                                                     1  
  P-value                                                         0.164559  

