


Reading Parameter File....................done.
Reading Marker Locus Description File.....done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.

  No analyses specified.
Performing FCOR default analysis...

Computing subtype correlations............done.
Computing standard errors.................done.
Writing output files......................done.

Analysis complete!



