



Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     4             1             M         .             .           
     4             2             F         .             .           
     4             3             F         1             2           
     4             4             F         1             2           
     4             5             F         1             2           
     4             6             M         1             2           
     5             1             M         .             .           
     5             2             F         .             .           
     5             3             F         1             2           
     5             4             F         1             2           


Markers for the first 10 individuals read from file: ped

     PED. ID       IND. ID       ABO         
     ------------  ------------  ------------
     4             1             A           
     4             2             A/B         
     4             3             A           
     4             4             A/B         
     4             5             A           
     4             6             A/B         
     5             1             A           
     5             2             A/B         
     5             3             O/O         
     5             4             A           

