pedigree
{
  delimiters = "\t"
  delimiter_mode = single
  individual_missing_value = "."

  sex_code, male = "M", female = "F", missing = ""

  pedigree_id = pedid
  individual_id = indid
  parent_id = dad
  parent_id = mom
  sex_field = sex

  trait = "proband", binary, affected = "1", unaffected = "0", missing = "."
  trait = "q1", missing = "0"

  string = dna_id

  marker = "Marker1 13", missing = "0"
  marker = "Marker2 18", missing = "0"
  marker = "Marker3 8", missing = "0"
  marker = "Marker4 13", missing = "0"
  marker = "Marker5 8", missing = "0"
  marker = "Marker6 9", missing = "0"
  marker = "Marker7 9", missing = "0"
  marker = "Marker8 8", missing = "."
}

marker
{
  allele_delimiter = "/"
}
