



Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     4             1             M         .             .           
     4             2             F         .             .           
     4             3             F         1             2           
     4             4             F         1             2           
     4             5             F         1             2           
     4             6             M         1             2           
     5             1             M         .             .           
     5             2             F         .             .           
     5             3             F         1             2           
     5             4             F         1             2           


Markers for the first 10 individuals read from file: ped

     PED. ID       IND. ID       Marker1 13    Marker2 18    Marker3 8     Marker4 13    Marker5 8     Marker6 9     Marker7 9     Marker8 8   
     ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
     4             1             0/0           0/0           0/0           0/0           0/0           0/0           0/0           ./.         
     4             2             0/0           0/0           0/0           0/0           0/0           0/0           0/0           ./.         
     4             3             0/0           0/0           3/6           7/8           1/2           2/7           2/7           1/6         
     4             4             0/0           0/0           3/8           7/8           1/2           2/7           2/7           1/6         
     4             5             0/0           0/0           3/8           7/8           2/2           2/7           2/7           1/6         
     4             6             0/0           0/0           3/8           7/8           1/3           2/7           2/4           1/7         
     5             1             0/0           0/0           0/0           0/0           0/0           0/0           0/0           ./.         
     5             2             0/0           0/0           0/0           0/0           0/0           0/0           0/0           ./.         
     5             3             2/5           3/11          3/6           7/8           1/2           2/7           2/7           1/6         
     5             4             5/5           3/11          3/8           7/8           1/2           2/7           2/7           1/6         

%MARKERINFO-W: No marker phenotype data for pedigree '4' at marker 'Marker1
               13'.
%MARKERINFO-W: No marker phenotype data for pedigree '4' at marker 'Marker2
               18'.
%MARKERINFO-W: No marker phenotype data for pedigree '6' at marker 'Marker2
               18'.
