


===============================
LODLINK Analysis 1 SUMMARY FILE
===============================


Options Selected
================
Main locus type                          trait
Main locus name                          segreg_analysis1

Lod scores                               no

Linkage tests                            yes
  Sex specific recombination fractions   no
  Assume homogeneity                     yes

Smith's test for homogeneity             no
  Sex specific recombination fractions   no

Morton's test for homogeneity            no
  Sex specific recombination fractions   no

Genotype probabilities                   no
  Sex specific recombination fractions   no


Results
=======




                  MLE                     Lod Score and Linkage Test    
                                          Using Recom. Fract. in [0, .5]
                                                                        
Locus             Recom       Recom       Lod         Chi         P-Value     P-Value     
                  Fract in    Fract in    Score       Square                  Upper       
                  [0, .5]     [0, 1]                  Stat                    Bound       
---------------   ---------   ---------   ---------   ---------   ---------   ---------   
T1                   0.0000        ---          177         816   < 1.0e-20   < 1.0e-20   
M1                   0.0044        ---         52.1         240   < 1.0e-20   < 1.0e-20   
M2                   0.0446        ---         31.1         143   < 1.0e-20   < 1.0e-20   
M3                   0.0643        ---         29.6         136   < 1.0e-20   < 1.0e-20   
M4                   0.2180        ---         6.31        29.1   3.509e-08   4.896e-07   
M5                   0.2292        ---         7.15        32.9   4.787e-09   7.084e-08   
M6                   0.3337        ---         1.54        7.11    0.003838     0.02862   
M7                   0.5000      0.5973           0        ---         ---         ---    
