=======================

     Freq Analysis

=======================

=======================
     Configuration
=======================

  Output file:                 freq           
  Founder weight:              Disabled       
  Max. likelihood estimation:  Enabled        
  Inbreeding coefficient:      Not estimated  

Note: A '*' by an MLE column indicates that the corresponding maximization may not have converged. Please review the detailed output file for more information.
=================================
     Allele frequencies 'm1'
=================================

----------------------------------------------------
  Allele  Founders only  Entire dataset  MLE        
----------------------------------------------------
  1        0.000000       0.687500        0.684796  
  2        1.000000       0.312500        0.315204  

=================================
     MAXIMIZATION RESULTS m1
=================================

--------------------------------------------------
  Parameter  Estimate   S.E.       Deriv          
--------------------------------------------------
  Alleles
          1   0.684796   0.186954   0.0000114247  
          2   0.315204   0.186954  -0.0000248210  
--------------------------------------------------

Final Log likelihood: -4.677551

=================================
     Allele frequencies 'm2'
=================================

----------------------------------------------------
  Allele  Founders only  Entire dataset  MLE        
----------------------------------------------------
  1        0.500000       0.666667        0.607624  
  2        0.500000       0.333333        0.392376  

=================================
     MAXIMIZATION RESULTS m2
=================================

--------------------------------------------------
  Parameter  Estimate   S.E.       Deriv          
--------------------------------------------------
  Alleles
          1   0.607624   0.178303   0.0000045706  
          2   0.392376   0.178303  -0.0000090483  
--------------------------------------------------

Final Log likelihood: -7.920528


