


%SIBPAL-W: The sex of individual 'I5' in pedigree 'F1' is believed to be male. 
           Sex code will be reset.
%SIBPAL-W: The sex of individual 'I7' in pedigree 'F1' is believed to be male. 
           Sex code will be reset.

Family structure information on the first 99 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     F1            I1            M         0             0           
     F1            I2            F         0             0           
     F1            I3            M         0             0           
     F1            I4            F         0             0           
     F1            I5            M         I1            I2          
     F1            I6            F         0             0           
     F1            I7            M         I3            I4          
     F1            I8            ?         I3            I4          
     F1            I9            F         I3            I4          
     F1            I10           F         I5            I6          
     F1            I11           M         I6            I7          
     F1            I12           F         I6            I7          
     F1            I13           M         I6            I7          
     F1            I14           F         I6            I7          
     F1            I15           M         I6            I7          
     F1            I16           M         0             0           
     F1            I17           M         I16           I9          
     F2            I1            M         0             0           
     F2            I2            F         0             0           
     F2            I3            M         0             0           
     F2            I4            F         0             0           
     F2            I5            M         I1            I2          
     F2            I6            F         0             0           
     F2            I7            M         I3            I4          
     F2            I8            M         I3            I4          
     F2            I9            F         I3            I4          
     F2            I10           F         I5            I6          
     F2            I11           M         I6            I7          
     F2            I12           F         I6            I7          
     F2            I13           M         I6            I7          
     F2            I14           F         I6            I7          
     F2            I15           M         I6            I7          
     F2            I16           M         0             0           
     F2            I17           M         I16           I9          
     F3            I1            M         0             0           
     F3            I2            F         0             0           
     F3            I3            M         0             0           
     F3            I4            F         I1            I2          
     F3            I5            M         I1            I2          
     F3            I6            F         0             0           
     F3            I7            M         I3            I4          
     F3            I8            F         I5            I6          
     F3            I9            F         I7            I8          


Phenotypes for the first 99 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         Trait1              
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------
     F1            I1            0                     1                     1                     17                    2                   
     F1            I2            1                     1                     1                     17                    6                   
     F1            I3            0                     1                     1                     17                    4                   
     F1            I4            1                     1                     1                     17                    4                   
     F1            I5            0                     1                     0                     17                    4                   
     F1            I6            1                     1                     1                     17                    6                   
     F1            I7            0                     1                     0                     17                    4                   
     F1            I8                                  1                     0                     17                    2                   
     F1            I9            1                     1                     0                     17                    6                   
     F1            I10           1                     1                     0                     17                    6                   
     F1            I11           0                     1                     0                     17                    6                   
     F1            I12           1                     1                     0                     17                    4                   
     F1            I13           0                     1                     0                     17                    4                   
     F1            I14           1                     1                     0                     17                    6                   
     F1            I15           0                     1                     0                     17                    4                   
     F1            I16           0                     1                     1                     17                    2                   
     F1            I17           0                     1                     0                     17                    4                   
     F2            I1            0                     1                     1                     17                    4                   
     F2            I2            1                     1                     1                     17                    2                   
     F2            I3            0                     1                     1                     17                    4                   
     F2            I4            1                     1                     1                     17                    6                   
     F2            I5            0                     1                     0                     17                    4                   
     F2            I6            1                     1                     1                     17                    4                   
     F2            I7            0                     1                     0                     17                    4                   
     F2            I8            0                     1                     0                     17                    6                   
     F2            I9            1                     1                     0                     17                    6                   
     F2            I10           1                     1                     0                     17                    2                   
     F2            I11           0                     1                     0                     17                    6                   
     F2            I12           1                     1                     0                     17                    4                   
     F2            I13           0                     1                     0                     17                    4                   
     F2            I14           1                     1                     0                     17                    4                   
     F2            I15           0                     1                     0                     17                    XX                  
     F2            I16           0                     1                     1                     17                    6                   
     F2            I17           0                     1                     0                     17                    6                   
     F3            I1            0                     1                     1                     9                     4                   
     F3            I2            1                     1                     1                     9                     2                   
     F3            I3            0                     1                     1                     9                     4                   
     F3            I4            1                     1                     0                     9                     6                   
     F3            I5            0                     1                     0                     9                     4                   
     F3            I6            1                     1                     1                     9                     4                   
     F3            I7            0                     1                     0                     9                     4                   
     F3            I8            1                     1                     0                     9                     6                   
     F3            I9            1                     1                     0                     9                     6                   

%SIBPAL-W: Only one marker present in ibd file.  Changed regression type to
           single_marker_regression.
