


Reading Parameter File....................done.
Reading Pedigree File.....................
              from 21.dat.................done.
Sorting Pedigrees.........................done.
Reading pairs.............................done.
Sorting pairs.............................done.

LODPAL analysis.......  1

Reading Pair Information File.............
              from pair.in................done.
Computing multipoint lod scores...........done.

LODPAL analysis.......  2

Reading Pair Information File.............
              from pair.in................done.
Computing multipoint lod scores...........done.

Analysis complete!



