


Reading Parameter File....................done.
Reading Pedigree File.....................
              from data2.ped..............done.
Sorting Pedigrees.........................done.

FCOR analysis........  1

Computing subtype correlations............done.
Computing standard errors.................done.

Computing main type correlations..........done.
Computing standard errors.................done.
Writing output files......................done.

Analysis complete!



