


Reading Parameter File....................done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Building pairs............................done.

RELPAL analysis.......  1
  Performing first level test.............done.
  Performing first level test.............done.
  Performing first level test.............done.

Analysis complete!



