


==============================================================================================
  Two-Level Haseman-Elston Regression Analysis for General Pedigree 

  - First (Individual) Level Wald Tests Detailed Output
==============================================================================================

  Traits : (1) - aff, Binary, affected = '1' , unaffected = '0'
           (2) - SEX_CODE, Binary, affected = '0' , unaffected = '1'
           (3) - halfsib, Quantitative

  Legend :
    *   - significance  .05 level
    **  - significance  .01 level
    *** - significance .001 level

==============================================================================================
Test 1
==============================================================================================
-----
Model
-----

aff, SEX_CODE, halfsib ~ [Intercept + age] + POLYGENIC_EFF + RANDOM_EFF

------------
Sample Count
------------

Number of individuals used at first level     = 565
Number of relative pairs used at second level = 508

--------------------
Estimates from Model
--------------------

Test                                                                             Nominal    
Variable                      Estimate Variance-Covariance             Chi-sq.   P-value    
------------------------- ------------ ----------------------------- --------- ---------    
age(1)                         -0.0079    0.0000    0.0000    0.0000  252.6705 0.0000000 ***
age(2)                         -0.0080    0.0000    0.0000    0.0000
age(3)                         -0.0154    0.0000    0.0000    0.0000

==============================================================================================
Test 2
==============================================================================================
-----
Model
-----

aff, SEX_CODE, halfsib ~ [Intercept + ATA103C06_ADD_245] + POLYGENIC_EFF + RANDOM_EFF

------------
Sample Count
------------

Number of individuals used at first level     = 110
Number of relative pairs used at second level = 85

--------------------
Estimates from Model
--------------------

Test                                                                             Nominal    
Variable                      Estimate Variance-Covariance             Chi-sq.   P-value    
------------------------- ------------ ----------------------------- --------- ---------    
ATA103C06_ADD_245(1)           -0.0055    0.0127   -0.0020   -0.0031    0.2928 0.9613859    
ATA103C06_ADD_245(2)            0.0614   -0.0020    0.0183    0.0030
ATA103C06_ADD_245(3)            0.0283   -0.0031    0.0030    0.0051

==============================================================================================
Test 3
==============================================================================================
-----
Model
-----

aff, SEX_CODE, halfsib ~ [Intercept + ATA34E08_ADD_161] + POLYGENIC_EFF + RANDOM_EFF

------------
Sample Count
------------

Number of individuals used at first level     = 373
Number of relative pairs used at second level = 333

--------------------
Estimates from Model
--------------------

Test                                                                             Nominal    
Variable                      Estimate Variance-Covariance             Chi-sq.   P-value    
------------------------- ------------ ----------------------------- --------- ---------    
ATA34E08_ADD_161(1)            -0.0324    0.0018   -0.0006   -0.0006    0.6354 0.8882806    
ATA34E08_ADD_161(2)             0.0146   -0.0006    0.0030    0.0007
ATA34E08_ADD_161(3)             0.0057   -0.0006    0.0007    0.0014

==============================================================================================

