


==============================================================================================
  Two-Level Haseman-Elston Regression Analysis for General Pedigree 

  - First (Individual) Level Wald Tests Detailed Output
==============================================================================================

  Traits : (1) - aff, Binary, affected = '1' , unaffected = '0'
           (2) - SEX_CODE, Binary, affected = '0' , unaffected = '1'
           (3) - halfsib, Quantitative

  Legend :
    *   - significance  .05 level
    **  - significance  .01 level
    *** - significance .001 level

==============================================================================================
Test 1
==============================================================================================
-----
Model
-----

aff, SEX_CODE, halfsib ~ [Intercept + age] + POLYGENIC_EFF + RANDOM_EFF

------------
Sample Count
------------

Number of individuals used at first level     = 565
Number of relative pairs used at second level = 508

--------------------
Estimates from Model
--------------------

Test                                                                             Nominal    
Variable                      Estimate Variance-Covariance             Chi-sq.   P-value    
------------------------- ------------ ----------------------------- --------- ---------    
age(1)                         -0.0081    0.0000    0.0000    0.0000  267.2774 0.0000000 ***
age(2)                         -0.0083    0.0000    0.0000    0.0000
age(3)                         -0.0155    0.0000    0.0000    0.0000

==============================================================================================
Test 2
==============================================================================================
-----
Model
-----

aff, SEX_CODE, halfsib ~ [Intercept + ATA103C06_ADD_245] + POLYGENIC_EFF + RANDOM_EFF

------------
Sample Count
------------

Number of individuals used at first level     = 566
Number of relative pairs used at second level = 511

--------------------
Estimates from Model
--------------------

Test                                                                             Nominal    
Variable                      Estimate Variance-Covariance             Chi-sq.   P-value    
------------------------- ------------ ----------------------------- --------- ---------    
ATA103C06_ADD_245(1)           -0.0154    0.0008   -0.0003   -0.0003    1.6421 0.6498907    
ATA103C06_ADD_245(2)            0.0468   -0.0003    0.0015    0.0004
ATA103C06_ADD_245(3)            0.0057   -0.0003    0.0004    0.0008

==============================================================================================
Test 3
==============================================================================================
-----
Model
-----

aff, SEX_CODE, halfsib ~ [Intercept + ATA34E08_ADD_161] + POLYGENIC_EFF + RANDOM_EFF

------------
Sample Count
------------

Number of individuals used at first level     = 553
Number of relative pairs used at second level = 484

--------------------
Estimates from Model
--------------------

Test                                                                             Nominal    
Variable                      Estimate Variance-Covariance             Chi-sq.   P-value    
------------------------- ------------ ----------------------------- --------- ---------    
ATA34E08_ADD_161(1)            -0.0318    0.0005    0.0004    0.0003    2.0028 0.5718203    
ATA34E08_ADD_161(2)            -0.0220    0.0004    0.0010    0.0003
ATA34E08_ADD_161(3)            -0.0147    0.0003    0.0003    0.0006

==============================================================================================

