


==============================
LODLINK Analysis 1 DETAIL FILE
==============================


Options Selected
================
Main locus type                          trait
Main locus name                          T1

Lod scores                               no

Linkage tests                            no

Smith's test for homogeneity             no

Morton's test for homogeneity            yes

  Sex-specific recombination fractions   no

  Groups Selected
  ===============
  group 1 pedigrees                1   10   11   12   13   14   15   16   17   18   19   2   20   21   22   23   24   25   3   4   5   6   7   8   9   
  group 2 pedigrees                26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   

Genotype probabilities                   no


Results
=======

                  Morton's Homogeneity Test


                  Group 1

Locus             Recom          Natural Log   
                  Fract in       Maximum       
                  [0, 1]         Likelihood    
---------------   ------------   -----------   
M1                    0.015334   -436.381230
M2                    0.025126   -618.539644


                  Group 2

Locus             Recom          Natural Log   
                  Fract in       Maximum       
                  [0, 1]         Likelihood    
---------------   ------------   -----------   
M1                    0.359180   -453.706880
M2                    0.431460   -623.037459


