


Reading Parameter File....................done.
Reading Marker Locus Description File.....done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Generating statistics.....................
Parsing LODLINK analyses ...


Parsing new analysis block ...


Parsing of LODLINK Analysis 1 complete.  Analysis valid.
------------------------------------------------------------------------------
Performing Morton's test for homogeneity ...
done.

Analysis complete!


