Unable to open Marker Locus Description file 'locus'. Please check your file.
Unable to open Marker Locus Description file 'locus'. Please check your file.
Unable to open Marker Locus Description file 'locus.typ'. Please check your
file.
Unable to open Marker Locus Description file 'locus.pen'. Please check your
file.
Unable to open Marker Locus Description file 'inval.typ'. Please check your
file.
