



Family structure information on the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     2             1             F         0             0           
     1             1             F         0             0           
     1             2             M         0             0           
     1             3             M         1             2           
     1             4             M         1             2           


Phenotypes for the first 20 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         rep                 
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------
     2             1             1                     0                     1                     1                     -                   
     1             1             1                     1                     1                     4                     -                   
     1             2             0                     1                     1                     4                     -                   
     1             3             0                     1                     0                     4                     -                   
     1             4             0                     1                     0                     4                     x                   


Markers for the first 20 individuals read from file: ped

     PED. ID       IND. ID       M1            M2          
     ------------  ------------  ------------  ------------
     2             1             1/1           1/1         
     1             1             ?/?           ?/?         
     1             2             1/3           1/2         
     1             3             1/2           1/1         
     1             4             1/2           1/3         

%DECIPHER-I: Mapping function not specified.  Using Haldane Mapping Function.

  Performing analysis: Analysis 1
  ===========================================================================

    Total population. 
      Determining possible haplotype combinations ................... done.
      Maximizing likelihood ......................................... done. 

  ===========================================================================

