
----------   test 1   ----------

mom: ax/ax
dad: by/ax
kid: ax/bx


Maximum likelihood estimation values - 
Sex-specific:           false
Uses alpha:             false

INPUT:

group_name        mle sub model
param_name        average recombination fraction
initial_estimate  0.25
initial_type      Independent
lower_bound       0
upper_bound       1

transition probability:  0.125

----------   test 2   ----------

mom: bx/ay
dad: bx/ay
kid: ax/ax


Maximum likelihood estimation values - 
Sex-specific:           true
Uses alpha:             false

INPUT:

group_name        mle sub model
param_name        male recombination fraction
initial_estimate  0.2
initial_type      Independent
lower_bound       0
upper_bound       1

group_name        mle sub model
param_name        female recombination fraction
initial_estimate  0.3
initial_type      Independent
lower_bound       0
upper_bound       1

transition probability:  0.015

----------   test 3   ----------

mom: bx/ay
dad: bx/ay
kid: ax/az


Maximum likelihood estimation values - 
Sex-specific:           true
Uses alpha:             false

INPUT:

group_name        mle sub model
param_name        male recombination fraction
initial_estimate  0.2
initial_type      Independent
lower_bound       0
upper_bound       1

group_name        mle sub model
param_name        female recombination fraction
initial_estimate  0.3
initial_type      Independent
lower_bound       0
upper_bound       1

transition probability:  0

----------   test 4   ----------

mom: bx/ay
dad: by/ax
kid: ax/by


Maximum likelihood estimation values - 
Sex-specific:           true
Uses alpha:             false

INPUT:

group_name        mle sub model
param_name        male recombination fraction
initial_estimate  0.2
initial_type      Independent
lower_bound       0
upper_bound       1

group_name        mle sub model
param_name        female recombination fraction
initial_estimate  0.3
initial_type      Independent
lower_bound       0
upper_bound       1

transition probability:  0.06
