
Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             F                                   
     1             2             M                                   
     1             3             M         1             2           
     1             4             F         1             2           
     1             5             M                                   
     1             6             F         4             5           


Phenotypes for the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         DISEASE               HEMATOCRIT            t                     u                     v                     w                     x                     y                     z                   
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             1                     1                     1                     6                     1                     30                                                                                                                                                                            
     1             2             0                     1                     1                     6                     0                     40                                                                                                                                                                            
     1             3             0                     1                     0                     6                     0                     27.1                                                                                                                                                                          
     1             4             1                     1                     0                     6                     1                     39                                                                                                                                                                            
     1             5             0                     1                     1                     6                     0                     37.6                                                                                                                                                                          
     1             6             1                     1                     0                     6                     1                     41.1                                                                                                                                                                          

%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 1 New Analysis Block 1 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:prev_estimate sub-block not relevant for continuous
                          trait.  Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 2 New Analysis Block 2 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:prev_estimate sub-block not relevant for continuous
                          trait.  Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 3 New Analysis Block 3 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:prev_estimate sub-block not relevant for continuous
                          trait.  Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 4 New Analysis Block 4 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 5 New Analysis Block 5 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Critical:Age is required for prevalence estimates when age of
                           onset is used.  Skipping analysis ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 6 New Analysis Block 6 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 7 New Analysis Block 7 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 8 New Analysis Block 8 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:prev_constraint sub-block not relevant for continuous
                          trait.  Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 9 New Analysis Block 9 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:prev_constraint sub-block not relevant for continuous
                          trait.  Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 10 New Analysis Block 10 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:prev_constraint sub-block not relevant for continuous
                          trait.  Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 11 New Analysis Block 11 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:prev_constraint sub-block not relevant for continuous
                          trait.  Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 12 New Analysis Block 12 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:prev_constraint sub-block not relevant for continuous
                          trait.  Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 13 New Analysis Block 13 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:prev_constraint sub-block not relevant for continuous
                          trait.  Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 14 New Analysis Block 14 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Critical:Attribute, R, in prev_constraint sub-block missing
                           or invalid.  Skipping analysis ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 15 New Analysis Block 15 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Critical:Number of affected persons, R, may not be greater
                           than sample size, N, in prev_constraint sub-block. 
                           Skipping analysis ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 16 New Analysis Block 16 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 17 New Analysis Block 17 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:Covariate name not specified in prev_constraint
                          sub-block.  Covariate will be ignored.
%TESTSEGREGPARSER-Error:Value for 'val'  attribute of covariate in
                        prev_constraint sub-block not understood.  Ignoring ...
%TESTSEGREGPARSER-Critical:covariate 'x' specified in prev_constraint sub-block
                           must also be a specifed in mean_cov sub-block,
                           suscept_cov sub-block or var_cov sub-block. Skipping
                           analysis ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 18 New Analysis Block 18 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Critical:covariate 'x' specified in prev_constraint sub-block
                           must also be a specifed in mean_cov sub-block,
                           suscept_cov sub-block or var_cov sub-block. Skipping
                           analysis ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 19 New Analysis Block 19 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:mean_cov sub-block not relevant for binary trait. 
                          Ignoring ...
%TESTSEGREGPARSER-Critical:covariate 'y' specified in prev_constraint sub-block
                           must also be a specifed in mean_cov sub-block,
                           suscept_cov sub-block or var_cov sub-block. Skipping
                           analysis ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 20 New Analysis Block 20 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 21 New Analysis Block 21 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 22 New Analysis Block 22 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 23 New Analysis Block 23 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:Both prev_constraint and prev_constraints sub-blocks
                        detected.  Will ignore prev_constraint sub-block.
%TESTSEGREGPARSER-Warning:duplicate constraint detected in prev_constraints
                          sub-block.  Second copy will be ignored.
%TESTSEGREGPARSER-Error:Parameter 'INVALID_CONSTRAINT' in prev_constraints
                        sub-block not recognized.  Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 24 New Analysis Block 24 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:duplicate constraint detected in prev_constraints
                          sub-block.  Second copy will be ignored.
%TESTSEGREGPARSER-Error:Parameter 'INVALID_CONSTRAINT' in prev_constraints
                        sub-block not recognized.  Ignoring ...
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Error:---------- 25 New Analysis Block 25 ---------- 
%TESTSEGREGPARSER-Error:
%TESTSEGREGPARSER-Warning:duplicate constraint detected in prev_constraints
                          sub-block.  Second copy will be ignored.
%TESTSEGREGPARSER-Error:Parameter 'INVALID_CONSTRAINT' in prev_constraints
                        sub-block not recognized.  Ignoring ...
