


Reading Parameter File....................done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Reading pairs.............................done.
Sorting pairs.............................done.

LODPAL analysis.......  1

Computing multipoint lod scores...........done.

LODPAL analysis.......  2

Reading Pair Information File.............
              from pros1xwt.in............done.
Computing multipoint lod scores...........done.

Analysis complete!



