



Family structure information on the first 100 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     0             10            M         0             0           
     0             11            F         0             0           
     0             12            M         10            11          
     0             20            M         0             0           
     0             21            F         0             0           
     0             22            M         20            21          
     0             23            M         20            21          
     0             30            M         0             0           
     0             31            F         0             0           
     0             32            M         30            31          
     0             40            M         0             0           
     0             41            F         0             0           
     0             42            M         40            41          
     0             43            M         40            41          
     0             44            M         40            41          
     0             50            M         0             0           
     0             51            F         0             0           
     0             52            M         50            51          
     0             53            M         50            51          
     0             60            M         0             0           
     0             61            F         0             0           
     0             62            M         60            61          


Phenotypes for the first 100 individuals read from file: ped

     PED. ID       IND. ID       SEX_CODE              t2                  
     ------------  ------------  --------------------  --------------------
     0             10            0                     2                   
     0             11            1                     1                   
     0             12            0                     2                   
     0             20            0                     1                   
     0             21            1                     2                   
     0             22            0                     1                   
     0             23            0                     2                   
     0             30            0                     1                   
     0             31            1                     2                   
     0             32            0                     1                   
     0             40            0                     2                   
     0             41            1                     1                   
     0             42            0                     2                   
     0             43            0                     1                   
     0             44            0                     2                   
     0             50            0                     1                   
     0             51            1                     2                   
     0             52            0                     1                   
     0             53            0                     2                   
     0             60            0                     1                   
     0             61            1                     2                   
     0             62            0                     1                   


Markers for the first 100 individuals read from file: ped

     PED. ID       IND. ID       ds          
     ------------  ------------  ------------
     0             10            1/1         
     0             11            1/1         
     0             12            1/1         
     0             20            1/1         
     0             21            1/2         
     0             22            1/1         
     0             23            1/2         
     0             30            1/1         
     0             31            2/2         
     0             32            1/2         
     0             40            1/2         
     0             41            1/2         
     0             42            1/1         
     0             43            1/2         
     0             44            2/2         
     0             50            1/2         
     0             51            2/2         
     0             52            1/2         
     0             53            2/2         
     0             60            2/2         
     0             61            2/2         
     0             62            2/2         

%FREQ-W: Pedigree '0' has 6 constituent pedigrees which are disjoint from one
         another.  This may not be intended.  Results may be incorrect.  See
         manual for details on constituent pedigrees.

New phenotypes for individuals created by function block(s) :

     PED. ID       IND. ID       M_tai                 M_utai              
     ------------  ------------  --------------------  --------------------
     0             10                                                      
     0             11                                                      
     0             12                                                      
     0             20                                                      
     0             21                                                      
     0             22            1                     0                   
     0             23            0                     1                   
     0             30                                                      
     0             31                                                      
     0             32                                                      
     0             40                                                      
     0             41                                                      
     0             42            1                     0                   
     0             43                                                      
     0             44            0                     1                   
     0             50                                                      
     0             51                                                      
     0             52            1                     0                   
     0             53            0                     1                   
     0             60                                                      
     0             61                                                      
     0             62                                                      


