


%PEDINFO-E: Error(s) building pedigree '2': 3 errors.
%PEDINFO-W: Both parents '1' and '2' have unknown sex and cannot be inferred.
%PEDINFO-W: Both parents '3' and '4' have unknown sex and cannot be inferred.
%PEDINFO-W: Both parents '5' and '6' have unknown sex and cannot be inferred.

Family structure information on the first 100 individuals read from file: dat

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             F                                   
     1             2             M                                   
     1             3             M                                   
     1             4             F         1             2           
     1             5             M         1             2           
     1             6             F                                   
     1             7             F         3             4           
     1             8             F         5             6           
     2             1                                                 
     2             2                                                 
     2             3                                                 
     2             4                       1             2           
     2             5                       1             2           
     2             6                                                 
     2             7             F         3             4           
     2             8             F         5             6           


Phenotypes for the first 100 individuals read from file: dat

     PED. ID       IND. ID       SEX_CODE              FAMILIAL_INDICATOR    FOUNDER_INDICATOR     PEDIGREE_SIZE         disease               HEMATOCRIT          
     ------------  ------------  --------------------  --------------------  --------------------  --------------------  --------------------  --------------------
     1             1             1                     1                     1                     8                     1                     30                  
     1             2             0                     1                     1                     8                     0                     40                  
     1             3             0                     1                     1                     8                     0                     27.1                
     1             4             1                     1                     0                     8                     0                     27.1                
     1             5             0                     1                     0                     8                     1                     39                  
     1             6             1                     1                     1                     8                     1                     41.1                
     1             7             1                     1                     0                     8                     0                     27.1                
     1             8             1                     1                     0                     8                     0                     27.1                
     2             1                                   1                     1                     8                     1                     30                  
     2             2                                   1                     1                     8                     0                     40                  
     2             3                                   1                     1                     8                     0                     27.1                
     2             4                                   1                     0                     8                     0                     27.1                
     2             5                                   1                     0                     8                     1                     39                  
     2             6                                   1                     1                     8                     1                     41.1                
     2             7             1                     1                     0                     8                     0                     27.1                
     2             8             1                     1                     0                     8                     0                     27.1                

%PEDINFO-E: Errors appear in pedigree data. Results may be incomplete.

New phenotypes for individuals created by function block(s) :

     PED. ID       IND. ID       a                   
     ------------  ------------  --------------------
     1             1             0                   
     1             2             0                   
     1             3             0                   
     1             4             0                   
     1             5             0                   
     1             6             0                   
     1             7             1                   
     1             8             -1                  
     2             1             0                   
     2             2             0                   
     2             3             0                   
     2             4             0                   
     2             5             0                   
     2             6             0                   
     2             7             0                   
     2             8             0                   


