





Family structure information on the first 10 individuals read from file: ped

     PED. ID       IND. ID       SEX       PARENT1       PARENT2     
     ------------  ------------  --------  ------------  ------------
     1             1             F                                   
     1             2             M                                   
     2             3             F                                   
     1             4             M         1             2           
     2             4             M                                   
     1             5             F         1             2           
     3             5             F                                   
     3             6             M                                   
     2             7             F         3             4           
     2             8             M         3             4           


Markers for the first 10 individuals read from file: ped

     PED. ID       IND. ID       M1            M2          
     ------------  ------------  ------------  ------------
     1             1             A/B           C/D         
     1             2             B/B           C/C         
     2             3             A/B           C/D         
     1             4             B/B           C/C         
     2             4             B/B           C/C         
     1             5             B/B           C/C         
     3             5             B/B           C/C         
     3             6             A/B           C/D         
     2             7             A/B           C/D         
     2             8             B/B           C/D         

