


==============================
LODLINK Analysis 1 DETAIL FILE
==============================


Options Selected
================
Main locus type                          marker
Main locus name                          M1

Lod scores                               yes

  Recombination Fractions Selected
  ================================
  Sex averaged         0.0000         0.0100         0.0500         0.1000         0.2000         0.3000         0.4000   

Linkage tests                            no

Smith's test for homogeneity             no

Morton's test for homogeneity            no

Genotype probabilities                   no


Results
=======

                  Lod Scores By Constituent Pedigree      
                  Non-Sex-Specific Recombination Fractions
                                                          

                  Constituent Pedigree in Pedigree 1 Containing Member 1

Locus             0.0000         0.0100         0.0500         0.1000         0.2000         0.3000         0.4000         
---------------   ------------   ------------   ------------   ------------   ------------   ------------   ------------   
M2                    0.301030       0.292345       0.257679       0.214844       0.133539       0.064458       0.017033   


                  Constituent Pedigree in Pedigree 2 Containing Member 3

Locus             0.0000         0.0100         0.0500         0.1000         0.2000         0.3000         0.4000         
---------------   ------------   ------------   ------------   ------------   ------------   ------------   ------------   
M2                   -Infinity      -1.402305      -0.721246      -0.443697      -0.193820      -0.075721      -0.017729   


                  Constituent Pedigree in Pedigree 3 Containing Member 6

Locus             0.0000         0.0100         0.0500         0.1000         0.2000         0.3000         0.4000         
---------------   ------------   ------------   ------------   ------------   ------------   ------------   ------------   
M2                    0.301030       0.292345       0.257679       0.214844       0.133539       0.064458       0.017033   


                  Constituent Pedigree in Pedigree 4 Containing Member 10

Locus             0.0000         0.0100         0.0500         0.1000         0.2000         0.3000         0.4000         
---------------   ------------   ------------   ------------   ------------   ------------   ------------   ------------   
M2                    0.301030       0.292345       0.257679       0.214844       0.133539       0.064458       0.017033   


                  Constituent Pedigree in Pedigree 5 Containing Member 12

Locus             0.0000         0.0100         0.0500         0.1000         0.2000         0.3000         0.4000         
---------------   ------------   ------------   ------------   ------------   ------------   ------------   ------------   
M2                   -Infinity      -1.402305      -0.721246      -0.443697      -0.193820      -0.075721      -0.017729   


                  Constituent Pedigree in Pedigree 6 Containing Member 15

Locus             0.0000         0.0100         0.0500         0.1000         0.2000         0.3000         0.4000         
---------------   ------------   ------------   ------------   ------------   ------------   ------------   ------------   
M2                   -Infinity      -1.402305      -0.721246      -0.443697      -0.193820      -0.075721      -0.017729   


