


===============================
LODLINK Analysis 2 SUMMARY FILE
===============================


Options Selected
================
Main locus type                          marker
Main locus name                          M1

Lod scores                               yes

  Recombination Fractions Selected
  ================================
  Male                 0.3000         0.4000         0.4000         0.4000         0.5000   
  Female               0.1000         0.0000         0.1000         0.2000         0.1000   

Linkage tests                            no

Smith's test for homogeneity             no

Morton's test for homogeneity            no

Genotype probabilities                   no


Results
=======

                  Lod Scores                                  
                  Sex-Specific Recombination Fractions        
                  Male Recom - 1st Row, Female Recom - 2nd Row

                  0.3000         0.4000         0.4000         0.4000         0.5000         
Locus             0.1000         0.0000         0.1000         0.2000         0.1000         
---------------   ------------   ------------   ------------   ------------   ------------   
M2                   -0.619356      -Infinity      -0.656213      -0.237763      -0.672551   
