


Reading Parameter File....................done.
Reading Marker Locus Description File.....done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.
Reading Genome Description File...........done.

GENIBD analysis.......  1

===========================================================================
Analysis 1 : Singlepoint analysis on regions (CHR3, X):
        * - Pedigrees with loops will not be processed.
===========================================================================

  Processing Region: CHR3
  =======================================

  Analysis 1: Pedigree 7
        Generating Single Point Likelihoods....................Done.


  Processing Region: X
  =======================================

  Analysis 1: Pedigree 7
        Generating Single Point Likelihoods....................Done.


GENIBD analysis.......  2

===========================================================================
Analysis 2 : Multipoint analysis on regions (CHR3, X):
        * - Maximum size for exact method is set to 18.
===========================================================================

  Processing Region: CHR3
  =======================================

  Analysis 2: Pedigree 7
        Generating Marker Likelihoods      ....................Done.
        Generating Multipoint Combined Info....................Done.
        Generating Multipoint IBDs         ....................Done.


  Processing Region: X
  =======================================

  Analysis 2: Pedigree 7
        Generating Marker Likelihoods      ....................Done.
        Generating Multipoint Combined Info....................Done.
        Generating Multipoint IBDs         ....................Done.


Analysis complete!



