


Reading Parameter File....................done.
Reading Marker Locus Description File.....done.
Reading Pedigree File.....................
              from ped....................done.
Sorting Pedigrees.........................done.

MARKERINFO analysis.......

Processing pedigree '10001'...............done.
Processing pedigree '10002'...............done.
Processing pedigree '10003'...............done.
Processing pedigree '10004'...............done.
Processing pedigree '10005'...............done.
Processing pedigree '10006'...............done.
Processing pedigree '10007'...............done.
Processing pedigree '10008'...............done.
Processing pedigree '10009'...............done.
Processing pedigree '10010'...............done.
Processing pedigree '10011'...............done.
Processing pedigree '10012'...............done.
Processing pedigree '10013'...............done.
Processing pedigree '10014'...............done.
Processing pedigree '10015'...............done.
Processing pedigree '10016'...............done.
Processing pedigree '10017'...............done.
Processing pedigree '10018'...............done.
Processing pedigree '10019'...............done.
Processing pedigree '10020'...............done.
Processing pedigree '10021'...............done.
Processing pedigree '10022'...............done.
Processing pedigree '10023'...............done.
Processing pedigree '10024'...............done.
Processing pedigree '10025'...............done.
Processing pedigree '10026'...............done.
Processing pedigree '10027'...............done.
Processing pedigree '10028'...............done.
Processing pedigree '10029'...............done.
Processing pedigree '10030'...............done.
Processing pedigree '10031'...............done.
Processing pedigree '10032'...............done.
Processing pedigree '10033'...............done.
Processing pedigree '10034'...............done.

Analysis complete!



