=================

     Results

=================

==============================
     Analysis description
==============================

  Title                        se____me                      
  Primary Trait                sqrtdbh (Quantitative)        
  Allow averaging              Enabled                       
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  

======================================
     Transformation configuration
======================================



Note: No transformation applied.

=======================
     Summary table
=======================

----------------------------------------------------------------------------------------
  Model      Intercept  Test cov.  Estimate   Std. err.  P-value (Wald)  P-value (LRT)  
----------------------------------------------------------------------------------------
  Alternate   5.021178  apres       0.255691   0.144260   0.076322        0.076788      
----------------------------------------------------------------------------------------

Note: Models with an asterisk (*) may not have converged.

================================
     Complete summary table
================================

----------------------------------------------------------------------------------------
  Model      Intercept  Test cov.  Estimate   Std. err.  P-value (Wald)  P-value (LRT)  
----------------------------------------------------------------------------------------
  Alternate   5.021178  apres       0.255691   0.144260   0.076322        0.076788      
----------------------------------------------------------------------------------------

Note: Models with an asterisk (*) may not have converged.

Note: See .det file for more information about each model

