=================

     Results

=================

Note: P-values for variance components and proportions are one-sided.  All others are two-sided.
The null hypothesis for transformation parameters is 'no transformation.'


==============================
     Analysis description
==============================

  Title                        se____me                      
  Primary Trait                sqrtdbh (Quantitative)        
  Allow averaging              Enabled                       
  Omit complete summary table  Disabled                      
  Summary table display order  By LRT p-value                
  Summary filter               Show no more than 10 results  

======================================
     Transformation configuration
======================================



Note: No transformation applied.

===========================

     Model 'Alternate'

===========================

============================
     Sample description
============================

  Number of individuals in dataset                                   942  
  Number of constituent pedigrees in dataset                           7  
  Number of singletons in dataset                                      0  
                                                                          
  Number of constituent pedigree members with complete information   499  
  Number of singletons with complete information                       0  
                                                                          

====================
     Covariates
====================

-----------------------------------------------------
  Name   Mean       Std. dev.  Min        Max        
-----------------------------------------------------
  apres   0.512146   0.499852   0.000000   1.000000  

================================================================
     MAXIMIZATION RESULTS Alternate without test covariates
================================================================

-----------------------------------------------------------------------------
  Parameter                 Estimate   S.E.       P-value     Deriv          
-----------------------------------------------------------------------------
  Variance components
                    Random   1.186789   0.530258   0.025212    0.0001340984  
                   Marital   0.142458   0.264096   0.294799    0.0003371748  
                   Sibling   1.364275   0.209973  < 1.00e-07   0.0000286689  

  Other parameters
            Total variance   2.693522   0.331429  < 1.00e-07   0.0000700321  

  Residual familial correlations
        Res full sibs corr   0.506502   0.068637  < 1.00e-07   0.0000000000  
  Res marital(spouse) corr   0.052889   0.103179   0.608234    0.0000000000  

  Environmental intraclass correlations
  Env marital(spouse) corr   0.052889   0.103179   0.608234    0.0000000000  
        Env full sibs corr   0.506502   0.068637  < 1.00e-07   0.0000000000  

                 Intercept   5.014864   0.098155  < 1.00e-07   0.0000000000  
-----------------------------------------------------------------------------

Final ln likelihood: -2372.144513

======================================================================
     VARIANCE-COVARIANCE MATRIX Alternate without test covariates
======================================================================

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            Random     Marital    Sibling    Total variance  Res full sibs corr  Res marital(spouse) corr  Env marital(spouse) corr  Env full sibs corr  Intercept  
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Random                     0.281173  -0.136094  -0.004931   0.140148       -0.028185           -0.053278                 -0.053278                 -0.028185           -0.001681  
  Marital                   -0.136094   0.069747  -0.001557  -0.067904        0.012191            0.027228                  0.027228                  0.012191            0.001031  
  Sibling                   -0.004931  -0.001557   0.044089   0.037601        0.009298           -0.001316                 -0.001316                  0.009298           -0.000818  
  Total variance             0.140148  -0.067904   0.037601   0.109845       -0.006696           -0.027367                 -0.027367                 -0.006696           -0.001468  
  Res full sibs corr        -0.028185   0.012191   0.009298  -0.006696        0.004711            0.004658                  0.004658                  0.004711           -2.76e-05  
  Res marital(spouse) corr  -0.053278   0.027228  -0.001316  -0.027367        0.004658            0.010646                  0.010646                  0.004658            0.000412  
  Env marital(spouse) corr  -0.053278   0.027228  -0.001316  -0.027367        0.004658            0.010646                  0.010646                  0.004658            0.000412  
  Env full sibs corr        -0.028185   0.012191   0.009298  -0.006696        0.004711            0.004658                  0.004658                  0.004711           -2.76e-05  
  Intercept                 -0.001681   0.001031  -0.000818  -0.001468       -2.76e-05            0.000412                  0.000412                 -2.76e-05            0.009634  

=============================================================
     MAXIMIZATION RESULTS Alternate with test covariates
=============================================================

-----------------------------------------------------------------------------
  Parameter                 Estimate   S.E.       P-value     Deriv          
-----------------------------------------------------------------------------
  Variance components
                    Random   1.171435   0.532758   0.027891    0.0000009211  
                   Marital   0.145080   0.265294   0.292236    0.0000107896  
                   Sibling   1.357988   0.208535  < 1.00e-07   0.0000286030  

  Other parameters
            Total variance   2.674503   0.330811  < 1.00e-07   0.0000017728  

  Residual familial correlations
        Res full sibs corr   0.507754   0.069270  < 1.00e-07   0.0000000000  
  Res marital(spouse) corr   0.054245   0.104498   0.603689    0.0000000000  

  Environmental intraclass correlations
  Env marital(spouse) corr   0.054245   0.104498   0.603689    0.0000000000  
        Env full sibs corr   0.507754   0.069270  < 1.00e-07   0.0000000000  

                 Intercept   5.021178   0.097975  < 1.00e-07   0.0000000000  

  Covariates
                     apres   0.255690   0.144259   0.076323    0.0000000000  
-----------------------------------------------------------------------------

Final ln likelihood: -2370.578709

===================================================================
     VARIANCE-COVARIANCE MATRIX Alternate with test covariates
===================================================================

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                            Random     Marital    Sibling    Total variance  Res full sibs corr  Res marital(spouse) corr  Env marital(spouse) corr  Env full sibs corr  Intercept  apres      
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Random                     0.283831  -0.137452  -0.005478   0.140900       -0.028798           -0.054251                 -0.054251                 -0.028798           -0.001979  -0.000623  
  Marital                   -0.137452   0.070381  -0.001201  -0.068272        0.012513            0.027700                  0.027700                  0.012513            0.001166   0.000321  
  Sibling                   -0.005478  -0.001201   0.043487   0.036808        0.009272           -0.001195                 -0.001195                  0.009272           -0.000749  -2.60e-05  
  Total variance             0.140900  -0.068272   0.036808   0.109436       -0.007014           -0.027747                 -0.027747                 -0.007014           -0.001561  -0.000328  
  Res full sibs corr        -0.028798   0.012513   0.009272  -0.007014        0.004798            0.004821                  0.004821                  0.004798            1.65e-05   5.26e-05  
  Res marital(spouse) corr  -0.054251   0.027700  -0.001195  -0.027747        0.004821            0.010920                  0.010920                  0.004821            0.000468   0.000127  
  Env marital(spouse) corr  -0.054251   0.027700  -0.001195  -0.027747        0.004821            0.010920                  0.010920                  0.004821            0.000468   0.000127  
  Env full sibs corr        -0.028798   0.012513   0.009272  -0.007014        0.004798            0.004821                  0.004821                  0.004798            1.65e-05   5.26e-05  
  Intercept                 -0.001979   0.001166  -0.000749  -0.001561        1.65e-05            0.000468                  0.000468                  1.65e-05            0.009599   0.000519  
  apres                     -0.000623   0.000321  -2.60e-05  -0.000328        5.26e-05            0.000127                  0.000127                  5.26e-05            0.000519   0.020811  

===============================
     Likelihood Ratio Test
===============================

  H0 ln likelihood Alternate without test covariates  -2372.144513  
  H1 ln likelihood Alternate with test covariates     -2370.578709  
                                                                    
  2 * |H0 - H1|                                           3.131608  
  Degrees of freedom                                             1  
  P-value                                                 0.076788  

